In [2]:
from transformers import pipeline, AutoModel, AutoTokenizer, BertForMaskedLM, AlbertTokenizer
import pandas as pd
import numpy as np
import os, time
import torch
from transformers import pipeline, BertTokenizer, BertForMaskedLM

#device = torch.device("cuda:0")

LOCAL_MODEL_PATH = './bert-ancient-chinese' 
tokenizer = BertTokenizer.from_pretrained(LOCAL_MODEL_PATH)
model = BertForMaskedLM.from_pretrained(LOCAL_MODEL_PATH)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)
model.eval()
device_id = 0 if torch.cuda.is_available() else -1
unmasker = pipeline("fill-mask", model=model, tokenizer=tokenizer, device=device_id)

Device set to use cpu

In [5]:
from core_embed import HookManager, utils
hook_manager = HookManager()

df_query = pd.read_excel("query_ancient.xlsx",index_col=0)
df_query.head()

                          Query
1.1    [DESC][TERM]關系者，[MASK]也。
1.2   [DESC][TERM]，為[MASK]之關系也。
2.1  [DESC][TERM]，何以言喻？[MASK]也。
2.2  [DESC][TERM]，何以名状？[MASK]也。
3.1    [DESC][TERM]，要義在諸[MASK]。

In [15]:
df_desc = pd.read_csv('../../1_DeepSeek_Description/ancient/ancient_results_final.csv', encoding="gb18030")
df_desc.head()

,古代人际关系名称_现汉,对应的现代人际关系,古代人際關係名稱_文言,description,query,Unnamed: 5
0,夫妻之間,夫-妻,夫妻之間,在中國古代宗法社會中，夫妻關係是『五倫』之一，以『夫為妻綱』為核心原則，強調男主外、女主內的...,夫妻之間,NaN
1,父子之間,父-子,父子之間,父子關係是儒家倫理的核心，位列『五倫』之首，以『父為子綱』為綱常。強調父親的絕對權威與子女的...,父子之間,NaN
2,父女之間,父-女,父女之間,在『男尊女卑』的古代社會框架下，父女關係深受性別角色影響。父親對女兒的權威體現於婚姻安排與行...,父女之間,NaN
3,母子之間,母-子,母子之間,母子關係在孝道文化中佔有特殊地位，雖受『夫死從子』觀念影響，但母親憑藉生育與養育之功仍享有尊...,母子之間,NaN
4,母女之間,母-女,母女之間,母女關係是古代女性生命經驗傳承的重要紐帶。母親負責將婦德、女紅、持家等『內闈之教』傳授給女兒...,母女之間,NaN

In [16]:
df_desc.iloc[[13,85],:]

,古代人际关系名称_现汉,对应的现代人际关系,古代人際關係名稱_文言,description,query,Unnamed: 5
13,外祖父與外孫之間,外祖父-外孙子,外祖父與外孫之間,作为外戚关系的重要体现，外祖父对外孙的权威性较祖父为弱，但仍享有尊重。在‘外孙异姓不得为后’...,外祖父與外孫之間,NaN
85,從祖母與從孫之間,从祖母-从孙子,從祖母與從孫之間,從祖母是祖父兄弟之妻（即伯叔祖母），從孫是孫輩中非直系但屬同宗旁支的男性後代。此關係屬五服內...,從祖母與從孫之間,NaN

In [17]:
text = df_query.iloc[3, :]["Query"]
for i, row in df_desc.iloc[:, :].iterrows():
    use_word = text.replace("[DESC]",row['description']).\
               replace("[TERM]",row['query'])
    print(use_word)
    break
unmasker(use_word)

在中國古代宗法社會中，夫妻關係是『五倫』之一，以『夫為妻綱』為核心原則，強調男主外、女主內的分工。婚姻多由『父母之命、媒妁之言』締結，重視門第相當與家族聯姻。理想關係體現為『相敬如賓』，妻子需遵守『三從四德』（未嫁從父、既嫁從夫、夫死從子；婦德、婦言、婦容、婦功），而丈夫對妻子亦有養育與保護之責。這種關係不僅是私人結合，更是承載祭祀祖先、延續香火、穩定社會秩序的倫理紐帶。夫妻之間，何以名状？[MASK]也。

[{'score': 0.15097926557064056,
  'token': 671,
  'token_str': '一',
  'sequence': '在 中 國 古 代 宗 法 社 會 中 ， 夫 妻 關 係 是 『 五 倫 』 之 一 ， 以 『 夫 為 妻 綱 』 為 核 心 原 則 ， 強 調 男 主 外 、 女 主 內 的 分 工 。 婚 姻 多 由 『 父 母 之 命 、 媒 妁 之 言 』 締 結 ， 重 視 門 第 相 當 與 家 族 聯 姻 。 理 想 關 係 體 現 為 『 相 敬 如 賓 』 ， 妻 子 需 遵 守 『 三 從 四 德 』 （ 未 嫁 從 父 、 既 嫁 從 夫 、 夫 死 從 子 ； 婦 德 、 婦 言 、 婦 容 、 婦 功 ） ， 而 丈 夫 對 妻 子 亦 有 養 育 與 保 護 之 責 。 這 種 關 係 不 僅 是 私 人 結 合 ， 更 是 承 載 祭 祀 祖 先 、 延 續 香 火 、 穩 定 社 會 秩 序 的 倫 理 紐 帶 。 夫 妻 之 間 ， 何 以 名 状 ？ 一 也 。'},
 {'score': 0.0613727793097496,
  'token': 4891,
  'token_str': '禮',
  'sequence': '在 中 國 古 代 宗 法 社 會 中 ， 夫 妻 關 係 是 『 五 倫 』 之 一 ， 以 『 夫 為 妻 綱 』 為 核 心 原 則 ， 強 調 男 主 外 、 女 主 內 的 分 工 。 婚 姻 多 由 『 父 母 之 命 、 媒 妁 之 言 』 締 結 ， 重 視 門 第 相 當 與 家 族 聯 姻 。 理 想 關 係 體 現 為 『 相 敬 如 賓 』 ， 妻 子 需 遵 守 『 三 從 四 德 』 （ 未 嫁 從 父 、 既 嫁 從 夫 、 夫 死 從 子 ； 婦 德 、 婦 言 、 婦 容 、 婦 功 ） ， 而 丈 夫 對 妻 子 亦 有 養 育 與 保 護 之 責 。 這 種 關 係 不 僅 是 私 人 結 合 ， 更 是 承 載 祭 祀 祖 先 、 延 續 香 火 、 穩 定 社 會 秩 序 的 倫 理 紐 帶 。 夫 妻 之 間 ， 何 以 名 状 ？ 禮 也 。'},
 {'score': 0.05613008886575699,
  'token': 5412,
  'token_str': '義',
  'sequence': '在 中 國 古 代 宗 法 社 會 中 ， 夫 妻 關 係 是 『 五 倫 』 之 一 ， 以 『 夫 為 妻 綱 』 為 核 心 原 則 ， 強 調 男 主 外 、 女 主 內 的 分 工 。 婚 姻 多 由 『 父 母 之 命 、 媒 妁 之 言 』 締 結 ， 重 視 門 第 相 當 與 家 族 聯 姻 。 理 想 關 係 體 現 為 『 相 敬 如 賓 』 ， 妻 子 需 遵 守 『 三 從 四 德 』 （ 未 嫁 從 父 、 既 嫁 從 夫 、 夫 死 從 子 ； 婦 德 、 婦 言 、 婦 容 、 婦 功 ） ， 而 丈 夫 對 妻 子 亦 有 養 育 與 保 護 之 責 。 這 種 關 係 不 僅 是 私 人 結 合 ， 更 是 承 載 祭 祀 祖 先 、 延 續 香 火 、 穩 定 社 會 秩 序 的 倫 理 紐 帶 。 夫 妻 之 間 ， 何 以 名 状 ？ 義 也 。'},
 {'score': 0.03420568257570267,
  'token': 1988,
  'token_str': '妻',
  'sequence': '在 中 國 古 代 宗 法 社 會 中 ， 夫 妻 關 係 是 『 五 倫 』 之 一 ， 以 『 夫 為 妻 綱 』 為 核 心 原 則 ， 強 調 男 主 外 、 女 主 內 的 分 工 。 婚 姻 多 由 『 父 母 之 命 、 媒 妁 之 言 』 締 結 ， 重 視 門 第 相 當 與 家 族 聯 姻 。 理 想 關 係 體 現 為 『 相 敬 如 賓 』 ， 妻 子 需 遵 守 『 三 從 四 德 』 （ 未 嫁 從 父 、 既 嫁 從 夫 、 夫 死 從 子 ； 婦 德 、 婦 言 、 婦 容 、 婦 功 ） ， 而 丈 夫 對 妻 子 亦 有 養 育 與 保 護 之 責 。 這 種 關 係 不 僅 是 私 人 結 合 ， 更 是 承 載 祭 祀 祖 先 、 延 續 香 火 、 穩 定 社 會 秩 序 的 倫 理 紐 帶 。 夫 妻 之 間 ， 何 以 名 状 ？ 妻 也 。'},
 {'score': 0.033385246992111206,
  'token': 6887,
  'token_str': '道',
  'sequence': '在 中 國 古 代 宗 法 社 會 中 ， 夫 妻 關 係 是 『 五 倫 』 之 一 ， 以 『 夫 為 妻 綱 』 為 核 心 原 則 ， 強 調 男 主 外 、 女 主 內 的 分 工 。 婚 姻 多 由 『 父 母 之 命 、 媒 妁 之 言 』 締 結 ， 重 視 門 第 相 當 與 家 族 聯 姻 。 理 想 關 係 體 現 為 『 相 敬 如 賓 』 ， 妻 子 需 遵 守 『 三 從 四 德 』 （ 未 嫁 從 父 、 既 嫁 從 夫 、 夫 死 從 子 ； 婦 德 、 婦 言 、 婦 容 、 婦 功 ） ， 而 丈 夫 對 妻 子 亦 有 養 育 與 保 護 之 責 。 這 種 關 係 不 僅 是 私 人 結 合 ， 更 是 承 載 祭 祀 祖 先 、 延 續 香 火 、 穩 定 社 會 秩 序 的 倫 理 紐 帶 。 夫 妻 之 間 ， 何 以 名 状 ？ 道 也 。'}]

In [18]:
for query_num, query_row in df_query.iloc[0:2, :].iterrows(): 
    arr_tit = ["CLS", "MASK", "關","系"]
    
    util = utils(arr_tit, unmasker.tokenizer.tokenize)
    text = query_row['Query']
    for v in [1,2]: # no additional requirement, just for create new files
        # output layer
        hook_manager.add_hook(unmasker.model.bert.encoder, util.getHook("embedding_output", v, reset = True))
        # 12 encoder layer
        for i in range(12):
            hook_manager.add_hook(unmasker.model.bert.encoder.layer[i], 
                                  util.getHook("encoder_layer%s" % i, v, reset = True))
        hook_manager.remove_hooks()

    for i, row in df_desc.iloc[:, :].iterrows():
        use_word = text.replace("[DESC]",row['description']).\
                   replace("[TERM]",row['query'])
        print(use_word)

        hook_manager.add_hook(unmasker.model.bert.encoder, util.getHook("embedding_output", 
                              row["query"], use_word))
        # 12 encoder layer
        for i in range(12):
            hook_manager.add_hook(unmasker.model.bert.encoder.layer[i], util.getHook("encoder_layer%s" % i, 
                                                                                     row["query"], use_word))
        res = unmasker(
            use_word
        )
        hook_manager.remove_hooks()
    time.sleep(5)
    os.rename("bert_embedding_data", "bac/q{}_bert_embedding_data".format(query_num))

在中國古代宗法社會中，夫妻關係是『五倫』之一，以『夫為妻綱』為核心原則，強調男主外、女主內的分工。婚姻多由『父母之命、媒妁之言』締結，重視門第相當與家族聯姻。理想關係體現為『相敬如賓』，妻子需遵守『三從四德』（未嫁從父、既嫁從夫、夫死從子；婦德、婦言、婦容、婦功），而丈夫對妻子亦有養育與保護之責。這種關係不僅是私人結合，更是承載祭祀祖先、延續香火、穩定社會秩序的倫理紐帶。夫妻之間關系者，[MASK]也。
父子關係是儒家倫理的核心，位列『五倫』之首，以『父為子綱』為綱常。強調父親的絕對權威與子女的絕對服從，所謂『孝道』要求子順從父命、繼承父志、光耀門楣。父親承擔教養、傳授家業之責，兒子則須恪守『晨昏定省』『父母在，不遠遊』等禮儀規範。此關係不僅是血緣紐帶，更是宗法制度中權力傳承、家族延續的基礎，具有強烈的等級性與責任性。父子之間關系者，[MASK]也。
在『男尊女卑』的古代社會框架下，父女關係深受性別角色影響。父親對女兒的權威體現於婚姻安排與行為管教，女兒須遵從《禮記》所載『女子十年不出，姆教婉娩聽從』的閨訓。父女間情感往往含蓄內斂，女兒出嫁前需學習女紅、祭祀禮儀以備夫家之責，出嫁後則歸屬夫族，所謂『嫁出去的女兒潑出去的水』。此關係以父親的保護與女兒的順從為特徵，且從屬於家族整體利益。父女之間關系者，[MASK]也。
母子關係在孝道文化中佔有特殊地位，雖受『夫死從子』觀念影響，但母親憑藉生育與養育之功仍享有尊重，尤其寡母常獲兒子加倍奉養。儒家提倡『孝悌』，兒子對母親須盡心侍奉，如《二十四孝》中典故所示。母親的角色重在『慈教』，通過言傳身教塑造子女品德，且常以『孟母三遷』為典範承擔教育啟蒙之責。此關係在嚴格的父權體系中，往往蘊含更為情感化的倫理連結。母子之間關系者，[MASK]也。
母女關係是古代女性生命經驗傳承的重要紐帶。母親負責將婦德、女紅、持家等『內闈之教』傳授給女兒，以備其未來擔任妻職與母職。關係特點體現為『閨閣之訓』的私密性與實用性，女兒須學習《女誡》《列女傳》等規範。在『從夫居』的婚姻制度下，母女情感常因女兒出嫁而轉為隱性聯繫，但母親通過教導女兒適應夫家生活，實質維繫了女性群體在父權結構中的生存智慧代際傳遞。母女之間關系者，[MASK]也。
在宗法制度下，兄弟關係以『兄友弟恭』為核心倫理。長兄承擔家族責任，享有繼承優先權；弟需敬順兄長，形成『長幼有序』的差序格局。這種關係既包含血緣親情，又隱含權力結構，常通過『分家』『共爨』等制度性安排體現經濟與社會連結。兄弟之間關系者，[MASK]也。
遵循『男女有別』與『內外之防』的原則，兄長對妹妹負有保護與監督之責，妹妹則需遵從兄長的教誨。婚前關係受『男女七歲不同席』等禮教約束，婚後妹妹成為外姓族人，關係轉為『外戚』層面的往來，但血緣紐帶仍在祭祀、婚喪等儀式中延續。兄妹之間關系者，[MASK]也。
姊長如母，在『長姊如母』觀念影響下，姊常分擔母親的教養職責。弟對姊需保持尊敬，但隨年齡增長，男性社會地位逐漸超越姊姊。這種關係存在性別與長幼秩序的雙重張力：姊雖年長卻因女性身份終將從屬夫家，弟則承擔本宗延續重任。姊弟之間關系者，[MASK]也。
在『閨閣』空間內形成的親密紐帶，婚前共同學習女紅、禮儀，婚後因各歸夫家而關係疏離。關係核心是『同氣連枝』的血緣認同，但受制於『婦人無外事』的規範，情感連結多通過歸寧、節慶往來維持，經濟與宗法層面的互動較弱。姊妹之間關系者，[MASK]也。
體現『隔代親』與『家族延續』雙重意涵。祖父作為家族權威象徵，通過為孫輩命名、教導族史等方式傳遞宗族認同；孫輩則承載祖父對血脈永續的寄託。這種關係跳脫了父子間的直接權威壓力，常帶有更濃厚的慈愛色彩，但仍在『昭穆制度』的祭祀序列中確立倫理位階。祖父與孫之間關系者，[MASK]也。
在宗法制度下，祖父对孙女具有权威性的监护责任，关系以‘慈严并济’为特征。祖父通常通过家训、礼教传递家族价值观，孙女则需恪守孝道与闺范。这种关系受到‘男女有别’原则的影响，情感表达较祖父与孙子的关系更为含蓄，但祖父常在婚配选择、品德教化方面发挥重要影响。祖父與孫女之間關系者，[MASK]也。
祖母对孙子往往体现‘隔代亲’的溺爱倾向，在家庭中常扮演调和严父教育的角色。孙子可通过祖母获得情感庇护，祖母亦通过孙子延续家族香火的期待获得精神慰藉。这种关系在礼法框架下具有一定弹性，常蕴含生活智慧与家族口述历史的传递。祖母與孫之間關系者，[MASK]也。
这是女性代际情感联结的重要纽带，祖母承担着对孙女进行女德教化、女红传授的责任。关系常围绕闺阁生活展开，祖母通过言传身教传递持家之道与妇礼规范。在‘内言不出于阃’的原则下，这种关系构成家族内部女性知识传承的封闭系统，情感亲密但受礼教严格约束。祖母與孫女之間關系者，[MASK]也。
作为外戚关系的重要体现，外祖父对外孙的权威性较祖父为弱，但仍享有尊重。在‘外孙异姓不得为后’的宗法观念下，这种关系更侧重情感联结与学问传授。外祖父常以赏识者而非管教者身份出现，可通过荐举、赠予等方式对外孙仕途或学业产生辅助性影响。外祖父與外孫之間關系者，[MASK]也。
这是宗族边界外最具弹性的隔代关系。外祖父对外孙女的约束力最弱，关系以节庆往来、礼物馈赠为主要表现形式。在‘姑舅之亲’的框架下，外祖父可对孙女的品德修养提出建议，但无权干涉其婚配与教化。这种关系常体现为节仪性的关怀，是父系宗法制度下难得的温情补充。外祖父與外孫女之間關系者，[MASK]也。
在中國古代宗法社會中，外祖母與外孫的關係屬於『外親』範疇，其親緣紐帶雖不如父系宗親受到制度性強調，但仍具有深厚的倫理情感。外祖母對外孫的疼愛常被形容為『隔代親』，帶有較為寬容、慈祥的特質。在禮制上，外孫對外祖母需行孝道，服制為『小功』（五服之一），體現『尊尊親親』的原則。這一關係在實際生活中往往承載著母系家族的情感聯繫與文化傳承。外祖母與外孫之間關系者，[MASK]也。
此關係同樣屬於外親，但在性別文化背景下具有特殊內涵。外祖母常被視為女性技藝、家風與道德教養的傳遞者，對外孫女往往承擔部分教化職責，如女紅、持家之道等。古代文獻中不乏外祖母撫育孤幼外孫女的記載，體現母系家族對女性後代的庇護功能。情感上較之外孫可能更添細膩親密，但受『男女有別』觀念影響，外孫女成年後與外祖母的公開互動較受限。外祖母與外孫女之間關系者，[MASK]也。
這是父系宗族中跨越三代的直系血親關係，在宗法制度中具有重要象徵意義。曾祖父代表家族源流與權威，曾孫則承載宗祧延續的期望，所謂『四世同堂』被視為家族興旺的祥瑞。曾祖父對曾孫通常表現為威嚴與慈愛並存，在禮法上曾孫需對曾祖父行孝，服制為『齊衰三月』。此關係強化了家族縱向的時間連續性，體現儒家『慎終追遠』的倫理觀。曾祖父與曾孫之間關系者，[MASK]也。
在嚴格宗法體系中，曾孫女因性別因素不列入承嗣主線，但作為直系血親仍受家族庇護。曾祖父對曾孫女的態度往往帶有傳統長輩對女性後代的保護性關愛，其互動多限於家族內部閨閣範圍。曾孫女對曾祖父需恪守孝道禮儀，但因其未來將嫁入他族，這種關係隱含著『暫駐性』的特質。古代家訓中常強調曾祖父對所有曾輩應一視同仁施以教化，體現『敦親睦族』的理想。曾祖父與曾孫女之間關系者，[MASK]也。
作為家族中最年長的女性尊長，曾祖母在家庭內享有特殊地位。她與曾孫的關係融合了宗法尊卑與母性慈愛，常被賦予『福壽雙全』的文化意象。曾祖母往往是家族口述歷史與生活智慧的傳承者，對曾孫的成長產生潛移默化的影響。在禮制上，曾孫需對曾祖母行孝，服制同於曾祖父。這一關係體現了中國古代家庭中女性長者通過血緣紐帶參與家族延續的倫理角色。曾祖母與曾孫之間關系者，[MASK]也。
在中國古代宗法制度下，曾祖母是曾孫女的直系四世尊長，屬於『高祖-曾祖-祖-父-己身』譜系中的女性尊親。這一關係體現了縱向家族血緣的延續性，曾祖母代表家族歷史與道德傳承的象徵，曾孫女則承載著家族未來的寄託。在禮制中，曾孫女對曾祖母需行孝道、遵教誨，而曾祖母往往通過口述家族故事、女德教導等方式傳遞家風，關係中蘊含著『慎終追遠』的倫理意涵。曾祖母與曾孫女之間關系者，[MASK]也。
高祖父為玄孫的五世直系祖先，屬於『天祖-高祖-曾祖-祖-父』譜系中的最高男性尊長。在古代家族觀念中，五世同堂被視為家族興旺的祥瑞之兆。高祖父作為家族權威的源頭象徵，玄孫則代表血脈的極遠延伸，二者關係跨越近百年時空，體現了『木本水源』的宗族認同。禮制上玄孫需對高祖父行極敬之禮，但實際生活中因年齡差距罕見直接互動，更多作為祭祀時血脈連通的儀式性關係存在。高祖父與玄孫之間關系者，[MASK]也。
高祖母是玄孫的五世女性尊親，其地位雖在宗法制度中依附於高祖父，但在家族內部往往被視為福壽與慈愛的化身。古代家族祭祀中，高祖母常與高祖父同受香火，體現『陰陽配享』的觀念。她與玄孫的關係帶有濃厚的神秘色彩，民間常將高祖母視為守護家族繁衍的『家神』之一。在實際倫理中，玄孫對高祖母需懷有對母系源頭的崇敬，這種關係強化了縱向親緣中女性祖先的紐帶作用。高祖母與玄孫之間關系者，[MASK]也。
此為母系三世代跨輩關係，外曾祖父是母親的祖父。在中國古代父系宗法為主導的背景下，外親關係雖較本宗為疏，但仍屬『五服』中的緦麻親（最輕喪服）。外曾祖父代表母系家族的淵源，其與外曾孫的關係體現了『外戚』血脈的橫向聯繫。這一關係常通過年節往來、壽禮問安等儀式性互動維持，既有親情溫潤的一面，也反映古代『內外有別』的親屬制度設計。外曾祖父與外曾孫之間關系者，[MASK]也。
作為母親的祖母，外曾祖母在父權社會中具有雙重邊緣性（女性+外親），但其往往在家族情感網絡中扮演溫情紐帶的角色。古代禮制規定外曾孫需對外曾祖母行孝養之禮，但較本宗曾祖母為輕。在實際生活中，外曾祖母常是外曾孫童年時聽聞母系家族歷史、獲得跨代寵愛的對象，這種關係體現了中國親屬制度中『血緣柔情』對剛性宗法結構的補充，亦展現女性長者在維繫姻親網絡中的獨特作用。外曾祖母與外曾孫之間關系者，[MASK]也。
在中國古代宗法社會中，祖先與後裔的關係具有神聖性與倫理性雙重特質。祖先被視為家族血脈與福澤的源頭，後裔則承擔祭祀、繼嗣與光耀門楣的責任。這種關係以『孝道』為核心，強調『慎終追遠』，通過宗廟祭祀、族譜編修等儀式強化縱向的血緣紐帶，形成家族認同與歷史連續感。後裔對祖先的尊崇不僅是情感寄託，更是維護宗族秩序與社會穩定的基礎。祖先與後裔之間關系者，[MASK]也。
伯父作為父親的兄長，在古代家族倫理中居於重要地位。伯侄關係屬於『五服』內的近親，受宗法制度規範：伯父對侄子負有教導、監護之責，尤其在父親早逝時可代行父權；侄子則需對伯父保持如父般的尊敬，稱謂上常尊稱為『伯父』或『世父』。這種關係體現了『長兄如父』的家族協作原則，強化了父系宗族內部的橫向凝聚力。伯父與侄子之間關系者，[MASK]也。
伯父與侄女的關係受到古代性別規範與內外有別的影響。伯父對侄女負有保護與監督之責，尤其在婚嫁事務上具有建議權；侄女則需恪守男女之防，對伯父保持恭敬但相對疏遠的禮節。由於女性終將出嫁成為『外姓人』，伯侄女關係的宗法義務弱於伯侄關係，但仍在家族道德範圍內強調長幼尊卑的禮儀約束。伯父與侄女之間關系者，[MASK]也。
伯母作為伯父之妻，與侄子的關係以『嬪婦之禮』為基礎。伯母承擔對侄子的日常關照之責，尤其在母親缺席時可代行養育職能；侄子則需視伯母如母，遵循『事諸父如事父，事諸母如事母』的倫理要求。這種關係體現了家族內部女性長輩對子侄輩的慈愛與教化角色，但互動中需恪守男女有別的禮制，親而不狎。伯母與侄子之間關系者，[MASK]也。
伯母與侄女的關係在古代女性內闈生活中尤為密切。伯母常作為侄女的女紅、禮儀教習者，亦是婚嫁事務的重要參與者；侄女則通過學習伯母的持家之道，傳承家族女性規範。這種關係以『姑侄之誼』為參照，強調女性長輩對未婚侄女的教導與庇護，是宗族內女性網絡的關鍵紐帶，同時也強化了『男外女內』空間秩序下的性别化倫理傳承。伯母與侄女之間關系者，[MASK]也。
叔父是父亲的兄弟，在宗法制度中属于‘五服’内的近亲。叔侄关系以‘孝悌’为伦理基础，侄子对叔父需持恭敬态度，叔父对侄子则承担教导与庇护责任。这种关系强调纵向的尊卑秩序，同时带有家族利益共同体的连带义务，在财产继承、婚丧事务中均有明确礼法规范。叔父與侄子之間關系者，[MASK]也。
关系性质与叔侄类似，但受古代性别规范影响，叔父对侄女的管教多通过女性亲属间接实施。侄女对叔父需恪守‘男女有别’之礼，日常接触较侄子更为疏离。在家族事务中，叔父对侄女的婚姻安排具有一定话语权，体现为‘父权延伸’下的监护角色。叔父與侄女之間關系者，[MASK]也。
叔母作为叔父之妻，其与侄子的关系以‘夫族亲属网络’为纽带。侄子对叔母需行子侄之礼，但交往分寸受‘男女大防’约束。在家庭生活中，叔母常以女性长辈身份参与对侄子的生活照料，关系亲密度取决于家族同居形式，总体较叔侄关系更侧重日常伦理而非宗法责任。叔母與侄子之間關系者，[MASK]也。
这是家族女性成员间的横向联系。叔母对侄女具有女性经验传授的义务，尤其在女红、家务等传统性别分工领域。双方关系往往较叔侄更为亲密，可形成类似母女的情感联结，但仍在‘长幼有序’框架下运作。侄女出嫁前，叔母常协助进行妇德教育，体现家族内部女性代际传承。叔母與侄女之間關系者，[MASK]也。
姑丈作为姑姑的丈夫，属于‘外姻’亲属。古代‘姑表亲’具有特殊地位，但姑丈与侄子无直接血亲关系，其互动以姑姑为中介。侄子对姑丈需持敬重态度，礼仪上类比叔父但亲密度较低。这种关系体现中国古代亲属制度中‘血亲为主，姻亲为辅’的特点，在重大事务中姑丈的话语权弱于本宗叔父。姑丈與侄子之間關系者，[MASK]也。
此為外親關係中的姻親關係。姑丈為父之姊妹的丈夫，屬尊長輩；侄女為兄弟之女，屬卑幼輩。在禮法上，侄女對姑丈需持敬重之禮，但關係較父系宗親疏遠，日常互動多依家庭場合而定，強調男女有別與尊卑有序。姑丈與侄女之間關系者，[MASK]也。
此為父系血親的外延關係。姑母為父之姊妹，屬本宗出嫁女子；侄子為兄弟之子。姑母在禮制中地位特殊，出嫁後仍與本家保持情感聯繫，對侄子有慈愛之責，侄子則需以敬孝相待。關係親密程度常因家庭而異，但受『姑舅之親』傳統影響，往往帶有溫情色彩。姑母與侄子之間關系者，[MASK]也。
此為父系女性親屬間的縱向關係。姑母為父之姊妹，侄女為兄弟之女。二者皆屬本宗女性，但姑母因輩分與年齡居尊。關係多體現為女性長輩對幼輩的教導與關懷，尤其在女德、女紅等家庭教育中可能產生影響，情感連結較細膩，但受『內外有別』規範約束。姑母與侄女之間關系者，[MASK]也。
此為母系血親的核心關係。舅父為母之兄弟，在宗法社會中屬『外親』尊長。甥為姊妹之子。舅父地位崇高，傳統有『舅父如父』之說，對甥有教導、庇護之責，尤其在婚喪等重大儀式中扮演重要角色。甥對舅父須恪守孝悌之禮，關係兼具權威與親近。舅父與甥之間關系者，[MASK]也。
此為母系血親中男女有別的親屬關係。舅父為母之兄弟，甥女為姊妹之女。甥女對舅父需遵從男女之防的禮教，但舅父仍對甥女有愛護之責。關係較舅甥之間多一重性別隔閡，互動多在家庭公開場合，情感表達較含蓄，然舅父在甥女的婚姻事務上常具話語權。舅父與甥女之間關系者，[MASK]也。
舅母是甥的母親兄弟之妻，屬外親姻親關係。在宗法制度下，舅母對甥的責任較為間接，但作為長輩仍享有一定尊重。甥對舅母的禮節性稱謂為『舅母』或『舅媽』，關係親疏常取決於與舅舅家庭的往來頻率，在重要節慶或家族儀式中需執晚輩禮。舅母與甥之間關系者，[MASK]也。
舅母是甥女的母親兄弟之妻，屬外親姻親關係。古代女性親屬關係較側重父系宗族，甥女與舅母的互動多隨母系往來而定。舅母對甥女無法定監護義務，但在婚嫁等事務上可能以女性長輩身份提供建議，甥女對舅母需保持禮貌性尊稱與禮節。舅母與甥女之間關系者，[MASK]也。
姨丈是甥的母親姐妹之夫，屬外親姻親關係。姨丈與甥的關係較為鬆散，其權威性低於父系姑父。甥對姨丈的稱謂通常為『姨丈』或『姨父』，雙方往來多依附於姨母與甥之母的姐妹情誼。在禮制中，姨丈對甥無宗法約束力，但可作為親屬網絡中的輔助性長輩。姨丈與甥之間關系者，[MASK]也。
姨丈是甥女的母親姐妹之夫，屬外親姻親關係。古代女性親屬關係中，姨丈與甥女的互動更為間接，多通過姨母或甥女之母維繫。甥女對姨丈行禮時需注重男女之防，稱謂用『姨丈』。此關係在家族事務中影響力較弱，主要體現為年節往來的禮儀性問候。姨丈與甥女之間關系者，[MASK]也。
姨母是甥的母親姐妹，屬外親血親關係。古代有『姨母如母』之說，但因屬母系親屬，在宗法地位上低於姑母。姨母對甥常有較深情感聯繫，尤其在甥幼年時可能參與撫育。甥對姨母需行孝悌之禮，稱謂為『姨母』或『姨娘』，關係親密度常高於姨丈與甥。姨母與甥之間關系者，[MASK]也。
此為母系血親關係，屬『從母』與『甥女』的倫常。姨母對甥女負有教導撫育之責，體現『母黨』親情；甥女對姨母需持敬重之心，禮儀上略遜於直系尊親但親近於一般旁親。關係特點是兼具血緣紐帶與慈愛教導，在家族互助、婚嫁指導等方面具有實際影響力。姨母與甥女之間關系者，[MASK]也。
此為父系同輩旁系血親關係，屬『同堂兄弟』。因共祀同一祖父，在宗法制度中視為『本家』核心成員，關係密切程度僅次於親兄弟。強調『昭穆有序』，依長幼定尊卑；在家族事務中需協力承擔宗族責任，經濟上常互通有無，體現『兄弟鬩於牆，外禦其侮』的宗族凝聚力。堂兄與堂弟之間關系者，[MASK]也。
此為父系同輩旁系血親關係，屬『同堂兄妹』。受『男女有別』禮教規範，相處需守『叔嫂不通問』之延伸原則，保持適當禮儀距離。堂兄對堂妹負有保護之責，堂妹婚嫁時堂兄可能參與議事；關係特點是血緣親近但交往受限，體現古代家族內部『長幼有序、內外有別』的倫理結構。堂兄與堂妹之間關系者，[MASK]也。
此為父系同輩旁系血親關係，屬『同堂姊弟』。堂姊對幼弟常懷教導照顧之責，類似『長姊如母』的延伸；堂弟需敬重堂姊，但成年後交往受『男女大防』影響。關係特點體現縱向的長幼倫理重於橫向的性別區隔，在家族生活中堂姊可參與管教、婚嫁勸誡等事務。堂姊與堂弟之間關系者，[MASK]也。
此為父系同輩旁系血親關係，屬『同堂姊妹』。因同屬女性，在『閨閣之內』交往較為密切，可共同參與女紅、祭祀準備等內宅事務。關係受『姊友妹恭』規範，長幼有序但親密程度高於異性堂親；婚嫁後往往成為家族聯姻網絡中的重要紐帶，體現女性在維繫宗族關係中的特殊作用。堂姊與堂妹之間關系者，[MASK]也。
在中國古代宗法社會中，表兄弟關係屬於外親（母族或妻族）的平輩男性親屬關係。雙方雖非同姓本宗，但因母親或祖母的姊妹關係而產生連結。這種關係在禮法上較本宗堂兄弟疏遠，但在實際交往中常因姻親紐帶而保持密切往來，尤其在士族門閥中可能涉及家族聯盟與利益互助。交往時需遵循『長幼有序』的原則，年長者稱表兄，年幼者稱表弟，儀節上略遜於本宗兄弟但仍重親誼。表兄與表弟之間關系者，[MASK]也。
此為外親中表兄妹的異性親屬關係，受到古代『同姓不婚』與『外親通婚』觀念的雙重影響。在禮制上，表兄妹因屬異姓（不同宗族），理論上可通婚（尤以姑表兄妹為常見），但實際受地域風俗與時代律令調節。日常交往需嚴格遵守『男女有別』的禮教規範，尤其在成年後需保持適當距離。關係內涵兼具親屬情誼與潛在的婚姻可能性，常成為家族鞏固姻親聯盟的考量對象。表兄與表妹之間關系者，[MASK]也。
作為外親中表姊弟的異性親屬關係，其特點受到年齡與性別雙重禮教規範的制約。表姊對表弟兼具親屬關照與『長幼之序』的權威性，尤其在童年階段可能存在類同胞的教導關係。成年後交往則須嚴格遵循男女大防，但因姊弟名分較兄妹更強調長幼差序，在禮法上相對表兄妹稍顯寬鬆。此關係在古代文學中常呈現為溫厚而不涉曖昧的親屬典範，極少作為婚姻考慮對象（因女性年長不符合傳統婚配偏好）。表姊與表弟之間關系者，[MASK]也。
此係外親中女性平輩親屬關係，其互動模式深植於古代女性的閨閣文化。表姊妹因分屬不同宗族，關係親疏常隨母系往來頻率而變動，但總體較本宗堂姊妹更具彈性與私密性。交往多圍繞女紅、詩書、閨中密語等女性空間活動，且可能成為各家族信息傳遞的隱性渠道。在婚姻層面，表姊妹間存在潛在的競爭或互助關係，尤其當涉及家族聯姻時，這種關係可能轉化為複雜的情感與利益紐帶。表姊與表妹之間關系者，[MASK]也。
特指父親姊妹（姑母）所生男性子嗣間的關係，是表親中具有特殊禮法意義的分支。在宗法制度下，姑表親被視為『骨肉之親』的延伸，因姑母出自本宗，其子女與本宗的血緣認同感常高於舅表或姨表關係。姑表兄弟間往往保持較密切的經濟與社會互助，甚至在某些地區形成優先通婚的慣例（如『姑舅表婚』）。這種關係典型體現了古代『親親為大』的倫理觀念，既是血緣情感的載體，也是宗族網絡向外拓展的重要樞紐。姑表兄與姑表弟之間關系者，[MASK]也。
在中國古代宗法社會中，姑表兄妹屬於『外親』範疇，其關係具有雙重屬性：一方面因血緣相連而親近，常被視為『中表之親』，在禮法上允許密切往來；另一方面受『同姓不婚』原則影響，姑表兄妹因異姓（父系姓氏不同）反而成為傳統婚姻選擇中常見的『姑舅表婚』配對之一，即『姑母之子娶舅父之女』在部分地區被鼓勵，體現了『親上加親』的聯姻觀念。日常相處需遵循『男女有別』的禮教規範，但較無血緣關係的男女交往更為寬鬆。姑表兄與姑表妹之間關系者，[MASK]也。
此關係與姑表兄妹類似，同屬異姓中表親，但因涉及長幼有序的倫理秩序，表姊對表弟往往帶有類同胞的關照義務，尤其在家族活動中需體現『姊友弟恭』的互動模式。在婚姻層面，『姑表婚』的傳統中此組合亦可能成為聯姻對象（舅父之子娶姑母之女），但實際執行受地域習俗差異影響。交往時需在血緣親情與男女大防之間取得平衡，表姊常承擔部分教導年幼表弟的家族責任。姑表姊與姑表弟之間關系者，[MASK]也。
作為同性別的中表親，關係相對自由密切，可類比同胞姊妹但帶有外親特徵。她們的互動不受男女大防限制，常共同參與女紅、節慶活動，形成緊密的情感支持網絡。在宗法制度下，姑表姊妹雖分屬不同姓氏家族，但通過母系血緣連結，成為家族間信息傳遞與人情往來的紐帶。婚後仍可能保持往來，但關係重心會逐漸向各自夫族轉移。姑表姊與姑表妹之間關系者，[MASK]也。
舅表兄弟屬於母黨親屬，在古代『舅權』文化背景下具有特殊地位。舅父在家族中常擔當仲裁者角色，其子嗣與姑母之子間的關係因而帶有儀式性同盟色彩。表兄弟間可如胞兄弟般親密交往，共同參與學業、社交活動，且因異姓不構成宗族內權力競爭，關係多顯融洽。在重要家族事務中，舅表兄弟常作為外家代表發揮影響力，體現『娘親舅大』的倫理傳統。舅表兄與舅表弟之間關系者，[MASK]也。
此關係在傳統婚俗中尤為重要，是『姑舅表婚』的另一主要形式（姑母之子娶舅父之女）。舅表兄妹的聯姻被視為對母系血緣的回饋與鞏固，具有『骨肉還家』的象徵意義。日常交往中，表兄對表妹負有保護責任，而表妹對舅家表兄的尊重常高於其他表親。若未成婚，則需遵守中表親的交往界限；若成婚，則兼具血緣親屬與姻親雙重紐帶，關係結構更為複雜緊密。舅表兄與舅表妹之間關系者，[MASK]也。
在中國古代宗法制度下，舅表姊弟屬於外親關係，同源於外祖父母。舅表姊為母系兄弟之女年長者，舅表弟為母系兄弟之子年幼者。此關係受『男女有別』與『長幼有序』倫理雙重規範：表姊對表弟有照顧之責，表弟對表姊需持敬重態度。因屬異性表親，日常交往需遵循禮教約束，但較無同姓宗親的嚴格避忌。在婚姻方面，古代雖存在表親通婚習俗，但舅表姊弟聯姻在禮法上較少見，多見於文學作品中的特殊敘事。舅表姊與舅表弟之間關系者，[MASK]也。
此為母系表親中的同性關係，同出舅氏一門。在中國古代家族結構中，舅表姊妹因血緣相近且性別相同，往往有較密切的交往空間。她們的關係受『姊妹倫理』影響，強調相互扶持與情感連結，常見於閨閣往來、女紅切磋等女性社交範疇。由於同屬外親，關係親密度通常高於堂姊妹（父系宗親），但低於同胞姊妹。在宗法地位上，二人皆依附於父系家族，彼此關係不涉及宗祧繼承等核心利益，故相對純粹。舅表姊與舅表妹之間關系者，[MASK]也。
姨表兄弟係母系姊妹之子間的橫向關係。在中國古代『姨母如母』的觀念影響下，姨表兄弟常被視為準同胞關係，交往較為親近。此關係特點在於：一則因母系血緣紐帶產生天然親近感；二則因分屬不同父系家族，無直接宗法競爭，關係多帶互助性質。古代社會中，姨表兄弟可共同求學、遊歷，在仕途或商業上形成聯盟，體現『外親相輔』的社會功能。但若涉及家族利益時，仍以各自父系宗族為先。姨表兄與姨表弟之間關系者，[MASK]也。
此為母系異性表親關係，具有雙重文化意涵：一方面受『姨表親，輩輩親』俗諺影響，關係較為親密自然；另一方面因男女之防，需守『禮』的界限。在古代婚姻制度中，姨表兄妹通婚是常見現象（如《紅樓夢》中寶玉與黛玉），被認為能『親上加親』。這種婚姻模式強化了兩個母系家族聯盟，但亦受士大夫階層『同姓不婚，異姓可婚』觀念的複雜影響。非婚姻情境下，二人互動需有長輩在場或通過家庭活動進行，體現『發乎情，止乎禮』的交往模式。姨表兄與姨表妹之間關系者，[MASK]也。
此關係呈現中國古代倫理中『長幼』與『男女』規範的交織。姨表姊作為年長女性，對表弟有教導、關照之責，類似『半師半姊』的角色；表弟則需對表姊表現尊敬與順從。這種關係常體現在家庭教育場景中，如表姊指導表弟讀書習禮。由於存在年齡與性別雙重差異，其親密程度通常低於姨表兄妹，但高於完全無血緣的男女交往。在婚姻層面，姨表姊弟婚配較為少見，因傳統婚配偏好男長女幼的結構，但特殊情況下（如家族安排）亦可能發生。姨表姊與姨表弟之間關系者，[MASK]也。
此为母系亲属关系中的平辈关系，属中表亲范畴。在宗法制度下，姨表姊妹虽非同姓本宗，但因母亲同出一源，关系较一般姻亲更为亲密。古代社会注重‘姨母如母’的伦理观念，姨表姊妹常以‘外家姊妹’相称，情感联结多带闺阁情谊，婚嫁前常有共同生活或往来，其亲密程度常介于亲姊妹与普通朋友之间，且关系受‘男女有别’礼教约束，婚后随各自家庭重心转移可能渐疏。姨表姊與姨表妹之間關系者，[MASK]也。
此为典型姻亲关系中的尊卑纵向关系，属‘外姻’范畴。岳父称婿为‘娇客’，既体现对女婿的客礼相待，又强调其非本宗成员的身份。关系以‘半子’伦理为核心——女婿需以事父之礼敬岳父，但岳父对其权威远低于对亲子；经济与宗族事务上女婿通常不介入岳父家族内部事务。关系受‘礼’严格规范，强调恭敬而非亲密，常见于节庆仪式性往来，且岳父对女婿的考察常关联女儿在夫家的地位。岳父與子婿之間關系者，[MASK]也。
此为姻亲关系中具有特殊礼法约束的尊卑关系。古礼强调‘男女授受不亲’，岳母与女婿间需保持‘疏不间亲’的距离，日常接触受限，尤忌独处。岳母对女婿的关怀多通过女儿间接表达，或体现于物质馈赠；女婿对岳母需持礼敬态度，但较之对岳父更少涉及责任义务。此关系常被形容为‘客情’，即客气有余而亲昵不足，在‘内外有别’的宅院空间中，岳母通常通过家庭女性成员与女婿间接沟通。岳母與子婿之間關系者，[MASK]也。
此为父权宗法制度下最具礼教敏感性的家庭关系之一，严格遵循‘男女之大防’。公公作为家长权威代表，与儿媳须保持极端疏离，日常‘不见面、不对话、不独处’是士大夫家庭常态。儿媳对公公需绝对恭敬，晨昏定省时亦多隔帘行礼；公公对儿媳的训导须通过儿子或婆婆转达。此关系完全建立在宗法伦理框架内，强调‘严肃恭敬’，情感交流几近于无，且公公对儿媳的评价直接影响其在家族中的地位。公公與兒媳之間關系者，[MASK]也。
此为父权家庭中最重要的女性纵向关系，具有支配与服从的鲜明特征。婆婆作为内宅权威，对儿媳享有教导、监督、惩戒的权力，关系本质是‘婆尊媳卑’的统属关系。古代‘新妇事舅姑如事父母’的礼法要求儿媳对婆婆绝对顺从，且需经历‘多年媳妇熬成婆’的漫长考验。此关系常包含实际生活指导、家务劳动分配、生育监督等日常互动，情感上既有‘母女’名义的伦理期待，又因权力结构易生矛盾，成为古代家庭戏剧的核心冲突之一。婆婆與兒媳之間關系者，[MASK]也。
此为外亲姻亲关系，属尊卑有序的伦理关系。舅父为母系尊长，甥媳为晚辈姻亲，二者关系受‘男女有别’与‘长幼有序’双重礼法约束。日常交往需恪守礼制，保持端庄距离，舅父对甥媳有泛化的家族监护责任，但不宜直接干涉其家务。在重大家族仪式中，甥媳需对舅父行晚辈礼，体现‘尊尊亲亲’的宗法精神。舅父與甥媳之間關系者，[MASK]也。
此为外亲与姻亲的交叉关系，带有半拟制性亲属色彩。舅父作为母方权威代表，对甥婿既有长辈的关怀义务，亦隐含对甥女婚姻状况的间接监督权。二者交往较甥媳更为宽松，可涉及家族事务商议，但仍需遵循‘敬长’原则。甥婿对舅父的礼敬程度常被视为衡量其家族融入度的重要标尺，关系本质是宗族网络的外延联结。舅父與甥婿之間關系者，[MASK]也。
此属宗亲核心圈层的尊卑关系，具有严格的礼法边界。伯父作为父系直系尊长，对侄媳负有家族教化责任，但受‘男女大防’制约，日常接触需通过家族女性成员中转。在祭祀、分产等重大事务中，伯父的权威可间接影响侄媳权益，而侄媳则需通过丈夫或姑舅履行对伯父的礼节义务，体现‘内外有别’的宗法秩序。伯父與侄媳之間關系者，[MASK]也。
此为宗亲与姻亲的垂直关系，带有明显的父权制特征。伯父作为家族权力结构的核心成员，对侄婿具有实质性的指导与约束权，尤其在职业选择、家族事务参与等方面影响力显著。二者关系以‘孝悌’伦理为基础，侄婿需主动向伯父请益，伯父则通过提携侄婿巩固家族势力。这种关系常成为家族资源代际传递的重要渠道。伯父與侄婿之間關系者，[MASK]也。
此为平辈姻亲关系，具有双向互助性与弹性权力结构。姊丈作为姐姐的丈夫，与妻弟形成‘郎舅之亲’，既有拟制性兄弟情谊，又存在隐性的利益联盟属性。在礼法上姊丈为尊，但实际相处常随双方年龄、社会地位动态调整。这种关系是家族联盟的横向纽带，既承担互助义务，也是调解姐妹在夫家处境的重要缓冲机制，所谓‘亲不过郎舅’即指其特殊亲密性。姊丈與妻弟之間關系者，[MASK]也。
此关系属于姻亲中的‘异姓连襟’关系。妹婿是妻子兄弟的妹妹之夫，在宗法制度下属于‘外姻’。双方关系以妻子家族为纽带，通常遵循‘亲疏有别’的原则：妻兄作为妻子本家的男性代表，对妹婿有一定礼仪上的尊长地位，但实际交往中更接近平辈姻亲，关系亲密度取决于两个联姻家庭的实际往来。在礼制上，双方互称‘姻兄’‘姻弟’，婚丧仪式中需按姻亲礼节互动。妹婿與妻兄之間關系者，[MASK]也。
此关系属于交叉姻亲关系。妹婿是妻子姐妹的丈夫，但妻姊在辈分上为长。古代家庭伦理中，妻姊地位高于妹婿，妹婿需以‘姨姊’相称并持敬重态度。由于涉及两个婚姻组合，双方关系往往受姐妹关系亲疏影响，在家族活动中需遵循‘长幼有序’的礼仪，但无严格法律义务。这种关系常见于大家族联姻网络，具有巩固家族联盟的社会功能。妹婿與妻姊之間關系者，[MASK]也。
此关系属于宗亲内的‘叔嫂伦理’，是五伦之外的重要家庭关系。在儒家礼法中，叔嫂之间需严格遵守‘叔嫂不通问’的防嫌原则（《礼记·曲礼》），日常交往需保持距离，禁止私相授受。但长嫂如母，若兄长早逝，叔对守节之嫂应持敬如母的态度。这一关系典型体现了古代‘男女有别’‘长幼有序’的双重伦理约束，是家族内部秩序的关键环节。叔與嫂之間關系者，[MASK]也。
此关系是血亲与姻亲的交织关系。姑作为丈夫的姐妹，在传统家庭结构中具有特殊地位：未嫁时是夫家血亲，已嫁后成为‘外嫁女’。姑嫂相处遵循‘姑尊嫂卑’的原则，未婚小姑在娘家地位常高于新妇，易生‘姑恶’现象。但礼法要求‘嫂敬姑慈’，双方需维持表面和谐以保家族稳定。这一关系反映了女性在父权家族中‘既 insider 又 outsider’的复杂身份。姑與嫂之間關系者，[MASK]也。
此关系属于宗法家庭中的‘叔伯-弟妇’关系。伯作为丈夫的长兄，在家族中具有权威地位。双方需严格遵循‘男女大防’与‘尊卑有序’，交往仅限于公开场合的礼节性问候。若丈夫早逝，伯对守节弟媳有监护责任，但不可直接接触，需通过女性亲属转达。这一关系体现了古代家族中‘兄权’对旁支婚姻单位的约束力，以及礼法对异性姻亲交往的极端限制。弟媳與伯之間關系者，[MASK]也。
在中國古代宗法社會中，兄妻（妯娌中的兄嫂）與弟妻（弟婦）的關係稱為『妯娌』。這是一種因兄弟婚姻而結成的擬血親關係，其相處遵循『長幼有序』的原則，兄嫂通常具有較高的家庭地位與話語權。妯娌關係常以『和』為貴，但實際中亦可能因家產分配、婆媳互動或子女教養等產生微妙競爭。在禮教規範下，雙方需維持表面和睦，共同承擔家族內務勞動與祭祀責任，體現『同居共財』家族結構中的協作與張力。兄妻與弟妻之間關系者，[MASK]也。
姊丈（姊夫）與妹婿（妹夫）的關係屬於『連襟』（亦稱『婭婿』）。這是一種通過姊妹婚姻結成的男性姻親關係，在宗法制度中屬於『外姻』範疇。連襟之間雖無直接血緣或經濟共同體義務，但常因家族聯姻、社會網絡構建而產生互助關係。古代士大夫階層中，連襟可能形成政治或文學同盟；在民間則體現為節慶往來、勞力互助等。此關係受『門當戶對』觀念影響深，雙方家族背景的對等性往往決定互動的緊密程度。姊丈與妹婿之間關系者，[MASK]也。
『婚家』指通過婚姻結成的兩姓家族關係，即『姻親』。在古代中國，這是一種重要的社會聯盟形式，具有強烈的宗族性與禮儀性。其內涵包括：1. 締結『秦晉之好』，強調兩姓世代通婚的盟約性；2. 遵循『六禮』規範的儀式性互動；3. 在政治、經濟層面形成互助網絡（尤見於士族門閥）。婚家關係受《朱子家禮》等規範制約，講究『禮尚往來』，但嫁女之家常處於相對謙卑地位，反映古代婚姻的『從夫居』特質與家族利益交換本質。婚家與婚家關系者，[MASK]也。
從祖父指祖父的兄弟（即伯祖父、叔祖父），從孫指兄弟之孫。這屬於『從父』宗親關係中的隔代縱向連結，在五服制度中屬『小功』或『緦麻』親。其特點為：1. 宗法意義上，從祖父對從孫有輔助教導之責，但監護權弱於直系祖父；2. 在家族祭祀中，從孫可能擔任從祖父支系的輔祭角色；3. 財產繼承上，從孫僅在『戶絕』等特殊情況下可獲得從祖父遺產。此關係體現古代『大宗-小宗』體系中旁系親屬既疏離又協作的倫理張力。從祖父與從孫之間關系者，[MASK]也。
此關係除具備從祖父與從孫的宗法特徵外，更顯現性別差異下的特殊規範：1. 從孫女在家族祭祀中通常無參與權，與從祖父的互動受限於『男女授受不親』的閨闈制度；2. 從祖父對從孫女的監護權體現在婚配決策上，可對其父母提出建議，但決定權低於直系祖父；3. 經濟關係上，從祖父可能在從孫女出嫁時贈送妝奩，以彰顯家族凝聚力。此關係折射出古代宗族制度中女性作為『邊緣化宗親』的依附性地位。從祖父與從孫女之間關系者，[MASK]也。
從祖母是祖父兄弟之妻（即伯叔祖母），從孫是孫輩中非直系但屬同宗旁支的男性後代。此關係屬五服內的旁系尊卑倫常，遵循《儀禮·喪服》中‘從祖祖父母’的服制規範（緦麻三月）。從祖母對從孫有宗族內的禮儀性教導責任，從孫需執恭順之禮，體現‘雖疏猶尊’的宗法原則。從祖母與從孫之間關系者，[MASK]也。
關係性質同從祖母與從孫，但性別為女性後代。在宗法制度下，從孫女對從祖母的禮節與從孫相同，但因其女性身份，更側重閨門內的女德傳承與婚嫁指導。祭祀活動中從孫女常協助從祖母進行內眷禮儀，體現‘男女有別，尊卑有序’的倫常分工。從祖母與從孫女之間關系者，[MASK]也。
從祖姑是祖父的姐妹（即姑祖母），從侄孫是侄孫輩的旁支男性後代。此關係屬‘外親’範疇但受宗法約束，服制為緦麻。從祖姑在家族中具有‘姑權’象徵，對從侄孫有道德訓誡之責，從侄孫逢年節需行謁見禮。關係特點融合血緣尊長與外嫁女性的雙重身份，體現‘姑尊侄卑’的禮法傳統。從祖姑與從侄孫之間關系者，[MASK]也。
指同曾祖父不同祖父的兄弟關係（即三從兄弟，古稱‘族兄弟’）。屬五服最邊緣的‘族兄弟’範疇，服制為緦麻。關係特點為‘親盡而義不盡’，雖血緣已疏，但在宗族活動中仍按長幼序齒，共守族規。經濟與法律上已無連坐責任，但宗族祭祀時需協作，體現‘收族’的宗法精神。再從兄與再從弟之間關系者，[MASK]也。
指同高祖的兄弟關係（即四從兄弟），已出五服。按《禮記·大傳》‘四世而緦，服之窮也’，此關係已無法定喪服義務，但仍在‘九族’概念內。交往依鄉黨禮俗而非宗法強制，強調‘同姓之誼’，在修譜、祭祖等重大宗族活動中保持禮儀性互動，體現‘百世不通婚’的宗族認同邊界。三從兄與三從弟之間關系者，[MASK]也。
堂伯与堂侄是基于父系宗族（同姓同宗）的亲属关系。堂伯是父亲堂兄弟中较年长者，堂侄则是堂兄弟之子。在宗法制度下，这种关系属于‘五服’内的‘期亲’（齐衰不杖期），具有明确的尊卑秩序。堂伯对堂侄有教导、庇护之责，堂侄则需恭敬遵从。在家族事务（如祭祀、分产）中，堂伯常作为宗族代表参与决策，关系较近但次于直系伯侄。堂伯與堂侄之間關系者，[MASK]也。
表叔与表侄是基于母系或嫁出女性亲属（异姓外亲）的亲属关系。表叔是母亲或出嫁姐妹的兄弟之子，表侄则是己身或兄弟之子。此关系属‘外亲’，在宗法体系中地位低于父系亲属，但仍有‘亲亲之义’。表叔对表侄的约束力较弱，关系以情谊为主，常见于年节往来或互助。古代‘表亲不通婚’的禁忌亦体现其亲属边界，但较之堂亲更为松散。表叔與表侄之間關系者，[MASK]也。
族伯叔与族侄是同宗但已出‘五服’的远房亲属关系。族伯叔是同一高祖以上祖先的后代中较父辈年长者。在宗族结构中，虽血缘疏远，但仍受‘同姓一家’观念维系。关系以宗族共同体为纽带，在修谱、祭祖、族田管理等事务中体现尊卑秩序。族伯叔可凭辈分参与族内公共事务调解，但对族侄无直接约束力，更多依靠族规乡约维系伦理距离。族伯叔與族侄之間關系者，[MASK]也。
族兄与族弟是同宗平辈男性关系，通常指出五服外的同辈族人。在宗族谱系中按昭穆排序，虽血缘已远，但仍以‘兄弟’相称，体现‘天下同姓为一家’的宗法观念。关系强调长幼有序（族兄为尊），在宗族活动中需遵守相应礼仪。日常交往中既有互助义务（如科举、经商提携），又因血缘疏淡而保持一定距离，是宗族网络中的横向伦理纽带。族兄與族弟之間關系者，[MASK]也。
族姊与族妹是同宗平辈女性关系，多指出嫁前的同族姐妹。在父系宗法下，女性在族谱中记载简略，关系主要通过父兄的宗族身份界定。未嫁时在族内共同参与女红、祭祀准备等活动，依年齿互称姊妹；出嫁后则随夫家身份定位，与原族姐妹关系逐渐淡化。此关系受‘男女有别’规范影响，交往限于闺阁之内，情感联结常让位于宗族礼仪要求。族姊與族妹之間關系者，[MASK]也。
这是基于父系宗族血缘的隔代旁系亲属关系。堂祖父是祖父的兄弟之子，属于同曾祖父的旁系长辈；堂侄孙则是堂兄弟之孙，属于同高祖的旁系晚辈。这一关系体现了古代宗法制度中‘五服’亲属的范围，虽非直系，但在祭祀、家族事务中仍有一定联系，其亲疏程度在《仪礼·丧服》中被归为‘缌麻’之亲。堂祖父與堂侄孫之間關系者，[MASK]也。
这是通过婚姻联结的宗族旁系隔代关系。堂祖母是堂祖父的妻子，虽无血缘关系，但通过婚姻进入父系宗族体系，在礼法上被视为家族成员。堂侄孙作为夫家旁系晚辈，需对其行尊长之礼。这一关系反映了古代‘夫妇一体’的宗法观念，女性通过婚姻获得在夫族中的伦理地位，并与夫族亲属形成拟制性亲属关系。堂祖母與堂侄孫之間關系者，[MASK]也。
这是由婚姻与血缘交叉形成的复合性姻亲关系。堂姊丈是堂姐的丈夫，属于姻亲中的‘外姻’；堂妻弟则是妻子堂兄弟的称谓，属妻党旁系亲属。两者间无直接血缘或婚姻联结，其关系建立于‘堂姐’与‘妻子’两个女性亲属的桥梁作用上，属于较疏远的间接姻亲，在传统礼制中互动较少，但仍需遵循‘男女有别’‘尊卑有序’的交往原则。堂姊丈與堂妻弟之間關系者，[MASK]也。
这是母党或妻党姻亲与父党旁系亲属的交叉关系。表嫂是表兄弟之妻，属外姻平辈；表叔则是父亲的表兄弟，属父党旁系长辈。两者分属不同亲属体系（表亲属‘外亲’，表叔属‘父党’），关系较为疏远。古代强调‘内外有别’，此类交叉关系在礼仪上需依各自辈分行礼，但实际社会交往中往往因亲属圈重叠而产生互动，体现了传统亲属网络的复杂性。表嫂與表叔之間關系者，[MASK]也。
这是完全基于婚姻联结的拟制性尊卑关系。姻伯叔指姻亲中的长辈男性（如妻子的伯叔、女婿的伯叔等），姻侄则是其对应的晚辈称谓。此类关系完全依靠婚姻建立，无血缘基础，属于‘三党’（父党、母党、妻党）中的姻亲范畴。在礼法上，双方需遵循‘尊长恤幼’的伦理规范，但其权利义务弱于血亲关系，且随婚姻存续而存在，具有较大的情境性与可变性。姻伯叔與姻侄之間關系者，[MASK]也。
舅公是母亲的舅舅，甥孙是姐妹的孙子。这是基于母系血缘延伸的跨代亲属关系，属于外亲范畴。在古代宗法制度下，舅公作为母族尊长，对甥孙具有礼仪性的权威和关爱责任，尤其在婚丧、分家等事务中常扮演见证或调解角色。甥孙则需对舅公保持尊敬，逢年过节或重要场合需行礼问候。这种关系体现了古代家族网络中母系纽带的重要性。舅公與甥孫之間關系者，[MASK]也。
姨婆是母亲的姨母，姨甥孙是姐妹的孙子。这是通过母系姐妹血缘联结的跨代亲属关系，属于外亲。姨婆作为母亲的长辈，对姨甥孙有慈爱关照的义务，尤其在母亲原生家族活动中（如祭祀、团聚）常体现亲密互动。古代社会重视'姨亲如母'的观念，姨婆在甥孙家庭遇到困难时可能提供支持，但相较于直系祖孙，其责任更多体现在情感与礼仪层面。姨婆與姨甥孫之間關系者，[MASK]也。
继祖父是祖父的续弦丈夫，继孙是儿子或女儿的子女。这是通过再婚形成的拟制直系亲属关系，缺乏血缘纽带。在古代宗法体系中，继祖父对继孙的权威较弱，但若继祖父承担了抚养责任，则双方需遵循'孝道'伦理，继孙应对其表示尊敬。家庭地位取决于继祖父是否被家族正式接纳，财产继承权通常受限，关系常受原生家族与继亲家族平衡的影响。繼祖父與繼孫之間關系者，[MASK]也。
继祖父是祖父的续弦丈夫，继孙女是儿子或女儿的子女。这是性别化的拟制直系关系，除继承关系特征外，还受到古代性别规范的影响。继祖父对继孙女负有道德保护责任，尤其在婚嫁事务中可能参与意见。继孙女需遵守'男女有别'的礼仪，保持适度尊敬。这种关系常因缺乏血缘而较为疏淡，但在强调家族和睦的伦理框架下，双方仍需维持表面礼数。繼祖父與繼孫女之間關系者，[MASK]也。
继祖母是祖父的续弦妻子，继孙是儿子或女儿的子女。这是通过婚姻联结的拟制直系关系。古代家庭中，继祖母若得到家族承认，可享有祖母的部分礼仪地位，但对继孙的管教权有限。继孙需对其行孝道礼仪，但情感亲密度常取决于继祖母是否生育子嗣及在家族中的实际地位。在祭祀、分家等事务中，继祖母通常不能完全等同于原生祖母，其关系受'嫡庶尊卑'观念影响较深。繼祖母與繼孫之間關系者，[MASK]也。
在中國古代宗法制度下，繼祖母是祖父續娶的妻子，與繼孫女無血緣關係，但通過婚姻進入家族。禮法上繼祖母享有祖母的名分與尊敬，繼孫女需執孝道禮儀，但實際親密度與情感連結常取決於家庭具體情境。宗族活動中繼祖母可參與教導女德、婚嫁指導等事務，其地位雖不及原配祖母，仍受家族禮制保障。繼祖母與繼孫女之間關系者，[MASK]也。
繼外祖父是母親繼父，與外孫無血緣紐帶。古代外戚關係本就較父系疏遠，繼外祖父更處親緣邊緣。禮儀往來多依母親的聯繫而定，若母親與繼父感情深厚，外孫或需執節問安；然在宗法體系中，繼外祖父對外孫幾無權威或義務，關係多流於形式性的禮節往還。繼外祖父與繼外孫之間關系者，[MASK]也。
此關係較外孫更添性別隔閡。古代女性深居簡出，繼外祖父與外孫女接觸有限，僅在年節家宴等場合依禮問候。外孫女對繼外祖父的禮敬程度常取決於母親態度，且因外嫁後關係更為淡薄。繼外祖父對外孫女幾無教養或婚配決定權，屬禮制框架下極疏遠的姻親連結。繼外祖父與繼外孫女之間關系者，[MASK]也。
繼外祖母是母親繼母，與外孫無血緣。古代女性通過婚姻進入外家，其名分雖為外祖母，但實際親疏受母親與繼母關係深刻影響。若母親幼受其撫育，則外孫或需以孝親之禮待之；然因外孫屬外姓男丁，繼外祖母對其教養、仕途等幾無介入空間，關係多體現為年節饋贈、問安等儀式性往來。繼外祖母與繼外孫之間關系者，[MASK]也。
雙重邊緣化的關係：既無血緣又屬外姓女性親屬。古代社會中，繼外祖母對外孫女的影響僅可能體現在女紅、婦德等閨閣教習場合，且須透過母親中介。外孫女出嫁後，此關係幾近斷裂。禮制雖要求『敬老』的普遍原則，但具體互動極度依賴家庭個案情感，宗法體系中幾乎不被記載或規範。繼外祖母與繼外孫女之間關系者，[MASK]也。
在宗法制度下，繼父子關係雖無血緣但受禮法約束。繼父對繼子有教養之責，但繼子對繼父的服喪規格低於生父（《儀禮·喪服》載『繼父同居者期，不同居者無服』）。財產繼承權常受限，需通過『立嗣』程序強化關係。關係核心在『義』而非『親』，易受家族內部張力影響。繼父與繼子之間關系者，[MASK]也。
受『男女之防』禮教嚴格規範，關係較繼父子更為疏離。繼父對繼女負監護教養之責至出嫁，但日常接觸受限。繼女出嫁後與繼父基本脫離法律關係，喪服僅為緦麻（三月）。財產繼承權極弱，關係本質是暫代性的監護義務，強調『防嫌』與『名節』維護。繼父與繼女之間關系者，[MASK]也。
宗法社會中極敏感的倫理關係。繼母雖具嫡母名分（《禮記·曲禮》『繼母如母』），但實際常受『晚娘苛待』社會敘事影響。繼子對繼母需行孝道，服斬衰三年，但繼母對繼子的教養權受族親監督。財產爭端多發，宋代後司法實踐中常以『母子名分』調解矛盾。繼母與繼子之間關系者，[MASK]也。
受女教體系塑造的閨閣關係。繼母對繼女的教化責任重於繼子，涉及女德、女紅等出嫁前培訓。關係親疏取決於繼母是否生有己女，易形成閨閣內權力階序。喪服同親生母女（齊衰三年），但情感聯結多依賴繼母個人德行，文學作品中常呈現為壓迫或救贖的兩極敘事。繼母與繼女之間關系者，[MASK]也。
屬『同父異母』或『同母異父』的特殊兄弟關係。宗法上區別於『同氣連枝』的嫡親兄弟，喪服降等（《儀禮》載『繼兄弟之服小功』）。共居時按長幼序齒，但分家時繼兄弟的財產權常低於嫡親子。關係游移於『義兄弟』與『血緣兄弟』之間，科舉時代的繼兄弟同年現象是重要聯結紐帶。繼兄與繼弟之間關系者，[MASK]也。
在宗法制度下，继兄妹因父母再婚形成拟制血缘关系。虽无直接血缘，但受'男女有别'礼教约束，日常相处需遵循'兄妹之礼'，在家庭伦理序列中通常比照亲兄妹定位。财产继承权低于嫡子，但若家族认可，仍可享有部分家族照顾义务。繼兄與繼妹之間關系者，[MASK]也。
受长幼有序伦理影响，继姊对继弟存在一定教导与照拂责任，类似'长姊如母'的延伸。弟对姊需持敬重态度，这种关系往往承载着维系重组家庭稳定的象征意义，其亲密程度常取决于继父母的实际态度及家族宗亲的认可度。繼姊與繼弟之間關系者，[MASK]也。
在女性内闱空间中形成的生活共同体关系。既共享'同室而居'的日常亲密性，又因继女身份存在潜在竞争（如嫁妆分配、婚配资源）。情感纽带常取决于生母在家庭中的地位及双方年龄差，宗族文书多将之统称为'姊妹'而不刻意区分血缘。繼姊與繼妹之間關系者，[MASK]也。
通过正式收养仪式建立的拟制父子关系，需经宗族见证与官府备案。养子可入宗谱、改姓氏，承担祭祀重任，法律地位近似嫡子。但实际家庭地位常受原生家庭背景、收养年龄及族老态度影响，经典案例可见《唐律疏议》对养子继承权的细致规定。養父與養子之間關系者，[MASK]也。
具有双重伦理属性：对外遵循'父子之伦'，养女需恪守孝道与闺阁礼法；对内隐含'男女大防'的特殊张力。养女婚姻权完全掌握在养父手中，其出嫁往往承载着为养父家族缔结社会联盟的功能，汉代'假子'现象中常见此类政治联姻案例。養父與養女之間關系者，[MASK]也。
在中國古代宗法制度下，養母與養子關係雖非血緣所繫，但經由正式收養程序（如過繼、立嗣）建立，具有法律與倫理上的親子效力。養子通常承擔祭祀、繼承家業的責任，養母則享有嫡母的尊嚴與孝養義務。此關係受《禮記》與歷代律法規範，強調『繼絕世』的宗族延續功能，情感上雖可能親如己出，但社會地位仍以宗法承嗣為核心。養母與養子之間關系者，[MASK]也。

FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'bert_embedding_data' -> 'bac/q1.1_bert_embedding_data'

In [6]:
for query_num, query_row in df_query.iloc[2:, :].iterrows(): 
    arr_tit = ["CLS", "MASK"]
    
    util = utils(arr_tit, unmasker.tokenizer.tokenize)
    text = query_row['Query']
    for v in [1,2]: # no additional requirement, just for create new files
        # output layer
        hook_manager.add_hook(unmasker.model.bert.encoder, util.getHook("embedding_output", v, reset = True))
        # 12 encoder layer
        for i in range(12):
            hook_manager.add_hook(unmasker.model.bert.encoder.layer[i], 
                                  util.getHook("encoder_layer%s" % i, v, reset = True))
        hook_manager.remove_hooks()

    for i, row in df_desc.iloc[:, :].iterrows():
        use_word = text.replace("[DESC]",row['description']).\
                   replace("[TERM]",row['query'])
        print(use_word)

        hook_manager.add_hook(unmasker.model.bert.encoder, util.getHook("embedding_output", 
                              row["query"], use_word))
        # 12 encoder layer
        for i in range(12):
            hook_manager.add_hook(unmasker.model.bert.encoder.layer[i], util.getHook("encoder_layer%s" % i, 
                                                                                     row["query"], use_word))
        res = unmasker(
            use_word
        )
        hook_manager.remove_hooks()
    time.sleep(5)
    os.rename("bert_embedding_data", "bac/q{}_bert_embedding_data".format(query_num))

男女曖昧之事，悖於人倫，是以隱於心而不擅發於外。其或發於外者，亦以含蓄之言，傳微妙之情，假落紅秋葉之詩，托香囊繡帕之物，暗致其情，不令外人見也，多是之類也。曖昧者之間，何以言喻？[MASK]也。
暗戀者，古語或謂單相思。男女之間，礙于父母之命，媒妁之言，婚姻之有定也，於是己固思慕彼而不敢以私意白，彼未知而己切思之，求之不得，其情之至者，所謂“寤寐思服，輾轉反側”是也。其恪于禮者，常以春蠶絲盡、桃花依舊之喻，暗寄其心而不外傳，亦或以暗中護助，不令其有艱困愁苦，而其稍逾制者，則或致佩飾之物也。古之暗戀者，多止乎此，至若季世綱常已墮，男女忽於大防，暗戀轉直，單思為雙，則奔者難禁。暗戀者與被暗戀者之間，何以言喻？[MASK]也。
報案者之于受害者也，或同系一人，或其鄰裡親朋之知情者也。自秦法以降，遞有閭閻連坐之策，凡知情不舉者，按律當坐，王安石所目保甲法，即是也。然世有升降，國有治亂，保甲連坐之策，可行乎令行禁止之時，而文恬武嬉之季，多具文視之耳。且古時刑偵之術寡而限期破案之律在，案犯易脫幹係而有司則損利祿，是以報案者亦須證據確鑿，無可指摘，庶免乎官府之糾擾而人財俱困也。又自董子以來，列朝以儒治國，親親相隱之教，風乎百世，是以近親之間，若非大義滅親之舉，概以不報官府為長，而以鄉約族規處置也。報案者與受害者之間，何以言喻？[MASK]也。
報案者與罪犯之間多對立之關系。報案者舉罪犯之罪，冀以律法懲之。然報案者或有因擿伏發隱而罹罪犯相脅相報之禍者也。又以保甲連坐之製與大義滅親之理，報案者與罪犯之間亦或為親戚鄰裏，此又非必是兩立之勢也。報案者與罪犯之間，何以言喻？[MASK]也。
文選詩集之編者與作者，或因敬重欣賞之情，或為功利實在之用。其功利實在之用著，如著者為高官、長輩、恩師者也，甚者編者或側己文於他人之文，以彰己名也。裁約編選之時，編者常善著者之才華功業。編者亦以其選裁左右讀者之理解。文選詩集之編者與作者，實為古時文人之文化品味、審美觀念、權力關係之鑒鏡也。文選之編者與作者之間，何以言喻？[MASK]也。
表兄弟姐妹者，視同近親，關系親近，家族之情亦深也。彼於童稚之時，可共遊學、相長互助，共解所遇之危難。禮，表兄弟姐妹須循一定之禮節，長愛少，少敬長。及漸長，循授受不親之訓，以其為異姓，可通婚姻故也。表兄弟姐妹之間，何以言喻？[MASK]也。
庖人之與食客者，為服務被服務之關系也。庖人主烹飪，以甘美之食奉食客，而食客亦須念庖人之生計。故庖人須盡其技以足食客之口，食客亦須慎待庖人所供之物，此亦理之常也。或有庖人專供於食客或主人之家，則曰名廚或私廚，其與食客主人之關系則更甚其他庖人也。庖人與食客之間，何以言喻？[MASK]也。
仇敵之間乃對立衝突之關係也。敵者，匹敵也，論其才智，則相儔類，而或以利益之不均、或以地位之不匹、或以權力之不及、或以忠誠之不貞，諸此之屬，心生怨望而欲戕害以快其心者，仇敵之事也。然則，仇敵既以相噬為常，亦以其相匹，而或生相惜之感，且古時人分等級，同匹儔之人，其未為仇敵之初，或有通家之好，秦晉之交而同窗之誼也，是以古之仇敵，視今日為複雜也。故經史詩賦之中，感概仇敵之才智氣節者，亦不知凡幾也。仇敵之間，何以言喻？[MASK]也。
施恩者與受恩者為恩義與感恩之關係。施恩者之助受恩者也，或以善行，或以援手，受恩者遂感念其德，雖滴水之恩，木瓜之贈，亦矢報以湧泉瓊瑤也。古以'知恩圖報'為德之大者也。施恩者與受恩者之間，何以言喻？[MASK]也。
青梅竹馬，即為男女自幼同遊嬉戲，心生情愫者也。其情純真深沉，或終為伉儷，或為知己。古時文人墨客之述此情者，至純至美，感人心脾。青梅竹馬之間，何以言喻？[MASK]也。
情敵者，二三人傾慕同一對象，遂相競爭。此關係中，有敵意、嫉妬、競爭至於殺心之複雜心緒，然亦或有互尊呼諒者。經史詩賦之中，論及情敵，常有激烈戲謔之矛盾，或高雅而囿於禮法，或直率而流於粗鄙。情敵之間，何以言喻？[MASK]也。
天人之間，乃天地人三才之並立關系，人宜順天地，而與萬物為一。儒道皆謂人當敬天地而順之，於是乎則和也。欲和天人，需通天意，欲通天意，則在貫三才之王者，以儒家正典之論，王者得位聖賢之大號，非權勢之稱也，是以為古代知識階層與君主權力間之製衡也。天人之間，何以言喻？[MASK]也。
人神之間以信仰敬畏為維繫，其方式不離祭祀、祈禱以通達於神靈也，其指歸在乎求得神靈庇佑，解其大惑，脫其苦厄，堅其心志，導其前路也。今之視古，則謂古之信神，原乎科技落後，而驚懼敬畏于自然未知之力量也。然商周以降，中華之地，人以配天，民為神主之論，敬鬼以遠之教，人能弘道之言，天命從德之誡，經籍之載，三教之說，鹹崇人之踐行而斥虛妄之求神也。然則子雖不言怪力亂神，而人之不齊，一致百慮，可導而不可壅，是以君子明辨天理，不惑神鬼，而不責民間之求神問卜以行善避災也。人神之間，何以言喻？[MASK]也。
泛泛之交，乃交情淺薄之普通關係也。於此關係，彼此不通心意，交遊往來，相待以禮而已。泛泛之交，或可謂之朋友，然為關係最疏者也。泛泛之交之間，何以言喻？[MASK]也。
店主與顧客，為買賣交易之雙方也。店主供貨品服務於顧客，顧客以財貨償之。店主須竭其誠以應顧客之需，顧客亦需尊店主之恭敬服務于我也。所謂“買賣不成仁義在”，古時買賣之道，理不逾此。店主與顧客之間，何以言喻？[MASK]也。
官場之尊卑上下，不可逾距。上之於下，等級之中，所差愈多，威勢愈強。是以官員之間，忠敬為首，然忠敬者，忠於所守也，非忠於上司某甲也。上之於下，亦有訓導保全之義，此即古之尊卑有序、和諧中正之道也。然世閒多難行也。官場之上下級之間，何以言喻？[MASK]也。
買賣之夥伴，所共求止於利而已，緣此須相信相助，共分其利。其間信與平最為重，買賣之夥伴須以誠交易，以平分利。彼此亦須行為相協，言語相洽，以求買賣之順遂。買賣之夥伴之間，何以言喻？[MASK]也。
買賣之競爭對手，以欲求多利，欲天下求購者多求於己而俾天下財富多歸於己，於是乎有對手生焉。然生財亦當有道，故相競爭者雖有相爭之欲而求勝於對方，亦皆須守信持中，不得狡求他人之利。要之，亦有尊重也。買賣之競爭對手之間，何以言喻？[MASK]也。
宗教師徒，在於信仰之傳續繼承。師者，教訓徒弟，徒者，尊師重道，忠於師命。其間尊與忠為最重，徒須尊師忠命，師須護持教徒。宗教師徒之間，何以言喻？[MASK]也。
百工之師父與學徒，在於技藝之傳承。傳技之時，師者須教導訓誡其徒，徒者須尊敬愛重其師。其間尊與忠為最重，徒須尊師忠命，師須護持教徒。師傅與學徒之間，何以言喻？[MASK]也。
古之掌櫃與客人，因買賣交易為緣。掌櫃者經營其店。客人者消費之人也，求店主之所供。掌櫃須供客人所需，以求信與利。客人亦須敬重掌櫃，不得違其買賣之道。掌櫃與客人之間，何以言喻？[MASK]也。
古之首領與反賊，以勢不兩雄為常。首領者，為國之首領，反賊者，為國之叛逆。首領須守其威勢與現有之秩序，反賊則欲反叛其威勢與現有之秩序。首領與反賊之間，何以言喻？[MASK]也。
叔侄為血親。叔者為父之弟，侄者為兄之子。叔有教育侄之責，侄須愛敬叔，然亦須視其父母之存亡與學識尊卑論叔撫育之任也。叔侄關係於家族之中為極重要之關係。叔侄之間，何以言喻？[MASK]也。
雙胞胎因其母一胎同產之同胞，其情於血親手足之中為最近也。同孕母腹，同生一時，同長一處，其形其態其跡在成人之前尤多為相似，故其未冠笄之時，蓋情最深厚，或施及平生。雙胞胎之間，何以言喻？[MASK]也。
於政治之中，兩方之會晤多因權與利之爭鬥也。多以其政治與國家所屬不同，冀會晤以求成結盟。兩方須守盟會之理，於守自身之利為上為底，亦宜慮對方之利，以成盟約也。政治談判中對立之雙方之間，何以言喻？[MASK]也。
堂兄弟姐妹為親戚，然其親不過於同胞兄弟姐妹。於家族之中，堂兄弟姐妹可與嫡子女同長共學，亦同為長者所愛，然於家財分配，若非嫡子女亡故出繼，則不得分其家財，然亦多有倚勢強奪家財之事。論及尊卑，堂兄弟姐妹之長者亦為家族所重。堂兄弟姐妹之間，何以言喻？[MASK]也。
古者以父系別家族，故同父異母與同母異父之子女之所受對待全然不同。若子女為同父異母，則其於家族之中尊卑貴賤則從母之所處為父之發妻、續弦、妾之等而不同，及其母之存亡與母家之勢而定，然其爲一家之人，則無疑也。若子女為同母異父，則多因父之續娶他婦，其母之前夫子女多為後嫁之家族異姓視之，其被賤待，亦其常也，然亦須視其後父家之心與其母家之勢。同父異母與同母異父之子女之間，何以言喻？[MASK]也。
繼子女之間，雖為親戚，但彼此犬牙交錯，一言難磬。繼母與繼父之子女之關系亦相去萬裏。古者，父親多主家族，父親續娶，繼母亦為繼子之母也。然若母親改醮，繼子則從母而入繼父家，其家族關系亦全然改換也。若父母於其前夫前妻亡故後另結婚姻，則或因繼父繼母之愛而另生齟齬。家產之分配，若其母為繼母，則繼子女（若其女子未嫁）以律法可得所應之家產。若其父為繼父，則繼子女非繼父及家族所允，以律法不得受家產。繼子女之間，何以言喻？[MASK]也。
古之為官，同僚之間以官位相近，同朝合堂，共謀於事。然或因其職所守相近，未免於相爭，而生齟齬者亦多有之。同僚之間尊卑之序則定以官位高低、資望長短。同僚之間，何以言喻？[MASK]也。
庠序之間，同窗之間以求學問知識為共識，相助於學，共進於道。然因修業之優劣，成績之高下，而生齟齬者亦有之。同窗之間，常為對等之交，然亦可守尊卑之禮而以年齒為序，此多為交往之禮便耳。同窗之間，何以言喻？[MASK]也。
所謂搭訕者，意在親近被搭訕者，以其欲與被搭訕者交好而有所圖也。搭訕者之於被搭訕者，或欲作綈袍之義，或欲結琴瑟之好，或欲為買賣之宜。二者之關系，主動與被動並存，不確與不穩共生。然搭訕者多有所求，故世貶其行，經史詩賦亦多譏之。搭訕者與被搭訕者之間，何以言喻？[MASK]也。
施害者乃刑案中為暴力罪行者也。受害者乃因施害者之暴而罹身體乃至於性命之禍也。施害者與受害者，或為兩立，或為抵牾。經史典籍錄此案件，多因其所涉或為欺公罔法，或為其案情之重大曲折，蒙冤者終得昭雪也。然亦多為尋常案件之受害與被害關系。刑案中之施害者與受害者之間，何以言喻？[MASK]也。
古之旁觀者乃睹罪案而無與者也。或為偶然，或特持中而觀也。旁觀者之與受害者，論其行多有意疏遠之，跡其心則漠然或哀憫，然則旁觀者亦有因保甲連坐製度而或肯作證者。刑案中之受害者與旁觀者之間，何以言喻？[MASK]也。
屋主者，有屋貰於人者也。承租者，僦屋於人者也。屋主與承租者，常為權利義務之交易，或有經濟利益之抵牾，然得租賃者，亦彼此利之中和也。屋主與承租者之間，何以言喻？[MASK]也。
夫婦之關係，雖為平等而以男性為主導，家中事務由男性裁決，女子應遵奉，然亦視母家地位及其實力。夫婦之間，尤重忠誠尊重，互為匹敵，互相照顧，守家族和睦也。夫婦之間，何以言喻？[MASK]也。
夥計與顧客之關係以商貿為基，夥計須敬、誠、勤、恭，供以良品及服務。顧客則於良品與服務，受之以禮，成兩全之美事。夥計與顧客之間，何以言喻？[MASK]也。
父母與子女之閒，以孝為要，從其道，分其憂，解其難。爲其子者須事親以終其天年，爲其女者，既嫁亦省親有定期，且盡力照拂有難者，不以有歸為辭也。父母則應愛憐其子、育其成才，仿三遷而擇佳處也。父母與子女之間，何以言喻？[MASK]也。
義父母與義子女之關係，亦以孝為要。養子須事長以終其天年，養女亦受為人女之道。義父母則應愛憐有度、育子成才。義父母與義子女之間，何以言喻？[MASK]也。
翁媳若父女，故以孝、敬、恭系之，然以非親之故，兼有男女之防，媳固當孝翁視親，亦從於令而不可逾于矩。翁當護其周全而不可密邇。要約以禮，不忘授受不親之訓也。公公與兒媳之間，何以言喻？[MASK]也。
婆媳乃家中上下級關係也。婆為長為尊，有督導教育之責，媳則尊之孝之，有若母子然。婦歸夫家，夫妻之外，婆媳為重大關係也。婆婆與兒媳之間，何以言喻？[MASK]也。
主人與家丁為主僕之關係。主人發號施令，家丁則從令而行，稟其忠也。此關係乃權力與經濟之關係之象徵，主人，富貴者也；家丁，卑賤者也，以此業為生。家丁亦有以契約而世代為奴，則主僕之分益固也。主人與家丁之間，何以言喻？[MASK]也。
地主與佃農之間，乃經濟之關係。地主佔田地，佃農租田以謀生。此關係為經濟依賴關係，地主因佃農而得益，佃農傍田地以得生。地主與佃農之間，何以言喻？[MASK]也。
店主與夥計乃勞動關係。店主以市肆營生，募選數夥計以經營，夥計從其令而行。此關係乃經濟與勞動之關係，店主因夥計而得益，夥計不辭辛苦而獲薪俸。店主與夥計之間，何以言喻？[MASK]也。
官員之與行賄者，權錢之交易也。官員有權，行賄者有金，進賄金以鬻權取利也。此雖違法之事，然世非罕見，甚或相沿成習而得以為默規，異代不鮮也。官員與行賄者之間，何以言喻？[MASK]也。
狀元、榜眼、探花，為科舉殿試之冠、亞、季稱謂也。考生之間，競爭、合作，以求仕進，固彼此為競爭對手。於科舉中，狀元為首，榜眼、探花次之。狀元與榜眼與探花之間，何以言喻？[MASK]也。
綠林好漢首領之與屬下（嘍羅），領導者與被領導者也。首領常以其勇武、智謀得天下，而為領導者。兩者之間，亦視將兵之關係，故於首領命令，屬下（嘍羅）須從而為之，等軍法也。綠林好漢之首領與屬下之間，何以言喻？[MASK]也。
繼父母與子女，乃法定親子關係也。或以原配父母猝然離世，或為離鸞別鳳，繼父母入其家庭，擔養育之責，子女須敬之、從之。繼子女承業於繼母家庭，禮也，法也；而繼父家庭者則或否也，視繼父及其家族態度而定。繼父母與子女之間，何以言喻？[MASK]也。
繼祖父母與繼孫，亦為法定之親子關係也。若父母猝然離世，或為離鸞別鳳，由一方再婚而入他家，則繼父母父母之父母為繼祖父母。繼祖父母有養育之恩澤，子女須孝敬順從之。繼祖父母與繼子孫之關係，視繼子女之與繼父母關係而迥別也，或為同姓則可親似家人，或為異姓而忽視之也。參繼父母-子女條。繼祖父母與繼孫之間，何以言喻？[MASK]也。
養父母與子女，緣以養育之恩，而成親子之情。或父母失於養育，或子女棄於街頭，有善人收養，則為養父母。養父母擔養育之責，子女須孝之同其親然。養子女承業，須視養父母及其家族之意，若有爭議，可訴之官府，然蓋罕見也。養父母與子女之間，何以言喻？[MASK]也。
古人尤重師生之誼，尊師重道，古之訓也。師者，傳道受業解惑之人，教人以禮以知以識以技。學生尊之、敬之，師者愛之、誨之，古時師生關係以父子關係為本，然孝廉科舉之興，亦俾染利祿之關聯也。師生之間，何以言喻？[MASK]也。
家庭（家族）私塾為昔者大家族子弟啟蒙教育之場所也。所聘之家庭私塾教師，或家族之飽學長者，或科場之落第者，或中而未仕者。教童稚以讀書寫字，其常業也，有言傳身教之責，教導其為人之道。故塾師之於弟子，或代族中長者訓誡子弟，或但為教書先生，視教師身份地位或其家族地位而定。家庭私塾教師與學生之間，何以言喻？[MASK]也。
小人于後世多目品行卑劣、心胸狹窄、唯利是圖之人。“小人之交”則指此等人之彼此關係也，其以利為本，漠視誠信，唯權謀與爭利而已。小人之交之間，何以言喻？[MASK]也。
佛教徒以佛法信仰為紐，慈悲為懷，同修而互助，以求得佛法真諦，共成和諧、平等、互助之關係。然自佛滅以來，教派紛然，利欲之心，恆難寂滅，故其以宗派、僧團、寺廟之異，彼此爭端，歷代恆有。佛教徒之間，何以言喻？[MASK]也。
道教徒以修仙教化為要務，無為而治，自然和諧，天地共生，萬物為一，以求長生不老，故道教徒之間，以平和、寬容、尊重為常。然其亦或以宗派、僧團、寺廟之異，而起爭端。道教徒之間，何以言喻？[MASK]也。
髮小者，自幼相識之友也，其行跡相似相同，故其交往甚近。兩人之間，可不甚囿於禮法，故率真而坦誠。發小之間，何以言喻？[MASK]也。
本地人之與異鄉人，關係複雜。以編戶齊民之故，民重遷徙，是以處於異域，本地人或嚴以防範，或疏以情感。又以方音之差、風俗之別，異鄉人恆倍感孤困。然亦有好客之人，助其在此安居也。本地人與異鄉人之間，何以言喻？[MASK]也。
土籍之人與客籍之人之問題，漢季以來，盤根錯節，乞于民清之際，未有終結也。其世居鄉土之地而編戶于官府者，謂之土籍之人；其離鄉背井、人徙居於他鄉而籍未更者，則為客籍之人。二者之異，於編戶齊民之策率有體現。大抵土籍之人地位高於客籍，故土籍之人多主人自視，深有自得之意。然客籍與土籍，雜處一地，或以田土之不均、或以經濟之不等、或以社會地位之不匹，或以稅賦政令之不平，而勢有消長。其間以土地、人口、政治權力諸此之屬而滋生矛盾，然和中寓爭，爭中寓和，幾世之後，二者以共處、合作與通婚之故，兼之戶籍更新，斷客為主之策，二者之異同，日愈消弭，并同土籍，此其常也。然舊之客籍未泯，而新之客籍又生，此又其常也。土籍人士與客籍人士之間，何以言喻？[MASK]也。
外祖父母與外孫或外孫女，多倫常親呢之情也。蓋將綱常倫理而觀之，則外祖父母之於外孫或外孫女，或不及外祖父母之於內孫或內孫女親密。然自私心而論，則未必如是，若紅樓夢中以座次定尊卑，外孫女林黛玉尊於內孫三春則是一例。此皆因家族結構而致，謂之外孫或外孫女當屬妻家，非屬夫家也，故禮數殊矣。外祖父母與外孫/外孫女之間，何以言喻？[MASK]也。
門當戶對之訂婚男女，其關係多由家族所定。其婚姻，非止兩人之結合，亦兩家以聯姻相合也。故其關係，或受家族、社會地位、財富等之影響。于訂婚之前，彼此交往不多，甚者未嘗謀面，然皆需遵家族與社會之規定，成合卺之禮。門當戶對之訂婚男女之間，何以言喻？[MASK]也。
私奔者，乃背禮叛教所以追情求愛也。常語以爲聘妻奔妾，然或以一見傾心欲早遂佳期，或以門戶不當而父母弗允，或以私情而拋其家室，不顧雙親兒女，終於淫奔者，以其愛戀之深，不可自抑也。然則負罵名，走他鄉，前途何卜，亦難以預知也。私奔男女之間，何以言喻？[MASK]也。
同科舉人之間，競爭與互助兼有之也。科舉，士進之途也，遂引天下讀書人埋頭于科舉之書。然進士之途窄矣，應試者多而中試者寡，其得高中以啓顯宦之階者則尤寡也。故于科考之時為競爭對手，然於考試之外，或可相學互助。考中者，若無素時芥蒂，咸可共相交友，以廣交際。同科舉人之間，何以言喻？[MASK]也。
同門師兄弟之間存恭謹相敬之情、患難相濟之意。其同拜一師，共得其教，故同門之情宜深矣。彼其有同門之敬助，攜手共進。若無有利祿貪欲之心，則同門師兄弟之間，充盈友愛之情，必也。同門師兄弟之間，何以言喻？[MASK]也。
同校學生之間，友情與競爭兼有之也。彼學於同一學校，有同窗共硯之情。然非獨限於共學之時矣，待卒業及從業後，亦可成通力合作之事。同校學生之間，何以言喻？[MASK]也。
山長者，書院衆師之長，亦書院之主管也；講席，書院所延聘之教師也。書院之治，向以寬而有別於官學也。官學之治，以屬官府而有等級高下之判。書院則否，以山長之道德文章為維繫也，以地方劃撥之田地房舍為生養也，是以山長之與講席，一講席之首座耳，志同則合，志異則散，山長之管書院者，攝也，固當共尊書院之規，不以勢相凌，是以寬。然有清之後，書院亦官學化也，非概得以寬一之。學府書院之山長與講席之間，何以言喻？[MASK]也。
同父同母之子女，為同胞之兄弟姊妹也，此乃血緣至親。同胞兄弟姊妹間多親呢，常勝於非同胞者。同父同母之子女之間，何以言喻？[MASK]也。
戲班與劇作者之間多合作也。劇作者撰作戲劇劇本，而戲班搬演劇作，以供觀眾欣賞。戲班之人身卑籍賤，然劇作者或為讀書人，位四民之首，甚者有功名焉，以差距懸殊之故，所謂合作者，亦鬆散之形式也。劇作者未必依演出之狀況而作成案頭之曲，戲班之於作品之呈現，亦未必符契原文，其違作者原意而有自行發揮之處者，蓋不勝舉也。戲班與劇作者之間，何以言喻？[MASK]也。

戲子，上臺演出者也；看官，觀賞表演者也。戲子以其表演技巧取悅看客，博看官捧場，而看官之回應，或於大快人心之處喝采，或於角色含冤負屈之處泣下。高超之技藝固得掌聲口譽，反之則致倒彩譏嘲。因之戲子須重看官之反應，然戲子卑微低賤，看官之於戲子，決於看官自身之態度與修養，借其賤戲子，以之為下等，亦不違世俗之德。戲子與看官之間，何以言喻？[MASK]也。
音樂曲藝人，以賞心悅耳之音求生計者也；聽眾，品賞其音樂曲藝者也。音樂曲藝人以其曲藝之才悅聽眾之耳，聽眾則據藝人之水準報以讚譽財物也。要之，藝人須以聽眾之反應為重，然曲藝人恆処賤籍，故與聽眾或不對等也。音樂曲藝人與聽眾之間，何以言喻？[MASK]也。
祖孫之間尊卑長幼宜井然有序。祖父母位高於父母，是以孫子女之於祖父母，尤須以禮敬重孝順之，以終其天年，是亦儒家倫理之不可或缺者也。祖孫之間，何以言喻？[MASK]也。
大夫，醫者之敬稱也。古之良大夫也，以扁鵲華佗之資，行救死扶傷之舉。病者若知曉大夫之醫術兼信之，則病者得瘳而醫者受譽，然則病者之與醫者，亦隨醫者口碑之優劣、人品之高下，與夫病者病情之變化、性格之差異而有別。大夫與病者之間，何以言喻？[MASK]也。
姨父姨母與侄子侄女之間存親戚之情也。姨父母以其長者慈顧幼小，幼者敬其長者，此為華夏家庭親情倫理之恆常。姨父姨母與侄子侄女之間，何以言喻？[MASK]也。
行俠仗義者，救受助者於水火災厄之中。仗其勇力，憑其志氣，赴人之困頓，軌俠之道義。至於受助者，則當銜環結草以報其恩也，是俠氣之所傳，而仁義有所弘也，夫緩人之所急，脫人之所危，曷可少也。行俠仗義者與受助者之間，何以言喻？[MASK]也。
妓女者，誤落風塵，陷於倡家，有姿色者賓客如市而衰老者落拓餘生。嫖客以錢財之豐厚，走馬章台，縱其情欲也。然二者之間，或漸生情愫，以成好合者，往往有之，然沉箱剃髮之悲，蓋尤其多也。狎妓違君子德風之誨，悖於人倫常理，為世之所誅責。然歷代官家律令以存秦樓楚館為慣例，《管子》發其端也。嫖客與妓女之間，何以言喻？[MASK]也。
掌櫃者，受店主所托，掌日常經營之事宜，凡貨物之進出、價格之定立、賬目之記錄諸類者皆須過問。掌櫃當不負店主所托之責，店主則當行察看之勸，以驗其實績。掌櫃與店主之間，何以言喻？[MASK]也。
夥計與掌櫃之間，上下級也。夥計，掌櫃之下屬也，掌日常營業之細事，凡接待賓客、售賣商品、搬運貨物之類也。掌櫃行指導管理之勸，而夥計聽其所命。掌櫃與夥計之間，何以言喻？[MASK]也。
捐助者，施以財物之助，不苛求彼之回報；受惠者，受其所助而當銜環結草，以報其恩德也。仁愛互助之義在其中矣。捐助者與受惠者之間，何以言喻？[MASK]也。
將領與士兵之間，上下級也。將領之帶兵也，其高明者在於寬嚴並濟，既嚴於治軍，又時彰仁愛兵卒之美德行，以兵為子。然軍令如山，故士兵須惟命是聽。此則軍隊令行禁止之法也。將領與士兵之間，何以言喻？[MASK]也。
考官之與考生，主試與被試者也。考官評考生之學識才能，而考生須受考官之評鑒。此乃科舉之制公正之途。及考畢，中試者與考官可立師生之誼以擴交際，季世則爲結党之一端也。考官與考生之間，何以言喻？[MASK]也。
家長敬重信任其子女之師也，是以教育之任托之。師長傳道受業解惑，以誨其子弟。總言之，師長位高權重，掌教學之法諸多事宜，故家長須聽而從之。彼此或以嚴父之姿共擔子弟教育之責。師長與家長之間，何以言喻？[MASK]也。
同鄉之間往來密切，彼此相助，共解困厄。同鄉之間，同飲一鄉之水，同言一方之音，風土人情共相習知，故他鄉之逢，倍感親切。同鄉之間，何以言喻？[MASK]也。
鄰里相處之道，可奠鄉里秩序之基。鄰里者，共助、共用、共慶，其要在乎協同互敬，講信修睦，可築鄉里之大同。結姻親、共耕織、連什伍，皆可固鄰里。鄰裡之間，何以言喻？[MASK]也。
相與出行者，同途之際，經歷相同，利益相干而目的相通也。故可相持互助，以應行途之變。同遊關係之要，在諸同心同德，共克困艱。相與出行者之間，何以言喻？[MASK]也。
從事買賣者，賣方或以物售之，或以役供之，買方則以貨貝易之。販賣貿買，需重信諾，禁詐紿。賣方所供務必價合質優，買方所償務必踐以約。買者與賣者之間，何以言喻？[MASK]也。
所謂行人，今之路人也，目有所接而言行不必交，以無深交之所需也。或逢於茶樓酒肆，或見於街巷坊裡，非有際會因緣，相交不過泛泛而已。行人之交多無深交厚誼可溯，然疏而有禮，遠而存敬。行人之間，何以言喻？[MASK]也。
狐朋狗友，品行不檢而相偕作樂取悅心欲者也，所好皆賭博、酗飲、狎妓之陋習。狐朋狗友之交，觥籌交錯、宴酣之樂顯於外，而犬馬聲色、熏心色欲隱其中也。狐朋狗黨之間，何以言喻？[MASK]也。
泛泛之友，可為同好，共論琴棋，共試酒茶，然多止於淺交。所謂淺交者，非親非疏，若敬若重，不甘于醴，亦非純淡如水也，以未深交之故也。泛泛之交之間，何以言喻？[MASK]也。
故舊者，情誼深遠之友也。故舊之友多共曆往事種種，然溫不增華，寒不改葉，能四時而不衰，歷險夷而仍固，相輔相助，情堅若金。故舊之間，何以言喻？[MASK]也。
摯友者，無血緣之親，然勝乎同產，雖貧富貴賤、生死離別不能阻隔之。摯友相交，以拳拳之心同攜手、共患難，實無價之友誼也。摯友之間，何以言喻？[MASK]也。
友誼之至境是謂知己。其情之深厚，遠勝泛泛相交，亦相異於親子牽絆，如奏高山流水于知音也，意動即神會，勝卻言語無數。互為知己者，彼之喜怒哀樂皆可歷歷於己心，至情至性，合若符契，而相敬之以禮；若得一知己，遑論肝膽相照，雖九死其猶未悔。友誼之至境，不過是也。知己之間，何以言喻？[MASK]也。
乞者與行者，多遇於市肆。乞者所欲者惟行者之施，行者之施亦可彰己憐憫之心。然二者相遇，行者多無所施，乞者或無所得，以不必施故也。乞丐與行人之間，何以言喻？[MASK]也。
新故官吏之閒，權力交接之關係也。去者有升、謫、免、致仕之別，而新任者，生疏于此間府衙事務，故舊任有授新任以經驗故事之責。然則離任者或以親近者安排新任左右，雖去任而威信存，且交接之際，多涉賦稅度支之核查、檔案文書之清點，案件審理之清白，田地戶口之數目，是以輕則生隙，重則黨伐。新故吏之間，何以言喻？[MASK]也。
獄卒之于囚犯，有羈押之權，囚犯受制于獄卒，受監守之限制。獄卒待囚犯何如，視囚犯家族之貴賤、案情判罰之輕重，及親友打點之多少而各異也。若利益相合，或義氣相投，獄卒囚犯亦可結友，然為獄卒者疾言厲色、受其暴虐者多為常態。獄卒與囚犯之間，何以言喻？[MASK]也。
告與被告，皆寄之律法以為己申訴辯白，而互為對立也。告劾者所求，伸曲理枉，以示法網恢恢；被告者所求，自證清白，以求洗冤昭雪。告與被告之辯，實關乎法治完備公正之有實否。告劾者與被告者之間，何以言喻？[MASK]也。
妻妾之間多明暗糾葛。妻者，主内也，總理治家教子之務。妾者，位卑于妻，多以存續香火，姿顏姣好之由納之。妻妾相處，或扶持相依，或勾心鬥角。《毛詩序》曰：“《關雎》樂得淑女以配君子，憂在進賢，不淫其色。”盡言正妻納妾之責，妻妾相處之道。妻妾之間，何以言喻？[MASK]也。
妻與外婦之間，相視若讎仇。外婦者，未娶而旁通也，無婚姻之名。外婦若有子，易致後宅不寧，亂尊卑之別，生分財之釁，是故妻與外婦多生齟齬。妻與外婦之間，何以言喻？[MASK]也。
夫暗合於外婦，苟且之舉也。二者無婚姻之名，為世所不齒。暗合者，或生相依相濡之情，亦或僅尋一夕貪歡。夫與外婦之間，何以言喻？[MASK]也。
遠親者，有血緣之絆，無近鄰之切，往來問候多訴諸婚喪嫁娶節氣，寄乎禮法倫常，以厚親戚之情。然澆薄之世，如涉祖業田產之爭，則雖遠親亦或生齟齬。遠親之間，何以言喻？[MASK]也。
子婿之於岳家，理應互敬互賴，然岳家垂青與否，多決於子婿之功名、族望。除入贅而改姓易族者，翁婿雖名為父子，實各異家，其情弗如同簷之婆媳遠甚，遑論血緣之親。岳家與子婿之間，何以言喻？[MASK]也。
同袍之誼，多喻軍旅士伍心心相惜。士卒征戰於沙場，同浴血汗、共赴國難，皆懷身先致死、盡忠報國之念。詩曰：豈曰無衣，與子同袍。是以同袍之親，勝似兄弟。同袍之間，何以言喻？[MASK]也。
官民之間，上下領屬之關係也。為官之道，必除害興利，善度民力，正風立綱；為民之要，必遵紀守法，立身行道。官民相處亦如父子，為人父則慈，為人子則孝，為人上則明，為人下則聖，父慈子孝，上明下聖，治之紀也。官民之間，何以言喻？[MASK]也。
結黨而敵對者，始於小人之同利，及其見利則爭先，或利盡而交疏，乃反相賊害。結黨者之利異，多為政見、觀念相抵，至成水火之勢。為求己利，雖其親戚兄弟不保也。敵對黨派之間，何以言喻？[MASK]也。
同盟即志同道合者。君子與君子以同道為朋，共守道義，行忠信，惜名節。是故同盟者得以守望相助，進退如一，莫逆於心。同盟黨派之間，何以言喻？[MASK]也。
保人者，受託于雙方顧主，牽繫買賣關係，以局外之身處理其間事務者也。顧主雙方多聘保人以求交易之公正，保人亦從中牟利。保人之制，早至魏晉隋唐已有所載，古商貿制度之完善據此可窺一二。保人與顧主之間，何以言喻？[MASK]也。
所謂忠臣，效忠于社稷者也，以鞠躬盡瘁、死而後已為己任，多為世之表率，歷代稱頌不絕。所謂逆賊，離君叛國者也，陷社稷於累卵之危、倒懸之急，世人為之不齒。忠臣與逆賊之間，何以言喻？[MASK]也。
主客之交，以互敬互重為本。為人主者，待人接物需完備周致，以求賓至如歸；為賓客者，亦需禮尚往來，以示謝忱。古之人倫禮制，亦見於主客相交之道也。主人與賓客之間，何以言喻？[MASK]也。
主奴者，主人為主而女婢為從也。主人有令，奴必應之，不可不從，以其必終於主人故也。奴之衣食起居，身家性命，全仰主意。主人和善體恤，則奴亦可豐足；主慳吝刻薄，則奴亦常縈困頓。然奴之私忠於其主也，不必係於主之慈暴，以世論其忠若犬故也。主奴之間，何以言喻？[MASK]也。
乳母之與嬰孩之家長，僱傭關係者也。家長或以嬌弱，或以矜貴，或以少乳，僱乳母以照料之。乳母當供乳於彼嬰幼，事其起居，乃或至教導培育。二者既系於僱傭，則信立為本而求職盡也。家長用人不疑，乳母方不墮其職也。乳母與家長之間，何以言喻？[MASK]也。
乳母之于嬰幼，保育者也。乳母非僅哺之以乳，且兼料其起居，助其成長，與其蒙學。長此以往，乳母或親愛嬰幼，嬰幼亦依戀乳母，此人情所致，本非乳母之分也。及長，嬰幼雖有生母，于禮當母事之，然愛信乳母，厚此而薄彼，亦時有之。雖然，若依通例，嬰幼年齒既長，無需哺乳，乳母之分即盡。更有甚者，就此別過，鮮復往來矣。乳母與嬰幼之間，何以言喻？[MASK]也。
凡職官者，常設正副。正者，統也。凡執掌決策，籌謀號令，皆出於正者。副者，輔也。或可決策，然猶為行正者之令耳。正副職官，或勾心鬥角，傾軋掣肘；或相交融洽，並力同心。二者相輔相成，乃自然之理，然彼此相爭，亦時有之。正職與副職之間，何以言喻？[MASK]也。
教首者，亦曰教主，一教之領袖也，享至高威權，眾人視之如神聖。教徒者，此教之信眾也。尊奉教首，篤信之，敬仰之，無敢有違。凡教之規，皆當嚴守；凡本教之義，教首之令，皆應踐行。由此可觀古時宗教神權之廣大威嚴，與夫信徒心靈之精誠純粹也。教首與教徒之間，何以言喻？[MASK]也。
一家一族，必有其祖。先祖後裔，分支散葉，世代相延，此乃家族形式之基本樣貌。祖為一族之源，綿綿瓜瓞，延而至今，其開創之始，嘉行善德，當銘於子孫，賡續不絕。子子孫孫需尊奉之，稱頌之，祠廟之，祭享之，且以顯祖榮宗為務，不可玷污門楣，蒙羞祖上。重祖以尚孝，古來如此。祖先與後代之間，何以言喻？[MASK]也。
保長坊長者，鄉裡街坊一方之長也，以平治鄉裡街坊之序，協官府理此地之事，上傳下達於鄉間坊間為責。居鄉裡街坊者，稱居民。居民需從保長，遵鄉規，然後可自主而為。此則城外之鄉裡，城内之街坊，其自轄之法也。保長與居民之間，何以言喻？[MASK]也。
遠房表親，雖非同胞，血緣略淺，然既系一族，兄弟姊妹之禮，仍需具備，並擔修睦之責，盡扶持之義。蓋開枝散葉，本自同宗，血濃於水，情繫其中，遠方表親，亦不可輕疏也。遠房表親之間，何以言喻？[MASK]也。
君臣之間，界限分明。君者，一國之主；臣者，輔君以治國也。君可行賞罰於臣，臣當履忠誠於君。君君，臣臣，各從其分，然孟子曰：“君之視臣如手足；則臣視君如腹心；君之視臣如犬馬，則臣視君如國人；君之視臣如土芥，則臣視君如寇讎。”是以君愛臣，則臣親君而易忠，反之則心離而人散，然儒者所謂臣之忠，忠乎社稷天下，非一人一姓也，而鼎革之節，革命之時，何謂稷天下，何謂一人一姓，人多混淆之，而一人一姓多樂其混淆也。由此觀之，君臣之間，錯綜複雜，一言難盡。君臣之義，乃上下之權力關係，亦涉個人與家國集體之關係也。君臣之間，何以言喻？[MASK]也。
債主與負債者，二者交通，繫於財幣。債務既成，負債者需依契約按時償之，逾期未償，債主可責之。此二者一關乎責權，二關乎財幣也。債主與負債者之間，何以言喻？[MASK]也。
親家者，姻親是也，為夫妻兩家父母之互稱。親家為同等之親戚，亦關世故人情。若夫婦敦睦，則親家亦諧，鮮有齟齬。親家之間，何以言喻？[MASK]也。
訟師之與司法者，因其職而相交也。事主有案，託於訟師，代寫文書，申訴有司，而司法者任於官府，審判其案。二者因本職而協作，並行業務於律法之事也。然地方司法，皆委縣令，多起於科舉，熟於治經，疏於律令，訟師與縣吏或沆瀣一氣，操縱案判，則蔽矣。訟師與司法者之間，何以言喻？[MASK]也。
訟師之於屬者，代理關係也。訟師以代撰訴狀為務，然亦可因之而受屬者之托，代其行訟。此二者一關乎責權，二關乎立信與代理也。訟師與屬者之間，何以言喻？[MASK]也。
捕快者，地方官府之差役也，以捉賊、治保為務。百姓為全身護財計，仰賴捕快；而捕快或濫權恣肆，百姓見而生畏。是以捕快百姓之間，關係微妙，一言難蔽百世之實。捕快與百姓之間，何以言喻？[MASK]也。
疑犯捕快，彼此對立。捕快之務，緝拿疑犯，而疑犯聞之，必逋逃藏匿，如鼠畏貓也。二者水火難容，矛盾多生。疑犯與捕快之間，何以言喻？[MASK]也。
罪犯之於人質，強之以力而脅其性命者也。犯人作奸犯科，將陷囹圄，恐牢獄之災，或挾人質以要官府。人質遭其挾而性命堪憂，以無可自主，常聽命于罪犯。罪犯與人質之間，何以言喻？[MASK]也。
罪犯所害之人，若有親眷，則稱苦主。苦主與罪犯為敵，視之為仇讎，冀官府緝捕，使其就法。或思血親之仇，不共戴天，則不俟官府，而有私報之也。罪犯與苦主之間，何以言喻？[MASK]也。
罪犯觸罪，或為旁人所觀。旁人既觀，則或有紛紛議論，批評褒貶。輿論所加，則罪犯聲名地位，亦隨之而更。是以旁人之論，或可左右決獄。而保甲之制，儒家之教，亦或使旁人作證，轉為證人也。罪犯與旁人之間，何以言喻？[MASK]也。
盜賊失主，彼此對立。盜賊之行，本系非法，謀竊失主，損其財物。依律，賊當償其失，並伏法受罰。盜賊與失主之間，何以言喻？[MASK]也。
罪犯與受害者，彼此對立。罪犯以非法加害於人，傷其身心。依律，賊當伏法受罰，以償其所害。罪犯與受害者之間，何以言喻？[MASK]也。
司法者與監察者，互相監督，彼此牽掣者也。司法者以審案為務，昭法之威，執法以正。監察者則督其行事或查其已行，以防其私弊貪腐，使司法必正也。司法者與監察者之間，何以言喻？[MASK]也。
罪犯同黨者，共犯是也。其所求所行，皆系非法，而三五聚夥，同籌共謀，一朝舉事，乃咸觸罪。依律，犯罪同黨未可消罪，以其明知共犯，或增其罪咎。罪犯同黨之間，何以言喻？[MASK]也。
賭徒之間，彼此相爭者也。其好博嗜賭，日以鬥雞走馬，喝雉呼盧，投注押寶為事，至於一擲千金，妄希橫富。故彼此爭財奪利，甚為激劇，不免舞弊詐欺，乃至身體相鬥者。厤朝之律法，以賭禁為常，故賭徒之間，世人皆視之為歪門邪道也。賭徒之間，何以言喻？[MASK]也。
文人與閱者，以文之賞識相交通者也。詩文曲賦，文人所作，常寓以其道其情，因傳其文而載其道也。閱者覽之，可明其道而體其情。夫閱者有感，或建言于文人，使其更改；而流播之廣狹，亦繫於後來之閱者。然限於古之實際，二者不得直接交通，故以單向為多。尋常閱者，難比文人之博觀群覽，不可左右其意。雖然，猶有閱者或與文人相厚，或業相關之業，或知音於後世，因而評論之，紹介之，出版之，則可左右文人之書寫，甚或筆削增潤其原文，而動搖世俗之喜好也。文人與閱者之間，何以言喻？[MASK]也。
文人多為士人之屬，論者亦品評之士。二者之間，實可相互磋磨學問，評鷙詩文者也。文人作詩文曲賦，而論者品藻之，其建言獻意，雖抒己之見，亦或左右文人之書寫也。於是論者作評，而文人參酌，以修色其作，推敲之定，一字之師，皆此類也。觀古之文俗世情，論者之于文人，抑揚者也。夫論者所尚，則以詩品詞話、文論筆談附益其作，播其芳名，俾傳之百世而其聲益顯，其文益高。反之，亦有詩文曲賦，論者毀之，因聲名不顯，浸微浸消者也。文人與論者之間，何以言喻？[MASK]也。
男女曖昧之事，悖於人倫，是以隱於心而不擅發於外。其或發於外者，亦以含蓄之言，傳微妙之情，假落紅秋葉之詩，托香囊繡帕之物，暗致其情，不令外人見也，多是之類也。曖昧者之間，何以名状？[MASK]也。
暗戀者，古語或謂單相思。男女之間，礙于父母之命，媒妁之言，婚姻之有定也，於是己固思慕彼而不敢以私意白，彼未知而己切思之，求之不得，其情之至者，所謂“寤寐思服，輾轉反側”是也。其恪于禮者，常以春蠶絲盡、桃花依舊之喻，暗寄其心而不外傳，亦或以暗中護助，不令其有艱困愁苦，而其稍逾制者，則或致佩飾之物也。古之暗戀者，多止乎此，至若季世綱常已墮，男女忽於大防，暗戀轉直，單思為雙，則奔者難禁。暗戀者與被暗戀者之間，何以名状？[MASK]也。
報案者之于受害者也，或同系一人，或其鄰裡親朋之知情者也。自秦法以降，遞有閭閻連坐之策，凡知情不舉者，按律當坐，王安石所目保甲法，即是也。然世有升降，國有治亂，保甲連坐之策，可行乎令行禁止之時，而文恬武嬉之季，多具文視之耳。且古時刑偵之術寡而限期破案之律在，案犯易脫幹係而有司則損利祿，是以報案者亦須證據確鑿，無可指摘，庶免乎官府之糾擾而人財俱困也。又自董子以來，列朝以儒治國，親親相隱之教，風乎百世，是以近親之間，若非大義滅親之舉，概以不報官府為長，而以鄉約族規處置也。報案者與受害者之間，何以名状？[MASK]也。
報案者與罪犯之間多對立之關系。報案者舉罪犯之罪，冀以律法懲之。然報案者或有因擿伏發隱而罹罪犯相脅相報之禍者也。又以保甲連坐之製與大義滅親之理，報案者與罪犯之間亦或為親戚鄰裏，此又非必是兩立之勢也。報案者與罪犯之間，何以名状？[MASK]也。
文選詩集之編者與作者，或因敬重欣賞之情，或為功利實在之用。其功利實在之用著，如著者為高官、長輩、恩師者也，甚者編者或側己文於他人之文，以彰己名也。裁約編選之時，編者常善著者之才華功業。編者亦以其選裁左右讀者之理解。文選詩集之編者與作者，實為古時文人之文化品味、審美觀念、權力關係之鑒鏡也。文選之編者與作者之間，何以名状？[MASK]也。
表兄弟姐妹者，視同近親，關系親近，家族之情亦深也。彼於童稚之時，可共遊學、相長互助，共解所遇之危難。禮，表兄弟姐妹須循一定之禮節，長愛少，少敬長。及漸長，循授受不親之訓，以其為異姓，可通婚姻故也。表兄弟姐妹之間，何以名状？[MASK]也。
庖人之與食客者，為服務被服務之關系也。庖人主烹飪，以甘美之食奉食客，而食客亦須念庖人之生計。故庖人須盡其技以足食客之口，食客亦須慎待庖人所供之物，此亦理之常也。或有庖人專供於食客或主人之家，則曰名廚或私廚，其與食客主人之關系則更甚其他庖人也。庖人與食客之間，何以名状？[MASK]也。
仇敵之間乃對立衝突之關係也。敵者，匹敵也，論其才智，則相儔類，而或以利益之不均、或以地位之不匹、或以權力之不及、或以忠誠之不貞，諸此之屬，心生怨望而欲戕害以快其心者，仇敵之事也。然則，仇敵既以相噬為常，亦以其相匹，而或生相惜之感，且古時人分等級，同匹儔之人，其未為仇敵之初，或有通家之好，秦晉之交而同窗之誼也，是以古之仇敵，視今日為複雜也。故經史詩賦之中，感概仇敵之才智氣節者，亦不知凡幾也。仇敵之間，何以名状？[MASK]也。

施恩者與受恩者為恩義與感恩之關係。施恩者之助受恩者也，或以善行，或以援手，受恩者遂感念其德，雖滴水之恩，木瓜之贈，亦矢報以湧泉瓊瑤也。古以'知恩圖報'為德之大者也。施恩者與受恩者之間，何以名状？[MASK]也。
青梅竹馬，即為男女自幼同遊嬉戲，心生情愫者也。其情純真深沉，或終為伉儷，或為知己。古時文人墨客之述此情者，至純至美，感人心脾。青梅竹馬之間，何以名状？[MASK]也。
情敵者，二三人傾慕同一對象，遂相競爭。此關係中，有敵意、嫉妬、競爭至於殺心之複雜心緒，然亦或有互尊呼諒者。經史詩賦之中，論及情敵，常有激烈戲謔之矛盾，或高雅而囿於禮法，或直率而流於粗鄙。情敵之間，何以名状？[MASK]也。
天人之間，乃天地人三才之並立關系，人宜順天地，而與萬物為一。儒道皆謂人當敬天地而順之，於是乎則和也。欲和天人，需通天意，欲通天意，則在貫三才之王者，以儒家正典之論，王者得位聖賢之大號，非權勢之稱也，是以為古代知識階層與君主權力間之製衡也。天人之間，何以名状？[MASK]也。
人神之間以信仰敬畏為維繫，其方式不離祭祀、祈禱以通達於神靈也，其指歸在乎求得神靈庇佑，解其大惑，脫其苦厄，堅其心志，導其前路也。今之視古，則謂古之信神，原乎科技落後，而驚懼敬畏于自然未知之力量也。然商周以降，中華之地，人以配天，民為神主之論，敬鬼以遠之教，人能弘道之言，天命從德之誡，經籍之載，三教之說，鹹崇人之踐行而斥虛妄之求神也。然則子雖不言怪力亂神，而人之不齊，一致百慮，可導而不可壅，是以君子明辨天理，不惑神鬼，而不責民間之求神問卜以行善避災也。人神之間，何以名状？[MASK]也。
泛泛之交，乃交情淺薄之普通關係也。於此關係，彼此不通心意，交遊往來，相待以禮而已。泛泛之交，或可謂之朋友，然為關係最疏者也。泛泛之交之間，何以名状？[MASK]也。
店主與顧客，為買賣交易之雙方也。店主供貨品服務於顧客，顧客以財貨償之。店主須竭其誠以應顧客之需，顧客亦需尊店主之恭敬服務于我也。所謂“買賣不成仁義在”，古時買賣之道，理不逾此。店主與顧客之間，何以名状？[MASK]也。
官場之尊卑上下，不可逾距。上之於下，等級之中，所差愈多，威勢愈強。是以官員之間，忠敬為首，然忠敬者，忠於所守也，非忠於上司某甲也。上之於下，亦有訓導保全之義，此即古之尊卑有序、和諧中正之道也。然世閒多難行也。官場之上下級之間，何以名状？[MASK]也。
買賣之夥伴，所共求止於利而已，緣此須相信相助，共分其利。其間信與平最為重，買賣之夥伴須以誠交易，以平分利。彼此亦須行為相協，言語相洽，以求買賣之順遂。買賣之夥伴之間，何以名状？[MASK]也。
買賣之競爭對手，以欲求多利，欲天下求購者多求於己而俾天下財富多歸於己，於是乎有對手生焉。然生財亦當有道，故相競爭者雖有相爭之欲而求勝於對方，亦皆須守信持中，不得狡求他人之利。要之，亦有尊重也。買賣之競爭對手之間，何以名状？[MASK]也。
宗教師徒，在於信仰之傳續繼承。師者，教訓徒弟，徒者，尊師重道，忠於師命。其間尊與忠為最重，徒須尊師忠命，師須護持教徒。宗教師徒之間，何以名状？[MASK]也。
百工之師父與學徒，在於技藝之傳承。傳技之時，師者須教導訓誡其徒，徒者須尊敬愛重其師。其間尊與忠為最重，徒須尊師忠命，師須護持教徒。師傅與學徒之間，何以名状？[MASK]也。
古之掌櫃與客人，因買賣交易為緣。掌櫃者經營其店。客人者消費之人也，求店主之所供。掌櫃須供客人所需，以求信與利。客人亦須敬重掌櫃，不得違其買賣之道。掌櫃與客人之間，何以名状？[MASK]也。
古之首領與反賊，以勢不兩雄為常。首領者，為國之首領，反賊者，為國之叛逆。首領須守其威勢與現有之秩序，反賊則欲反叛其威勢與現有之秩序。首領與反賊之間，何以名状？[MASK]也。
叔侄為血親。叔者為父之弟，侄者為兄之子。叔有教育侄之責，侄須愛敬叔，然亦須視其父母之存亡與學識尊卑論叔撫育之任也。叔侄關係於家族之中為極重要之關係。叔侄之間，何以名状？[MASK]也。
雙胞胎因其母一胎同產之同胞，其情於血親手足之中為最近也。同孕母腹，同生一時，同長一處，其形其態其跡在成人之前尤多為相似，故其未冠笄之時，蓋情最深厚，或施及平生。雙胞胎之間，何以名状？[MASK]也。
於政治之中，兩方之會晤多因權與利之爭鬥也。多以其政治與國家所屬不同，冀會晤以求成結盟。兩方須守盟會之理，於守自身之利為上為底，亦宜慮對方之利，以成盟約也。政治談判中對立之雙方之間，何以名状？[MASK]也。
堂兄弟姐妹為親戚，然其親不過於同胞兄弟姐妹。於家族之中，堂兄弟姐妹可與嫡子女同長共學，亦同為長者所愛，然於家財分配，若非嫡子女亡故出繼，則不得分其家財，然亦多有倚勢強奪家財之事。論及尊卑，堂兄弟姐妹之長者亦為家族所重。堂兄弟姐妹之間，何以名状？[MASK]也。
古者以父系別家族，故同父異母與同母異父之子女之所受對待全然不同。若子女為同父異母，則其於家族之中尊卑貴賤則從母之所處為父之發妻、續弦、妾之等而不同，及其母之存亡與母家之勢而定，然其爲一家之人，則無疑也。若子女為同母異父，則多因父之續娶他婦，其母之前夫子女多為後嫁之家族異姓視之，其被賤待，亦其常也，然亦須視其後父家之心與其母家之勢。同父異母與同母異父之子女之間，何以名状？[MASK]也。
繼子女之間，雖為親戚，但彼此犬牙交錯，一言難磬。繼母與繼父之子女之關系亦相去萬裏。古者，父親多主家族，父親續娶，繼母亦為繼子之母也。然若母親改醮，繼子則從母而入繼父家，其家族關系亦全然改換也。若父母於其前夫前妻亡故後另結婚姻，則或因繼父繼母之愛而另生齟齬。家產之分配，若其母為繼母，則繼子女（若其女子未嫁）以律法可得所應之家產。若其父為繼父，則繼子女非繼父及家族所允，以律法不得受家產。繼子女之間，何以名状？[MASK]也。
古之為官，同僚之間以官位相近，同朝合堂，共謀於事。然或因其職所守相近，未免於相爭，而生齟齬者亦多有之。同僚之間尊卑之序則定以官位高低、資望長短。同僚之間，何以名状？[MASK]也。
庠序之間，同窗之間以求學問知識為共識，相助於學，共進於道。然因修業之優劣，成績之高下，而生齟齬者亦有之。同窗之間，常為對等之交，然亦可守尊卑之禮而以年齒為序，此多為交往之禮便耳。同窗之間，何以名状？[MASK]也。
所謂搭訕者，意在親近被搭訕者，以其欲與被搭訕者交好而有所圖也。搭訕者之於被搭訕者，或欲作綈袍之義，或欲結琴瑟之好，或欲為買賣之宜。二者之關系，主動與被動並存，不確與不穩共生。然搭訕者多有所求，故世貶其行，經史詩賦亦多譏之。搭訕者與被搭訕者之間，何以名状？[MASK]也。
施害者乃刑案中為暴力罪行者也。受害者乃因施害者之暴而罹身體乃至於性命之禍也。施害者與受害者，或為兩立，或為抵牾。經史典籍錄此案件，多因其所涉或為欺公罔法，或為其案情之重大曲折，蒙冤者終得昭雪也。然亦多為尋常案件之受害與被害關系。刑案中之施害者與受害者之間，何以名状？[MASK]也。
古之旁觀者乃睹罪案而無與者也。或為偶然，或特持中而觀也。旁觀者之與受害者，論其行多有意疏遠之，跡其心則漠然或哀憫，然則旁觀者亦有因保甲連坐製度而或肯作證者。刑案中之受害者與旁觀者之間，何以名状？[MASK]也。
屋主者，有屋貰於人者也。承租者，僦屋於人者也。屋主與承租者，常為權利義務之交易，或有經濟利益之抵牾，然得租賃者，亦彼此利之中和也。屋主與承租者之間，何以名状？[MASK]也。
夫婦之關係，雖為平等而以男性為主導，家中事務由男性裁決，女子應遵奉，然亦視母家地位及其實力。夫婦之間，尤重忠誠尊重，互為匹敵，互相照顧，守家族和睦也。夫婦之間，何以名状？[MASK]也。
夥計與顧客之關係以商貿為基，夥計須敬、誠、勤、恭，供以良品及服務。顧客則於良品與服務，受之以禮，成兩全之美事。夥計與顧客之間，何以名状？[MASK]也。
父母與子女之閒，以孝為要，從其道，分其憂，解其難。爲其子者須事親以終其天年，爲其女者，既嫁亦省親有定期，且盡力照拂有難者，不以有歸為辭也。父母則應愛憐其子、育其成才，仿三遷而擇佳處也。父母與子女之間，何以名状？[MASK]也。
義父母與義子女之關係，亦以孝為要。養子須事長以終其天年，養女亦受為人女之道。義父母則應愛憐有度、育子成才。義父母與義子女之間，何以名状？[MASK]也。
翁媳若父女，故以孝、敬、恭系之，然以非親之故，兼有男女之防，媳固當孝翁視親，亦從於令而不可逾于矩。翁當護其周全而不可密邇。要約以禮，不忘授受不親之訓也。公公與兒媳之間，何以名状？[MASK]也。
婆媳乃家中上下級關係也。婆為長為尊，有督導教育之責，媳則尊之孝之，有若母子然。婦歸夫家，夫妻之外，婆媳為重大關係也。婆婆與兒媳之間，何以名状？[MASK]也。
主人與家丁為主僕之關係。主人發號施令，家丁則從令而行，稟其忠也。此關係乃權力與經濟之關係之象徵，主人，富貴者也；家丁，卑賤者也，以此業為生。家丁亦有以契約而世代為奴，則主僕之分益固也。主人與家丁之間，何以名状？[MASK]也。
地主與佃農之間，乃經濟之關係。地主佔田地，佃農租田以謀生。此關係為經濟依賴關係，地主因佃農而得益，佃農傍田地以得生。地主與佃農之間，何以名状？[MASK]也。
店主與夥計乃勞動關係。店主以市肆營生，募選數夥計以經營，夥計從其令而行。此關係乃經濟與勞動之關係，店主因夥計而得益，夥計不辭辛苦而獲薪俸。店主與夥計之間，何以名状？[MASK]也。
官員之與行賄者，權錢之交易也。官員有權，行賄者有金，進賄金以鬻權取利也。此雖違法之事，然世非罕見，甚或相沿成習而得以為默規，異代不鮮也。官員與行賄者之間，何以名状？[MASK]也。
狀元、榜眼、探花，為科舉殿試之冠、亞、季稱謂也。考生之間，競爭、合作，以求仕進，固彼此為競爭對手。於科舉中，狀元為首，榜眼、探花次之。狀元與榜眼與探花之間，何以名状？[MASK]也。
綠林好漢首領之與屬下（嘍羅），領導者與被領導者也。首領常以其勇武、智謀得天下，而為領導者。兩者之間，亦視將兵之關係，故於首領命令，屬下（嘍羅）須從而為之，等軍法也。綠林好漢之首領與屬下之間，何以名状？[MASK]也。
繼父母與子女，乃法定親子關係也。或以原配父母猝然離世，或為離鸞別鳳，繼父母入其家庭，擔養育之責，子女須敬之、從之。繼子女承業於繼母家庭，禮也，法也；而繼父家庭者則或否也，視繼父及其家族態度而定。繼父母與子女之間，何以名状？[MASK]也。
繼祖父母與繼孫，亦為法定之親子關係也。若父母猝然離世，或為離鸞別鳳，由一方再婚而入他家，則繼父母父母之父母為繼祖父母。繼祖父母有養育之恩澤，子女須孝敬順從之。繼祖父母與繼子孫之關係，視繼子女之與繼父母關係而迥別也，或為同姓則可親似家人，或為異姓而忽視之也。參繼父母-子女條。繼祖父母與繼孫之間，何以名状？[MASK]也。
養父母與子女，緣以養育之恩，而成親子之情。或父母失於養育，或子女棄於街頭，有善人收養，則為養父母。養父母擔養育之責，子女須孝之同其親然。養子女承業，須視養父母及其家族之意，若有爭議，可訴之官府，然蓋罕見也。養父母與子女之間，何以名状？[MASK]也。
古人尤重師生之誼，尊師重道，古之訓也。師者，傳道受業解惑之人，教人以禮以知以識以技。學生尊之、敬之，師者愛之、誨之，古時師生關係以父子關係為本，然孝廉科舉之興，亦俾染利祿之關聯也。師生之間，何以名状？[MASK]也。
家庭（家族）私塾為昔者大家族子弟啟蒙教育之場所也。所聘之家庭私塾教師，或家族之飽學長者，或科場之落第者，或中而未仕者。教童稚以讀書寫字，其常業也，有言傳身教之責，教導其為人之道。故塾師之於弟子，或代族中長者訓誡子弟，或但為教書先生，視教師身份地位或其家族地位而定。家庭私塾教師與學生之間，何以名状？[MASK]也。
小人于後世多目品行卑劣、心胸狹窄、唯利是圖之人。“小人之交”則指此等人之彼此關係也，其以利為本，漠視誠信，唯權謀與爭利而已。小人之交之間，何以名状？[MASK]也。
佛教徒以佛法信仰為紐，慈悲為懷，同修而互助，以求得佛法真諦，共成和諧、平等、互助之關係。然自佛滅以來，教派紛然，利欲之心，恆難寂滅，故其以宗派、僧團、寺廟之異，彼此爭端，歷代恆有。佛教徒之間，何以名状？[MASK]也。
道教徒以修仙教化為要務，無為而治，自然和諧，天地共生，萬物為一，以求長生不老，故道教徒之間，以平和、寬容、尊重為常。然其亦或以宗派、僧團、寺廟之異，而起爭端。道教徒之間，何以名状？[MASK]也。
髮小者，自幼相識之友也，其行跡相似相同，故其交往甚近。兩人之間，可不甚囿於禮法，故率真而坦誠。發小之間，何以名状？[MASK]也。
本地人之與異鄉人，關係複雜。以編戶齊民之故，民重遷徙，是以處於異域，本地人或嚴以防範，或疏以情感。又以方音之差、風俗之別，異鄉人恆倍感孤困。然亦有好客之人，助其在此安居也。本地人與異鄉人之間，何以名状？[MASK]也。
土籍之人與客籍之人之問題，漢季以來，盤根錯節，乞于民清之際，未有終結也。其世居鄉土之地而編戶于官府者，謂之土籍之人；其離鄉背井、人徙居於他鄉而籍未更者，則為客籍之人。二者之異，於編戶齊民之策率有體現。大抵土籍之人地位高於客籍，故土籍之人多主人自視，深有自得之意。然客籍與土籍，雜處一地，或以田土之不均、或以經濟之不等、或以社會地位之不匹，或以稅賦政令之不平，而勢有消長。其間以土地、人口、政治權力諸此之屬而滋生矛盾，然和中寓爭，爭中寓和，幾世之後，二者以共處、合作與通婚之故，兼之戶籍更新，斷客為主之策，二者之異同，日愈消弭，并同土籍，此其常也。然舊之客籍未泯，而新之客籍又生，此又其常也。土籍人士與客籍人士之間，何以名状？[MASK]也。
外祖父母與外孫或外孫女，多倫常親呢之情也。蓋將綱常倫理而觀之，則外祖父母之於外孫或外孫女，或不及外祖父母之於內孫或內孫女親密。然自私心而論，則未必如是，若紅樓夢中以座次定尊卑，外孫女林黛玉尊於內孫三春則是一例。此皆因家族結構而致，謂之外孫或外孫女當屬妻家，非屬夫家也，故禮數殊矣。外祖父母與外孫/外孫女之間，何以名状？[MASK]也。
門當戶對之訂婚男女，其關係多由家族所定。其婚姻，非止兩人之結合，亦兩家以聯姻相合也。故其關係，或受家族、社會地位、財富等之影響。于訂婚之前，彼此交往不多，甚者未嘗謀面，然皆需遵家族與社會之規定，成合卺之禮。門當戶對之訂婚男女之間，何以名状？[MASK]也。
私奔者，乃背禮叛教所以追情求愛也。常語以爲聘妻奔妾，然或以一見傾心欲早遂佳期，或以門戶不當而父母弗允，或以私情而拋其家室，不顧雙親兒女，終於淫奔者，以其愛戀之深，不可自抑也。然則負罵名，走他鄉，前途何卜，亦難以預知也。私奔男女之間，何以名状？[MASK]也。
同科舉人之間，競爭與互助兼有之也。科舉，士進之途也，遂引天下讀書人埋頭于科舉之書。然進士之途窄矣，應試者多而中試者寡，其得高中以啓顯宦之階者則尤寡也。故于科考之時為競爭對手，然於考試之外，或可相學互助。考中者，若無素時芥蒂，咸可共相交友，以廣交際。同科舉人之間，何以名状？[MASK]也。
同門師兄弟之間存恭謹相敬之情、患難相濟之意。其同拜一師，共得其教，故同門之情宜深矣。彼其有同門之敬助，攜手共進。若無有利祿貪欲之心，則同門師兄弟之間，充盈友愛之情，必也。同門師兄弟之間，何以名状？[MASK]也。
同校學生之間，友情與競爭兼有之也。彼學於同一學校，有同窗共硯之情。然非獨限於共學之時矣，待卒業及從業後，亦可成通力合作之事。同校學生之間，何以名状？[MASK]也。
山長者，書院衆師之長，亦書院之主管也；講席，書院所延聘之教師也。書院之治，向以寬而有別於官學也。官學之治，以屬官府而有等級高下之判。書院則否，以山長之道德文章為維繫也，以地方劃撥之田地房舍為生養也，是以山長之與講席，一講席之首座耳，志同則合，志異則散，山長之管書院者，攝也，固當共尊書院之規，不以勢相凌，是以寬。然有清之後，書院亦官學化也，非概得以寬一之。學府書院之山長與講席之間，何以名状？[MASK]也。
同父同母之子女，為同胞之兄弟姊妹也，此乃血緣至親。同胞兄弟姊妹間多親呢，常勝於非同胞者。同父同母之子女之間，何以名状？[MASK]也。
戲班與劇作者之間多合作也。劇作者撰作戲劇劇本，而戲班搬演劇作，以供觀眾欣賞。戲班之人身卑籍賤，然劇作者或為讀書人，位四民之首，甚者有功名焉，以差距懸殊之故，所謂合作者，亦鬆散之形式也。劇作者未必依演出之狀況而作成案頭之曲，戲班之於作品之呈現，亦未必符契原文，其違作者原意而有自行發揮之處者，蓋不勝舉也。戲班與劇作者之間，何以名状？[MASK]也。
戲子，上臺演出者也；看官，觀賞表演者也。戲子以其表演技巧取悅看客，博看官捧場，而看官之回應，或於大快人心之處喝采，或於角色含冤負屈之處泣下。高超之技藝固得掌聲口譽，反之則致倒彩譏嘲。因之戲子須重看官之反應，然戲子卑微低賤，看官之於戲子，決於看官自身之態度與修養，借其賤戲子，以之為下等，亦不違世俗之德。戲子與看官之間，何以名状？[MASK]也。
音樂曲藝人，以賞心悅耳之音求生計者也；聽眾，品賞其音樂曲藝者也。音樂曲藝人以其曲藝之才悅聽眾之耳，聽眾則據藝人之水準報以讚譽財物也。要之，藝人須以聽眾之反應為重，然曲藝人恆処賤籍，故與聽眾或不對等也。音樂曲藝人與聽眾之間，何以名状？[MASK]也。
祖孫之間尊卑長幼宜井然有序。祖父母位高於父母，是以孫子女之於祖父母，尤須以禮敬重孝順之，以終其天年，是亦儒家倫理之不可或缺者也。祖孫之間，何以名状？[MASK]也。
大夫，醫者之敬稱也。古之良大夫也，以扁鵲華佗之資，行救死扶傷之舉。病者若知曉大夫之醫術兼信之，則病者得瘳而醫者受譽，然則病者之與醫者，亦隨醫者口碑之優劣、人品之高下，與夫病者病情之變化、性格之差異而有別。大夫與病者之間，何以名状？[MASK]也。
姨父姨母與侄子侄女之間存親戚之情也。姨父母以其長者慈顧幼小，幼者敬其長者，此為華夏家庭親情倫理之恆常。姨父姨母與侄子侄女之間，何以名状？[MASK]也。
行俠仗義者，救受助者於水火災厄之中。仗其勇力，憑其志氣，赴人之困頓，軌俠之道義。至於受助者，則當銜環結草以報其恩也，是俠氣之所傳，而仁義有所弘也，夫緩人之所急，脫人之所危，曷可少也。行俠仗義者與受助者之間，何以名状？[MASK]也。
妓女者，誤落風塵，陷於倡家，有姿色者賓客如市而衰老者落拓餘生。嫖客以錢財之豐厚，走馬章台，縱其情欲也。然二者之間，或漸生情愫，以成好合者，往往有之，然沉箱剃髮之悲，蓋尤其多也。狎妓違君子德風之誨，悖於人倫常理，為世之所誅責。然歷代官家律令以存秦樓楚館為慣例，《管子》發其端也。嫖客與妓女之間，何以名状？[MASK]也。
掌櫃者，受店主所托，掌日常經營之事宜，凡貨物之進出、價格之定立、賬目之記錄諸類者皆須過問。掌櫃當不負店主所托之責，店主則當行察看之勸，以驗其實績。掌櫃與店主之間，何以名状？[MASK]也。
夥計與掌櫃之間，上下級也。夥計，掌櫃之下屬也，掌日常營業之細事，凡接待賓客、售賣商品、搬運貨物之類也。掌櫃行指導管理之勸，而夥計聽其所命。掌櫃與夥計之間，何以名状？[MASK]也。
捐助者，施以財物之助，不苛求彼之回報；受惠者，受其所助而當銜環結草，以報其恩德也。仁愛互助之義在其中矣。捐助者與受惠者之間，何以名状？[MASK]也。
將領與士兵之間，上下級也。將領之帶兵也，其高明者在於寬嚴並濟，既嚴於治軍，又時彰仁愛兵卒之美德行，以兵為子。然軍令如山，故士兵須惟命是聽。此則軍隊令行禁止之法也。將領與士兵之間，何以名状？[MASK]也。
考官之與考生，主試與被試者也。考官評考生之學識才能，而考生須受考官之評鑒。此乃科舉之制公正之途。及考畢，中試者與考官可立師生之誼以擴交際，季世則爲結党之一端也。考官與考生之間，何以名状？[MASK]也。

家長敬重信任其子女之師也，是以教育之任托之。師長傳道受業解惑，以誨其子弟。總言之，師長位高權重，掌教學之法諸多事宜，故家長須聽而從之。彼此或以嚴父之姿共擔子弟教育之責。師長與家長之間，何以名状？[MASK]也。
同鄉之間往來密切，彼此相助，共解困厄。同鄉之間，同飲一鄉之水，同言一方之音，風土人情共相習知，故他鄉之逢，倍感親切。同鄉之間，何以名状？[MASK]也。
鄰里相處之道，可奠鄉里秩序之基。鄰里者，共助、共用、共慶，其要在乎協同互敬，講信修睦，可築鄉里之大同。結姻親、共耕織、連什伍，皆可固鄰里。鄰裡之間，何以名状？[MASK]也。
相與出行者，同途之際，經歷相同，利益相干而目的相通也。故可相持互助，以應行途之變。同遊關係之要，在諸同心同德，共克困艱。相與出行者之間，何以名状？[MASK]也。
從事買賣者，賣方或以物售之，或以役供之，買方則以貨貝易之。販賣貿買，需重信諾，禁詐紿。賣方所供務必價合質優，買方所償務必踐以約。買者與賣者之間，何以名状？[MASK]也。
所謂行人，今之路人也，目有所接而言行不必交，以無深交之所需也。或逢於茶樓酒肆，或見於街巷坊裡，非有際會因緣，相交不過泛泛而已。行人之交多無深交厚誼可溯，然疏而有禮，遠而存敬。行人之間，何以名状？[MASK]也。
狐朋狗友，品行不檢而相偕作樂取悅心欲者也，所好皆賭博、酗飲、狎妓之陋習。狐朋狗友之交，觥籌交錯、宴酣之樂顯於外，而犬馬聲色、熏心色欲隱其中也。狐朋狗黨之間，何以名状？[MASK]也。
泛泛之友，可為同好，共論琴棋，共試酒茶，然多止於淺交。所謂淺交者，非親非疏，若敬若重，不甘于醴，亦非純淡如水也，以未深交之故也。泛泛之交之間，何以名状？[MASK]也。
故舊者，情誼深遠之友也。故舊之友多共曆往事種種，然溫不增華，寒不改葉，能四時而不衰，歷險夷而仍固，相輔相助，情堅若金。故舊之間，何以名状？[MASK]也。
摯友者，無血緣之親，然勝乎同產，雖貧富貴賤、生死離別不能阻隔之。摯友相交，以拳拳之心同攜手、共患難，實無價之友誼也。摯友之間，何以名状？[MASK]也。
友誼之至境是謂知己。其情之深厚，遠勝泛泛相交，亦相異於親子牽絆，如奏高山流水于知音也，意動即神會，勝卻言語無數。互為知己者，彼之喜怒哀樂皆可歷歷於己心，至情至性，合若符契，而相敬之以禮；若得一知己，遑論肝膽相照，雖九死其猶未悔。友誼之至境，不過是也。知己之間，何以名状？[MASK]也。
乞者與行者，多遇於市肆。乞者所欲者惟行者之施，行者之施亦可彰己憐憫之心。然二者相遇，行者多無所施，乞者或無所得，以不必施故也。乞丐與行人之間，何以名状？[MASK]也。
新故官吏之閒，權力交接之關係也。去者有升、謫、免、致仕之別，而新任者，生疏于此間府衙事務，故舊任有授新任以經驗故事之責。然則離任者或以親近者安排新任左右，雖去任而威信存，且交接之際，多涉賦稅度支之核查、檔案文書之清點，案件審理之清白，田地戶口之數目，是以輕則生隙，重則黨伐。新故吏之間，何以名状？[MASK]也。
獄卒之于囚犯，有羈押之權，囚犯受制于獄卒，受監守之限制。獄卒待囚犯何如，視囚犯家族之貴賤、案情判罰之輕重，及親友打點之多少而各異也。若利益相合，或義氣相投，獄卒囚犯亦可結友，然為獄卒者疾言厲色、受其暴虐者多為常態。獄卒與囚犯之間，何以名状？[MASK]也。
告與被告，皆寄之律法以為己申訴辯白，而互為對立也。告劾者所求，伸曲理枉，以示法網恢恢；被告者所求，自證清白，以求洗冤昭雪。告與被告之辯，實關乎法治完備公正之有實否。告劾者與被告者之間，何以名状？[MASK]也。
妻妾之間多明暗糾葛。妻者，主内也，總理治家教子之務。妾者，位卑于妻，多以存續香火，姿顏姣好之由納之。妻妾相處，或扶持相依，或勾心鬥角。《毛詩序》曰：“《關雎》樂得淑女以配君子，憂在進賢，不淫其色。”盡言正妻納妾之責，妻妾相處之道。妻妾之間，何以名状？[MASK]也。
妻與外婦之間，相視若讎仇。外婦者，未娶而旁通也，無婚姻之名。外婦若有子，易致後宅不寧，亂尊卑之別，生分財之釁，是故妻與外婦多生齟齬。妻與外婦之間，何以名状？[MASK]也。
夫暗合於外婦，苟且之舉也。二者無婚姻之名，為世所不齒。暗合者，或生相依相濡之情，亦或僅尋一夕貪歡。夫與外婦之間，何以名状？[MASK]也。
遠親者，有血緣之絆，無近鄰之切，往來問候多訴諸婚喪嫁娶節氣，寄乎禮法倫常，以厚親戚之情。然澆薄之世，如涉祖業田產之爭，則雖遠親亦或生齟齬。遠親之間，何以名状？[MASK]也。
子婿之於岳家，理應互敬互賴，然岳家垂青與否，多決於子婿之功名、族望。除入贅而改姓易族者，翁婿雖名為父子，實各異家，其情弗如同簷之婆媳遠甚，遑論血緣之親。岳家與子婿之間，何以名状？[MASK]也。
同袍之誼，多喻軍旅士伍心心相惜。士卒征戰於沙場，同浴血汗、共赴國難，皆懷身先致死、盡忠報國之念。詩曰：豈曰無衣，與子同袍。是以同袍之親，勝似兄弟。同袍之間，何以名状？[MASK]也。
官民之間，上下領屬之關係也。為官之道，必除害興利，善度民力，正風立綱；為民之要，必遵紀守法，立身行道。官民相處亦如父子，為人父則慈，為人子則孝，為人上則明，為人下則聖，父慈子孝，上明下聖，治之紀也。官民之間，何以名状？[MASK]也。
結黨而敵對者，始於小人之同利，及其見利則爭先，或利盡而交疏，乃反相賊害。結黨者之利異，多為政見、觀念相抵，至成水火之勢。為求己利，雖其親戚兄弟不保也。敵對黨派之間，何以名状？[MASK]也。
同盟即志同道合者。君子與君子以同道為朋，共守道義，行忠信，惜名節。是故同盟者得以守望相助，進退如一，莫逆於心。同盟黨派之間，何以名状？[MASK]也。
保人者，受託于雙方顧主，牽繫買賣關係，以局外之身處理其間事務者也。顧主雙方多聘保人以求交易之公正，保人亦從中牟利。保人之制，早至魏晉隋唐已有所載，古商貿制度之完善據此可窺一二。保人與顧主之間，何以名状？[MASK]也。
所謂忠臣，效忠于社稷者也，以鞠躬盡瘁、死而後已為己任，多為世之表率，歷代稱頌不絕。所謂逆賊，離君叛國者也，陷社稷於累卵之危、倒懸之急，世人為之不齒。忠臣與逆賊之間，何以名状？[MASK]也。
主客之交，以互敬互重為本。為人主者，待人接物需完備周致，以求賓至如歸；為賓客者，亦需禮尚往來，以示謝忱。古之人倫禮制，亦見於主客相交之道也。主人與賓客之間，何以名状？[MASK]也。
主奴者，主人為主而女婢為從也。主人有令，奴必應之，不可不從，以其必終於主人故也。奴之衣食起居，身家性命，全仰主意。主人和善體恤，則奴亦可豐足；主慳吝刻薄，則奴亦常縈困頓。然奴之私忠於其主也，不必係於主之慈暴，以世論其忠若犬故也。主奴之間，何以名状？[MASK]也。
乳母之與嬰孩之家長，僱傭關係者也。家長或以嬌弱，或以矜貴，或以少乳，僱乳母以照料之。乳母當供乳於彼嬰幼，事其起居，乃或至教導培育。二者既系於僱傭，則信立為本而求職盡也。家長用人不疑，乳母方不墮其職也。乳母與家長之間，何以名状？[MASK]也。
乳母之于嬰幼，保育者也。乳母非僅哺之以乳，且兼料其起居，助其成長，與其蒙學。長此以往，乳母或親愛嬰幼，嬰幼亦依戀乳母，此人情所致，本非乳母之分也。及長，嬰幼雖有生母，于禮當母事之，然愛信乳母，厚此而薄彼，亦時有之。雖然，若依通例，嬰幼年齒既長，無需哺乳，乳母之分即盡。更有甚者，就此別過，鮮復往來矣。乳母與嬰幼之間，何以名状？[MASK]也。
凡職官者，常設正副。正者，統也。凡執掌決策，籌謀號令，皆出於正者。副者，輔也。或可決策，然猶為行正者之令耳。正副職官，或勾心鬥角，傾軋掣肘；或相交融洽，並力同心。二者相輔相成，乃自然之理，然彼此相爭，亦時有之。正職與副職之間，何以名状？[MASK]也。
教首者，亦曰教主，一教之領袖也，享至高威權，眾人視之如神聖。教徒者，此教之信眾也。尊奉教首，篤信之，敬仰之，無敢有違。凡教之規，皆當嚴守；凡本教之義，教首之令，皆應踐行。由此可觀古時宗教神權之廣大威嚴，與夫信徒心靈之精誠純粹也。教首與教徒之間，何以名状？[MASK]也。
一家一族，必有其祖。先祖後裔，分支散葉，世代相延，此乃家族形式之基本樣貌。祖為一族之源，綿綿瓜瓞，延而至今，其開創之始，嘉行善德，當銘於子孫，賡續不絕。子子孫孫需尊奉之，稱頌之，祠廟之，祭享之，且以顯祖榮宗為務，不可玷污門楣，蒙羞祖上。重祖以尚孝，古來如此。祖先與後代之間，何以名状？[MASK]也。
保長坊長者，鄉裡街坊一方之長也，以平治鄉裡街坊之序，協官府理此地之事，上傳下達於鄉間坊間為責。居鄉裡街坊者，稱居民。居民需從保長，遵鄉規，然後可自主而為。此則城外之鄉裡，城内之街坊，其自轄之法也。保長與居民之間，何以名状？[MASK]也。
遠房表親，雖非同胞，血緣略淺，然既系一族，兄弟姊妹之禮，仍需具備，並擔修睦之責，盡扶持之義。蓋開枝散葉，本自同宗，血濃於水，情繫其中，遠方表親，亦不可輕疏也。遠房表親之間，何以名状？[MASK]也。
君臣之間，界限分明。君者，一國之主；臣者，輔君以治國也。君可行賞罰於臣，臣當履忠誠於君。君君，臣臣，各從其分，然孟子曰：“君之視臣如手足；則臣視君如腹心；君之視臣如犬馬，則臣視君如國人；君之視臣如土芥，則臣視君如寇讎。”是以君愛臣，則臣親君而易忠，反之則心離而人散，然儒者所謂臣之忠，忠乎社稷天下，非一人一姓也，而鼎革之節，革命之時，何謂稷天下，何謂一人一姓，人多混淆之，而一人一姓多樂其混淆也。由此觀之，君臣之間，錯綜複雜，一言難盡。君臣之義，乃上下之權力關係，亦涉個人與家國集體之關係也。君臣之間，何以名状？[MASK]也。
債主與負債者，二者交通，繫於財幣。債務既成，負債者需依契約按時償之，逾期未償，債主可責之。此二者一關乎責權，二關乎財幣也。債主與負債者之間，何以名状？[MASK]也。
親家者，姻親是也，為夫妻兩家父母之互稱。親家為同等之親戚，亦關世故人情。若夫婦敦睦，則親家亦諧，鮮有齟齬。親家之間，何以名状？[MASK]也。
訟師之與司法者，因其職而相交也。事主有案，託於訟師，代寫文書，申訴有司，而司法者任於官府，審判其案。二者因本職而協作，並行業務於律法之事也。然地方司法，皆委縣令，多起於科舉，熟於治經，疏於律令，訟師與縣吏或沆瀣一氣，操縱案判，則蔽矣。訟師與司法者之間，何以名状？[MASK]也。
訟師之於屬者，代理關係也。訟師以代撰訴狀為務，然亦可因之而受屬者之托，代其行訟。此二者一關乎責權，二關乎立信與代理也。訟師與屬者之間，何以名状？[MASK]也。
捕快者，地方官府之差役也，以捉賊、治保為務。百姓為全身護財計，仰賴捕快；而捕快或濫權恣肆，百姓見而生畏。是以捕快百姓之間，關係微妙，一言難蔽百世之實。捕快與百姓之間，何以名状？[MASK]也。
疑犯捕快，彼此對立。捕快之務，緝拿疑犯，而疑犯聞之，必逋逃藏匿，如鼠畏貓也。二者水火難容，矛盾多生。疑犯與捕快之間，何以名状？[MASK]也。
罪犯之於人質，強之以力而脅其性命者也。犯人作奸犯科，將陷囹圄，恐牢獄之災，或挾人質以要官府。人質遭其挾而性命堪憂，以無可自主，常聽命于罪犯。罪犯與人質之間，何以名状？[MASK]也。
罪犯所害之人，若有親眷，則稱苦主。苦主與罪犯為敵，視之為仇讎，冀官府緝捕，使其就法。或思血親之仇，不共戴天，則不俟官府，而有私報之也。罪犯與苦主之間，何以名状？[MASK]也。
罪犯觸罪，或為旁人所觀。旁人既觀，則或有紛紛議論，批評褒貶。輿論所加，則罪犯聲名地位，亦隨之而更。是以旁人之論，或可左右決獄。而保甲之制，儒家之教，亦或使旁人作證，轉為證人也。罪犯與旁人之間，何以名状？[MASK]也。
盜賊失主，彼此對立。盜賊之行，本系非法，謀竊失主，損其財物。依律，賊當償其失，並伏法受罰。盜賊與失主之間，何以名状？[MASK]也。
罪犯與受害者，彼此對立。罪犯以非法加害於人，傷其身心。依律，賊當伏法受罰，以償其所害。罪犯與受害者之間，何以名状？[MASK]也。
司法者與監察者，互相監督，彼此牽掣者也。司法者以審案為務，昭法之威，執法以正。監察者則督其行事或查其已行，以防其私弊貪腐，使司法必正也。司法者與監察者之間，何以名状？[MASK]也。
罪犯同黨者，共犯是也。其所求所行，皆系非法，而三五聚夥，同籌共謀，一朝舉事，乃咸觸罪。依律，犯罪同黨未可消罪，以其明知共犯，或增其罪咎。罪犯同黨之間，何以名状？[MASK]也。
賭徒之間，彼此相爭者也。其好博嗜賭，日以鬥雞走馬，喝雉呼盧，投注押寶為事，至於一擲千金，妄希橫富。故彼此爭財奪利，甚為激劇，不免舞弊詐欺，乃至身體相鬥者。厤朝之律法，以賭禁為常，故賭徒之間，世人皆視之為歪門邪道也。賭徒之間，何以名状？[MASK]也。
文人與閱者，以文之賞識相交通者也。詩文曲賦，文人所作，常寓以其道其情，因傳其文而載其道也。閱者覽之，可明其道而體其情。夫閱者有感，或建言于文人，使其更改；而流播之廣狹，亦繫於後來之閱者。然限於古之實際，二者不得直接交通，故以單向為多。尋常閱者，難比文人之博觀群覽，不可左右其意。雖然，猶有閱者或與文人相厚，或業相關之業，或知音於後世，因而評論之，紹介之，出版之，則可左右文人之書寫，甚或筆削增潤其原文，而動搖世俗之喜好也。文人與閱者之間，何以名状？[MASK]也。
文人多為士人之屬，論者亦品評之士。二者之間，實可相互磋磨學問，評鷙詩文者也。文人作詩文曲賦，而論者品藻之，其建言獻意，雖抒己之見，亦或左右文人之書寫也。於是論者作評，而文人參酌，以修色其作，推敲之定，一字之師，皆此類也。觀古之文俗世情，論者之于文人，抑揚者也。夫論者所尚，則以詩品詞話、文論筆談附益其作，播其芳名，俾傳之百世而其聲益顯，其文益高。反之，亦有詩文曲賦，論者毀之，因聲名不顯，浸微浸消者也。文人與論者之間，何以名状？[MASK]也。
男女曖昧之事，悖於人倫，是以隱於心而不擅發於外。其或發於外者，亦以含蓄之言，傳微妙之情，假落紅秋葉之詩，托香囊繡帕之物，暗致其情，不令外人見也，多是之類也。曖昧者之間，要義在諸[MASK]。
暗戀者，古語或謂單相思。男女之間，礙于父母之命，媒妁之言，婚姻之有定也，於是己固思慕彼而不敢以私意白，彼未知而己切思之，求之不得，其情之至者，所謂“寤寐思服，輾轉反側”是也。其恪于禮者，常以春蠶絲盡、桃花依舊之喻，暗寄其心而不外傳，亦或以暗中護助，不令其有艱困愁苦，而其稍逾制者，則或致佩飾之物也。古之暗戀者，多止乎此，至若季世綱常已墮，男女忽於大防，暗戀轉直，單思為雙，則奔者難禁。暗戀者與被暗戀者之間，要義在諸[MASK]。
報案者之于受害者也，或同系一人，或其鄰裡親朋之知情者也。自秦法以降，遞有閭閻連坐之策，凡知情不舉者，按律當坐，王安石所目保甲法，即是也。然世有升降，國有治亂，保甲連坐之策，可行乎令行禁止之時，而文恬武嬉之季，多具文視之耳。且古時刑偵之術寡而限期破案之律在，案犯易脫幹係而有司則損利祿，是以報案者亦須證據確鑿，無可指摘，庶免乎官府之糾擾而人財俱困也。又自董子以來，列朝以儒治國，親親相隱之教，風乎百世，是以近親之間，若非大義滅親之舉，概以不報官府為長，而以鄉約族規處置也。報案者與受害者之間，要義在諸[MASK]。
報案者與罪犯之間多對立之關系。報案者舉罪犯之罪，冀以律法懲之。然報案者或有因擿伏發隱而罹罪犯相脅相報之禍者也。又以保甲連坐之製與大義滅親之理，報案者與罪犯之間亦或為親戚鄰裏，此又非必是兩立之勢也。報案者與罪犯之間，要義在諸[MASK]。
文選詩集之編者與作者，或因敬重欣賞之情，或為功利實在之用。其功利實在之用著，如著者為高官、長輩、恩師者也，甚者編者或側己文於他人之文，以彰己名也。裁約編選之時，編者常善著者之才華功業。編者亦以其選裁左右讀者之理解。文選詩集之編者與作者，實為古時文人之文化品味、審美觀念、權力關係之鑒鏡也。文選之編者與作者之間，要義在諸[MASK]。
表兄弟姐妹者，視同近親，關系親近，家族之情亦深也。彼於童稚之時，可共遊學、相長互助，共解所遇之危難。禮，表兄弟姐妹須循一定之禮節，長愛少，少敬長。及漸長，循授受不親之訓，以其為異姓，可通婚姻故也。表兄弟姐妹之間，要義在諸[MASK]。
庖人之與食客者，為服務被服務之關系也。庖人主烹飪，以甘美之食奉食客，而食客亦須念庖人之生計。故庖人須盡其技以足食客之口，食客亦須慎待庖人所供之物，此亦理之常也。或有庖人專供於食客或主人之家，則曰名廚或私廚，其與食客主人之關系則更甚其他庖人也。庖人與食客之間，要義在諸[MASK]。
仇敵之間乃對立衝突之關係也。敵者，匹敵也，論其才智，則相儔類，而或以利益之不均、或以地位之不匹、或以權力之不及、或以忠誠之不貞，諸此之屬，心生怨望而欲戕害以快其心者，仇敵之事也。然則，仇敵既以相噬為常，亦以其相匹，而或生相惜之感，且古時人分等級，同匹儔之人，其未為仇敵之初，或有通家之好，秦晉之交而同窗之誼也，是以古之仇敵，視今日為複雜也。故經史詩賦之中，感概仇敵之才智氣節者，亦不知凡幾也。仇敵之間，要義在諸[MASK]。
施恩者與受恩者為恩義與感恩之關係。施恩者之助受恩者也，或以善行，或以援手，受恩者遂感念其德，雖滴水之恩，木瓜之贈，亦矢報以湧泉瓊瑤也。古以'知恩圖報'為德之大者也。施恩者與受恩者之間，要義在諸[MASK]。
青梅竹馬，即為男女自幼同遊嬉戲，心生情愫者也。其情純真深沉，或終為伉儷，或為知己。古時文人墨客之述此情者，至純至美，感人心脾。青梅竹馬之間，要義在諸[MASK]。
情敵者，二三人傾慕同一對象，遂相競爭。此關係中，有敵意、嫉妬、競爭至於殺心之複雜心緒，然亦或有互尊呼諒者。經史詩賦之中，論及情敵，常有激烈戲謔之矛盾，或高雅而囿於禮法，或直率而流於粗鄙。情敵之間，要義在諸[MASK]。
天人之間，乃天地人三才之並立關系，人宜順天地，而與萬物為一。儒道皆謂人當敬天地而順之，於是乎則和也。欲和天人，需通天意，欲通天意，則在貫三才之王者，以儒家正典之論，王者得位聖賢之大號，非權勢之稱也，是以為古代知識階層與君主權力間之製衡也。天人之間，要義在諸[MASK]。
人神之間以信仰敬畏為維繫，其方式不離祭祀、祈禱以通達於神靈也，其指歸在乎求得神靈庇佑，解其大惑，脫其苦厄，堅其心志，導其前路也。今之視古，則謂古之信神，原乎科技落後，而驚懼敬畏于自然未知之力量也。然商周以降，中華之地，人以配天，民為神主之論，敬鬼以遠之教，人能弘道之言，天命從德之誡，經籍之載，三教之說，鹹崇人之踐行而斥虛妄之求神也。然則子雖不言怪力亂神，而人之不齊，一致百慮，可導而不可壅，是以君子明辨天理，不惑神鬼，而不責民間之求神問卜以行善避災也。人神之間，要義在諸[MASK]。
泛泛之交，乃交情淺薄之普通關係也。於此關係，彼此不通心意，交遊往來，相待以禮而已。泛泛之交，或可謂之朋友，然為關係最疏者也。泛泛之交之間，要義在諸[MASK]。
店主與顧客，為買賣交易之雙方也。店主供貨品服務於顧客，顧客以財貨償之。店主須竭其誠以應顧客之需，顧客亦需尊店主之恭敬服務于我也。所謂“買賣不成仁義在”，古時買賣之道，理不逾此。店主與顧客之間，要義在諸[MASK]。
官場之尊卑上下，不可逾距。上之於下，等級之中，所差愈多，威勢愈強。是以官員之間，忠敬為首，然忠敬者，忠於所守也，非忠於上司某甲也。上之於下，亦有訓導保全之義，此即古之尊卑有序、和諧中正之道也。然世閒多難行也。官場之上下級之間，要義在諸[MASK]。
買賣之夥伴，所共求止於利而已，緣此須相信相助，共分其利。其間信與平最為重，買賣之夥伴須以誠交易，以平分利。彼此亦須行為相協，言語相洽，以求買賣之順遂。買賣之夥伴之間，要義在諸[MASK]。
買賣之競爭對手，以欲求多利，欲天下求購者多求於己而俾天下財富多歸於己，於是乎有對手生焉。然生財亦當有道，故相競爭者雖有相爭之欲而求勝於對方，亦皆須守信持中，不得狡求他人之利。要之，亦有尊重也。買賣之競爭對手之間，要義在諸[MASK]。
宗教師徒，在於信仰之傳續繼承。師者，教訓徒弟，徒者，尊師重道，忠於師命。其間尊與忠為最重，徒須尊師忠命，師須護持教徒。宗教師徒之間，要義在諸[MASK]。

百工之師父與學徒，在於技藝之傳承。傳技之時，師者須教導訓誡其徒，徒者須尊敬愛重其師。其間尊與忠為最重，徒須尊師忠命，師須護持教徒。師傅與學徒之間，要義在諸[MASK]。
古之掌櫃與客人，因買賣交易為緣。掌櫃者經營其店。客人者消費之人也，求店主之所供。掌櫃須供客人所需，以求信與利。客人亦須敬重掌櫃，不得違其買賣之道。掌櫃與客人之間，要義在諸[MASK]。
古之首領與反賊，以勢不兩雄為常。首領者，為國之首領，反賊者，為國之叛逆。首領須守其威勢與現有之秩序，反賊則欲反叛其威勢與現有之秩序。首領與反賊之間，要義在諸[MASK]。
叔侄為血親。叔者為父之弟，侄者為兄之子。叔有教育侄之責，侄須愛敬叔，然亦須視其父母之存亡與學識尊卑論叔撫育之任也。叔侄關係於家族之中為極重要之關係。叔侄之間，要義在諸[MASK]。
雙胞胎因其母一胎同產之同胞，其情於血親手足之中為最近也。同孕母腹，同生一時，同長一處，其形其態其跡在成人之前尤多為相似，故其未冠笄之時，蓋情最深厚，或施及平生。雙胞胎之間，要義在諸[MASK]。
於政治之中，兩方之會晤多因權與利之爭鬥也。多以其政治與國家所屬不同，冀會晤以求成結盟。兩方須守盟會之理，於守自身之利為上為底，亦宜慮對方之利，以成盟約也。政治談判中對立之雙方之間，要義在諸[MASK]。
堂兄弟姐妹為親戚，然其親不過於同胞兄弟姐妹。於家族之中，堂兄弟姐妹可與嫡子女同長共學，亦同為長者所愛，然於家財分配，若非嫡子女亡故出繼，則不得分其家財，然亦多有倚勢強奪家財之事。論及尊卑，堂兄弟姐妹之長者亦為家族所重。堂兄弟姐妹之間，要義在諸[MASK]。
古者以父系別家族，故同父異母與同母異父之子女之所受對待全然不同。若子女為同父異母，則其於家族之中尊卑貴賤則從母之所處為父之發妻、續弦、妾之等而不同，及其母之存亡與母家之勢而定，然其爲一家之人，則無疑也。若子女為同母異父，則多因父之續娶他婦，其母之前夫子女多為後嫁之家族異姓視之，其被賤待，亦其常也，然亦須視其後父家之心與其母家之勢。同父異母與同母異父之子女之間，要義在諸[MASK]。
繼子女之間，雖為親戚，但彼此犬牙交錯，一言難磬。繼母與繼父之子女之關系亦相去萬裏。古者，父親多主家族，父親續娶，繼母亦為繼子之母也。然若母親改醮，繼子則從母而入繼父家，其家族關系亦全然改換也。若父母於其前夫前妻亡故後另結婚姻，則或因繼父繼母之愛而另生齟齬。家產之分配，若其母為繼母，則繼子女（若其女子未嫁）以律法可得所應之家產。若其父為繼父，則繼子女非繼父及家族所允，以律法不得受家產。繼子女之間，要義在諸[MASK]。
古之為官，同僚之間以官位相近，同朝合堂，共謀於事。然或因其職所守相近，未免於相爭，而生齟齬者亦多有之。同僚之間尊卑之序則定以官位高低、資望長短。同僚之間，要義在諸[MASK]。
庠序之間，同窗之間以求學問知識為共識，相助於學，共進於道。然因修業之優劣，成績之高下，而生齟齬者亦有之。同窗之間，常為對等之交，然亦可守尊卑之禮而以年齒為序，此多為交往之禮便耳。同窗之間，要義在諸[MASK]。
所謂搭訕者，意在親近被搭訕者，以其欲與被搭訕者交好而有所圖也。搭訕者之於被搭訕者，或欲作綈袍之義，或欲結琴瑟之好，或欲為買賣之宜。二者之關系，主動與被動並存，不確與不穩共生。然搭訕者多有所求，故世貶其行，經史詩賦亦多譏之。搭訕者與被搭訕者之間，要義在諸[MASK]。
施害者乃刑案中為暴力罪行者也。受害者乃因施害者之暴而罹身體乃至於性命之禍也。施害者與受害者，或為兩立，或為抵牾。經史典籍錄此案件，多因其所涉或為欺公罔法，或為其案情之重大曲折，蒙冤者終得昭雪也。然亦多為尋常案件之受害與被害關系。刑案中之施害者與受害者之間，要義在諸[MASK]。
古之旁觀者乃睹罪案而無與者也。或為偶然，或特持中而觀也。旁觀者之與受害者，論其行多有意疏遠之，跡其心則漠然或哀憫，然則旁觀者亦有因保甲連坐製度而或肯作證者。刑案中之受害者與旁觀者之間，要義在諸[MASK]。
屋主者，有屋貰於人者也。承租者，僦屋於人者也。屋主與承租者，常為權利義務之交易，或有經濟利益之抵牾，然得租賃者，亦彼此利之中和也。屋主與承租者之間，要義在諸[MASK]。
夫婦之關係，雖為平等而以男性為主導，家中事務由男性裁決，女子應遵奉，然亦視母家地位及其實力。夫婦之間，尤重忠誠尊重，互為匹敵，互相照顧，守家族和睦也。夫婦之間，要義在諸[MASK]。
夥計與顧客之關係以商貿為基，夥計須敬、誠、勤、恭，供以良品及服務。顧客則於良品與服務，受之以禮，成兩全之美事。夥計與顧客之間，要義在諸[MASK]。
父母與子女之閒，以孝為要，從其道，分其憂，解其難。爲其子者須事親以終其天年，爲其女者，既嫁亦省親有定期，且盡力照拂有難者，不以有歸為辭也。父母則應愛憐其子、育其成才，仿三遷而擇佳處也。父母與子女之間，要義在諸[MASK]。
義父母與義子女之關係，亦以孝為要。養子須事長以終其天年，養女亦受為人女之道。義父母則應愛憐有度、育子成才。義父母與義子女之間，要義在諸[MASK]。
翁媳若父女，故以孝、敬、恭系之，然以非親之故，兼有男女之防，媳固當孝翁視親，亦從於令而不可逾于矩。翁當護其周全而不可密邇。要約以禮，不忘授受不親之訓也。公公與兒媳之間，要義在諸[MASK]。
婆媳乃家中上下級關係也。婆為長為尊，有督導教育之責，媳則尊之孝之，有若母子然。婦歸夫家，夫妻之外，婆媳為重大關係也。婆婆與兒媳之間，要義在諸[MASK]。
主人與家丁為主僕之關係。主人發號施令，家丁則從令而行，稟其忠也。此關係乃權力與經濟之關係之象徵，主人，富貴者也；家丁，卑賤者也，以此業為生。家丁亦有以契約而世代為奴，則主僕之分益固也。主人與家丁之間，要義在諸[MASK]。
地主與佃農之間，乃經濟之關係。地主佔田地，佃農租田以謀生。此關係為經濟依賴關係，地主因佃農而得益，佃農傍田地以得生。地主與佃農之間，要義在諸[MASK]。
店主與夥計乃勞動關係。店主以市肆營生，募選數夥計以經營，夥計從其令而行。此關係乃經濟與勞動之關係，店主因夥計而得益，夥計不辭辛苦而獲薪俸。店主與夥計之間，要義在諸[MASK]。
官員之與行賄者，權錢之交易也。官員有權，行賄者有金，進賄金以鬻權取利也。此雖違法之事，然世非罕見，甚或相沿成習而得以為默規，異代不鮮也。官員與行賄者之間，要義在諸[MASK]。
狀元、榜眼、探花，為科舉殿試之冠、亞、季稱謂也。考生之間，競爭、合作，以求仕進，固彼此為競爭對手。於科舉中，狀元為首，榜眼、探花次之。狀元與榜眼與探花之間，要義在諸[MASK]。
綠林好漢首領之與屬下（嘍羅），領導者與被領導者也。首領常以其勇武、智謀得天下，而為領導者。兩者之間，亦視將兵之關係，故於首領命令，屬下（嘍羅）須從而為之，等軍法也。綠林好漢之首領與屬下之間，要義在諸[MASK]。
繼父母與子女，乃法定親子關係也。或以原配父母猝然離世，或為離鸞別鳳，繼父母入其家庭，擔養育之責，子女須敬之、從之。繼子女承業於繼母家庭，禮也，法也；而繼父家庭者則或否也，視繼父及其家族態度而定。繼父母與子女之間，要義在諸[MASK]。
繼祖父母與繼孫，亦為法定之親子關係也。若父母猝然離世，或為離鸞別鳳，由一方再婚而入他家，則繼父母父母之父母為繼祖父母。繼祖父母有養育之恩澤，子女須孝敬順從之。繼祖父母與繼子孫之關係，視繼子女之與繼父母關係而迥別也，或為同姓則可親似家人，或為異姓而忽視之也。參繼父母-子女條。繼祖父母與繼孫之間，要義在諸[MASK]。
養父母與子女，緣以養育之恩，而成親子之情。或父母失於養育，或子女棄於街頭，有善人收養，則為養父母。養父母擔養育之責，子女須孝之同其親然。養子女承業，須視養父母及其家族之意，若有爭議，可訴之官府，然蓋罕見也。養父母與子女之間，要義在諸[MASK]。
古人尤重師生之誼，尊師重道，古之訓也。師者，傳道受業解惑之人，教人以禮以知以識以技。學生尊之、敬之，師者愛之、誨之，古時師生關係以父子關係為本，然孝廉科舉之興，亦俾染利祿之關聯也。師生之間，要義在諸[MASK]。
家庭（家族）私塾為昔者大家族子弟啟蒙教育之場所也。所聘之家庭私塾教師，或家族之飽學長者，或科場之落第者，或中而未仕者。教童稚以讀書寫字，其常業也，有言傳身教之責，教導其為人之道。故塾師之於弟子，或代族中長者訓誡子弟，或但為教書先生，視教師身份地位或其家族地位而定。家庭私塾教師與學生之間，要義在諸[MASK]。
小人于後世多目品行卑劣、心胸狹窄、唯利是圖之人。“小人之交”則指此等人之彼此關係也，其以利為本，漠視誠信，唯權謀與爭利而已。小人之交之間，要義在諸[MASK]。
佛教徒以佛法信仰為紐，慈悲為懷，同修而互助，以求得佛法真諦，共成和諧、平等、互助之關係。然自佛滅以來，教派紛然，利欲之心，恆難寂滅，故其以宗派、僧團、寺廟之異，彼此爭端，歷代恆有。佛教徒之間，要義在諸[MASK]。
道教徒以修仙教化為要務，無為而治，自然和諧，天地共生，萬物為一，以求長生不老，故道教徒之間，以平和、寬容、尊重為常。然其亦或以宗派、僧團、寺廟之異，而起爭端。道教徒之間，要義在諸[MASK]。
髮小者，自幼相識之友也，其行跡相似相同，故其交往甚近。兩人之間，可不甚囿於禮法，故率真而坦誠。發小之間，要義在諸[MASK]。
本地人之與異鄉人，關係複雜。以編戶齊民之故，民重遷徙，是以處於異域，本地人或嚴以防範，或疏以情感。又以方音之差、風俗之別，異鄉人恆倍感孤困。然亦有好客之人，助其在此安居也。本地人與異鄉人之間，要義在諸[MASK]。
土籍之人與客籍之人之問題，漢季以來，盤根錯節，乞于民清之際，未有終結也。其世居鄉土之地而編戶于官府者，謂之土籍之人；其離鄉背井、人徙居於他鄉而籍未更者，則為客籍之人。二者之異，於編戶齊民之策率有體現。大抵土籍之人地位高於客籍，故土籍之人多主人自視，深有自得之意。然客籍與土籍，雜處一地，或以田土之不均、或以經濟之不等、或以社會地位之不匹，或以稅賦政令之不平，而勢有消長。其間以土地、人口、政治權力諸此之屬而滋生矛盾，然和中寓爭，爭中寓和，幾世之後，二者以共處、合作與通婚之故，兼之戶籍更新，斷客為主之策，二者之異同，日愈消弭，并同土籍，此其常也。然舊之客籍未泯，而新之客籍又生，此又其常也。土籍人士與客籍人士之間，要義在諸[MASK]。
外祖父母與外孫或外孫女，多倫常親呢之情也。蓋將綱常倫理而觀之，則外祖父母之於外孫或外孫女，或不及外祖父母之於內孫或內孫女親密。然自私心而論，則未必如是，若紅樓夢中以座次定尊卑，外孫女林黛玉尊於內孫三春則是一例。此皆因家族結構而致，謂之外孫或外孫女當屬妻家，非屬夫家也，故禮數殊矣。外祖父母與外孫/外孫女之間，要義在諸[MASK]。
門當戶對之訂婚男女，其關係多由家族所定。其婚姻，非止兩人之結合，亦兩家以聯姻相合也。故其關係，或受家族、社會地位、財富等之影響。于訂婚之前，彼此交往不多，甚者未嘗謀面，然皆需遵家族與社會之規定，成合卺之禮。門當戶對之訂婚男女之間，要義在諸[MASK]。
私奔者，乃背禮叛教所以追情求愛也。常語以爲聘妻奔妾，然或以一見傾心欲早遂佳期，或以門戶不當而父母弗允，或以私情而拋其家室，不顧雙親兒女，終於淫奔者，以其愛戀之深，不可自抑也。然則負罵名，走他鄉，前途何卜，亦難以預知也。私奔男女之間，要義在諸[MASK]。
同科舉人之間，競爭與互助兼有之也。科舉，士進之途也，遂引天下讀書人埋頭于科舉之書。然進士之途窄矣，應試者多而中試者寡，其得高中以啓顯宦之階者則尤寡也。故于科考之時為競爭對手，然於考試之外，或可相學互助。考中者，若無素時芥蒂，咸可共相交友，以廣交際。同科舉人之間，要義在諸[MASK]。
同門師兄弟之間存恭謹相敬之情、患難相濟之意。其同拜一師，共得其教，故同門之情宜深矣。彼其有同門之敬助，攜手共進。若無有利祿貪欲之心，則同門師兄弟之間，充盈友愛之情，必也。同門師兄弟之間，要義在諸[MASK]。
同校學生之間，友情與競爭兼有之也。彼學於同一學校，有同窗共硯之情。然非獨限於共學之時矣，待卒業及從業後，亦可成通力合作之事。同校學生之間，要義在諸[MASK]。
山長者，書院衆師之長，亦書院之主管也；講席，書院所延聘之教師也。書院之治，向以寬而有別於官學也。官學之治，以屬官府而有等級高下之判。書院則否，以山長之道德文章為維繫也，以地方劃撥之田地房舍為生養也，是以山長之與講席，一講席之首座耳，志同則合，志異則散，山長之管書院者，攝也，固當共尊書院之規，不以勢相凌，是以寬。然有清之後，書院亦官學化也，非概得以寬一之。學府書院之山長與講席之間，要義在諸[MASK]。
同父同母之子女，為同胞之兄弟姊妹也，此乃血緣至親。同胞兄弟姊妹間多親呢，常勝於非同胞者。同父同母之子女之間，要義在諸[MASK]。
戲班與劇作者之間多合作也。劇作者撰作戲劇劇本，而戲班搬演劇作，以供觀眾欣賞。戲班之人身卑籍賤，然劇作者或為讀書人，位四民之首，甚者有功名焉，以差距懸殊之故，所謂合作者，亦鬆散之形式也。劇作者未必依演出之狀況而作成案頭之曲，戲班之於作品之呈現，亦未必符契原文，其違作者原意而有自行發揮之處者，蓋不勝舉也。戲班與劇作者之間，要義在諸[MASK]。
戲子，上臺演出者也；看官，觀賞表演者也。戲子以其表演技巧取悅看客，博看官捧場，而看官之回應，或於大快人心之處喝采，或於角色含冤負屈之處泣下。高超之技藝固得掌聲口譽，反之則致倒彩譏嘲。因之戲子須重看官之反應，然戲子卑微低賤，看官之於戲子，決於看官自身之態度與修養，借其賤戲子，以之為下等，亦不違世俗之德。戲子與看官之間，要義在諸[MASK]。
音樂曲藝人，以賞心悅耳之音求生計者也；聽眾，品賞其音樂曲藝者也。音樂曲藝人以其曲藝之才悅聽眾之耳，聽眾則據藝人之水準報以讚譽財物也。要之，藝人須以聽眾之反應為重，然曲藝人恆処賤籍，故與聽眾或不對等也。音樂曲藝人與聽眾之間，要義在諸[MASK]。
祖孫之間尊卑長幼宜井然有序。祖父母位高於父母，是以孫子女之於祖父母，尤須以禮敬重孝順之，以終其天年，是亦儒家倫理之不可或缺者也。祖孫之間，要義在諸[MASK]。
大夫，醫者之敬稱也。古之良大夫也，以扁鵲華佗之資，行救死扶傷之舉。病者若知曉大夫之醫術兼信之，則病者得瘳而醫者受譽，然則病者之與醫者，亦隨醫者口碑之優劣、人品之高下，與夫病者病情之變化、性格之差異而有別。大夫與病者之間，要義在諸[MASK]。
姨父姨母與侄子侄女之間存親戚之情也。姨父母以其長者慈顧幼小，幼者敬其長者，此為華夏家庭親情倫理之恆常。姨父姨母與侄子侄女之間，要義在諸[MASK]。
行俠仗義者，救受助者於水火災厄之中。仗其勇力，憑其志氣，赴人之困頓，軌俠之道義。至於受助者，則當銜環結草以報其恩也，是俠氣之所傳，而仁義有所弘也，夫緩人之所急，脫人之所危，曷可少也。行俠仗義者與受助者之間，要義在諸[MASK]。
妓女者，誤落風塵，陷於倡家，有姿色者賓客如市而衰老者落拓餘生。嫖客以錢財之豐厚，走馬章台，縱其情欲也。然二者之間，或漸生情愫，以成好合者，往往有之，然沉箱剃髮之悲，蓋尤其多也。狎妓違君子德風之誨，悖於人倫常理，為世之所誅責。然歷代官家律令以存秦樓楚館為慣例，《管子》發其端也。嫖客與妓女之間，要義在諸[MASK]。
掌櫃者，受店主所托，掌日常經營之事宜，凡貨物之進出、價格之定立、賬目之記錄諸類者皆須過問。掌櫃當不負店主所托之責，店主則當行察看之勸，以驗其實績。掌櫃與店主之間，要義在諸[MASK]。
夥計與掌櫃之間，上下級也。夥計，掌櫃之下屬也，掌日常營業之細事，凡接待賓客、售賣商品、搬運貨物之類也。掌櫃行指導管理之勸，而夥計聽其所命。掌櫃與夥計之間，要義在諸[MASK]。
捐助者，施以財物之助，不苛求彼之回報；受惠者，受其所助而當銜環結草，以報其恩德也。仁愛互助之義在其中矣。捐助者與受惠者之間，要義在諸[MASK]。
將領與士兵之間，上下級也。將領之帶兵也，其高明者在於寬嚴並濟，既嚴於治軍，又時彰仁愛兵卒之美德行，以兵為子。然軍令如山，故士兵須惟命是聽。此則軍隊令行禁止之法也。將領與士兵之間，要義在諸[MASK]。
考官之與考生，主試與被試者也。考官評考生之學識才能，而考生須受考官之評鑒。此乃科舉之制公正之途。及考畢，中試者與考官可立師生之誼以擴交際，季世則爲結党之一端也。考官與考生之間，要義在諸[MASK]。
家長敬重信任其子女之師也，是以教育之任托之。師長傳道受業解惑，以誨其子弟。總言之，師長位高權重，掌教學之法諸多事宜，故家長須聽而從之。彼此或以嚴父之姿共擔子弟教育之責。師長與家長之間，要義在諸[MASK]。
同鄉之間往來密切，彼此相助，共解困厄。同鄉之間，同飲一鄉之水，同言一方之音，風土人情共相習知，故他鄉之逢，倍感親切。同鄉之間，要義在諸[MASK]。
鄰里相處之道，可奠鄉里秩序之基。鄰里者，共助、共用、共慶，其要在乎協同互敬，講信修睦，可築鄉里之大同。結姻親、共耕織、連什伍，皆可固鄰里。鄰裡之間，要義在諸[MASK]。
相與出行者，同途之際，經歷相同，利益相干而目的相通也。故可相持互助，以應行途之變。同遊關係之要，在諸同心同德，共克困艱。相與出行者之間，要義在諸[MASK]。
從事買賣者，賣方或以物售之，或以役供之，買方則以貨貝易之。販賣貿買，需重信諾，禁詐紿。賣方所供務必價合質優，買方所償務必踐以約。買者與賣者之間，要義在諸[MASK]。
所謂行人，今之路人也，目有所接而言行不必交，以無深交之所需也。或逢於茶樓酒肆，或見於街巷坊裡，非有際會因緣，相交不過泛泛而已。行人之交多無深交厚誼可溯，然疏而有禮，遠而存敬。行人之間，要義在諸[MASK]。
狐朋狗友，品行不檢而相偕作樂取悅心欲者也，所好皆賭博、酗飲、狎妓之陋習。狐朋狗友之交，觥籌交錯、宴酣之樂顯於外，而犬馬聲色、熏心色欲隱其中也。狐朋狗黨之間，要義在諸[MASK]。
泛泛之友，可為同好，共論琴棋，共試酒茶，然多止於淺交。所謂淺交者，非親非疏，若敬若重，不甘于醴，亦非純淡如水也，以未深交之故也。泛泛之交之間，要義在諸[MASK]。
故舊者，情誼深遠之友也。故舊之友多共曆往事種種，然溫不增華，寒不改葉，能四時而不衰，歷險夷而仍固，相輔相助，情堅若金。故舊之間，要義在諸[MASK]。
摯友者，無血緣之親，然勝乎同產，雖貧富貴賤、生死離別不能阻隔之。摯友相交，以拳拳之心同攜手、共患難，實無價之友誼也。摯友之間，要義在諸[MASK]。
友誼之至境是謂知己。其情之深厚，遠勝泛泛相交，亦相異於親子牽絆，如奏高山流水于知音也，意動即神會，勝卻言語無數。互為知己者，彼之喜怒哀樂皆可歷歷於己心，至情至性，合若符契，而相敬之以禮；若得一知己，遑論肝膽相照，雖九死其猶未悔。友誼之至境，不過是也。知己之間，要義在諸[MASK]。
乞者與行者，多遇於市肆。乞者所欲者惟行者之施，行者之施亦可彰己憐憫之心。然二者相遇，行者多無所施，乞者或無所得，以不必施故也。乞丐與行人之間，要義在諸[MASK]。
新故官吏之閒，權力交接之關係也。去者有升、謫、免、致仕之別，而新任者，生疏于此間府衙事務，故舊任有授新任以經驗故事之責。然則離任者或以親近者安排新任左右，雖去任而威信存，且交接之際，多涉賦稅度支之核查、檔案文書之清點，案件審理之清白，田地戶口之數目，是以輕則生隙，重則黨伐。新故吏之間，要義在諸[MASK]。
獄卒之于囚犯，有羈押之權，囚犯受制于獄卒，受監守之限制。獄卒待囚犯何如，視囚犯家族之貴賤、案情判罰之輕重，及親友打點之多少而各異也。若利益相合，或義氣相投，獄卒囚犯亦可結友，然為獄卒者疾言厲色、受其暴虐者多為常態。獄卒與囚犯之間，要義在諸[MASK]。
告與被告，皆寄之律法以為己申訴辯白，而互為對立也。告劾者所求，伸曲理枉，以示法網恢恢；被告者所求，自證清白，以求洗冤昭雪。告與被告之辯，實關乎法治完備公正之有實否。告劾者與被告者之間，要義在諸[MASK]。
妻妾之間多明暗糾葛。妻者，主内也，總理治家教子之務。妾者，位卑于妻，多以存續香火，姿顏姣好之由納之。妻妾相處，或扶持相依，或勾心鬥角。《毛詩序》曰：“《關雎》樂得淑女以配君子，憂在進賢，不淫其色。”盡言正妻納妾之責，妻妾相處之道。妻妾之間，要義在諸[MASK]。

妻與外婦之間，相視若讎仇。外婦者，未娶而旁通也，無婚姻之名。外婦若有子，易致後宅不寧，亂尊卑之別，生分財之釁，是故妻與外婦多生齟齬。妻與外婦之間，要義在諸[MASK]。
夫暗合於外婦，苟且之舉也。二者無婚姻之名，為世所不齒。暗合者，或生相依相濡之情，亦或僅尋一夕貪歡。夫與外婦之間，要義在諸[MASK]。
遠親者，有血緣之絆，無近鄰之切，往來問候多訴諸婚喪嫁娶節氣，寄乎禮法倫常，以厚親戚之情。然澆薄之世，如涉祖業田產之爭，則雖遠親亦或生齟齬。遠親之間，要義在諸[MASK]。
子婿之於岳家，理應互敬互賴，然岳家垂青與否，多決於子婿之功名、族望。除入贅而改姓易族者，翁婿雖名為父子，實各異家，其情弗如同簷之婆媳遠甚，遑論血緣之親。岳家與子婿之間，要義在諸[MASK]。
同袍之誼，多喻軍旅士伍心心相惜。士卒征戰於沙場，同浴血汗、共赴國難，皆懷身先致死、盡忠報國之念。詩曰：豈曰無衣，與子同袍。是以同袍之親，勝似兄弟。同袍之間，要義在諸[MASK]。
官民之間，上下領屬之關係也。為官之道，必除害興利，善度民力，正風立綱；為民之要，必遵紀守法，立身行道。官民相處亦如父子，為人父則慈，為人子則孝，為人上則明，為人下則聖，父慈子孝，上明下聖，治之紀也。官民之間，要義在諸[MASK]。
結黨而敵對者，始於小人之同利，及其見利則爭先，或利盡而交疏，乃反相賊害。結黨者之利異，多為政見、觀念相抵，至成水火之勢。為求己利，雖其親戚兄弟不保也。敵對黨派之間，要義在諸[MASK]。
同盟即志同道合者。君子與君子以同道為朋，共守道義，行忠信，惜名節。是故同盟者得以守望相助，進退如一，莫逆於心。同盟黨派之間，要義在諸[MASK]。
保人者，受託于雙方顧主，牽繫買賣關係，以局外之身處理其間事務者也。顧主雙方多聘保人以求交易之公正，保人亦從中牟利。保人之制，早至魏晉隋唐已有所載，古商貿制度之完善據此可窺一二。保人與顧主之間，要義在諸[MASK]。
所謂忠臣，效忠于社稷者也，以鞠躬盡瘁、死而後已為己任，多為世之表率，歷代稱頌不絕。所謂逆賊，離君叛國者也，陷社稷於累卵之危、倒懸之急，世人為之不齒。忠臣與逆賊之間，要義在諸[MASK]。
主客之交，以互敬互重為本。為人主者，待人接物需完備周致，以求賓至如歸；為賓客者，亦需禮尚往來，以示謝忱。古之人倫禮制，亦見於主客相交之道也。主人與賓客之間，要義在諸[MASK]。
主奴者，主人為主而女婢為從也。主人有令，奴必應之，不可不從，以其必終於主人故也。奴之衣食起居，身家性命，全仰主意。主人和善體恤，則奴亦可豐足；主慳吝刻薄，則奴亦常縈困頓。然奴之私忠於其主也，不必係於主之慈暴，以世論其忠若犬故也。主奴之間，要義在諸[MASK]。
乳母之與嬰孩之家長，僱傭關係者也。家長或以嬌弱，或以矜貴，或以少乳，僱乳母以照料之。乳母當供乳於彼嬰幼，事其起居，乃或至教導培育。二者既系於僱傭，則信立為本而求職盡也。家長用人不疑，乳母方不墮其職也。乳母與家長之間，要義在諸[MASK]。
乳母之于嬰幼，保育者也。乳母非僅哺之以乳，且兼料其起居，助其成長，與其蒙學。長此以往，乳母或親愛嬰幼，嬰幼亦依戀乳母，此人情所致，本非乳母之分也。及長，嬰幼雖有生母，于禮當母事之，然愛信乳母，厚此而薄彼，亦時有之。雖然，若依通例，嬰幼年齒既長，無需哺乳，乳母之分即盡。更有甚者，就此別過，鮮復往來矣。乳母與嬰幼之間，要義在諸[MASK]。
凡職官者，常設正副。正者，統也。凡執掌決策，籌謀號令，皆出於正者。副者，輔也。或可決策，然猶為行正者之令耳。正副職官，或勾心鬥角，傾軋掣肘；或相交融洽，並力同心。二者相輔相成，乃自然之理，然彼此相爭，亦時有之。正職與副職之間，要義在諸[MASK]。
教首者，亦曰教主，一教之領袖也，享至高威權，眾人視之如神聖。教徒者，此教之信眾也。尊奉教首，篤信之，敬仰之，無敢有違。凡教之規，皆當嚴守；凡本教之義，教首之令，皆應踐行。由此可觀古時宗教神權之廣大威嚴，與夫信徒心靈之精誠純粹也。教首與教徒之間，要義在諸[MASK]。
一家一族，必有其祖。先祖後裔，分支散葉，世代相延，此乃家族形式之基本樣貌。祖為一族之源，綿綿瓜瓞，延而至今，其開創之始，嘉行善德，當銘於子孫，賡續不絕。子子孫孫需尊奉之，稱頌之，祠廟之，祭享之，且以顯祖榮宗為務，不可玷污門楣，蒙羞祖上。重祖以尚孝，古來如此。祖先與後代之間，要義在諸[MASK]。
保長坊長者，鄉裡街坊一方之長也，以平治鄉裡街坊之序，協官府理此地之事，上傳下達於鄉間坊間為責。居鄉裡街坊者，稱居民。居民需從保長，遵鄉規，然後可自主而為。此則城外之鄉裡，城内之街坊，其自轄之法也。保長與居民之間，要義在諸[MASK]。
遠房表親，雖非同胞，血緣略淺，然既系一族，兄弟姊妹之禮，仍需具備，並擔修睦之責，盡扶持之義。蓋開枝散葉，本自同宗，血濃於水，情繫其中，遠方表親，亦不可輕疏也。遠房表親之間，要義在諸[MASK]。
君臣之間，界限分明。君者，一國之主；臣者，輔君以治國也。君可行賞罰於臣，臣當履忠誠於君。君君，臣臣，各從其分，然孟子曰：“君之視臣如手足；則臣視君如腹心；君之視臣如犬馬，則臣視君如國人；君之視臣如土芥，則臣視君如寇讎。”是以君愛臣，則臣親君而易忠，反之則心離而人散，然儒者所謂臣之忠，忠乎社稷天下，非一人一姓也，而鼎革之節，革命之時，何謂稷天下，何謂一人一姓，人多混淆之，而一人一姓多樂其混淆也。由此觀之，君臣之間，錯綜複雜，一言難盡。君臣之義，乃上下之權力關係，亦涉個人與家國集體之關係也。君臣之間，要義在諸[MASK]。
債主與負債者，二者交通，繫於財幣。債務既成，負債者需依契約按時償之，逾期未償，債主可責之。此二者一關乎責權，二關乎財幣也。債主與負債者之間，要義在諸[MASK]。
親家者，姻親是也，為夫妻兩家父母之互稱。親家為同等之親戚，亦關世故人情。若夫婦敦睦，則親家亦諧，鮮有齟齬。親家之間，要義在諸[MASK]。
訟師之與司法者，因其職而相交也。事主有案，託於訟師，代寫文書，申訴有司，而司法者任於官府，審判其案。二者因本職而協作，並行業務於律法之事也。然地方司法，皆委縣令，多起於科舉，熟於治經，疏於律令，訟師與縣吏或沆瀣一氣，操縱案判，則蔽矣。訟師與司法者之間，要義在諸[MASK]。
訟師之於屬者，代理關係也。訟師以代撰訴狀為務，然亦可因之而受屬者之托，代其行訟。此二者一關乎責權，二關乎立信與代理也。訟師與屬者之間，要義在諸[MASK]。
捕快者，地方官府之差役也，以捉賊、治保為務。百姓為全身護財計，仰賴捕快；而捕快或濫權恣肆，百姓見而生畏。是以捕快百姓之間，關係微妙，一言難蔽百世之實。捕快與百姓之間，要義在諸[MASK]。
疑犯捕快，彼此對立。捕快之務，緝拿疑犯，而疑犯聞之，必逋逃藏匿，如鼠畏貓也。二者水火難容，矛盾多生。疑犯與捕快之間，要義在諸[MASK]。
罪犯之於人質，強之以力而脅其性命者也。犯人作奸犯科，將陷囹圄，恐牢獄之災，或挾人質以要官府。人質遭其挾而性命堪憂，以無可自主，常聽命于罪犯。罪犯與人質之間，要義在諸[MASK]。
罪犯所害之人，若有親眷，則稱苦主。苦主與罪犯為敵，視之為仇讎，冀官府緝捕，使其就法。或思血親之仇，不共戴天，則不俟官府，而有私報之也。罪犯與苦主之間，要義在諸[MASK]。
罪犯觸罪，或為旁人所觀。旁人既觀，則或有紛紛議論，批評褒貶。輿論所加，則罪犯聲名地位，亦隨之而更。是以旁人之論，或可左右決獄。而保甲之制，儒家之教，亦或使旁人作證，轉為證人也。罪犯與旁人之間，要義在諸[MASK]。
盜賊失主，彼此對立。盜賊之行，本系非法，謀竊失主，損其財物。依律，賊當償其失，並伏法受罰。盜賊與失主之間，要義在諸[MASK]。
罪犯與受害者，彼此對立。罪犯以非法加害於人，傷其身心。依律，賊當伏法受罰，以償其所害。罪犯與受害者之間，要義在諸[MASK]。
司法者與監察者，互相監督，彼此牽掣者也。司法者以審案為務，昭法之威，執法以正。監察者則督其行事或查其已行，以防其私弊貪腐，使司法必正也。司法者與監察者之間，要義在諸[MASK]。
罪犯同黨者，共犯是也。其所求所行，皆系非法，而三五聚夥，同籌共謀，一朝舉事，乃咸觸罪。依律，犯罪同黨未可消罪，以其明知共犯，或增其罪咎。罪犯同黨之間，要義在諸[MASK]。
賭徒之間，彼此相爭者也。其好博嗜賭，日以鬥雞走馬，喝雉呼盧，投注押寶為事，至於一擲千金，妄希橫富。故彼此爭財奪利，甚為激劇，不免舞弊詐欺，乃至身體相鬥者。厤朝之律法，以賭禁為常，故賭徒之間，世人皆視之為歪門邪道也。賭徒之間，要義在諸[MASK]。
文人與閱者，以文之賞識相交通者也。詩文曲賦，文人所作，常寓以其道其情，因傳其文而載其道也。閱者覽之，可明其道而體其情。夫閱者有感，或建言于文人，使其更改；而流播之廣狹，亦繫於後來之閱者。然限於古之實際，二者不得直接交通，故以單向為多。尋常閱者，難比文人之博觀群覽，不可左右其意。雖然，猶有閱者或與文人相厚，或業相關之業，或知音於後世，因而評論之，紹介之，出版之，則可左右文人之書寫，甚或筆削增潤其原文，而動搖世俗之喜好也。文人與閱者之間，要義在諸[MASK]。
文人多為士人之屬，論者亦品評之士。二者之間，實可相互磋磨學問，評鷙詩文者也。文人作詩文曲賦，而論者品藻之，其建言獻意，雖抒己之見，亦或左右文人之書寫也。於是論者作評，而文人參酌，以修色其作，推敲之定，一字之師，皆此類也。觀古之文俗世情，論者之于文人，抑揚者也。夫論者所尚，則以詩品詞話、文論筆談附益其作，播其芳名，俾傳之百世而其聲益顯，其文益高。反之，亦有詩文曲賦，論者毀之，因聲名不顯，浸微浸消者也。文人與論者之間，要義在諸[MASK]。
男女曖昧之事，悖於人倫，是以隱於心而不擅發於外。其或發於外者，亦以含蓄之言，傳微妙之情，假落紅秋葉之詩，托香囊繡帕之物，暗致其情，不令外人見也，多是之類也。曖昧者之間，以[MASK]為重。
暗戀者，古語或謂單相思。男女之間，礙于父母之命，媒妁之言，婚姻之有定也，於是己固思慕彼而不敢以私意白，彼未知而己切思之，求之不得，其情之至者，所謂“寤寐思服，輾轉反側”是也。其恪于禮者，常以春蠶絲盡、桃花依舊之喻，暗寄其心而不外傳，亦或以暗中護助，不令其有艱困愁苦，而其稍逾制者，則或致佩飾之物也。古之暗戀者，多止乎此，至若季世綱常已墮，男女忽於大防，暗戀轉直，單思為雙，則奔者難禁。暗戀者與被暗戀者之間，以[MASK]為重。
報案者之于受害者也，或同系一人，或其鄰裡親朋之知情者也。自秦法以降，遞有閭閻連坐之策，凡知情不舉者，按律當坐，王安石所目保甲法，即是也。然世有升降，國有治亂，保甲連坐之策，可行乎令行禁止之時，而文恬武嬉之季，多具文視之耳。且古時刑偵之術寡而限期破案之律在，案犯易脫幹係而有司則損利祿，是以報案者亦須證據確鑿，無可指摘，庶免乎官府之糾擾而人財俱困也。又自董子以來，列朝以儒治國，親親相隱之教，風乎百世，是以近親之間，若非大義滅親之舉，概以不報官府為長，而以鄉約族規處置也。報案者與受害者之間，以[MASK]為重。
報案者與罪犯之間多對立之關系。報案者舉罪犯之罪，冀以律法懲之。然報案者或有因擿伏發隱而罹罪犯相脅相報之禍者也。又以保甲連坐之製與大義滅親之理，報案者與罪犯之間亦或為親戚鄰裏，此又非必是兩立之勢也。報案者與罪犯之間，以[MASK]為重。
文選詩集之編者與作者，或因敬重欣賞之情，或為功利實在之用。其功利實在之用著，如著者為高官、長輩、恩師者也，甚者編者或側己文於他人之文，以彰己名也。裁約編選之時，編者常善著者之才華功業。編者亦以其選裁左右讀者之理解。文選詩集之編者與作者，實為古時文人之文化品味、審美觀念、權力關係之鑒鏡也。文選之編者與作者之間，以[MASK]為重。
表兄弟姐妹者，視同近親，關系親近，家族之情亦深也。彼於童稚之時，可共遊學、相長互助，共解所遇之危難。禮，表兄弟姐妹須循一定之禮節，長愛少，少敬長。及漸長，循授受不親之訓，以其為異姓，可通婚姻故也。表兄弟姐妹之間，以[MASK]為重。
庖人之與食客者，為服務被服務之關系也。庖人主烹飪，以甘美之食奉食客，而食客亦須念庖人之生計。故庖人須盡其技以足食客之口，食客亦須慎待庖人所供之物，此亦理之常也。或有庖人專供於食客或主人之家，則曰名廚或私廚，其與食客主人之關系則更甚其他庖人也。庖人與食客之間，以[MASK]為重。
仇敵之間乃對立衝突之關係也。敵者，匹敵也，論其才智，則相儔類，而或以利益之不均、或以地位之不匹、或以權力之不及、或以忠誠之不貞，諸此之屬，心生怨望而欲戕害以快其心者，仇敵之事也。然則，仇敵既以相噬為常，亦以其相匹，而或生相惜之感，且古時人分等級，同匹儔之人，其未為仇敵之初，或有通家之好，秦晉之交而同窗之誼也，是以古之仇敵，視今日為複雜也。故經史詩賦之中，感概仇敵之才智氣節者，亦不知凡幾也。仇敵之間，以[MASK]為重。
施恩者與受恩者為恩義與感恩之關係。施恩者之助受恩者也，或以善行，或以援手，受恩者遂感念其德，雖滴水之恩，木瓜之贈，亦矢報以湧泉瓊瑤也。古以'知恩圖報'為德之大者也。施恩者與受恩者之間，以[MASK]為重。
青梅竹馬，即為男女自幼同遊嬉戲，心生情愫者也。其情純真深沉，或終為伉儷，或為知己。古時文人墨客之述此情者，至純至美，感人心脾。青梅竹馬之間，以[MASK]為重。
情敵者，二三人傾慕同一對象，遂相競爭。此關係中，有敵意、嫉妬、競爭至於殺心之複雜心緒，然亦或有互尊呼諒者。經史詩賦之中，論及情敵，常有激烈戲謔之矛盾，或高雅而囿於禮法，或直率而流於粗鄙。情敵之間，以[MASK]為重。
天人之間，乃天地人三才之並立關系，人宜順天地，而與萬物為一。儒道皆謂人當敬天地而順之，於是乎則和也。欲和天人，需通天意，欲通天意，則在貫三才之王者，以儒家正典之論，王者得位聖賢之大號，非權勢之稱也，是以為古代知識階層與君主權力間之製衡也。天人之間，以[MASK]為重。
人神之間以信仰敬畏為維繫，其方式不離祭祀、祈禱以通達於神靈也，其指歸在乎求得神靈庇佑，解其大惑，脫其苦厄，堅其心志，導其前路也。今之視古，則謂古之信神，原乎科技落後，而驚懼敬畏于自然未知之力量也。然商周以降，中華之地，人以配天，民為神主之論，敬鬼以遠之教，人能弘道之言，天命從德之誡，經籍之載，三教之說，鹹崇人之踐行而斥虛妄之求神也。然則子雖不言怪力亂神，而人之不齊，一致百慮，可導而不可壅，是以君子明辨天理，不惑神鬼，而不責民間之求神問卜以行善避災也。人神之間，以[MASK]為重。
泛泛之交，乃交情淺薄之普通關係也。於此關係，彼此不通心意，交遊往來，相待以禮而已。泛泛之交，或可謂之朋友，然為關係最疏者也。泛泛之交之間，以[MASK]為重。
店主與顧客，為買賣交易之雙方也。店主供貨品服務於顧客，顧客以財貨償之。店主須竭其誠以應顧客之需，顧客亦需尊店主之恭敬服務于我也。所謂“買賣不成仁義在”，古時買賣之道，理不逾此。店主與顧客之間，以[MASK]為重。
官場之尊卑上下，不可逾距。上之於下，等級之中，所差愈多，威勢愈強。是以官員之間，忠敬為首，然忠敬者，忠於所守也，非忠於上司某甲也。上之於下，亦有訓導保全之義，此即古之尊卑有序、和諧中正之道也。然世閒多難行也。官場之上下級之間，以[MASK]為重。
買賣之夥伴，所共求止於利而已，緣此須相信相助，共分其利。其間信與平最為重，買賣之夥伴須以誠交易，以平分利。彼此亦須行為相協，言語相洽，以求買賣之順遂。買賣之夥伴之間，以[MASK]為重。
買賣之競爭對手，以欲求多利，欲天下求購者多求於己而俾天下財富多歸於己，於是乎有對手生焉。然生財亦當有道，故相競爭者雖有相爭之欲而求勝於對方，亦皆須守信持中，不得狡求他人之利。要之，亦有尊重也。買賣之競爭對手之間，以[MASK]為重。
宗教師徒，在於信仰之傳續繼承。師者，教訓徒弟，徒者，尊師重道，忠於師命。其間尊與忠為最重，徒須尊師忠命，師須護持教徒。宗教師徒之間，以[MASK]為重。
百工之師父與學徒，在於技藝之傳承。傳技之時，師者須教導訓誡其徒，徒者須尊敬愛重其師。其間尊與忠為最重，徒須尊師忠命，師須護持教徒。師傅與學徒之間，以[MASK]為重。
古之掌櫃與客人，因買賣交易為緣。掌櫃者經營其店。客人者消費之人也，求店主之所供。掌櫃須供客人所需，以求信與利。客人亦須敬重掌櫃，不得違其買賣之道。掌櫃與客人之間，以[MASK]為重。
古之首領與反賊，以勢不兩雄為常。首領者，為國之首領，反賊者，為國之叛逆。首領須守其威勢與現有之秩序，反賊則欲反叛其威勢與現有之秩序。首領與反賊之間，以[MASK]為重。
叔侄為血親。叔者為父之弟，侄者為兄之子。叔有教育侄之責，侄須愛敬叔，然亦須視其父母之存亡與學識尊卑論叔撫育之任也。叔侄關係於家族之中為極重要之關係。叔侄之間，以[MASK]為重。
雙胞胎因其母一胎同產之同胞，其情於血親手足之中為最近也。同孕母腹，同生一時，同長一處，其形其態其跡在成人之前尤多為相似，故其未冠笄之時，蓋情最深厚，或施及平生。雙胞胎之間，以[MASK]為重。
於政治之中，兩方之會晤多因權與利之爭鬥也。多以其政治與國家所屬不同，冀會晤以求成結盟。兩方須守盟會之理，於守自身之利為上為底，亦宜慮對方之利，以成盟約也。政治談判中對立之雙方之間，以[MASK]為重。
堂兄弟姐妹為親戚，然其親不過於同胞兄弟姐妹。於家族之中，堂兄弟姐妹可與嫡子女同長共學，亦同為長者所愛，然於家財分配，若非嫡子女亡故出繼，則不得分其家財，然亦多有倚勢強奪家財之事。論及尊卑，堂兄弟姐妹之長者亦為家族所重。堂兄弟姐妹之間，以[MASK]為重。
古者以父系別家族，故同父異母與同母異父之子女之所受對待全然不同。若子女為同父異母，則其於家族之中尊卑貴賤則從母之所處為父之發妻、續弦、妾之等而不同，及其母之存亡與母家之勢而定，然其爲一家之人，則無疑也。若子女為同母異父，則多因父之續娶他婦，其母之前夫子女多為後嫁之家族異姓視之，其被賤待，亦其常也，然亦須視其後父家之心與其母家之勢。同父異母與同母異父之子女之間，以[MASK]為重。
繼子女之間，雖為親戚，但彼此犬牙交錯，一言難磬。繼母與繼父之子女之關系亦相去萬裏。古者，父親多主家族，父親續娶，繼母亦為繼子之母也。然若母親改醮，繼子則從母而入繼父家，其家族關系亦全然改換也。若父母於其前夫前妻亡故後另結婚姻，則或因繼父繼母之愛而另生齟齬。家產之分配，若其母為繼母，則繼子女（若其女子未嫁）以律法可得所應之家產。若其父為繼父，則繼子女非繼父及家族所允，以律法不得受家產。繼子女之間，以[MASK]為重。
古之為官，同僚之間以官位相近，同朝合堂，共謀於事。然或因其職所守相近，未免於相爭，而生齟齬者亦多有之。同僚之間尊卑之序則定以官位高低、資望長短。同僚之間，以[MASK]為重。
庠序之間，同窗之間以求學問知識為共識，相助於學，共進於道。然因修業之優劣，成績之高下，而生齟齬者亦有之。同窗之間，常為對等之交，然亦可守尊卑之禮而以年齒為序，此多為交往之禮便耳。同窗之間，以[MASK]為重。
所謂搭訕者，意在親近被搭訕者，以其欲與被搭訕者交好而有所圖也。搭訕者之於被搭訕者，或欲作綈袍之義，或欲結琴瑟之好，或欲為買賣之宜。二者之關系，主動與被動並存，不確與不穩共生。然搭訕者多有所求，故世貶其行，經史詩賦亦多譏之。搭訕者與被搭訕者之間，以[MASK]為重。
施害者乃刑案中為暴力罪行者也。受害者乃因施害者之暴而罹身體乃至於性命之禍也。施害者與受害者，或為兩立，或為抵牾。經史典籍錄此案件，多因其所涉或為欺公罔法，或為其案情之重大曲折，蒙冤者終得昭雪也。然亦多為尋常案件之受害與被害關系。刑案中之施害者與受害者之間，以[MASK]為重。
古之旁觀者乃睹罪案而無與者也。或為偶然，或特持中而觀也。旁觀者之與受害者，論其行多有意疏遠之，跡其心則漠然或哀憫，然則旁觀者亦有因保甲連坐製度而或肯作證者。刑案中之受害者與旁觀者之間，以[MASK]為重。

屋主者，有屋貰於人者也。承租者，僦屋於人者也。屋主與承租者，常為權利義務之交易，或有經濟利益之抵牾，然得租賃者，亦彼此利之中和也。屋主與承租者之間，以[MASK]為重。
夫婦之關係，雖為平等而以男性為主導，家中事務由男性裁決，女子應遵奉，然亦視母家地位及其實力。夫婦之間，尤重忠誠尊重，互為匹敵，互相照顧，守家族和睦也。夫婦之間，以[MASK]為重。
夥計與顧客之關係以商貿為基，夥計須敬、誠、勤、恭，供以良品及服務。顧客則於良品與服務，受之以禮，成兩全之美事。夥計與顧客之間，以[MASK]為重。
父母與子女之閒，以孝為要，從其道，分其憂，解其難。爲其子者須事親以終其天年，爲其女者，既嫁亦省親有定期，且盡力照拂有難者，不以有歸為辭也。父母則應愛憐其子、育其成才，仿三遷而擇佳處也。父母與子女之間，以[MASK]為重。
義父母與義子女之關係，亦以孝為要。養子須事長以終其天年，養女亦受為人女之道。義父母則應愛憐有度、育子成才。義父母與義子女之間，以[MASK]為重。
翁媳若父女，故以孝、敬、恭系之，然以非親之故，兼有男女之防，媳固當孝翁視親，亦從於令而不可逾于矩。翁當護其周全而不可密邇。要約以禮，不忘授受不親之訓也。公公與兒媳之間，以[MASK]為重。
婆媳乃家中上下級關係也。婆為長為尊，有督導教育之責，媳則尊之孝之，有若母子然。婦歸夫家，夫妻之外，婆媳為重大關係也。婆婆與兒媳之間，以[MASK]為重。
主人與家丁為主僕之關係。主人發號施令，家丁則從令而行，稟其忠也。此關係乃權力與經濟之關係之象徵，主人，富貴者也；家丁，卑賤者也，以此業為生。家丁亦有以契約而世代為奴，則主僕之分益固也。主人與家丁之間，以[MASK]為重。
地主與佃農之間，乃經濟之關係。地主佔田地，佃農租田以謀生。此關係為經濟依賴關係，地主因佃農而得益，佃農傍田地以得生。地主與佃農之間，以[MASK]為重。
店主與夥計乃勞動關係。店主以市肆營生，募選數夥計以經營，夥計從其令而行。此關係乃經濟與勞動之關係，店主因夥計而得益，夥計不辭辛苦而獲薪俸。店主與夥計之間，以[MASK]為重。
官員之與行賄者，權錢之交易也。官員有權，行賄者有金，進賄金以鬻權取利也。此雖違法之事，然世非罕見，甚或相沿成習而得以為默規，異代不鮮也。官員與行賄者之間，以[MASK]為重。
狀元、榜眼、探花，為科舉殿試之冠、亞、季稱謂也。考生之間，競爭、合作，以求仕進，固彼此為競爭對手。於科舉中，狀元為首，榜眼、探花次之。狀元與榜眼與探花之間，以[MASK]為重。
綠林好漢首領之與屬下（嘍羅），領導者與被領導者也。首領常以其勇武、智謀得天下，而為領導者。兩者之間，亦視將兵之關係，故於首領命令，屬下（嘍羅）須從而為之，等軍法也。綠林好漢之首領與屬下之間，以[MASK]為重。
繼父母與子女，乃法定親子關係也。或以原配父母猝然離世，或為離鸞別鳳，繼父母入其家庭，擔養育之責，子女須敬之、從之。繼子女承業於繼母家庭，禮也，法也；而繼父家庭者則或否也，視繼父及其家族態度而定。繼父母與子女之間，以[MASK]為重。
繼祖父母與繼孫，亦為法定之親子關係也。若父母猝然離世，或為離鸞別鳳，由一方再婚而入他家，則繼父母父母之父母為繼祖父母。繼祖父母有養育之恩澤，子女須孝敬順從之。繼祖父母與繼子孫之關係，視繼子女之與繼父母關係而迥別也，或為同姓則可親似家人，或為異姓而忽視之也。參繼父母-子女條。繼祖父母與繼孫之間，以[MASK]為重。
養父母與子女，緣以養育之恩，而成親子之情。或父母失於養育，或子女棄於街頭，有善人收養，則為養父母。養父母擔養育之責，子女須孝之同其親然。養子女承業，須視養父母及其家族之意，若有爭議，可訴之官府，然蓋罕見也。養父母與子女之間，以[MASK]為重。
古人尤重師生之誼，尊師重道，古之訓也。師者，傳道受業解惑之人，教人以禮以知以識以技。學生尊之、敬之，師者愛之、誨之，古時師生關係以父子關係為本，然孝廉科舉之興，亦俾染利祿之關聯也。師生之間，以[MASK]為重。
家庭（家族）私塾為昔者大家族子弟啟蒙教育之場所也。所聘之家庭私塾教師，或家族之飽學長者，或科場之落第者，或中而未仕者。教童稚以讀書寫字，其常業也，有言傳身教之責，教導其為人之道。故塾師之於弟子，或代族中長者訓誡子弟，或但為教書先生，視教師身份地位或其家族地位而定。家庭私塾教師與學生之間，以[MASK]為重。
小人于後世多目品行卑劣、心胸狹窄、唯利是圖之人。“小人之交”則指此等人之彼此關係也，其以利為本，漠視誠信，唯權謀與爭利而已。小人之交之間，以[MASK]為重。
佛教徒以佛法信仰為紐，慈悲為懷，同修而互助，以求得佛法真諦，共成和諧、平等、互助之關係。然自佛滅以來，教派紛然，利欲之心，恆難寂滅，故其以宗派、僧團、寺廟之異，彼此爭端，歷代恆有。佛教徒之間，以[MASK]為重。
道教徒以修仙教化為要務，無為而治，自然和諧，天地共生，萬物為一，以求長生不老，故道教徒之間，以平和、寬容、尊重為常。然其亦或以宗派、僧團、寺廟之異，而起爭端。道教徒之間，以[MASK]為重。
髮小者，自幼相識之友也，其行跡相似相同，故其交往甚近。兩人之間，可不甚囿於禮法，故率真而坦誠。發小之間，以[MASK]為重。
本地人之與異鄉人，關係複雜。以編戶齊民之故，民重遷徙，是以處於異域，本地人或嚴以防範，或疏以情感。又以方音之差、風俗之別，異鄉人恆倍感孤困。然亦有好客之人，助其在此安居也。本地人與異鄉人之間，以[MASK]為重。
土籍之人與客籍之人之問題，漢季以來，盤根錯節，乞于民清之際，未有終結也。其世居鄉土之地而編戶于官府者，謂之土籍之人；其離鄉背井、人徙居於他鄉而籍未更者，則為客籍之人。二者之異，於編戶齊民之策率有體現。大抵土籍之人地位高於客籍，故土籍之人多主人自視，深有自得之意。然客籍與土籍，雜處一地，或以田土之不均、或以經濟之不等、或以社會地位之不匹，或以稅賦政令之不平，而勢有消長。其間以土地、人口、政治權力諸此之屬而滋生矛盾，然和中寓爭，爭中寓和，幾世之後，二者以共處、合作與通婚之故，兼之戶籍更新，斷客為主之策，二者之異同，日愈消弭，并同土籍，此其常也。然舊之客籍未泯，而新之客籍又生，此又其常也。土籍人士與客籍人士之間，以[MASK]為重。
外祖父母與外孫或外孫女，多倫常親呢之情也。蓋將綱常倫理而觀之，則外祖父母之於外孫或外孫女，或不及外祖父母之於內孫或內孫女親密。然自私心而論，則未必如是，若紅樓夢中以座次定尊卑，外孫女林黛玉尊於內孫三春則是一例。此皆因家族結構而致，謂之外孫或外孫女當屬妻家，非屬夫家也，故禮數殊矣。外祖父母與外孫/外孫女之間，以[MASK]為重。
門當戶對之訂婚男女，其關係多由家族所定。其婚姻，非止兩人之結合，亦兩家以聯姻相合也。故其關係，或受家族、社會地位、財富等之影響。于訂婚之前，彼此交往不多，甚者未嘗謀面，然皆需遵家族與社會之規定，成合卺之禮。門當戶對之訂婚男女之間，以[MASK]為重。
私奔者，乃背禮叛教所以追情求愛也。常語以爲聘妻奔妾，然或以一見傾心欲早遂佳期，或以門戶不當而父母弗允，或以私情而拋其家室，不顧雙親兒女，終於淫奔者，以其愛戀之深，不可自抑也。然則負罵名，走他鄉，前途何卜，亦難以預知也。私奔男女之間，以[MASK]為重。
同科舉人之間，競爭與互助兼有之也。科舉，士進之途也，遂引天下讀書人埋頭于科舉之書。然進士之途窄矣，應試者多而中試者寡，其得高中以啓顯宦之階者則尤寡也。故于科考之時為競爭對手，然於考試之外，或可相學互助。考中者，若無素時芥蒂，咸可共相交友，以廣交際。同科舉人之間，以[MASK]為重。
同門師兄弟之間存恭謹相敬之情、患難相濟之意。其同拜一師，共得其教，故同門之情宜深矣。彼其有同門之敬助，攜手共進。若無有利祿貪欲之心，則同門師兄弟之間，充盈友愛之情，必也。同門師兄弟之間，以[MASK]為重。
同校學生之間，友情與競爭兼有之也。彼學於同一學校，有同窗共硯之情。然非獨限於共學之時矣，待卒業及從業後，亦可成通力合作之事。同校學生之間，以[MASK]為重。
山長者，書院衆師之長，亦書院之主管也；講席，書院所延聘之教師也。書院之治，向以寬而有別於官學也。官學之治，以屬官府而有等級高下之判。書院則否，以山長之道德文章為維繫也，以地方劃撥之田地房舍為生養也，是以山長之與講席，一講席之首座耳，志同則合，志異則散，山長之管書院者，攝也，固當共尊書院之規，不以勢相凌，是以寬。然有清之後，書院亦官學化也，非概得以寬一之。學府書院之山長與講席之間，以[MASK]為重。
同父同母之子女，為同胞之兄弟姊妹也，此乃血緣至親。同胞兄弟姊妹間多親呢，常勝於非同胞者。同父同母之子女之間，以[MASK]為重。
戲班與劇作者之間多合作也。劇作者撰作戲劇劇本，而戲班搬演劇作，以供觀眾欣賞。戲班之人身卑籍賤，然劇作者或為讀書人，位四民之首，甚者有功名焉，以差距懸殊之故，所謂合作者，亦鬆散之形式也。劇作者未必依演出之狀況而作成案頭之曲，戲班之於作品之呈現，亦未必符契原文，其違作者原意而有自行發揮之處者，蓋不勝舉也。戲班與劇作者之間，以[MASK]為重。
戲子，上臺演出者也；看官，觀賞表演者也。戲子以其表演技巧取悅看客，博看官捧場，而看官之回應，或於大快人心之處喝采，或於角色含冤負屈之處泣下。高超之技藝固得掌聲口譽，反之則致倒彩譏嘲。因之戲子須重看官之反應，然戲子卑微低賤，看官之於戲子，決於看官自身之態度與修養，借其賤戲子，以之為下等，亦不違世俗之德。戲子與看官之間，以[MASK]為重。
音樂曲藝人，以賞心悅耳之音求生計者也；聽眾，品賞其音樂曲藝者也。音樂曲藝人以其曲藝之才悅聽眾之耳，聽眾則據藝人之水準報以讚譽財物也。要之，藝人須以聽眾之反應為重，然曲藝人恆処賤籍，故與聽眾或不對等也。音樂曲藝人與聽眾之間，以[MASK]為重。
祖孫之間尊卑長幼宜井然有序。祖父母位高於父母，是以孫子女之於祖父母，尤須以禮敬重孝順之，以終其天年，是亦儒家倫理之不可或缺者也。祖孫之間，以[MASK]為重。
大夫，醫者之敬稱也。古之良大夫也，以扁鵲華佗之資，行救死扶傷之舉。病者若知曉大夫之醫術兼信之，則病者得瘳而醫者受譽，然則病者之與醫者，亦隨醫者口碑之優劣、人品之高下，與夫病者病情之變化、性格之差異而有別。大夫與病者之間，以[MASK]為重。
姨父姨母與侄子侄女之間存親戚之情也。姨父母以其長者慈顧幼小，幼者敬其長者，此為華夏家庭親情倫理之恆常。姨父姨母與侄子侄女之間，以[MASK]為重。
行俠仗義者，救受助者於水火災厄之中。仗其勇力，憑其志氣，赴人之困頓，軌俠之道義。至於受助者，則當銜環結草以報其恩也，是俠氣之所傳，而仁義有所弘也，夫緩人之所急，脫人之所危，曷可少也。行俠仗義者與受助者之間，以[MASK]為重。
妓女者，誤落風塵，陷於倡家，有姿色者賓客如市而衰老者落拓餘生。嫖客以錢財之豐厚，走馬章台，縱其情欲也。然二者之間，或漸生情愫，以成好合者，往往有之，然沉箱剃髮之悲，蓋尤其多也。狎妓違君子德風之誨，悖於人倫常理，為世之所誅責。然歷代官家律令以存秦樓楚館為慣例，《管子》發其端也。嫖客與妓女之間，以[MASK]為重。
掌櫃者，受店主所托，掌日常經營之事宜，凡貨物之進出、價格之定立、賬目之記錄諸類者皆須過問。掌櫃當不負店主所托之責，店主則當行察看之勸，以驗其實績。掌櫃與店主之間，以[MASK]為重。
夥計與掌櫃之間，上下級也。夥計，掌櫃之下屬也，掌日常營業之細事，凡接待賓客、售賣商品、搬運貨物之類也。掌櫃行指導管理之勸，而夥計聽其所命。掌櫃與夥計之間，以[MASK]為重。
捐助者，施以財物之助，不苛求彼之回報；受惠者，受其所助而當銜環結草，以報其恩德也。仁愛互助之義在其中矣。捐助者與受惠者之間，以[MASK]為重。
將領與士兵之間，上下級也。將領之帶兵也，其高明者在於寬嚴並濟，既嚴於治軍，又時彰仁愛兵卒之美德行，以兵為子。然軍令如山，故士兵須惟命是聽。此則軍隊令行禁止之法也。將領與士兵之間，以[MASK]為重。
考官之與考生，主試與被試者也。考官評考生之學識才能，而考生須受考官之評鑒。此乃科舉之制公正之途。及考畢，中試者與考官可立師生之誼以擴交際，季世則爲結党之一端也。考官與考生之間，以[MASK]為重。
家長敬重信任其子女之師也，是以教育之任托之。師長傳道受業解惑，以誨其子弟。總言之，師長位高權重，掌教學之法諸多事宜，故家長須聽而從之。彼此或以嚴父之姿共擔子弟教育之責。師長與家長之間，以[MASK]為重。
同鄉之間往來密切，彼此相助，共解困厄。同鄉之間，同飲一鄉之水，同言一方之音，風土人情共相習知，故他鄉之逢，倍感親切。同鄉之間，以[MASK]為重。
鄰里相處之道，可奠鄉里秩序之基。鄰里者，共助、共用、共慶，其要在乎協同互敬，講信修睦，可築鄉里之大同。結姻親、共耕織、連什伍，皆可固鄰里。鄰裡之間，以[MASK]為重。
相與出行者，同途之際，經歷相同，利益相干而目的相通也。故可相持互助，以應行途之變。同遊關係之要，在諸同心同德，共克困艱。相與出行者之間，以[MASK]為重。
從事買賣者，賣方或以物售之，或以役供之，買方則以貨貝易之。販賣貿買，需重信諾，禁詐紿。賣方所供務必價合質優，買方所償務必踐以約。買者與賣者之間，以[MASK]為重。
所謂行人，今之路人也，目有所接而言行不必交，以無深交之所需也。或逢於茶樓酒肆，或見於街巷坊裡，非有際會因緣，相交不過泛泛而已。行人之交多無深交厚誼可溯，然疏而有禮，遠而存敬。行人之間，以[MASK]為重。
狐朋狗友，品行不檢而相偕作樂取悅心欲者也，所好皆賭博、酗飲、狎妓之陋習。狐朋狗友之交，觥籌交錯、宴酣之樂顯於外，而犬馬聲色、熏心色欲隱其中也。狐朋狗黨之間，以[MASK]為重。
泛泛之友，可為同好，共論琴棋，共試酒茶，然多止於淺交。所謂淺交者，非親非疏，若敬若重，不甘于醴，亦非純淡如水也，以未深交之故也。泛泛之交之間，以[MASK]為重。
故舊者，情誼深遠之友也。故舊之友多共曆往事種種，然溫不增華，寒不改葉，能四時而不衰，歷險夷而仍固，相輔相助，情堅若金。故舊之間，以[MASK]為重。
摯友者，無血緣之親，然勝乎同產，雖貧富貴賤、生死離別不能阻隔之。摯友相交，以拳拳之心同攜手、共患難，實無價之友誼也。摯友之間，以[MASK]為重。
友誼之至境是謂知己。其情之深厚，遠勝泛泛相交，亦相異於親子牽絆，如奏高山流水于知音也，意動即神會，勝卻言語無數。互為知己者，彼之喜怒哀樂皆可歷歷於己心，至情至性，合若符契，而相敬之以禮；若得一知己，遑論肝膽相照，雖九死其猶未悔。友誼之至境，不過是也。知己之間，以[MASK]為重。
乞者與行者，多遇於市肆。乞者所欲者惟行者之施，行者之施亦可彰己憐憫之心。然二者相遇，行者多無所施，乞者或無所得，以不必施故也。乞丐與行人之間，以[MASK]為重。
新故官吏之閒，權力交接之關係也。去者有升、謫、免、致仕之別，而新任者，生疏于此間府衙事務，故舊任有授新任以經驗故事之責。然則離任者或以親近者安排新任左右，雖去任而威信存，且交接之際，多涉賦稅度支之核查、檔案文書之清點，案件審理之清白，田地戶口之數目，是以輕則生隙，重則黨伐。新故吏之間，以[MASK]為重。
獄卒之于囚犯，有羈押之權，囚犯受制于獄卒，受監守之限制。獄卒待囚犯何如，視囚犯家族之貴賤、案情判罰之輕重，及親友打點之多少而各異也。若利益相合，或義氣相投，獄卒囚犯亦可結友，然為獄卒者疾言厲色、受其暴虐者多為常態。獄卒與囚犯之間，以[MASK]為重。
告與被告，皆寄之律法以為己申訴辯白，而互為對立也。告劾者所求，伸曲理枉，以示法網恢恢；被告者所求，自證清白，以求洗冤昭雪。告與被告之辯，實關乎法治完備公正之有實否。告劾者與被告者之間，以[MASK]為重。
妻妾之間多明暗糾葛。妻者，主内也，總理治家教子之務。妾者，位卑于妻，多以存續香火，姿顏姣好之由納之。妻妾相處，或扶持相依，或勾心鬥角。《毛詩序》曰：“《關雎》樂得淑女以配君子，憂在進賢，不淫其色。”盡言正妻納妾之責，妻妾相處之道。妻妾之間，以[MASK]為重。
妻與外婦之間，相視若讎仇。外婦者，未娶而旁通也，無婚姻之名。外婦若有子，易致後宅不寧，亂尊卑之別，生分財之釁，是故妻與外婦多生齟齬。妻與外婦之間，以[MASK]為重。
夫暗合於外婦，苟且之舉也。二者無婚姻之名，為世所不齒。暗合者，或生相依相濡之情，亦或僅尋一夕貪歡。夫與外婦之間，以[MASK]為重。
遠親者，有血緣之絆，無近鄰之切，往來問候多訴諸婚喪嫁娶節氣，寄乎禮法倫常，以厚親戚之情。然澆薄之世，如涉祖業田產之爭，則雖遠親亦或生齟齬。遠親之間，以[MASK]為重。
子婿之於岳家，理應互敬互賴，然岳家垂青與否，多決於子婿之功名、族望。除入贅而改姓易族者，翁婿雖名為父子，實各異家，其情弗如同簷之婆媳遠甚，遑論血緣之親。岳家與子婿之間，以[MASK]為重。
同袍之誼，多喻軍旅士伍心心相惜。士卒征戰於沙場，同浴血汗、共赴國難，皆懷身先致死、盡忠報國之念。詩曰：豈曰無衣，與子同袍。是以同袍之親，勝似兄弟。同袍之間，以[MASK]為重。
官民之間，上下領屬之關係也。為官之道，必除害興利，善度民力，正風立綱；為民之要，必遵紀守法，立身行道。官民相處亦如父子，為人父則慈，為人子則孝，為人上則明，為人下則聖，父慈子孝，上明下聖，治之紀也。官民之間，以[MASK]為重。
結黨而敵對者，始於小人之同利，及其見利則爭先，或利盡而交疏，乃反相賊害。結黨者之利異，多為政見、觀念相抵，至成水火之勢。為求己利，雖其親戚兄弟不保也。敵對黨派之間，以[MASK]為重。
同盟即志同道合者。君子與君子以同道為朋，共守道義，行忠信，惜名節。是故同盟者得以守望相助，進退如一，莫逆於心。同盟黨派之間，以[MASK]為重。
保人者，受託于雙方顧主，牽繫買賣關係，以局外之身處理其間事務者也。顧主雙方多聘保人以求交易之公正，保人亦從中牟利。保人之制，早至魏晉隋唐已有所載，古商貿制度之完善據此可窺一二。保人與顧主之間，以[MASK]為重。
所謂忠臣，效忠于社稷者也，以鞠躬盡瘁、死而後已為己任，多為世之表率，歷代稱頌不絕。所謂逆賊，離君叛國者也，陷社稷於累卵之危、倒懸之急，世人為之不齒。忠臣與逆賊之間，以[MASK]為重。
主客之交，以互敬互重為本。為人主者，待人接物需完備周致，以求賓至如歸；為賓客者，亦需禮尚往來，以示謝忱。古之人倫禮制，亦見於主客相交之道也。主人與賓客之間，以[MASK]為重。
主奴者，主人為主而女婢為從也。主人有令，奴必應之，不可不從，以其必終於主人故也。奴之衣食起居，身家性命，全仰主意。主人和善體恤，則奴亦可豐足；主慳吝刻薄，則奴亦常縈困頓。然奴之私忠於其主也，不必係於主之慈暴，以世論其忠若犬故也。主奴之間，以[MASK]為重。
乳母之與嬰孩之家長，僱傭關係者也。家長或以嬌弱，或以矜貴，或以少乳，僱乳母以照料之。乳母當供乳於彼嬰幼，事其起居，乃或至教導培育。二者既系於僱傭，則信立為本而求職盡也。家長用人不疑，乳母方不墮其職也。乳母與家長之間，以[MASK]為重。
乳母之于嬰幼，保育者也。乳母非僅哺之以乳，且兼料其起居，助其成長，與其蒙學。長此以往，乳母或親愛嬰幼，嬰幼亦依戀乳母，此人情所致，本非乳母之分也。及長，嬰幼雖有生母，于禮當母事之，然愛信乳母，厚此而薄彼，亦時有之。雖然，若依通例，嬰幼年齒既長，無需哺乳，乳母之分即盡。更有甚者，就此別過，鮮復往來矣。乳母與嬰幼之間，以[MASK]為重。
凡職官者，常設正副。正者，統也。凡執掌決策，籌謀號令，皆出於正者。副者，輔也。或可決策，然猶為行正者之令耳。正副職官，或勾心鬥角，傾軋掣肘；或相交融洽，並力同心。二者相輔相成，乃自然之理，然彼此相爭，亦時有之。正職與副職之間，以[MASK]為重。
教首者，亦曰教主，一教之領袖也，享至高威權，眾人視之如神聖。教徒者，此教之信眾也。尊奉教首，篤信之，敬仰之，無敢有違。凡教之規，皆當嚴守；凡本教之義，教首之令，皆應踐行。由此可觀古時宗教神權之廣大威嚴，與夫信徒心靈之精誠純粹也。教首與教徒之間，以[MASK]為重。

一家一族，必有其祖。先祖後裔，分支散葉，世代相延，此乃家族形式之基本樣貌。祖為一族之源，綿綿瓜瓞，延而至今，其開創之始，嘉行善德，當銘於子孫，賡續不絕。子子孫孫需尊奉之，稱頌之，祠廟之，祭享之，且以顯祖榮宗為務，不可玷污門楣，蒙羞祖上。重祖以尚孝，古來如此。祖先與後代之間，以[MASK]為重。
保長坊長者，鄉裡街坊一方之長也，以平治鄉裡街坊之序，協官府理此地之事，上傳下達於鄉間坊間為責。居鄉裡街坊者，稱居民。居民需從保長，遵鄉規，然後可自主而為。此則城外之鄉裡，城内之街坊，其自轄之法也。保長與居民之間，以[MASK]為重。
遠房表親，雖非同胞，血緣略淺，然既系一族，兄弟姊妹之禮，仍需具備，並擔修睦之責，盡扶持之義。蓋開枝散葉，本自同宗，血濃於水，情繫其中，遠方表親，亦不可輕疏也。遠房表親之間，以[MASK]為重。
君臣之間，界限分明。君者，一國之主；臣者，輔君以治國也。君可行賞罰於臣，臣當履忠誠於君。君君，臣臣，各從其分，然孟子曰：“君之視臣如手足；則臣視君如腹心；君之視臣如犬馬，則臣視君如國人；君之視臣如土芥，則臣視君如寇讎。”是以君愛臣，則臣親君而易忠，反之則心離而人散，然儒者所謂臣之忠，忠乎社稷天下，非一人一姓也，而鼎革之節，革命之時，何謂稷天下，何謂一人一姓，人多混淆之，而一人一姓多樂其混淆也。由此觀之，君臣之間，錯綜複雜，一言難盡。君臣之義，乃上下之權力關係，亦涉個人與家國集體之關係也。君臣之間，以[MASK]為重。
債主與負債者，二者交通，繫於財幣。債務既成，負債者需依契約按時償之，逾期未償，債主可責之。此二者一關乎責權，二關乎財幣也。債主與負債者之間，以[MASK]為重。
親家者，姻親是也，為夫妻兩家父母之互稱。親家為同等之親戚，亦關世故人情。若夫婦敦睦，則親家亦諧，鮮有齟齬。親家之間，以[MASK]為重。
訟師之與司法者，因其職而相交也。事主有案，託於訟師，代寫文書，申訴有司，而司法者任於官府，審判其案。二者因本職而協作，並行業務於律法之事也。然地方司法，皆委縣令，多起於科舉，熟於治經，疏於律令，訟師與縣吏或沆瀣一氣，操縱案判，則蔽矣。訟師與司法者之間，以[MASK]為重。
訟師之於屬者，代理關係也。訟師以代撰訴狀為務，然亦可因之而受屬者之托，代其行訟。此二者一關乎責權，二關乎立信與代理也。訟師與屬者之間，以[MASK]為重。
捕快者，地方官府之差役也，以捉賊、治保為務。百姓為全身護財計，仰賴捕快；而捕快或濫權恣肆，百姓見而生畏。是以捕快百姓之間，關係微妙，一言難蔽百世之實。捕快與百姓之間，以[MASK]為重。
疑犯捕快，彼此對立。捕快之務，緝拿疑犯，而疑犯聞之，必逋逃藏匿，如鼠畏貓也。二者水火難容，矛盾多生。疑犯與捕快之間，以[MASK]為重。
罪犯之於人質，強之以力而脅其性命者也。犯人作奸犯科，將陷囹圄，恐牢獄之災，或挾人質以要官府。人質遭其挾而性命堪憂，以無可自主，常聽命于罪犯。罪犯與人質之間，以[MASK]為重。
罪犯所害之人，若有親眷，則稱苦主。苦主與罪犯為敵，視之為仇讎，冀官府緝捕，使其就法。或思血親之仇，不共戴天，則不俟官府，而有私報之也。罪犯與苦主之間，以[MASK]為重。
罪犯觸罪，或為旁人所觀。旁人既觀，則或有紛紛議論，批評褒貶。輿論所加，則罪犯聲名地位，亦隨之而更。是以旁人之論，或可左右決獄。而保甲之制，儒家之教，亦或使旁人作證，轉為證人也。罪犯與旁人之間，以[MASK]為重。
盜賊失主，彼此對立。盜賊之行，本系非法，謀竊失主，損其財物。依律，賊當償其失，並伏法受罰。盜賊與失主之間，以[MASK]為重。
罪犯與受害者，彼此對立。罪犯以非法加害於人，傷其身心。依律，賊當伏法受罰，以償其所害。罪犯與受害者之間，以[MASK]為重。
司法者與監察者，互相監督，彼此牽掣者也。司法者以審案為務，昭法之威，執法以正。監察者則督其行事或查其已行，以防其私弊貪腐，使司法必正也。司法者與監察者之間，以[MASK]為重。
罪犯同黨者，共犯是也。其所求所行，皆系非法，而三五聚夥，同籌共謀，一朝舉事，乃咸觸罪。依律，犯罪同黨未可消罪，以其明知共犯，或增其罪咎。罪犯同黨之間，以[MASK]為重。
賭徒之間，彼此相爭者也。其好博嗜賭，日以鬥雞走馬，喝雉呼盧，投注押寶為事，至於一擲千金，妄希橫富。故彼此爭財奪利，甚為激劇，不免舞弊詐欺，乃至身體相鬥者。厤朝之律法，以賭禁為常，故賭徒之間，世人皆視之為歪門邪道也。賭徒之間，以[MASK]為重。
文人與閱者，以文之賞識相交通者也。詩文曲賦，文人所作，常寓以其道其情，因傳其文而載其道也。閱者覽之，可明其道而體其情。夫閱者有感，或建言于文人，使其更改；而流播之廣狹，亦繫於後來之閱者。然限於古之實際，二者不得直接交通，故以單向為多。尋常閱者，難比文人之博觀群覽，不可左右其意。雖然，猶有閱者或與文人相厚，或業相關之業，或知音於後世，因而評論之，紹介之，出版之，則可左右文人之書寫，甚或筆削增潤其原文，而動搖世俗之喜好也。文人與閱者之間，以[MASK]為重。
文人多為士人之屬，論者亦品評之士。二者之間，實可相互磋磨學問，評鷙詩文者也。文人作詩文曲賦，而論者品藻之，其建言獻意，雖抒己之見，亦或左右文人之書寫也。於是論者作評，而文人參酌，以修色其作，推敲之定，一字之師，皆此類也。觀古之文俗世情，論者之于文人，抑揚者也。夫論者所尚，則以詩品詞話、文論筆談附益其作，播其芳名，俾傳之百世而其聲益顯，其文益高。反之，亦有詩文曲賦，論者毀之，因聲名不顯，浸微浸消者也。文人與論者之間，以[MASK]為重。
男女曖昧之事，悖於人倫，是以隱於心而不擅發於外。其或發於外者，亦以含蓄之言，傳微妙之情，假落紅秋葉之詩，托香囊繡帕之物，暗致其情，不令外人見也，多是之類也。曖昧者之間，以[MASK]為本。
暗戀者，古語或謂單相思。男女之間，礙于父母之命，媒妁之言，婚姻之有定也，於是己固思慕彼而不敢以私意白，彼未知而己切思之，求之不得，其情之至者，所謂“寤寐思服，輾轉反側”是也。其恪于禮者，常以春蠶絲盡、桃花依舊之喻，暗寄其心而不外傳，亦或以暗中護助，不令其有艱困愁苦，而其稍逾制者，則或致佩飾之物也。古之暗戀者，多止乎此，至若季世綱常已墮，男女忽於大防，暗戀轉直，單思為雙，則奔者難禁。暗戀者與被暗戀者之間，以[MASK]為本。
報案者之于受害者也，或同系一人，或其鄰裡親朋之知情者也。自秦法以降，遞有閭閻連坐之策，凡知情不舉者，按律當坐，王安石所目保甲法，即是也。然世有升降，國有治亂，保甲連坐之策，可行乎令行禁止之時，而文恬武嬉之季，多具文視之耳。且古時刑偵之術寡而限期破案之律在，案犯易脫幹係而有司則損利祿，是以報案者亦須證據確鑿，無可指摘，庶免乎官府之糾擾而人財俱困也。又自董子以來，列朝以儒治國，親親相隱之教，風乎百世，是以近親之間，若非大義滅親之舉，概以不報官府為長，而以鄉約族規處置也。報案者與受害者之間，以[MASK]為本。
報案者與罪犯之間多對立之關系。報案者舉罪犯之罪，冀以律法懲之。然報案者或有因擿伏發隱而罹罪犯相脅相報之禍者也。又以保甲連坐之製與大義滅親之理，報案者與罪犯之間亦或為親戚鄰裏，此又非必是兩立之勢也。報案者與罪犯之間，以[MASK]為本。
文選詩集之編者與作者，或因敬重欣賞之情，或為功利實在之用。其功利實在之用著，如著者為高官、長輩、恩師者也，甚者編者或側己文於他人之文，以彰己名也。裁約編選之時，編者常善著者之才華功業。編者亦以其選裁左右讀者之理解。文選詩集之編者與作者，實為古時文人之文化品味、審美觀念、權力關係之鑒鏡也。文選之編者與作者之間，以[MASK]為本。
表兄弟姐妹者，視同近親，關系親近，家族之情亦深也。彼於童稚之時，可共遊學、相長互助，共解所遇之危難。禮，表兄弟姐妹須循一定之禮節，長愛少，少敬長。及漸長，循授受不親之訓，以其為異姓，可通婚姻故也。表兄弟姐妹之間，以[MASK]為本。
庖人之與食客者，為服務被服務之關系也。庖人主烹飪，以甘美之食奉食客，而食客亦須念庖人之生計。故庖人須盡其技以足食客之口，食客亦須慎待庖人所供之物，此亦理之常也。或有庖人專供於食客或主人之家，則曰名廚或私廚，其與食客主人之關系則更甚其他庖人也。庖人與食客之間，以[MASK]為本。
仇敵之間乃對立衝突之關係也。敵者，匹敵也，論其才智，則相儔類，而或以利益之不均、或以地位之不匹、或以權力之不及、或以忠誠之不貞，諸此之屬，心生怨望而欲戕害以快其心者，仇敵之事也。然則，仇敵既以相噬為常，亦以其相匹，而或生相惜之感，且古時人分等級，同匹儔之人，其未為仇敵之初，或有通家之好，秦晉之交而同窗之誼也，是以古之仇敵，視今日為複雜也。故經史詩賦之中，感概仇敵之才智氣節者，亦不知凡幾也。仇敵之間，以[MASK]為本。
施恩者與受恩者為恩義與感恩之關係。施恩者之助受恩者也，或以善行，或以援手，受恩者遂感念其德，雖滴水之恩，木瓜之贈，亦矢報以湧泉瓊瑤也。古以'知恩圖報'為德之大者也。施恩者與受恩者之間，以[MASK]為本。
青梅竹馬，即為男女自幼同遊嬉戲，心生情愫者也。其情純真深沉，或終為伉儷，或為知己。古時文人墨客之述此情者，至純至美，感人心脾。青梅竹馬之間，以[MASK]為本。
情敵者，二三人傾慕同一對象，遂相競爭。此關係中，有敵意、嫉妬、競爭至於殺心之複雜心緒，然亦或有互尊呼諒者。經史詩賦之中，論及情敵，常有激烈戲謔之矛盾，或高雅而囿於禮法，或直率而流於粗鄙。情敵之間，以[MASK]為本。
天人之間，乃天地人三才之並立關系，人宜順天地，而與萬物為一。儒道皆謂人當敬天地而順之，於是乎則和也。欲和天人，需通天意，欲通天意，則在貫三才之王者，以儒家正典之論，王者得位聖賢之大號，非權勢之稱也，是以為古代知識階層與君主權力間之製衡也。天人之間，以[MASK]為本。
人神之間以信仰敬畏為維繫，其方式不離祭祀、祈禱以通達於神靈也，其指歸在乎求得神靈庇佑，解其大惑，脫其苦厄，堅其心志，導其前路也。今之視古，則謂古之信神，原乎科技落後，而驚懼敬畏于自然未知之力量也。然商周以降，中華之地，人以配天，民為神主之論，敬鬼以遠之教，人能弘道之言，天命從德之誡，經籍之載，三教之說，鹹崇人之踐行而斥虛妄之求神也。然則子雖不言怪力亂神，而人之不齊，一致百慮，可導而不可壅，是以君子明辨天理，不惑神鬼，而不責民間之求神問卜以行善避災也。人神之間，以[MASK]為本。
泛泛之交，乃交情淺薄之普通關係也。於此關係，彼此不通心意，交遊往來，相待以禮而已。泛泛之交，或可謂之朋友，然為關係最疏者也。泛泛之交之間，以[MASK]為本。
店主與顧客，為買賣交易之雙方也。店主供貨品服務於顧客，顧客以財貨償之。店主須竭其誠以應顧客之需，顧客亦需尊店主之恭敬服務于我也。所謂“買賣不成仁義在”，古時買賣之道，理不逾此。店主與顧客之間，以[MASK]為本。
官場之尊卑上下，不可逾距。上之於下，等級之中，所差愈多，威勢愈強。是以官員之間，忠敬為首，然忠敬者，忠於所守也，非忠於上司某甲也。上之於下，亦有訓導保全之義，此即古之尊卑有序、和諧中正之道也。然世閒多難行也。官場之上下級之間，以[MASK]為本。
買賣之夥伴，所共求止於利而已，緣此須相信相助，共分其利。其間信與平最為重，買賣之夥伴須以誠交易，以平分利。彼此亦須行為相協，言語相洽，以求買賣之順遂。買賣之夥伴之間，以[MASK]為本。
買賣之競爭對手，以欲求多利，欲天下求購者多求於己而俾天下財富多歸於己，於是乎有對手生焉。然生財亦當有道，故相競爭者雖有相爭之欲而求勝於對方，亦皆須守信持中，不得狡求他人之利。要之，亦有尊重也。買賣之競爭對手之間，以[MASK]為本。
宗教師徒，在於信仰之傳續繼承。師者，教訓徒弟，徒者，尊師重道，忠於師命。其間尊與忠為最重，徒須尊師忠命，師須護持教徒。宗教師徒之間，以[MASK]為本。
百工之師父與學徒，在於技藝之傳承。傳技之時，師者須教導訓誡其徒，徒者須尊敬愛重其師。其間尊與忠為最重，徒須尊師忠命，師須護持教徒。師傅與學徒之間，以[MASK]為本。
古之掌櫃與客人，因買賣交易為緣。掌櫃者經營其店。客人者消費之人也，求店主之所供。掌櫃須供客人所需，以求信與利。客人亦須敬重掌櫃，不得違其買賣之道。掌櫃與客人之間，以[MASK]為本。
古之首領與反賊，以勢不兩雄為常。首領者，為國之首領，反賊者，為國之叛逆。首領須守其威勢與現有之秩序，反賊則欲反叛其威勢與現有之秩序。首領與反賊之間，以[MASK]為本。
叔侄為血親。叔者為父之弟，侄者為兄之子。叔有教育侄之責，侄須愛敬叔，然亦須視其父母之存亡與學識尊卑論叔撫育之任也。叔侄關係於家族之中為極重要之關係。叔侄之間，以[MASK]為本。
雙胞胎因其母一胎同產之同胞，其情於血親手足之中為最近也。同孕母腹，同生一時，同長一處，其形其態其跡在成人之前尤多為相似，故其未冠笄之時，蓋情最深厚，或施及平生。雙胞胎之間，以[MASK]為本。
於政治之中，兩方之會晤多因權與利之爭鬥也。多以其政治與國家所屬不同，冀會晤以求成結盟。兩方須守盟會之理，於守自身之利為上為底，亦宜慮對方之利，以成盟約也。政治談判中對立之雙方之間，以[MASK]為本。
堂兄弟姐妹為親戚，然其親不過於同胞兄弟姐妹。於家族之中，堂兄弟姐妹可與嫡子女同長共學，亦同為長者所愛，然於家財分配，若非嫡子女亡故出繼，則不得分其家財，然亦多有倚勢強奪家財之事。論及尊卑，堂兄弟姐妹之長者亦為家族所重。堂兄弟姐妹之間，以[MASK]為本。
古者以父系別家族，故同父異母與同母異父之子女之所受對待全然不同。若子女為同父異母，則其於家族之中尊卑貴賤則從母之所處為父之發妻、續弦、妾之等而不同，及其母之存亡與母家之勢而定，然其爲一家之人，則無疑也。若子女為同母異父，則多因父之續娶他婦，其母之前夫子女多為後嫁之家族異姓視之，其被賤待，亦其常也，然亦須視其後父家之心與其母家之勢。同父異母與同母異父之子女之間，以[MASK]為本。
繼子女之間，雖為親戚，但彼此犬牙交錯，一言難磬。繼母與繼父之子女之關系亦相去萬裏。古者，父親多主家族，父親續娶，繼母亦為繼子之母也。然若母親改醮，繼子則從母而入繼父家，其家族關系亦全然改換也。若父母於其前夫前妻亡故後另結婚姻，則或因繼父繼母之愛而另生齟齬。家產之分配，若其母為繼母，則繼子女（若其女子未嫁）以律法可得所應之家產。若其父為繼父，則繼子女非繼父及家族所允，以律法不得受家產。繼子女之間，以[MASK]為本。
古之為官，同僚之間以官位相近，同朝合堂，共謀於事。然或因其職所守相近，未免於相爭，而生齟齬者亦多有之。同僚之間尊卑之序則定以官位高低、資望長短。同僚之間，以[MASK]為本。
庠序之間，同窗之間以求學問知識為共識，相助於學，共進於道。然因修業之優劣，成績之高下，而生齟齬者亦有之。同窗之間，常為對等之交，然亦可守尊卑之禮而以年齒為序，此多為交往之禮便耳。同窗之間，以[MASK]為本。
所謂搭訕者，意在親近被搭訕者，以其欲與被搭訕者交好而有所圖也。搭訕者之於被搭訕者，或欲作綈袍之義，或欲結琴瑟之好，或欲為買賣之宜。二者之關系，主動與被動並存，不確與不穩共生。然搭訕者多有所求，故世貶其行，經史詩賦亦多譏之。搭訕者與被搭訕者之間，以[MASK]為本。
施害者乃刑案中為暴力罪行者也。受害者乃因施害者之暴而罹身體乃至於性命之禍也。施害者與受害者，或為兩立，或為抵牾。經史典籍錄此案件，多因其所涉或為欺公罔法，或為其案情之重大曲折，蒙冤者終得昭雪也。然亦多為尋常案件之受害與被害關系。刑案中之施害者與受害者之間，以[MASK]為本。
古之旁觀者乃睹罪案而無與者也。或為偶然，或特持中而觀也。旁觀者之與受害者，論其行多有意疏遠之，跡其心則漠然或哀憫，然則旁觀者亦有因保甲連坐製度而或肯作證者。刑案中之受害者與旁觀者之間，以[MASK]為本。
屋主者，有屋貰於人者也。承租者，僦屋於人者也。屋主與承租者，常為權利義務之交易，或有經濟利益之抵牾，然得租賃者，亦彼此利之中和也。屋主與承租者之間，以[MASK]為本。
夫婦之關係，雖為平等而以男性為主導，家中事務由男性裁決，女子應遵奉，然亦視母家地位及其實力。夫婦之間，尤重忠誠尊重，互為匹敵，互相照顧，守家族和睦也。夫婦之間，以[MASK]為本。
夥計與顧客之關係以商貿為基，夥計須敬、誠、勤、恭，供以良品及服務。顧客則於良品與服務，受之以禮，成兩全之美事。夥計與顧客之間，以[MASK]為本。
父母與子女之閒，以孝為要，從其道，分其憂，解其難。爲其子者須事親以終其天年，爲其女者，既嫁亦省親有定期，且盡力照拂有難者，不以有歸為辭也。父母則應愛憐其子、育其成才，仿三遷而擇佳處也。父母與子女之間，以[MASK]為本。
義父母與義子女之關係，亦以孝為要。養子須事長以終其天年，養女亦受為人女之道。義父母則應愛憐有度、育子成才。義父母與義子女之間，以[MASK]為本。
翁媳若父女，故以孝、敬、恭系之，然以非親之故，兼有男女之防，媳固當孝翁視親，亦從於令而不可逾于矩。翁當護其周全而不可密邇。要約以禮，不忘授受不親之訓也。公公與兒媳之間，以[MASK]為本。
婆媳乃家中上下級關係也。婆為長為尊，有督導教育之責，媳則尊之孝之，有若母子然。婦歸夫家，夫妻之外，婆媳為重大關係也。婆婆與兒媳之間，以[MASK]為本。
主人與家丁為主僕之關係。主人發號施令，家丁則從令而行，稟其忠也。此關係乃權力與經濟之關係之象徵，主人，富貴者也；家丁，卑賤者也，以此業為生。家丁亦有以契約而世代為奴，則主僕之分益固也。主人與家丁之間，以[MASK]為本。
地主與佃農之間，乃經濟之關係。地主佔田地，佃農租田以謀生。此關係為經濟依賴關係，地主因佃農而得益，佃農傍田地以得生。地主與佃農之間，以[MASK]為本。
店主與夥計乃勞動關係。店主以市肆營生，募選數夥計以經營，夥計從其令而行。此關係乃經濟與勞動之關係，店主因夥計而得益，夥計不辭辛苦而獲薪俸。店主與夥計之間，以[MASK]為本。
官員之與行賄者，權錢之交易也。官員有權，行賄者有金，進賄金以鬻權取利也。此雖違法之事，然世非罕見，甚或相沿成習而得以為默規，異代不鮮也。官員與行賄者之間，以[MASK]為本。
狀元、榜眼、探花，為科舉殿試之冠、亞、季稱謂也。考生之間，競爭、合作，以求仕進，固彼此為競爭對手。於科舉中，狀元為首，榜眼、探花次之。狀元與榜眼與探花之間，以[MASK]為本。
綠林好漢首領之與屬下（嘍羅），領導者與被領導者也。首領常以其勇武、智謀得天下，而為領導者。兩者之間，亦視將兵之關係，故於首領命令，屬下（嘍羅）須從而為之，等軍法也。綠林好漢之首領與屬下之間，以[MASK]為本。
繼父母與子女，乃法定親子關係也。或以原配父母猝然離世，或為離鸞別鳳，繼父母入其家庭，擔養育之責，子女須敬之、從之。繼子女承業於繼母家庭，禮也，法也；而繼父家庭者則或否也，視繼父及其家族態度而定。繼父母與子女之間，以[MASK]為本。
繼祖父母與繼孫，亦為法定之親子關係也。若父母猝然離世，或為離鸞別鳳，由一方再婚而入他家，則繼父母父母之父母為繼祖父母。繼祖父母有養育之恩澤，子女須孝敬順從之。繼祖父母與繼子孫之關係，視繼子女之與繼父母關係而迥別也，或為同姓則可親似家人，或為異姓而忽視之也。參繼父母-子女條。繼祖父母與繼孫之間，以[MASK]為本。
養父母與子女，緣以養育之恩，而成親子之情。或父母失於養育，或子女棄於街頭，有善人收養，則為養父母。養父母擔養育之責，子女須孝之同其親然。養子女承業，須視養父母及其家族之意，若有爭議，可訴之官府，然蓋罕見也。養父母與子女之間，以[MASK]為本。
古人尤重師生之誼，尊師重道，古之訓也。師者，傳道受業解惑之人，教人以禮以知以識以技。學生尊之、敬之，師者愛之、誨之，古時師生關係以父子關係為本，然孝廉科舉之興，亦俾染利祿之關聯也。師生之間，以[MASK]為本。

家庭（家族）私塾為昔者大家族子弟啟蒙教育之場所也。所聘之家庭私塾教師，或家族之飽學長者，或科場之落第者，或中而未仕者。教童稚以讀書寫字，其常業也，有言傳身教之責，教導其為人之道。故塾師之於弟子，或代族中長者訓誡子弟，或但為教書先生，視教師身份地位或其家族地位而定。家庭私塾教師與學生之間，以[MASK]為本。
小人于後世多目品行卑劣、心胸狹窄、唯利是圖之人。“小人之交”則指此等人之彼此關係也，其以利為本，漠視誠信，唯權謀與爭利而已。小人之交之間，以[MASK]為本。
佛教徒以佛法信仰為紐，慈悲為懷，同修而互助，以求得佛法真諦，共成和諧、平等、互助之關係。然自佛滅以來，教派紛然，利欲之心，恆難寂滅，故其以宗派、僧團、寺廟之異，彼此爭端，歷代恆有。佛教徒之間，以[MASK]為本。
道教徒以修仙教化為要務，無為而治，自然和諧，天地共生，萬物為一，以求長生不老，故道教徒之間，以平和、寬容、尊重為常。然其亦或以宗派、僧團、寺廟之異，而起爭端。道教徒之間，以[MASK]為本。
髮小者，自幼相識之友也，其行跡相似相同，故其交往甚近。兩人之間，可不甚囿於禮法，故率真而坦誠。發小之間，以[MASK]為本。
本地人之與異鄉人，關係複雜。以編戶齊民之故，民重遷徙，是以處於異域，本地人或嚴以防範，或疏以情感。又以方音之差、風俗之別，異鄉人恆倍感孤困。然亦有好客之人，助其在此安居也。本地人與異鄉人之間，以[MASK]為本。
土籍之人與客籍之人之問題，漢季以來，盤根錯節，乞于民清之際，未有終結也。其世居鄉土之地而編戶于官府者，謂之土籍之人；其離鄉背井、人徙居於他鄉而籍未更者，則為客籍之人。二者之異，於編戶齊民之策率有體現。大抵土籍之人地位高於客籍，故土籍之人多主人自視，深有自得之意。然客籍與土籍，雜處一地，或以田土之不均、或以經濟之不等、或以社會地位之不匹，或以稅賦政令之不平，而勢有消長。其間以土地、人口、政治權力諸此之屬而滋生矛盾，然和中寓爭，爭中寓和，幾世之後，二者以共處、合作與通婚之故，兼之戶籍更新，斷客為主之策，二者之異同，日愈消弭，并同土籍，此其常也。然舊之客籍未泯，而新之客籍又生，此又其常也。土籍人士與客籍人士之間，以[MASK]為本。
外祖父母與外孫或外孫女，多倫常親呢之情也。蓋將綱常倫理而觀之，則外祖父母之於外孫或外孫女，或不及外祖父母之於內孫或內孫女親密。然自私心而論，則未必如是，若紅樓夢中以座次定尊卑，外孫女林黛玉尊於內孫三春則是一例。此皆因家族結構而致，謂之外孫或外孫女當屬妻家，非屬夫家也，故禮數殊矣。外祖父母與外孫/外孫女之間，以[MASK]為本。
門當戶對之訂婚男女，其關係多由家族所定。其婚姻，非止兩人之結合，亦兩家以聯姻相合也。故其關係，或受家族、社會地位、財富等之影響。于訂婚之前，彼此交往不多，甚者未嘗謀面，然皆需遵家族與社會之規定，成合卺之禮。門當戶對之訂婚男女之間，以[MASK]為本。
私奔者，乃背禮叛教所以追情求愛也。常語以爲聘妻奔妾，然或以一見傾心欲早遂佳期，或以門戶不當而父母弗允，或以私情而拋其家室，不顧雙親兒女，終於淫奔者，以其愛戀之深，不可自抑也。然則負罵名，走他鄉，前途何卜，亦難以預知也。私奔男女之間，以[MASK]為本。
同科舉人之間，競爭與互助兼有之也。科舉，士進之途也，遂引天下讀書人埋頭于科舉之書。然進士之途窄矣，應試者多而中試者寡，其得高中以啓顯宦之階者則尤寡也。故于科考之時為競爭對手，然於考試之外，或可相學互助。考中者，若無素時芥蒂，咸可共相交友，以廣交際。同科舉人之間，以[MASK]為本。
同門師兄弟之間存恭謹相敬之情、患難相濟之意。其同拜一師，共得其教，故同門之情宜深矣。彼其有同門之敬助，攜手共進。若無有利祿貪欲之心，則同門師兄弟之間，充盈友愛之情，必也。同門師兄弟之間，以[MASK]為本。
同校學生之間，友情與競爭兼有之也。彼學於同一學校，有同窗共硯之情。然非獨限於共學之時矣，待卒業及從業後，亦可成通力合作之事。同校學生之間，以[MASK]為本。
山長者，書院衆師之長，亦書院之主管也；講席，書院所延聘之教師也。書院之治，向以寬而有別於官學也。官學之治，以屬官府而有等級高下之判。書院則否，以山長之道德文章為維繫也，以地方劃撥之田地房舍為生養也，是以山長之與講席，一講席之首座耳，志同則合，志異則散，山長之管書院者，攝也，固當共尊書院之規，不以勢相凌，是以寬。然有清之後，書院亦官學化也，非概得以寬一之。學府書院之山長與講席之間，以[MASK]為本。
同父同母之子女，為同胞之兄弟姊妹也，此乃血緣至親。同胞兄弟姊妹間多親呢，常勝於非同胞者。同父同母之子女之間，以[MASK]為本。
戲班與劇作者之間多合作也。劇作者撰作戲劇劇本，而戲班搬演劇作，以供觀眾欣賞。戲班之人身卑籍賤，然劇作者或為讀書人，位四民之首，甚者有功名焉，以差距懸殊之故，所謂合作者，亦鬆散之形式也。劇作者未必依演出之狀況而作成案頭之曲，戲班之於作品之呈現，亦未必符契原文，其違作者原意而有自行發揮之處者，蓋不勝舉也。戲班與劇作者之間，以[MASK]為本。
戲子，上臺演出者也；看官，觀賞表演者也。戲子以其表演技巧取悅看客，博看官捧場，而看官之回應，或於大快人心之處喝采，或於角色含冤負屈之處泣下。高超之技藝固得掌聲口譽，反之則致倒彩譏嘲。因之戲子須重看官之反應，然戲子卑微低賤，看官之於戲子，決於看官自身之態度與修養，借其賤戲子，以之為下等，亦不違世俗之德。戲子與看官之間，以[MASK]為本。
音樂曲藝人，以賞心悅耳之音求生計者也；聽眾，品賞其音樂曲藝者也。音樂曲藝人以其曲藝之才悅聽眾之耳，聽眾則據藝人之水準報以讚譽財物也。要之，藝人須以聽眾之反應為重，然曲藝人恆処賤籍，故與聽眾或不對等也。音樂曲藝人與聽眾之間，以[MASK]為本。
祖孫之間尊卑長幼宜井然有序。祖父母位高於父母，是以孫子女之於祖父母，尤須以禮敬重孝順之，以終其天年，是亦儒家倫理之不可或缺者也。祖孫之間，以[MASK]為本。
大夫，醫者之敬稱也。古之良大夫也，以扁鵲華佗之資，行救死扶傷之舉。病者若知曉大夫之醫術兼信之，則病者得瘳而醫者受譽，然則病者之與醫者，亦隨醫者口碑之優劣、人品之高下，與夫病者病情之變化、性格之差異而有別。大夫與病者之間，以[MASK]為本。
姨父姨母與侄子侄女之間存親戚之情也。姨父母以其長者慈顧幼小，幼者敬其長者，此為華夏家庭親情倫理之恆常。姨父姨母與侄子侄女之間，以[MASK]為本。
行俠仗義者，救受助者於水火災厄之中。仗其勇力，憑其志氣，赴人之困頓，軌俠之道義。至於受助者，則當銜環結草以報其恩也，是俠氣之所傳，而仁義有所弘也，夫緩人之所急，脫人之所危，曷可少也。行俠仗義者與受助者之間，以[MASK]為本。
妓女者，誤落風塵，陷於倡家，有姿色者賓客如市而衰老者落拓餘生。嫖客以錢財之豐厚，走馬章台，縱其情欲也。然二者之間，或漸生情愫，以成好合者，往往有之，然沉箱剃髮之悲，蓋尤其多也。狎妓違君子德風之誨，悖於人倫常理，為世之所誅責。然歷代官家律令以存秦樓楚館為慣例，《管子》發其端也。嫖客與妓女之間，以[MASK]為本。
掌櫃者，受店主所托，掌日常經營之事宜，凡貨物之進出、價格之定立、賬目之記錄諸類者皆須過問。掌櫃當不負店主所托之責，店主則當行察看之勸，以驗其實績。掌櫃與店主之間，以[MASK]為本。
夥計與掌櫃之間，上下級也。夥計，掌櫃之下屬也，掌日常營業之細事，凡接待賓客、售賣商品、搬運貨物之類也。掌櫃行指導管理之勸，而夥計聽其所命。掌櫃與夥計之間，以[MASK]為本。
捐助者，施以財物之助，不苛求彼之回報；受惠者，受其所助而當銜環結草，以報其恩德也。仁愛互助之義在其中矣。捐助者與受惠者之間，以[MASK]為本。
將領與士兵之間，上下級也。將領之帶兵也，其高明者在於寬嚴並濟，既嚴於治軍，又時彰仁愛兵卒之美德行，以兵為子。然軍令如山，故士兵須惟命是聽。此則軍隊令行禁止之法也。將領與士兵之間，以[MASK]為本。
考官之與考生，主試與被試者也。考官評考生之學識才能，而考生須受考官之評鑒。此乃科舉之制公正之途。及考畢，中試者與考官可立師生之誼以擴交際，季世則爲結党之一端也。考官與考生之間，以[MASK]為本。
家長敬重信任其子女之師也，是以教育之任托之。師長傳道受業解惑，以誨其子弟。總言之，師長位高權重，掌教學之法諸多事宜，故家長須聽而從之。彼此或以嚴父之姿共擔子弟教育之責。師長與家長之間，以[MASK]為本。
同鄉之間往來密切，彼此相助，共解困厄。同鄉之間，同飲一鄉之水，同言一方之音，風土人情共相習知，故他鄉之逢，倍感親切。同鄉之間，以[MASK]為本。
鄰里相處之道，可奠鄉里秩序之基。鄰里者，共助、共用、共慶，其要在乎協同互敬，講信修睦，可築鄉里之大同。結姻親、共耕織、連什伍，皆可固鄰里。鄰裡之間，以[MASK]為本。
相與出行者，同途之際，經歷相同，利益相干而目的相通也。故可相持互助，以應行途之變。同遊關係之要，在諸同心同德，共克困艱。相與出行者之間，以[MASK]為本。
從事買賣者，賣方或以物售之，或以役供之，買方則以貨貝易之。販賣貿買，需重信諾，禁詐紿。賣方所供務必價合質優，買方所償務必踐以約。買者與賣者之間，以[MASK]為本。
所謂行人，今之路人也，目有所接而言行不必交，以無深交之所需也。或逢於茶樓酒肆，或見於街巷坊裡，非有際會因緣，相交不過泛泛而已。行人之交多無深交厚誼可溯，然疏而有禮，遠而存敬。行人之間，以[MASK]為本。
狐朋狗友，品行不檢而相偕作樂取悅心欲者也，所好皆賭博、酗飲、狎妓之陋習。狐朋狗友之交，觥籌交錯、宴酣之樂顯於外，而犬馬聲色、熏心色欲隱其中也。狐朋狗黨之間，以[MASK]為本。
泛泛之友，可為同好，共論琴棋，共試酒茶，然多止於淺交。所謂淺交者，非親非疏，若敬若重，不甘于醴，亦非純淡如水也，以未深交之故也。泛泛之交之間，以[MASK]為本。
故舊者，情誼深遠之友也。故舊之友多共曆往事種種，然溫不增華，寒不改葉，能四時而不衰，歷險夷而仍固，相輔相助，情堅若金。故舊之間，以[MASK]為本。
摯友者，無血緣之親，然勝乎同產，雖貧富貴賤、生死離別不能阻隔之。摯友相交，以拳拳之心同攜手、共患難，實無價之友誼也。摯友之間，以[MASK]為本。
友誼之至境是謂知己。其情之深厚，遠勝泛泛相交，亦相異於親子牽絆，如奏高山流水于知音也，意動即神會，勝卻言語無數。互為知己者，彼之喜怒哀樂皆可歷歷於己心，至情至性，合若符契，而相敬之以禮；若得一知己，遑論肝膽相照，雖九死其猶未悔。友誼之至境，不過是也。知己之間，以[MASK]為本。
乞者與行者，多遇於市肆。乞者所欲者惟行者之施，行者之施亦可彰己憐憫之心。然二者相遇，行者多無所施，乞者或無所得，以不必施故也。乞丐與行人之間，以[MASK]為本。
新故官吏之閒，權力交接之關係也。去者有升、謫、免、致仕之別，而新任者，生疏于此間府衙事務，故舊任有授新任以經驗故事之責。然則離任者或以親近者安排新任左右，雖去任而威信存，且交接之際，多涉賦稅度支之核查、檔案文書之清點，案件審理之清白，田地戶口之數目，是以輕則生隙，重則黨伐。新故吏之間，以[MASK]為本。
獄卒之于囚犯，有羈押之權，囚犯受制于獄卒，受監守之限制。獄卒待囚犯何如，視囚犯家族之貴賤、案情判罰之輕重，及親友打點之多少而各異也。若利益相合，或義氣相投，獄卒囚犯亦可結友，然為獄卒者疾言厲色、受其暴虐者多為常態。獄卒與囚犯之間，以[MASK]為本。
告與被告，皆寄之律法以為己申訴辯白，而互為對立也。告劾者所求，伸曲理枉，以示法網恢恢；被告者所求，自證清白，以求洗冤昭雪。告與被告之辯，實關乎法治完備公正之有實否。告劾者與被告者之間，以[MASK]為本。
妻妾之間多明暗糾葛。妻者，主内也，總理治家教子之務。妾者，位卑于妻，多以存續香火，姿顏姣好之由納之。妻妾相處，或扶持相依，或勾心鬥角。《毛詩序》曰：“《關雎》樂得淑女以配君子，憂在進賢，不淫其色。”盡言正妻納妾之責，妻妾相處之道。妻妾之間，以[MASK]為本。
妻與外婦之間，相視若讎仇。外婦者，未娶而旁通也，無婚姻之名。外婦若有子，易致後宅不寧，亂尊卑之別，生分財之釁，是故妻與外婦多生齟齬。妻與外婦之間，以[MASK]為本。
夫暗合於外婦，苟且之舉也。二者無婚姻之名，為世所不齒。暗合者，或生相依相濡之情，亦或僅尋一夕貪歡。夫與外婦之間，以[MASK]為本。
遠親者，有血緣之絆，無近鄰之切，往來問候多訴諸婚喪嫁娶節氣，寄乎禮法倫常，以厚親戚之情。然澆薄之世，如涉祖業田產之爭，則雖遠親亦或生齟齬。遠親之間，以[MASK]為本。
子婿之於岳家，理應互敬互賴，然岳家垂青與否，多決於子婿之功名、族望。除入贅而改姓易族者，翁婿雖名為父子，實各異家，其情弗如同簷之婆媳遠甚，遑論血緣之親。岳家與子婿之間，以[MASK]為本。
同袍之誼，多喻軍旅士伍心心相惜。士卒征戰於沙場，同浴血汗、共赴國難，皆懷身先致死、盡忠報國之念。詩曰：豈曰無衣，與子同袍。是以同袍之親，勝似兄弟。同袍之間，以[MASK]為本。
官民之間，上下領屬之關係也。為官之道，必除害興利，善度民力，正風立綱；為民之要，必遵紀守法，立身行道。官民相處亦如父子，為人父則慈，為人子則孝，為人上則明，為人下則聖，父慈子孝，上明下聖，治之紀也。官民之間，以[MASK]為本。
結黨而敵對者，始於小人之同利，及其見利則爭先，或利盡而交疏，乃反相賊害。結黨者之利異，多為政見、觀念相抵，至成水火之勢。為求己利，雖其親戚兄弟不保也。敵對黨派之間，以[MASK]為本。
同盟即志同道合者。君子與君子以同道為朋，共守道義，行忠信，惜名節。是故同盟者得以守望相助，進退如一，莫逆於心。同盟黨派之間，以[MASK]為本。
保人者，受託于雙方顧主，牽繫買賣關係，以局外之身處理其間事務者也。顧主雙方多聘保人以求交易之公正，保人亦從中牟利。保人之制，早至魏晉隋唐已有所載，古商貿制度之完善據此可窺一二。保人與顧主之間，以[MASK]為本。
所謂忠臣，效忠于社稷者也，以鞠躬盡瘁、死而後已為己任，多為世之表率，歷代稱頌不絕。所謂逆賊，離君叛國者也，陷社稷於累卵之危、倒懸之急，世人為之不齒。忠臣與逆賊之間，以[MASK]為本。
主客之交，以互敬互重為本。為人主者，待人接物需完備周致，以求賓至如歸；為賓客者，亦需禮尚往來，以示謝忱。古之人倫禮制，亦見於主客相交之道也。主人與賓客之間，以[MASK]為本。
主奴者，主人為主而女婢為從也。主人有令，奴必應之，不可不從，以其必終於主人故也。奴之衣食起居，身家性命，全仰主意。主人和善體恤，則奴亦可豐足；主慳吝刻薄，則奴亦常縈困頓。然奴之私忠於其主也，不必係於主之慈暴，以世論其忠若犬故也。主奴之間，以[MASK]為本。
乳母之與嬰孩之家長，僱傭關係者也。家長或以嬌弱，或以矜貴，或以少乳，僱乳母以照料之。乳母當供乳於彼嬰幼，事其起居，乃或至教導培育。二者既系於僱傭，則信立為本而求職盡也。家長用人不疑，乳母方不墮其職也。乳母與家長之間，以[MASK]為本。
乳母之于嬰幼，保育者也。乳母非僅哺之以乳，且兼料其起居，助其成長，與其蒙學。長此以往，乳母或親愛嬰幼，嬰幼亦依戀乳母，此人情所致，本非乳母之分也。及長，嬰幼雖有生母，于禮當母事之，然愛信乳母，厚此而薄彼，亦時有之。雖然，若依通例，嬰幼年齒既長，無需哺乳，乳母之分即盡。更有甚者，就此別過，鮮復往來矣。乳母與嬰幼之間，以[MASK]為本。
凡職官者，常設正副。正者，統也。凡執掌決策，籌謀號令，皆出於正者。副者，輔也。或可決策，然猶為行正者之令耳。正副職官，或勾心鬥角，傾軋掣肘；或相交融洽，並力同心。二者相輔相成，乃自然之理，然彼此相爭，亦時有之。正職與副職之間，以[MASK]為本。
教首者，亦曰教主，一教之領袖也，享至高威權，眾人視之如神聖。教徒者，此教之信眾也。尊奉教首，篤信之，敬仰之，無敢有違。凡教之規，皆當嚴守；凡本教之義，教首之令，皆應踐行。由此可觀古時宗教神權之廣大威嚴，與夫信徒心靈之精誠純粹也。教首與教徒之間，以[MASK]為本。
一家一族，必有其祖。先祖後裔，分支散葉，世代相延，此乃家族形式之基本樣貌。祖為一族之源，綿綿瓜瓞，延而至今，其開創之始，嘉行善德，當銘於子孫，賡續不絕。子子孫孫需尊奉之，稱頌之，祠廟之，祭享之，且以顯祖榮宗為務，不可玷污門楣，蒙羞祖上。重祖以尚孝，古來如此。祖先與後代之間，以[MASK]為本。
保長坊長者，鄉裡街坊一方之長也，以平治鄉裡街坊之序，協官府理此地之事，上傳下達於鄉間坊間為責。居鄉裡街坊者，稱居民。居民需從保長，遵鄉規，然後可自主而為。此則城外之鄉裡，城内之街坊，其自轄之法也。保長與居民之間，以[MASK]為本。
遠房表親，雖非同胞，血緣略淺，然既系一族，兄弟姊妹之禮，仍需具備，並擔修睦之責，盡扶持之義。蓋開枝散葉，本自同宗，血濃於水，情繫其中，遠方表親，亦不可輕疏也。遠房表親之間，以[MASK]為本。
君臣之間，界限分明。君者，一國之主；臣者，輔君以治國也。君可行賞罰於臣，臣當履忠誠於君。君君，臣臣，各從其分，然孟子曰：“君之視臣如手足；則臣視君如腹心；君之視臣如犬馬，則臣視君如國人；君之視臣如土芥，則臣視君如寇讎。”是以君愛臣，則臣親君而易忠，反之則心離而人散，然儒者所謂臣之忠，忠乎社稷天下，非一人一姓也，而鼎革之節，革命之時，何謂稷天下，何謂一人一姓，人多混淆之，而一人一姓多樂其混淆也。由此觀之，君臣之間，錯綜複雜，一言難盡。君臣之義，乃上下之權力關係，亦涉個人與家國集體之關係也。君臣之間，以[MASK]為本。
債主與負債者，二者交通，繫於財幣。債務既成，負債者需依契約按時償之，逾期未償，債主可責之。此二者一關乎責權，二關乎財幣也。債主與負債者之間，以[MASK]為本。
親家者，姻親是也，為夫妻兩家父母之互稱。親家為同等之親戚，亦關世故人情。若夫婦敦睦，則親家亦諧，鮮有齟齬。親家之間，以[MASK]為本。
訟師之與司法者，因其職而相交也。事主有案，託於訟師，代寫文書，申訴有司，而司法者任於官府，審判其案。二者因本職而協作，並行業務於律法之事也。然地方司法，皆委縣令，多起於科舉，熟於治經，疏於律令，訟師與縣吏或沆瀣一氣，操縱案判，則蔽矣。訟師與司法者之間，以[MASK]為本。
訟師之於屬者，代理關係也。訟師以代撰訴狀為務，然亦可因之而受屬者之托，代其行訟。此二者一關乎責權，二關乎立信與代理也。訟師與屬者之間，以[MASK]為本。
捕快者，地方官府之差役也，以捉賊、治保為務。百姓為全身護財計，仰賴捕快；而捕快或濫權恣肆，百姓見而生畏。是以捕快百姓之間，關係微妙，一言難蔽百世之實。捕快與百姓之間，以[MASK]為本。
疑犯捕快，彼此對立。捕快之務，緝拿疑犯，而疑犯聞之，必逋逃藏匿，如鼠畏貓也。二者水火難容，矛盾多生。疑犯與捕快之間，以[MASK]為本。
罪犯之於人質，強之以力而脅其性命者也。犯人作奸犯科，將陷囹圄，恐牢獄之災，或挾人質以要官府。人質遭其挾而性命堪憂，以無可自主，常聽命于罪犯。罪犯與人質之間，以[MASK]為本。
罪犯所害之人，若有親眷，則稱苦主。苦主與罪犯為敵，視之為仇讎，冀官府緝捕，使其就法。或思血親之仇，不共戴天，則不俟官府，而有私報之也。罪犯與苦主之間，以[MASK]為本。
罪犯觸罪，或為旁人所觀。旁人既觀，則或有紛紛議論，批評褒貶。輿論所加，則罪犯聲名地位，亦隨之而更。是以旁人之論，或可左右決獄。而保甲之制，儒家之教，亦或使旁人作證，轉為證人也。罪犯與旁人之間，以[MASK]為本。
盜賊失主，彼此對立。盜賊之行，本系非法，謀竊失主，損其財物。依律，賊當償其失，並伏法受罰。盜賊與失主之間，以[MASK]為本。
罪犯與受害者，彼此對立。罪犯以非法加害於人，傷其身心。依律，賊當伏法受罰，以償其所害。罪犯與受害者之間，以[MASK]為本。

司法者與監察者，互相監督，彼此牽掣者也。司法者以審案為務，昭法之威，執法以正。監察者則督其行事或查其已行，以防其私弊貪腐，使司法必正也。司法者與監察者之間，以[MASK]為本。
罪犯同黨者，共犯是也。其所求所行，皆系非法，而三五聚夥，同籌共謀，一朝舉事，乃咸觸罪。依律，犯罪同黨未可消罪，以其明知共犯，或增其罪咎。罪犯同黨之間，以[MASK]為本。
賭徒之間，彼此相爭者也。其好博嗜賭，日以鬥雞走馬，喝雉呼盧，投注押寶為事，至於一擲千金，妄希橫富。故彼此爭財奪利，甚為激劇，不免舞弊詐欺，乃至身體相鬥者。厤朝之律法，以賭禁為常，故賭徒之間，世人皆視之為歪門邪道也。賭徒之間，以[MASK]為本。
文人與閱者，以文之賞識相交通者也。詩文曲賦，文人所作，常寓以其道其情，因傳其文而載其道也。閱者覽之，可明其道而體其情。夫閱者有感，或建言于文人，使其更改；而流播之廣狹，亦繫於後來之閱者。然限於古之實際，二者不得直接交通，故以單向為多。尋常閱者，難比文人之博觀群覽，不可左右其意。雖然，猶有閱者或與文人相厚，或業相關之業，或知音於後世，因而評論之，紹介之，出版之，則可左右文人之書寫，甚或筆削增潤其原文，而動搖世俗之喜好也。文人與閱者之間，以[MASK]為本。
文人多為士人之屬，論者亦品評之士。二者之間，實可相互磋磨學問，評鷙詩文者也。文人作詩文曲賦，而論者品藻之，其建言獻意，雖抒己之見，亦或左右文人之書寫也。於是論者作評，而文人參酌，以修色其作，推敲之定，一字之師，皆此類也。觀古之文俗世情，論者之于文人，抑揚者也。夫論者所尚，則以詩品詞話、文論筆談附益其作，播其芳名，俾傳之百世而其聲益顯，其文益高。反之，亦有詩文曲賦，論者毀之，因聲名不顯，浸微浸消者也。文人與論者之間，以[MASK]為本。
男女曖昧之事，悖於人倫，是以隱於心而不擅發於外。其或發於外者，亦以含蓄之言，傳微妙之情，假落紅秋葉之詩，托香囊繡帕之物，暗致其情，不令外人見也，多是之類也。曖昧者之間，多[MASK]。
暗戀者，古語或謂單相思。男女之間，礙于父母之命，媒妁之言，婚姻之有定也，於是己固思慕彼而不敢以私意白，彼未知而己切思之，求之不得，其情之至者，所謂“寤寐思服，輾轉反側”是也。其恪于禮者，常以春蠶絲盡、桃花依舊之喻，暗寄其心而不外傳，亦或以暗中護助，不令其有艱困愁苦，而其稍逾制者，則或致佩飾之物也。古之暗戀者，多止乎此，至若季世綱常已墮，男女忽於大防，暗戀轉直，單思為雙，則奔者難禁。暗戀者與被暗戀者之間，多[MASK]。
報案者之于受害者也，或同系一人，或其鄰裡親朋之知情者也。自秦法以降，遞有閭閻連坐之策，凡知情不舉者，按律當坐，王安石所目保甲法，即是也。然世有升降，國有治亂，保甲連坐之策，可行乎令行禁止之時，而文恬武嬉之季，多具文視之耳。且古時刑偵之術寡而限期破案之律在，案犯易脫幹係而有司則損利祿，是以報案者亦須證據確鑿，無可指摘，庶免乎官府之糾擾而人財俱困也。又自董子以來，列朝以儒治國，親親相隱之教，風乎百世，是以近親之間，若非大義滅親之舉，概以不報官府為長，而以鄉約族規處置也。報案者與受害者之間，多[MASK]。
報案者與罪犯之間多對立之關系。報案者舉罪犯之罪，冀以律法懲之。然報案者或有因擿伏發隱而罹罪犯相脅相報之禍者也。又以保甲連坐之製與大義滅親之理，報案者與罪犯之間亦或為親戚鄰裏，此又非必是兩立之勢也。報案者與罪犯之間，多[MASK]。
文選詩集之編者與作者，或因敬重欣賞之情，或為功利實在之用。其功利實在之用著，如著者為高官、長輩、恩師者也，甚者編者或側己文於他人之文，以彰己名也。裁約編選之時，編者常善著者之才華功業。編者亦以其選裁左右讀者之理解。文選詩集之編者與作者，實為古時文人之文化品味、審美觀念、權力關係之鑒鏡也。文選之編者與作者之間，多[MASK]。
表兄弟姐妹者，視同近親，關系親近，家族之情亦深也。彼於童稚之時，可共遊學、相長互助，共解所遇之危難。禮，表兄弟姐妹須循一定之禮節，長愛少，少敬長。及漸長，循授受不親之訓，以其為異姓，可通婚姻故也。表兄弟姐妹之間，多[MASK]。
庖人之與食客者，為服務被服務之關系也。庖人主烹飪，以甘美之食奉食客，而食客亦須念庖人之生計。故庖人須盡其技以足食客之口，食客亦須慎待庖人所供之物，此亦理之常也。或有庖人專供於食客或主人之家，則曰名廚或私廚，其與食客主人之關系則更甚其他庖人也。庖人與食客之間，多[MASK]。
仇敵之間乃對立衝突之關係也。敵者，匹敵也，論其才智，則相儔類，而或以利益之不均、或以地位之不匹、或以權力之不及、或以忠誠之不貞，諸此之屬，心生怨望而欲戕害以快其心者，仇敵之事也。然則，仇敵既以相噬為常，亦以其相匹，而或生相惜之感，且古時人分等級，同匹儔之人，其未為仇敵之初，或有通家之好，秦晉之交而同窗之誼也，是以古之仇敵，視今日為複雜也。故經史詩賦之中，感概仇敵之才智氣節者，亦不知凡幾也。仇敵之間，多[MASK]。
施恩者與受恩者為恩義與感恩之關係。施恩者之助受恩者也，或以善行，或以援手，受恩者遂感念其德，雖滴水之恩，木瓜之贈，亦矢報以湧泉瓊瑤也。古以'知恩圖報'為德之大者也。施恩者與受恩者之間，多[MASK]。
青梅竹馬，即為男女自幼同遊嬉戲，心生情愫者也。其情純真深沉，或終為伉儷，或為知己。古時文人墨客之述此情者，至純至美，感人心脾。青梅竹馬之間，多[MASK]。
情敵者，二三人傾慕同一對象，遂相競爭。此關係中，有敵意、嫉妬、競爭至於殺心之複雜心緒，然亦或有互尊呼諒者。經史詩賦之中，論及情敵，常有激烈戲謔之矛盾，或高雅而囿於禮法，或直率而流於粗鄙。情敵之間，多[MASK]。
天人之間，乃天地人三才之並立關系，人宜順天地，而與萬物為一。儒道皆謂人當敬天地而順之，於是乎則和也。欲和天人，需通天意，欲通天意，則在貫三才之王者，以儒家正典之論，王者得位聖賢之大號，非權勢之稱也，是以為古代知識階層與君主權力間之製衡也。天人之間，多[MASK]。
人神之間以信仰敬畏為維繫，其方式不離祭祀、祈禱以通達於神靈也，其指歸在乎求得神靈庇佑，解其大惑，脫其苦厄，堅其心志，導其前路也。今之視古，則謂古之信神，原乎科技落後，而驚懼敬畏于自然未知之力量也。然商周以降，中華之地，人以配天，民為神主之論，敬鬼以遠之教，人能弘道之言，天命從德之誡，經籍之載，三教之說，鹹崇人之踐行而斥虛妄之求神也。然則子雖不言怪力亂神，而人之不齊，一致百慮，可導而不可壅，是以君子明辨天理，不惑神鬼，而不責民間之求神問卜以行善避災也。人神之間，多[MASK]。
泛泛之交，乃交情淺薄之普通關係也。於此關係，彼此不通心意，交遊往來，相待以禮而已。泛泛之交，或可謂之朋友，然為關係最疏者也。泛泛之交之間，多[MASK]。
店主與顧客，為買賣交易之雙方也。店主供貨品服務於顧客，顧客以財貨償之。店主須竭其誠以應顧客之需，顧客亦需尊店主之恭敬服務于我也。所謂“買賣不成仁義在”，古時買賣之道，理不逾此。店主與顧客之間，多[MASK]。
官場之尊卑上下，不可逾距。上之於下，等級之中，所差愈多，威勢愈強。是以官員之間，忠敬為首，然忠敬者，忠於所守也，非忠於上司某甲也。上之於下，亦有訓導保全之義，此即古之尊卑有序、和諧中正之道也。然世閒多難行也。官場之上下級之間，多[MASK]。
買賣之夥伴，所共求止於利而已，緣此須相信相助，共分其利。其間信與平最為重，買賣之夥伴須以誠交易，以平分利。彼此亦須行為相協，言語相洽，以求買賣之順遂。買賣之夥伴之間，多[MASK]。
買賣之競爭對手，以欲求多利，欲天下求購者多求於己而俾天下財富多歸於己，於是乎有對手生焉。然生財亦當有道，故相競爭者雖有相爭之欲而求勝於對方，亦皆須守信持中，不得狡求他人之利。要之，亦有尊重也。買賣之競爭對手之間，多[MASK]。
宗教師徒，在於信仰之傳續繼承。師者，教訓徒弟，徒者，尊師重道，忠於師命。其間尊與忠為最重，徒須尊師忠命，師須護持教徒。宗教師徒之間，多[MASK]。
百工之師父與學徒，在於技藝之傳承。傳技之時，師者須教導訓誡其徒，徒者須尊敬愛重其師。其間尊與忠為最重，徒須尊師忠命，師須護持教徒。師傅與學徒之間，多[MASK]。
古之掌櫃與客人，因買賣交易為緣。掌櫃者經營其店。客人者消費之人也，求店主之所供。掌櫃須供客人所需，以求信與利。客人亦須敬重掌櫃，不得違其買賣之道。掌櫃與客人之間，多[MASK]。
古之首領與反賊，以勢不兩雄為常。首領者，為國之首領，反賊者，為國之叛逆。首領須守其威勢與現有之秩序，反賊則欲反叛其威勢與現有之秩序。首領與反賊之間，多[MASK]。
叔侄為血親。叔者為父之弟，侄者為兄之子。叔有教育侄之責，侄須愛敬叔，然亦須視其父母之存亡與學識尊卑論叔撫育之任也。叔侄關係於家族之中為極重要之關係。叔侄之間，多[MASK]。
雙胞胎因其母一胎同產之同胞，其情於血親手足之中為最近也。同孕母腹，同生一時，同長一處，其形其態其跡在成人之前尤多為相似，故其未冠笄之時，蓋情最深厚，或施及平生。雙胞胎之間，多[MASK]。
於政治之中，兩方之會晤多因權與利之爭鬥也。多以其政治與國家所屬不同，冀會晤以求成結盟。兩方須守盟會之理，於守自身之利為上為底，亦宜慮對方之利，以成盟約也。政治談判中對立之雙方之間，多[MASK]。
堂兄弟姐妹為親戚，然其親不過於同胞兄弟姐妹。於家族之中，堂兄弟姐妹可與嫡子女同長共學，亦同為長者所愛，然於家財分配，若非嫡子女亡故出繼，則不得分其家財，然亦多有倚勢強奪家財之事。論及尊卑，堂兄弟姐妹之長者亦為家族所重。堂兄弟姐妹之間，多[MASK]。
古者以父系別家族，故同父異母與同母異父之子女之所受對待全然不同。若子女為同父異母，則其於家族之中尊卑貴賤則從母之所處為父之發妻、續弦、妾之等而不同，及其母之存亡與母家之勢而定，然其爲一家之人，則無疑也。若子女為同母異父，則多因父之續娶他婦，其母之前夫子女多為後嫁之家族異姓視之，其被賤待，亦其常也，然亦須視其後父家之心與其母家之勢。同父異母與同母異父之子女之間，多[MASK]。
繼子女之間，雖為親戚，但彼此犬牙交錯，一言難磬。繼母與繼父之子女之關系亦相去萬裏。古者，父親多主家族，父親續娶，繼母亦為繼子之母也。然若母親改醮，繼子則從母而入繼父家，其家族關系亦全然改換也。若父母於其前夫前妻亡故後另結婚姻，則或因繼父繼母之愛而另生齟齬。家產之分配，若其母為繼母，則繼子女（若其女子未嫁）以律法可得所應之家產。若其父為繼父，則繼子女非繼父及家族所允，以律法不得受家產。繼子女之間，多[MASK]。
古之為官，同僚之間以官位相近，同朝合堂，共謀於事。然或因其職所守相近，未免於相爭，而生齟齬者亦多有之。同僚之間尊卑之序則定以官位高低、資望長短。同僚之間，多[MASK]。
庠序之間，同窗之間以求學問知識為共識，相助於學，共進於道。然因修業之優劣，成績之高下，而生齟齬者亦有之。同窗之間，常為對等之交，然亦可守尊卑之禮而以年齒為序，此多為交往之禮便耳。同窗之間，多[MASK]。
所謂搭訕者，意在親近被搭訕者，以其欲與被搭訕者交好而有所圖也。搭訕者之於被搭訕者，或欲作綈袍之義，或欲結琴瑟之好，或欲為買賣之宜。二者之關系，主動與被動並存，不確與不穩共生。然搭訕者多有所求，故世貶其行，經史詩賦亦多譏之。搭訕者與被搭訕者之間，多[MASK]。
施害者乃刑案中為暴力罪行者也。受害者乃因施害者之暴而罹身體乃至於性命之禍也。施害者與受害者，或為兩立，或為抵牾。經史典籍錄此案件，多因其所涉或為欺公罔法，或為其案情之重大曲折，蒙冤者終得昭雪也。然亦多為尋常案件之受害與被害關系。刑案中之施害者與受害者之間，多[MASK]。
古之旁觀者乃睹罪案而無與者也。或為偶然，或特持中而觀也。旁觀者之與受害者，論其行多有意疏遠之，跡其心則漠然或哀憫，然則旁觀者亦有因保甲連坐製度而或肯作證者。刑案中之受害者與旁觀者之間，多[MASK]。
屋主者，有屋貰於人者也。承租者，僦屋於人者也。屋主與承租者，常為權利義務之交易，或有經濟利益之抵牾，然得租賃者，亦彼此利之中和也。屋主與承租者之間，多[MASK]。
夫婦之關係，雖為平等而以男性為主導，家中事務由男性裁決，女子應遵奉，然亦視母家地位及其實力。夫婦之間，尤重忠誠尊重，互為匹敵，互相照顧，守家族和睦也。夫婦之間，多[MASK]。
夥計與顧客之關係以商貿為基，夥計須敬、誠、勤、恭，供以良品及服務。顧客則於良品與服務，受之以禮，成兩全之美事。夥計與顧客之間，多[MASK]。
父母與子女之閒，以孝為要，從其道，分其憂，解其難。爲其子者須事親以終其天年，爲其女者，既嫁亦省親有定期，且盡力照拂有難者，不以有歸為辭也。父母則應愛憐其子、育其成才，仿三遷而擇佳處也。父母與子女之間，多[MASK]。
義父母與義子女之關係，亦以孝為要。養子須事長以終其天年，養女亦受為人女之道。義父母則應愛憐有度、育子成才。義父母與義子女之間，多[MASK]。
翁媳若父女，故以孝、敬、恭系之，然以非親之故，兼有男女之防，媳固當孝翁視親，亦從於令而不可逾于矩。翁當護其周全而不可密邇。要約以禮，不忘授受不親之訓也。公公與兒媳之間，多[MASK]。
婆媳乃家中上下級關係也。婆為長為尊，有督導教育之責，媳則尊之孝之，有若母子然。婦歸夫家，夫妻之外，婆媳為重大關係也。婆婆與兒媳之間，多[MASK]。
主人與家丁為主僕之關係。主人發號施令，家丁則從令而行，稟其忠也。此關係乃權力與經濟之關係之象徵，主人，富貴者也；家丁，卑賤者也，以此業為生。家丁亦有以契約而世代為奴，則主僕之分益固也。主人與家丁之間，多[MASK]。
地主與佃農之間，乃經濟之關係。地主佔田地，佃農租田以謀生。此關係為經濟依賴關係，地主因佃農而得益，佃農傍田地以得生。地主與佃農之間，多[MASK]。
店主與夥計乃勞動關係。店主以市肆營生，募選數夥計以經營，夥計從其令而行。此關係乃經濟與勞動之關係，店主因夥計而得益，夥計不辭辛苦而獲薪俸。店主與夥計之間，多[MASK]。
官員之與行賄者，權錢之交易也。官員有權，行賄者有金，進賄金以鬻權取利也。此雖違法之事，然世非罕見，甚或相沿成習而得以為默規，異代不鮮也。官員與行賄者之間，多[MASK]。
狀元、榜眼、探花，為科舉殿試之冠、亞、季稱謂也。考生之間，競爭、合作，以求仕進，固彼此為競爭對手。於科舉中，狀元為首，榜眼、探花次之。狀元與榜眼與探花之間，多[MASK]。
綠林好漢首領之與屬下（嘍羅），領導者與被領導者也。首領常以其勇武、智謀得天下，而為領導者。兩者之間，亦視將兵之關係，故於首領命令，屬下（嘍羅）須從而為之，等軍法也。綠林好漢之首領與屬下之間，多[MASK]。
繼父母與子女，乃法定親子關係也。或以原配父母猝然離世，或為離鸞別鳳，繼父母入其家庭，擔養育之責，子女須敬之、從之。繼子女承業於繼母家庭，禮也，法也；而繼父家庭者則或否也，視繼父及其家族態度而定。繼父母與子女之間，多[MASK]。
繼祖父母與繼孫，亦為法定之親子關係也。若父母猝然離世，或為離鸞別鳳，由一方再婚而入他家，則繼父母父母之父母為繼祖父母。繼祖父母有養育之恩澤，子女須孝敬順從之。繼祖父母與繼子孫之關係，視繼子女之與繼父母關係而迥別也，或為同姓則可親似家人，或為異姓而忽視之也。參繼父母-子女條。繼祖父母與繼孫之間，多[MASK]。
養父母與子女，緣以養育之恩，而成親子之情。或父母失於養育，或子女棄於街頭，有善人收養，則為養父母。養父母擔養育之責，子女須孝之同其親然。養子女承業，須視養父母及其家族之意，若有爭議，可訴之官府，然蓋罕見也。養父母與子女之間，多[MASK]。
古人尤重師生之誼，尊師重道，古之訓也。師者，傳道受業解惑之人，教人以禮以知以識以技。學生尊之、敬之，師者愛之、誨之，古時師生關係以父子關係為本，然孝廉科舉之興，亦俾染利祿之關聯也。師生之間，多[MASK]。
家庭（家族）私塾為昔者大家族子弟啟蒙教育之場所也。所聘之家庭私塾教師，或家族之飽學長者，或科場之落第者，或中而未仕者。教童稚以讀書寫字，其常業也，有言傳身教之責，教導其為人之道。故塾師之於弟子，或代族中長者訓誡子弟，或但為教書先生，視教師身份地位或其家族地位而定。家庭私塾教師與學生之間，多[MASK]。
小人于後世多目品行卑劣、心胸狹窄、唯利是圖之人。“小人之交”則指此等人之彼此關係也，其以利為本，漠視誠信，唯權謀與爭利而已。小人之交之間，多[MASK]。
佛教徒以佛法信仰為紐，慈悲為懷，同修而互助，以求得佛法真諦，共成和諧、平等、互助之關係。然自佛滅以來，教派紛然，利欲之心，恆難寂滅，故其以宗派、僧團、寺廟之異，彼此爭端，歷代恆有。佛教徒之間，多[MASK]。
道教徒以修仙教化為要務，無為而治，自然和諧，天地共生，萬物為一，以求長生不老，故道教徒之間，以平和、寬容、尊重為常。然其亦或以宗派、僧團、寺廟之異，而起爭端。道教徒之間，多[MASK]。
髮小者，自幼相識之友也，其行跡相似相同，故其交往甚近。兩人之間，可不甚囿於禮法，故率真而坦誠。發小之間，多[MASK]。
本地人之與異鄉人，關係複雜。以編戶齊民之故，民重遷徙，是以處於異域，本地人或嚴以防範，或疏以情感。又以方音之差、風俗之別，異鄉人恆倍感孤困。然亦有好客之人，助其在此安居也。本地人與異鄉人之間，多[MASK]。
土籍之人與客籍之人之問題，漢季以來，盤根錯節，乞于民清之際，未有終結也。其世居鄉土之地而編戶于官府者，謂之土籍之人；其離鄉背井、人徙居於他鄉而籍未更者，則為客籍之人。二者之異，於編戶齊民之策率有體現。大抵土籍之人地位高於客籍，故土籍之人多主人自視，深有自得之意。然客籍與土籍，雜處一地，或以田土之不均、或以經濟之不等、或以社會地位之不匹，或以稅賦政令之不平，而勢有消長。其間以土地、人口、政治權力諸此之屬而滋生矛盾，然和中寓爭，爭中寓和，幾世之後，二者以共處、合作與通婚之故，兼之戶籍更新，斷客為主之策，二者之異同，日愈消弭，并同土籍，此其常也。然舊之客籍未泯，而新之客籍又生，此又其常也。土籍人士與客籍人士之間，多[MASK]。
外祖父母與外孫或外孫女，多倫常親呢之情也。蓋將綱常倫理而觀之，則外祖父母之於外孫或外孫女，或不及外祖父母之於內孫或內孫女親密。然自私心而論，則未必如是，若紅樓夢中以座次定尊卑，外孫女林黛玉尊於內孫三春則是一例。此皆因家族結構而致，謂之外孫或外孫女當屬妻家，非屬夫家也，故禮數殊矣。外祖父母與外孫/外孫女之間，多[MASK]。
門當戶對之訂婚男女，其關係多由家族所定。其婚姻，非止兩人之結合，亦兩家以聯姻相合也。故其關係，或受家族、社會地位、財富等之影響。于訂婚之前，彼此交往不多，甚者未嘗謀面，然皆需遵家族與社會之規定，成合卺之禮。門當戶對之訂婚男女之間，多[MASK]。
私奔者，乃背禮叛教所以追情求愛也。常語以爲聘妻奔妾，然或以一見傾心欲早遂佳期，或以門戶不當而父母弗允，或以私情而拋其家室，不顧雙親兒女，終於淫奔者，以其愛戀之深，不可自抑也。然則負罵名，走他鄉，前途何卜，亦難以預知也。私奔男女之間，多[MASK]。
同科舉人之間，競爭與互助兼有之也。科舉，士進之途也，遂引天下讀書人埋頭于科舉之書。然進士之途窄矣，應試者多而中試者寡，其得高中以啓顯宦之階者則尤寡也。故于科考之時為競爭對手，然於考試之外，或可相學互助。考中者，若無素時芥蒂，咸可共相交友，以廣交際。同科舉人之間，多[MASK]。
同門師兄弟之間存恭謹相敬之情、患難相濟之意。其同拜一師，共得其教，故同門之情宜深矣。彼其有同門之敬助，攜手共進。若無有利祿貪欲之心，則同門師兄弟之間，充盈友愛之情，必也。同門師兄弟之間，多[MASK]。
同校學生之間，友情與競爭兼有之也。彼學於同一學校，有同窗共硯之情。然非獨限於共學之時矣，待卒業及從業後，亦可成通力合作之事。同校學生之間，多[MASK]。

山長者，書院衆師之長，亦書院之主管也；講席，書院所延聘之教師也。書院之治，向以寬而有別於官學也。官學之治，以屬官府而有等級高下之判。書院則否，以山長之道德文章為維繫也，以地方劃撥之田地房舍為生養也，是以山長之與講席，一講席之首座耳，志同則合，志異則散，山長之管書院者，攝也，固當共尊書院之規，不以勢相凌，是以寬。然有清之後，書院亦官學化也，非概得以寬一之。學府書院之山長與講席之間，多[MASK]。
同父同母之子女，為同胞之兄弟姊妹也，此乃血緣至親。同胞兄弟姊妹間多親呢，常勝於非同胞者。同父同母之子女之間，多[MASK]。
戲班與劇作者之間多合作也。劇作者撰作戲劇劇本，而戲班搬演劇作，以供觀眾欣賞。戲班之人身卑籍賤，然劇作者或為讀書人，位四民之首，甚者有功名焉，以差距懸殊之故，所謂合作者，亦鬆散之形式也。劇作者未必依演出之狀況而作成案頭之曲，戲班之於作品之呈現，亦未必符契原文，其違作者原意而有自行發揮之處者，蓋不勝舉也。戲班與劇作者之間，多[MASK]。
戲子，上臺演出者也；看官，觀賞表演者也。戲子以其表演技巧取悅看客，博看官捧場，而看官之回應，或於大快人心之處喝采，或於角色含冤負屈之處泣下。高超之技藝固得掌聲口譽，反之則致倒彩譏嘲。因之戲子須重看官之反應，然戲子卑微低賤，看官之於戲子，決於看官自身之態度與修養，借其賤戲子，以之為下等，亦不違世俗之德。戲子與看官之間，多[MASK]。
音樂曲藝人，以賞心悅耳之音求生計者也；聽眾，品賞其音樂曲藝者也。音樂曲藝人以其曲藝之才悅聽眾之耳，聽眾則據藝人之水準報以讚譽財物也。要之，藝人須以聽眾之反應為重，然曲藝人恆処賤籍，故與聽眾或不對等也。音樂曲藝人與聽眾之間，多[MASK]。
祖孫之間尊卑長幼宜井然有序。祖父母位高於父母，是以孫子女之於祖父母，尤須以禮敬重孝順之，以終其天年，是亦儒家倫理之不可或缺者也。祖孫之間，多[MASK]。
大夫，醫者之敬稱也。古之良大夫也，以扁鵲華佗之資，行救死扶傷之舉。病者若知曉大夫之醫術兼信之，則病者得瘳而醫者受譽，然則病者之與醫者，亦隨醫者口碑之優劣、人品之高下，與夫病者病情之變化、性格之差異而有別。大夫與病者之間，多[MASK]。
姨父姨母與侄子侄女之間存親戚之情也。姨父母以其長者慈顧幼小，幼者敬其長者，此為華夏家庭親情倫理之恆常。姨父姨母與侄子侄女之間，多[MASK]。
行俠仗義者，救受助者於水火災厄之中。仗其勇力，憑其志氣，赴人之困頓，軌俠之道義。至於受助者，則當銜環結草以報其恩也，是俠氣之所傳，而仁義有所弘也，夫緩人之所急，脫人之所危，曷可少也。行俠仗義者與受助者之間，多[MASK]。
妓女者，誤落風塵，陷於倡家，有姿色者賓客如市而衰老者落拓餘生。嫖客以錢財之豐厚，走馬章台，縱其情欲也。然二者之間，或漸生情愫，以成好合者，往往有之，然沉箱剃髮之悲，蓋尤其多也。狎妓違君子德風之誨，悖於人倫常理，為世之所誅責。然歷代官家律令以存秦樓楚館為慣例，《管子》發其端也。嫖客與妓女之間，多[MASK]。
掌櫃者，受店主所托，掌日常經營之事宜，凡貨物之進出、價格之定立、賬目之記錄諸類者皆須過問。掌櫃當不負店主所托之責，店主則當行察看之勸，以驗其實績。掌櫃與店主之間，多[MASK]。
夥計與掌櫃之間，上下級也。夥計，掌櫃之下屬也，掌日常營業之細事，凡接待賓客、售賣商品、搬運貨物之類也。掌櫃行指導管理之勸，而夥計聽其所命。掌櫃與夥計之間，多[MASK]。
捐助者，施以財物之助，不苛求彼之回報；受惠者，受其所助而當銜環結草，以報其恩德也。仁愛互助之義在其中矣。捐助者與受惠者之間，多[MASK]。
將領與士兵之間，上下級也。將領之帶兵也，其高明者在於寬嚴並濟，既嚴於治軍，又時彰仁愛兵卒之美德行，以兵為子。然軍令如山，故士兵須惟命是聽。此則軍隊令行禁止之法也。將領與士兵之間，多[MASK]。
考官之與考生，主試與被試者也。考官評考生之學識才能，而考生須受考官之評鑒。此乃科舉之制公正之途。及考畢，中試者與考官可立師生之誼以擴交際，季世則爲結党之一端也。考官與考生之間，多[MASK]。
家長敬重信任其子女之師也，是以教育之任托之。師長傳道受業解惑，以誨其子弟。總言之，師長位高權重，掌教學之法諸多事宜，故家長須聽而從之。彼此或以嚴父之姿共擔子弟教育之責。師長與家長之間，多[MASK]。
同鄉之間往來密切，彼此相助，共解困厄。同鄉之間，同飲一鄉之水，同言一方之音，風土人情共相習知，故他鄉之逢，倍感親切。同鄉之間，多[MASK]。
鄰里相處之道，可奠鄉里秩序之基。鄰里者，共助、共用、共慶，其要在乎協同互敬，講信修睦，可築鄉里之大同。結姻親、共耕織、連什伍，皆可固鄰里。鄰裡之間，多[MASK]。
相與出行者，同途之際，經歷相同，利益相干而目的相通也。故可相持互助，以應行途之變。同遊關係之要，在諸同心同德，共克困艱。相與出行者之間，多[MASK]。
從事買賣者，賣方或以物售之，或以役供之，買方則以貨貝易之。販賣貿買，需重信諾，禁詐紿。賣方所供務必價合質優，買方所償務必踐以約。買者與賣者之間，多[MASK]。
所謂行人，今之路人也，目有所接而言行不必交，以無深交之所需也。或逢於茶樓酒肆，或見於街巷坊裡，非有際會因緣，相交不過泛泛而已。行人之交多無深交厚誼可溯，然疏而有禮，遠而存敬。行人之間，多[MASK]。
狐朋狗友，品行不檢而相偕作樂取悅心欲者也，所好皆賭博、酗飲、狎妓之陋習。狐朋狗友之交，觥籌交錯、宴酣之樂顯於外，而犬馬聲色、熏心色欲隱其中也。狐朋狗黨之間，多[MASK]。
泛泛之友，可為同好，共論琴棋，共試酒茶，然多止於淺交。所謂淺交者，非親非疏，若敬若重，不甘于醴，亦非純淡如水也，以未深交之故也。泛泛之交之間，多[MASK]。
故舊者，情誼深遠之友也。故舊之友多共曆往事種種，然溫不增華，寒不改葉，能四時而不衰，歷險夷而仍固，相輔相助，情堅若金。故舊之間，多[MASK]。
摯友者，無血緣之親，然勝乎同產，雖貧富貴賤、生死離別不能阻隔之。摯友相交，以拳拳之心同攜手、共患難，實無價之友誼也。摯友之間，多[MASK]。
友誼之至境是謂知己。其情之深厚，遠勝泛泛相交，亦相異於親子牽絆，如奏高山流水于知音也，意動即神會，勝卻言語無數。互為知己者，彼之喜怒哀樂皆可歷歷於己心，至情至性，合若符契，而相敬之以禮；若得一知己，遑論肝膽相照，雖九死其猶未悔。友誼之至境，不過是也。知己之間，多[MASK]。
乞者與行者，多遇於市肆。乞者所欲者惟行者之施，行者之施亦可彰己憐憫之心。然二者相遇，行者多無所施，乞者或無所得，以不必施故也。乞丐與行人之間，多[MASK]。
新故官吏之閒，權力交接之關係也。去者有升、謫、免、致仕之別，而新任者，生疏于此間府衙事務，故舊任有授新任以經驗故事之責。然則離任者或以親近者安排新任左右，雖去任而威信存，且交接之際，多涉賦稅度支之核查、檔案文書之清點，案件審理之清白，田地戶口之數目，是以輕則生隙，重則黨伐。新故吏之間，多[MASK]。
獄卒之于囚犯，有羈押之權，囚犯受制于獄卒，受監守之限制。獄卒待囚犯何如，視囚犯家族之貴賤、案情判罰之輕重，及親友打點之多少而各異也。若利益相合，或義氣相投，獄卒囚犯亦可結友，然為獄卒者疾言厲色、受其暴虐者多為常態。獄卒與囚犯之間，多[MASK]。
告與被告，皆寄之律法以為己申訴辯白，而互為對立也。告劾者所求，伸曲理枉，以示法網恢恢；被告者所求，自證清白，以求洗冤昭雪。告與被告之辯，實關乎法治完備公正之有實否。告劾者與被告者之間，多[MASK]。
妻妾之間多明暗糾葛。妻者，主内也，總理治家教子之務。妾者，位卑于妻，多以存續香火，姿顏姣好之由納之。妻妾相處，或扶持相依，或勾心鬥角。《毛詩序》曰：“《關雎》樂得淑女以配君子，憂在進賢，不淫其色。”盡言正妻納妾之責，妻妾相處之道。妻妾之間，多[MASK]。
妻與外婦之間，相視若讎仇。外婦者，未娶而旁通也，無婚姻之名。外婦若有子，易致後宅不寧，亂尊卑之別，生分財之釁，是故妻與外婦多生齟齬。妻與外婦之間，多[MASK]。
夫暗合於外婦，苟且之舉也。二者無婚姻之名，為世所不齒。暗合者，或生相依相濡之情，亦或僅尋一夕貪歡。夫與外婦之間，多[MASK]。
遠親者，有血緣之絆，無近鄰之切，往來問候多訴諸婚喪嫁娶節氣，寄乎禮法倫常，以厚親戚之情。然澆薄之世，如涉祖業田產之爭，則雖遠親亦或生齟齬。遠親之間，多[MASK]。
子婿之於岳家，理應互敬互賴，然岳家垂青與否，多決於子婿之功名、族望。除入贅而改姓易族者，翁婿雖名為父子，實各異家，其情弗如同簷之婆媳遠甚，遑論血緣之親。岳家與子婿之間，多[MASK]。
同袍之誼，多喻軍旅士伍心心相惜。士卒征戰於沙場，同浴血汗、共赴國難，皆懷身先致死、盡忠報國之念。詩曰：豈曰無衣，與子同袍。是以同袍之親，勝似兄弟。同袍之間，多[MASK]。
官民之間，上下領屬之關係也。為官之道，必除害興利，善度民力，正風立綱；為民之要，必遵紀守法，立身行道。官民相處亦如父子，為人父則慈，為人子則孝，為人上則明，為人下則聖，父慈子孝，上明下聖，治之紀也。官民之間，多[MASK]。
結黨而敵對者，始於小人之同利，及其見利則爭先，或利盡而交疏，乃反相賊害。結黨者之利異，多為政見、觀念相抵，至成水火之勢。為求己利，雖其親戚兄弟不保也。敵對黨派之間，多[MASK]。
同盟即志同道合者。君子與君子以同道為朋，共守道義，行忠信，惜名節。是故同盟者得以守望相助，進退如一，莫逆於心。同盟黨派之間，多[MASK]。
保人者，受託于雙方顧主，牽繫買賣關係，以局外之身處理其間事務者也。顧主雙方多聘保人以求交易之公正，保人亦從中牟利。保人之制，早至魏晉隋唐已有所載，古商貿制度之完善據此可窺一二。保人與顧主之間，多[MASK]。
所謂忠臣，效忠于社稷者也，以鞠躬盡瘁、死而後已為己任，多為世之表率，歷代稱頌不絕。所謂逆賊，離君叛國者也，陷社稷於累卵之危、倒懸之急，世人為之不齒。忠臣與逆賊之間，多[MASK]。
主客之交，以互敬互重為本。為人主者，待人接物需完備周致，以求賓至如歸；為賓客者，亦需禮尚往來，以示謝忱。古之人倫禮制，亦見於主客相交之道也。主人與賓客之間，多[MASK]。
主奴者，主人為主而女婢為從也。主人有令，奴必應之，不可不從，以其必終於主人故也。奴之衣食起居，身家性命，全仰主意。主人和善體恤，則奴亦可豐足；主慳吝刻薄，則奴亦常縈困頓。然奴之私忠於其主也，不必係於主之慈暴，以世論其忠若犬故也。主奴之間，多[MASK]。
乳母之與嬰孩之家長，僱傭關係者也。家長或以嬌弱，或以矜貴，或以少乳，僱乳母以照料之。乳母當供乳於彼嬰幼，事其起居，乃或至教導培育。二者既系於僱傭，則信立為本而求職盡也。家長用人不疑，乳母方不墮其職也。乳母與家長之間，多[MASK]。
乳母之于嬰幼，保育者也。乳母非僅哺之以乳，且兼料其起居，助其成長，與其蒙學。長此以往，乳母或親愛嬰幼，嬰幼亦依戀乳母，此人情所致，本非乳母之分也。及長，嬰幼雖有生母，于禮當母事之，然愛信乳母，厚此而薄彼，亦時有之。雖然，若依通例，嬰幼年齒既長，無需哺乳，乳母之分即盡。更有甚者，就此別過，鮮復往來矣。乳母與嬰幼之間，多[MASK]。
凡職官者，常設正副。正者，統也。凡執掌決策，籌謀號令，皆出於正者。副者，輔也。或可決策，然猶為行正者之令耳。正副職官，或勾心鬥角，傾軋掣肘；或相交融洽，並力同心。二者相輔相成，乃自然之理，然彼此相爭，亦時有之。正職與副職之間，多[MASK]。
教首者，亦曰教主，一教之領袖也，享至高威權，眾人視之如神聖。教徒者，此教之信眾也。尊奉教首，篤信之，敬仰之，無敢有違。凡教之規，皆當嚴守；凡本教之義，教首之令，皆應踐行。由此可觀古時宗教神權之廣大威嚴，與夫信徒心靈之精誠純粹也。教首與教徒之間，多[MASK]。
一家一族，必有其祖。先祖後裔，分支散葉，世代相延，此乃家族形式之基本樣貌。祖為一族之源，綿綿瓜瓞，延而至今，其開創之始，嘉行善德，當銘於子孫，賡續不絕。子子孫孫需尊奉之，稱頌之，祠廟之，祭享之，且以顯祖榮宗為務，不可玷污門楣，蒙羞祖上。重祖以尚孝，古來如此。祖先與後代之間，多[MASK]。
保長坊長者，鄉裡街坊一方之長也，以平治鄉裡街坊之序，協官府理此地之事，上傳下達於鄉間坊間為責。居鄉裡街坊者，稱居民。居民需從保長，遵鄉規，然後可自主而為。此則城外之鄉裡，城内之街坊，其自轄之法也。保長與居民之間，多[MASK]。
遠房表親，雖非同胞，血緣略淺，然既系一族，兄弟姊妹之禮，仍需具備，並擔修睦之責，盡扶持之義。蓋開枝散葉，本自同宗，血濃於水，情繫其中，遠方表親，亦不可輕疏也。遠房表親之間，多[MASK]。
君臣之間，界限分明。君者，一國之主；臣者，輔君以治國也。君可行賞罰於臣，臣當履忠誠於君。君君，臣臣，各從其分，然孟子曰：“君之視臣如手足；則臣視君如腹心；君之視臣如犬馬，則臣視君如國人；君之視臣如土芥，則臣視君如寇讎。”是以君愛臣，則臣親君而易忠，反之則心離而人散，然儒者所謂臣之忠，忠乎社稷天下，非一人一姓也，而鼎革之節，革命之時，何謂稷天下，何謂一人一姓，人多混淆之，而一人一姓多樂其混淆也。由此觀之，君臣之間，錯綜複雜，一言難盡。君臣之義，乃上下之權力關係，亦涉個人與家國集體之關係也。君臣之間，多[MASK]。
債主與負債者，二者交通，繫於財幣。債務既成，負債者需依契約按時償之，逾期未償，債主可責之。此二者一關乎責權，二關乎財幣也。債主與負債者之間，多[MASK]。
親家者，姻親是也，為夫妻兩家父母之互稱。親家為同等之親戚，亦關世故人情。若夫婦敦睦，則親家亦諧，鮮有齟齬。親家之間，多[MASK]。
訟師之與司法者，因其職而相交也。事主有案，託於訟師，代寫文書，申訴有司，而司法者任於官府，審判其案。二者因本職而協作，並行業務於律法之事也。然地方司法，皆委縣令，多起於科舉，熟於治經，疏於律令，訟師與縣吏或沆瀣一氣，操縱案判，則蔽矣。訟師與司法者之間，多[MASK]。
訟師之於屬者，代理關係也。訟師以代撰訴狀為務，然亦可因之而受屬者之托，代其行訟。此二者一關乎責權，二關乎立信與代理也。訟師與屬者之間，多[MASK]。
捕快者，地方官府之差役也，以捉賊、治保為務。百姓為全身護財計，仰賴捕快；而捕快或濫權恣肆，百姓見而生畏。是以捕快百姓之間，關係微妙，一言難蔽百世之實。捕快與百姓之間，多[MASK]。
疑犯捕快，彼此對立。捕快之務，緝拿疑犯，而疑犯聞之，必逋逃藏匿，如鼠畏貓也。二者水火難容，矛盾多生。疑犯與捕快之間，多[MASK]。
罪犯之於人質，強之以力而脅其性命者也。犯人作奸犯科，將陷囹圄，恐牢獄之災，或挾人質以要官府。人質遭其挾而性命堪憂，以無可自主，常聽命于罪犯。罪犯與人質之間，多[MASK]。
罪犯所害之人，若有親眷，則稱苦主。苦主與罪犯為敵，視之為仇讎，冀官府緝捕，使其就法。或思血親之仇，不共戴天，則不俟官府，而有私報之也。罪犯與苦主之間，多[MASK]。
罪犯觸罪，或為旁人所觀。旁人既觀，則或有紛紛議論，批評褒貶。輿論所加，則罪犯聲名地位，亦隨之而更。是以旁人之論，或可左右決獄。而保甲之制，儒家之教，亦或使旁人作證，轉為證人也。罪犯與旁人之間，多[MASK]。
盜賊失主，彼此對立。盜賊之行，本系非法，謀竊失主，損其財物。依律，賊當償其失，並伏法受罰。盜賊與失主之間，多[MASK]。
罪犯與受害者，彼此對立。罪犯以非法加害於人，傷其身心。依律，賊當伏法受罰，以償其所害。罪犯與受害者之間，多[MASK]。
司法者與監察者，互相監督，彼此牽掣者也。司法者以審案為務，昭法之威，執法以正。監察者則督其行事或查其已行，以防其私弊貪腐，使司法必正也。司法者與監察者之間，多[MASK]。
罪犯同黨者，共犯是也。其所求所行，皆系非法，而三五聚夥，同籌共謀，一朝舉事，乃咸觸罪。依律，犯罪同黨未可消罪，以其明知共犯，或增其罪咎。罪犯同黨之間，多[MASK]。
賭徒之間，彼此相爭者也。其好博嗜賭，日以鬥雞走馬，喝雉呼盧，投注押寶為事，至於一擲千金，妄希橫富。故彼此爭財奪利，甚為激劇，不免舞弊詐欺，乃至身體相鬥者。厤朝之律法，以賭禁為常，故賭徒之間，世人皆視之為歪門邪道也。賭徒之間，多[MASK]。
文人與閱者，以文之賞識相交通者也。詩文曲賦，文人所作，常寓以其道其情，因傳其文而載其道也。閱者覽之，可明其道而體其情。夫閱者有感，或建言于文人，使其更改；而流播之廣狹，亦繫於後來之閱者。然限於古之實際，二者不得直接交通，故以單向為多。尋常閱者，難比文人之博觀群覽，不可左右其意。雖然，猶有閱者或與文人相厚，或業相關之業，或知音於後世，因而評論之，紹介之，出版之，則可左右文人之書寫，甚或筆削增潤其原文，而動搖世俗之喜好也。文人與閱者之間，多[MASK]。
文人多為士人之屬，論者亦品評之士。二者之間，實可相互磋磨學問，評鷙詩文者也。文人作詩文曲賦，而論者品藻之，其建言獻意，雖抒己之見，亦或左右文人之書寫也。於是論者作評，而文人參酌，以修色其作，推敲之定，一字之師，皆此類也。觀古之文俗世情，論者之于文人，抑揚者也。夫論者所尚，則以詩品詞話、文論筆談附益其作，播其芳名，俾傳之百世而其聲益顯，其文益高。反之，亦有詩文曲賦，論者毀之，因聲名不顯，浸微浸消者也。文人與論者之間，多[MASK]。
男女曖昧之事，悖於人倫，是以隱於心而不擅發於外。其或發於外者，亦以含蓄之言，傳微妙之情，假落紅秋葉之詩，托香囊繡帕之物，暗致其情，不令外人見也，多是之類也。曖昧者之間，視若[MASK]。
暗戀者，古語或謂單相思。男女之間，礙于父母之命，媒妁之言，婚姻之有定也，於是己固思慕彼而不敢以私意白，彼未知而己切思之，求之不得，其情之至者，所謂“寤寐思服，輾轉反側”是也。其恪于禮者，常以春蠶絲盡、桃花依舊之喻，暗寄其心而不外傳，亦或以暗中護助，不令其有艱困愁苦，而其稍逾制者，則或致佩飾之物也。古之暗戀者，多止乎此，至若季世綱常已墮，男女忽於大防，暗戀轉直，單思為雙，則奔者難禁。暗戀者與被暗戀者之間，視若[MASK]。
報案者之于受害者也，或同系一人，或其鄰裡親朋之知情者也。自秦法以降，遞有閭閻連坐之策，凡知情不舉者，按律當坐，王安石所目保甲法，即是也。然世有升降，國有治亂，保甲連坐之策，可行乎令行禁止之時，而文恬武嬉之季，多具文視之耳。且古時刑偵之術寡而限期破案之律在，案犯易脫幹係而有司則損利祿，是以報案者亦須證據確鑿，無可指摘，庶免乎官府之糾擾而人財俱困也。又自董子以來，列朝以儒治國，親親相隱之教，風乎百世，是以近親之間，若非大義滅親之舉，概以不報官府為長，而以鄉約族規處置也。報案者與受害者之間，視若[MASK]。
報案者與罪犯之間多對立之關系。報案者舉罪犯之罪，冀以律法懲之。然報案者或有因擿伏發隱而罹罪犯相脅相報之禍者也。又以保甲連坐之製與大義滅親之理，報案者與罪犯之間亦或為親戚鄰裏，此又非必是兩立之勢也。報案者與罪犯之間，視若[MASK]。
文選詩集之編者與作者，或因敬重欣賞之情，或為功利實在之用。其功利實在之用著，如著者為高官、長輩、恩師者也，甚者編者或側己文於他人之文，以彰己名也。裁約編選之時，編者常善著者之才華功業。編者亦以其選裁左右讀者之理解。文選詩集之編者與作者，實為古時文人之文化品味、審美觀念、權力關係之鑒鏡也。文選之編者與作者之間，視若[MASK]。
表兄弟姐妹者，視同近親，關系親近，家族之情亦深也。彼於童稚之時，可共遊學、相長互助，共解所遇之危難。禮，表兄弟姐妹須循一定之禮節，長愛少，少敬長。及漸長，循授受不親之訓，以其為異姓，可通婚姻故也。表兄弟姐妹之間，視若[MASK]。
庖人之與食客者，為服務被服務之關系也。庖人主烹飪，以甘美之食奉食客，而食客亦須念庖人之生計。故庖人須盡其技以足食客之口，食客亦須慎待庖人所供之物，此亦理之常也。或有庖人專供於食客或主人之家，則曰名廚或私廚，其與食客主人之關系則更甚其他庖人也。庖人與食客之間，視若[MASK]。

仇敵之間乃對立衝突之關係也。敵者，匹敵也，論其才智，則相儔類，而或以利益之不均、或以地位之不匹、或以權力之不及、或以忠誠之不貞，諸此之屬，心生怨望而欲戕害以快其心者，仇敵之事也。然則，仇敵既以相噬為常，亦以其相匹，而或生相惜之感，且古時人分等級，同匹儔之人，其未為仇敵之初，或有通家之好，秦晉之交而同窗之誼也，是以古之仇敵，視今日為複雜也。故經史詩賦之中，感概仇敵之才智氣節者，亦不知凡幾也。仇敵之間，視若[MASK]。
施恩者與受恩者為恩義與感恩之關係。施恩者之助受恩者也，或以善行，或以援手，受恩者遂感念其德，雖滴水之恩，木瓜之贈，亦矢報以湧泉瓊瑤也。古以'知恩圖報'為德之大者也。施恩者與受恩者之間，視若[MASK]。
青梅竹馬，即為男女自幼同遊嬉戲，心生情愫者也。其情純真深沉，或終為伉儷，或為知己。古時文人墨客之述此情者，至純至美，感人心脾。青梅竹馬之間，視若[MASK]。
情敵者，二三人傾慕同一對象，遂相競爭。此關係中，有敵意、嫉妬、競爭至於殺心之複雜心緒，然亦或有互尊呼諒者。經史詩賦之中，論及情敵，常有激烈戲謔之矛盾，或高雅而囿於禮法，或直率而流於粗鄙。情敵之間，視若[MASK]。
天人之間，乃天地人三才之並立關系，人宜順天地，而與萬物為一。儒道皆謂人當敬天地而順之，於是乎則和也。欲和天人，需通天意，欲通天意，則在貫三才之王者，以儒家正典之論，王者得位聖賢之大號，非權勢之稱也，是以為古代知識階層與君主權力間之製衡也。天人之間，視若[MASK]。
人神之間以信仰敬畏為維繫，其方式不離祭祀、祈禱以通達於神靈也，其指歸在乎求得神靈庇佑，解其大惑，脫其苦厄，堅其心志，導其前路也。今之視古，則謂古之信神，原乎科技落後，而驚懼敬畏于自然未知之力量也。然商周以降，中華之地，人以配天，民為神主之論，敬鬼以遠之教，人能弘道之言，天命從德之誡，經籍之載，三教之說，鹹崇人之踐行而斥虛妄之求神也。然則子雖不言怪力亂神，而人之不齊，一致百慮，可導而不可壅，是以君子明辨天理，不惑神鬼，而不責民間之求神問卜以行善避災也。人神之間，視若[MASK]。
泛泛之交，乃交情淺薄之普通關係也。於此關係，彼此不通心意，交遊往來，相待以禮而已。泛泛之交，或可謂之朋友，然為關係最疏者也。泛泛之交之間，視若[MASK]。
店主與顧客，為買賣交易之雙方也。店主供貨品服務於顧客，顧客以財貨償之。店主須竭其誠以應顧客之需，顧客亦需尊店主之恭敬服務于我也。所謂“買賣不成仁義在”，古時買賣之道，理不逾此。店主與顧客之間，視若[MASK]。
官場之尊卑上下，不可逾距。上之於下，等級之中，所差愈多，威勢愈強。是以官員之間，忠敬為首，然忠敬者，忠於所守也，非忠於上司某甲也。上之於下，亦有訓導保全之義，此即古之尊卑有序、和諧中正之道也。然世閒多難行也。官場之上下級之間，視若[MASK]。
買賣之夥伴，所共求止於利而已，緣此須相信相助，共分其利。其間信與平最為重，買賣之夥伴須以誠交易，以平分利。彼此亦須行為相協，言語相洽，以求買賣之順遂。買賣之夥伴之間，視若[MASK]。
買賣之競爭對手，以欲求多利，欲天下求購者多求於己而俾天下財富多歸於己，於是乎有對手生焉。然生財亦當有道，故相競爭者雖有相爭之欲而求勝於對方，亦皆須守信持中，不得狡求他人之利。要之，亦有尊重也。買賣之競爭對手之間，視若[MASK]。
宗教師徒，在於信仰之傳續繼承。師者，教訓徒弟，徒者，尊師重道，忠於師命。其間尊與忠為最重，徒須尊師忠命，師須護持教徒。宗教師徒之間，視若[MASK]。
百工之師父與學徒，在於技藝之傳承。傳技之時，師者須教導訓誡其徒，徒者須尊敬愛重其師。其間尊與忠為最重，徒須尊師忠命，師須護持教徒。師傅與學徒之間，視若[MASK]。
古之掌櫃與客人，因買賣交易為緣。掌櫃者經營其店。客人者消費之人也，求店主之所供。掌櫃須供客人所需，以求信與利。客人亦須敬重掌櫃，不得違其買賣之道。掌櫃與客人之間，視若[MASK]。
古之首領與反賊，以勢不兩雄為常。首領者，為國之首領，反賊者，為國之叛逆。首領須守其威勢與現有之秩序，反賊則欲反叛其威勢與現有之秩序。首領與反賊之間，視若[MASK]。
叔侄為血親。叔者為父之弟，侄者為兄之子。叔有教育侄之責，侄須愛敬叔，然亦須視其父母之存亡與學識尊卑論叔撫育之任也。叔侄關係於家族之中為極重要之關係。叔侄之間，視若[MASK]。
雙胞胎因其母一胎同產之同胞，其情於血親手足之中為最近也。同孕母腹，同生一時，同長一處，其形其態其跡在成人之前尤多為相似，故其未冠笄之時，蓋情最深厚，或施及平生。雙胞胎之間，視若[MASK]。
於政治之中，兩方之會晤多因權與利之爭鬥也。多以其政治與國家所屬不同，冀會晤以求成結盟。兩方須守盟會之理，於守自身之利為上為底，亦宜慮對方之利，以成盟約也。政治談判中對立之雙方之間，視若[MASK]。
堂兄弟姐妹為親戚，然其親不過於同胞兄弟姐妹。於家族之中，堂兄弟姐妹可與嫡子女同長共學，亦同為長者所愛，然於家財分配，若非嫡子女亡故出繼，則不得分其家財，然亦多有倚勢強奪家財之事。論及尊卑，堂兄弟姐妹之長者亦為家族所重。堂兄弟姐妹之間，視若[MASK]。
古者以父系別家族，故同父異母與同母異父之子女之所受對待全然不同。若子女為同父異母，則其於家族之中尊卑貴賤則從母之所處為父之發妻、續弦、妾之等而不同，及其母之存亡與母家之勢而定，然其爲一家之人，則無疑也。若子女為同母異父，則多因父之續娶他婦，其母之前夫子女多為後嫁之家族異姓視之，其被賤待，亦其常也，然亦須視其後父家之心與其母家之勢。同父異母與同母異父之子女之間，視若[MASK]。
繼子女之間，雖為親戚，但彼此犬牙交錯，一言難磬。繼母與繼父之子女之關系亦相去萬裏。古者，父親多主家族，父親續娶，繼母亦為繼子之母也。然若母親改醮，繼子則從母而入繼父家，其家族關系亦全然改換也。若父母於其前夫前妻亡故後另結婚姻，則或因繼父繼母之愛而另生齟齬。家產之分配，若其母為繼母，則繼子女（若其女子未嫁）以律法可得所應之家產。若其父為繼父，則繼子女非繼父及家族所允，以律法不得受家產。繼子女之間，視若[MASK]。
古之為官，同僚之間以官位相近，同朝合堂，共謀於事。然或因其職所守相近，未免於相爭，而生齟齬者亦多有之。同僚之間尊卑之序則定以官位高低、資望長短。同僚之間，視若[MASK]。
庠序之間，同窗之間以求學問知識為共識，相助於學，共進於道。然因修業之優劣，成績之高下，而生齟齬者亦有之。同窗之間，常為對等之交，然亦可守尊卑之禮而以年齒為序，此多為交往之禮便耳。同窗之間，視若[MASK]。
所謂搭訕者，意在親近被搭訕者，以其欲與被搭訕者交好而有所圖也。搭訕者之於被搭訕者，或欲作綈袍之義，或欲結琴瑟之好，或欲為買賣之宜。二者之關系，主動與被動並存，不確與不穩共生。然搭訕者多有所求，故世貶其行，經史詩賦亦多譏之。搭訕者與被搭訕者之間，視若[MASK]。
施害者乃刑案中為暴力罪行者也。受害者乃因施害者之暴而罹身體乃至於性命之禍也。施害者與受害者，或為兩立，或為抵牾。經史典籍錄此案件，多因其所涉或為欺公罔法，或為其案情之重大曲折，蒙冤者終得昭雪也。然亦多為尋常案件之受害與被害關系。刑案中之施害者與受害者之間，視若[MASK]。
古之旁觀者乃睹罪案而無與者也。或為偶然，或特持中而觀也。旁觀者之與受害者，論其行多有意疏遠之，跡其心則漠然或哀憫，然則旁觀者亦有因保甲連坐製度而或肯作證者。刑案中之受害者與旁觀者之間，視若[MASK]。
屋主者，有屋貰於人者也。承租者，僦屋於人者也。屋主與承租者，常為權利義務之交易，或有經濟利益之抵牾，然得租賃者，亦彼此利之中和也。屋主與承租者之間，視若[MASK]。
夫婦之關係，雖為平等而以男性為主導，家中事務由男性裁決，女子應遵奉，然亦視母家地位及其實力。夫婦之間，尤重忠誠尊重，互為匹敵，互相照顧，守家族和睦也。夫婦之間，視若[MASK]。
夥計與顧客之關係以商貿為基，夥計須敬、誠、勤、恭，供以良品及服務。顧客則於良品與服務，受之以禮，成兩全之美事。夥計與顧客之間，視若[MASK]。
父母與子女之閒，以孝為要，從其道，分其憂，解其難。爲其子者須事親以終其天年，爲其女者，既嫁亦省親有定期，且盡力照拂有難者，不以有歸為辭也。父母則應愛憐其子、育其成才，仿三遷而擇佳處也。父母與子女之間，視若[MASK]。
義父母與義子女之關係，亦以孝為要。養子須事長以終其天年，養女亦受為人女之道。義父母則應愛憐有度、育子成才。義父母與義子女之間，視若[MASK]。
翁媳若父女，故以孝、敬、恭系之，然以非親之故，兼有男女之防，媳固當孝翁視親，亦從於令而不可逾于矩。翁當護其周全而不可密邇。要約以禮，不忘授受不親之訓也。公公與兒媳之間，視若[MASK]。
婆媳乃家中上下級關係也。婆為長為尊，有督導教育之責，媳則尊之孝之，有若母子然。婦歸夫家，夫妻之外，婆媳為重大關係也。婆婆與兒媳之間，視若[MASK]。
主人與家丁為主僕之關係。主人發號施令，家丁則從令而行，稟其忠也。此關係乃權力與經濟之關係之象徵，主人，富貴者也；家丁，卑賤者也，以此業為生。家丁亦有以契約而世代為奴，則主僕之分益固也。主人與家丁之間，視若[MASK]。
地主與佃農之間，乃經濟之關係。地主佔田地，佃農租田以謀生。此關係為經濟依賴關係，地主因佃農而得益，佃農傍田地以得生。地主與佃農之間，視若[MASK]。
店主與夥計乃勞動關係。店主以市肆營生，募選數夥計以經營，夥計從其令而行。此關係乃經濟與勞動之關係，店主因夥計而得益，夥計不辭辛苦而獲薪俸。店主與夥計之間，視若[MASK]。
官員之與行賄者，權錢之交易也。官員有權，行賄者有金，進賄金以鬻權取利也。此雖違法之事，然世非罕見，甚或相沿成習而得以為默規，異代不鮮也。官員與行賄者之間，視若[MASK]。
狀元、榜眼、探花，為科舉殿試之冠、亞、季稱謂也。考生之間，競爭、合作，以求仕進，固彼此為競爭對手。於科舉中，狀元為首，榜眼、探花次之。狀元與榜眼與探花之間，視若[MASK]。
綠林好漢首領之與屬下（嘍羅），領導者與被領導者也。首領常以其勇武、智謀得天下，而為領導者。兩者之間，亦視將兵之關係，故於首領命令，屬下（嘍羅）須從而為之，等軍法也。綠林好漢之首領與屬下之間，視若[MASK]。
繼父母與子女，乃法定親子關係也。或以原配父母猝然離世，或為離鸞別鳳，繼父母入其家庭，擔養育之責，子女須敬之、從之。繼子女承業於繼母家庭，禮也，法也；而繼父家庭者則或否也，視繼父及其家族態度而定。繼父母與子女之間，視若[MASK]。
繼祖父母與繼孫，亦為法定之親子關係也。若父母猝然離世，或為離鸞別鳳，由一方再婚而入他家，則繼父母父母之父母為繼祖父母。繼祖父母有養育之恩澤，子女須孝敬順從之。繼祖父母與繼子孫之關係，視繼子女之與繼父母關係而迥別也，或為同姓則可親似家人，或為異姓而忽視之也。參繼父母-子女條。繼祖父母與繼孫之間，視若[MASK]。
養父母與子女，緣以養育之恩，而成親子之情。或父母失於養育，或子女棄於街頭，有善人收養，則為養父母。養父母擔養育之責，子女須孝之同其親然。養子女承業，須視養父母及其家族之意，若有爭議，可訴之官府，然蓋罕見也。養父母與子女之間，視若[MASK]。
古人尤重師生之誼，尊師重道，古之訓也。師者，傳道受業解惑之人，教人以禮以知以識以技。學生尊之、敬之，師者愛之、誨之，古時師生關係以父子關係為本，然孝廉科舉之興，亦俾染利祿之關聯也。師生之間，視若[MASK]。
家庭（家族）私塾為昔者大家族子弟啟蒙教育之場所也。所聘之家庭私塾教師，或家族之飽學長者，或科場之落第者，或中而未仕者。教童稚以讀書寫字，其常業也，有言傳身教之責，教導其為人之道。故塾師之於弟子，或代族中長者訓誡子弟，或但為教書先生，視教師身份地位或其家族地位而定。家庭私塾教師與學生之間，視若[MASK]。
小人于後世多目品行卑劣、心胸狹窄、唯利是圖之人。“小人之交”則指此等人之彼此關係也，其以利為本，漠視誠信，唯權謀與爭利而已。小人之交之間，視若[MASK]。
佛教徒以佛法信仰為紐，慈悲為懷，同修而互助，以求得佛法真諦，共成和諧、平等、互助之關係。然自佛滅以來，教派紛然，利欲之心，恆難寂滅，故其以宗派、僧團、寺廟之異，彼此爭端，歷代恆有。佛教徒之間，視若[MASK]。
道教徒以修仙教化為要務，無為而治，自然和諧，天地共生，萬物為一，以求長生不老，故道教徒之間，以平和、寬容、尊重為常。然其亦或以宗派、僧團、寺廟之異，而起爭端。道教徒之間，視若[MASK]。
髮小者，自幼相識之友也，其行跡相似相同，故其交往甚近。兩人之間，可不甚囿於禮法，故率真而坦誠。發小之間，視若[MASK]。
本地人之與異鄉人，關係複雜。以編戶齊民之故，民重遷徙，是以處於異域，本地人或嚴以防範，或疏以情感。又以方音之差、風俗之別，異鄉人恆倍感孤困。然亦有好客之人，助其在此安居也。本地人與異鄉人之間，視若[MASK]。
土籍之人與客籍之人之問題，漢季以來，盤根錯節，乞于民清之際，未有終結也。其世居鄉土之地而編戶于官府者，謂之土籍之人；其離鄉背井、人徙居於他鄉而籍未更者，則為客籍之人。二者之異，於編戶齊民之策率有體現。大抵土籍之人地位高於客籍，故土籍之人多主人自視，深有自得之意。然客籍與土籍，雜處一地，或以田土之不均、或以經濟之不等、或以社會地位之不匹，或以稅賦政令之不平，而勢有消長。其間以土地、人口、政治權力諸此之屬而滋生矛盾，然和中寓爭，爭中寓和，幾世之後，二者以共處、合作與通婚之故，兼之戶籍更新，斷客為主之策，二者之異同，日愈消弭，并同土籍，此其常也。然舊之客籍未泯，而新之客籍又生，此又其常也。土籍人士與客籍人士之間，視若[MASK]。
外祖父母與外孫或外孫女，多倫常親呢之情也。蓋將綱常倫理而觀之，則外祖父母之於外孫或外孫女，或不及外祖父母之於內孫或內孫女親密。然自私心而論，則未必如是，若紅樓夢中以座次定尊卑，外孫女林黛玉尊於內孫三春則是一例。此皆因家族結構而致，謂之外孫或外孫女當屬妻家，非屬夫家也，故禮數殊矣。外祖父母與外孫/外孫女之間，視若[MASK]。
門當戶對之訂婚男女，其關係多由家族所定。其婚姻，非止兩人之結合，亦兩家以聯姻相合也。故其關係，或受家族、社會地位、財富等之影響。于訂婚之前，彼此交往不多，甚者未嘗謀面，然皆需遵家族與社會之規定，成合卺之禮。門當戶對之訂婚男女之間，視若[MASK]。
私奔者，乃背禮叛教所以追情求愛也。常語以爲聘妻奔妾，然或以一見傾心欲早遂佳期，或以門戶不當而父母弗允，或以私情而拋其家室，不顧雙親兒女，終於淫奔者，以其愛戀之深，不可自抑也。然則負罵名，走他鄉，前途何卜，亦難以預知也。私奔男女之間，視若[MASK]。
同科舉人之間，競爭與互助兼有之也。科舉，士進之途也，遂引天下讀書人埋頭于科舉之書。然進士之途窄矣，應試者多而中試者寡，其得高中以啓顯宦之階者則尤寡也。故于科考之時為競爭對手，然於考試之外，或可相學互助。考中者，若無素時芥蒂，咸可共相交友，以廣交際。同科舉人之間，視若[MASK]。
同門師兄弟之間存恭謹相敬之情、患難相濟之意。其同拜一師，共得其教，故同門之情宜深矣。彼其有同門之敬助，攜手共進。若無有利祿貪欲之心，則同門師兄弟之間，充盈友愛之情，必也。同門師兄弟之間，視若[MASK]。
同校學生之間，友情與競爭兼有之也。彼學於同一學校，有同窗共硯之情。然非獨限於共學之時矣，待卒業及從業後，亦可成通力合作之事。同校學生之間，視若[MASK]。
山長者，書院衆師之長，亦書院之主管也；講席，書院所延聘之教師也。書院之治，向以寬而有別於官學也。官學之治，以屬官府而有等級高下之判。書院則否，以山長之道德文章為維繫也，以地方劃撥之田地房舍為生養也，是以山長之與講席，一講席之首座耳，志同則合，志異則散，山長之管書院者，攝也，固當共尊書院之規，不以勢相凌，是以寬。然有清之後，書院亦官學化也，非概得以寬一之。學府書院之山長與講席之間，視若[MASK]。
同父同母之子女，為同胞之兄弟姊妹也，此乃血緣至親。同胞兄弟姊妹間多親呢，常勝於非同胞者。同父同母之子女之間，視若[MASK]。
戲班與劇作者之間多合作也。劇作者撰作戲劇劇本，而戲班搬演劇作，以供觀眾欣賞。戲班之人身卑籍賤，然劇作者或為讀書人，位四民之首，甚者有功名焉，以差距懸殊之故，所謂合作者，亦鬆散之形式也。劇作者未必依演出之狀況而作成案頭之曲，戲班之於作品之呈現，亦未必符契原文，其違作者原意而有自行發揮之處者，蓋不勝舉也。戲班與劇作者之間，視若[MASK]。
戲子，上臺演出者也；看官，觀賞表演者也。戲子以其表演技巧取悅看客，博看官捧場，而看官之回應，或於大快人心之處喝采，或於角色含冤負屈之處泣下。高超之技藝固得掌聲口譽，反之則致倒彩譏嘲。因之戲子須重看官之反應，然戲子卑微低賤，看官之於戲子，決於看官自身之態度與修養，借其賤戲子，以之為下等，亦不違世俗之德。戲子與看官之間，視若[MASK]。
音樂曲藝人，以賞心悅耳之音求生計者也；聽眾，品賞其音樂曲藝者也。音樂曲藝人以其曲藝之才悅聽眾之耳，聽眾則據藝人之水準報以讚譽財物也。要之，藝人須以聽眾之反應為重，然曲藝人恆処賤籍，故與聽眾或不對等也。音樂曲藝人與聽眾之間，視若[MASK]。
祖孫之間尊卑長幼宜井然有序。祖父母位高於父母，是以孫子女之於祖父母，尤須以禮敬重孝順之，以終其天年，是亦儒家倫理之不可或缺者也。祖孫之間，視若[MASK]。
大夫，醫者之敬稱也。古之良大夫也，以扁鵲華佗之資，行救死扶傷之舉。病者若知曉大夫之醫術兼信之，則病者得瘳而醫者受譽，然則病者之與醫者，亦隨醫者口碑之優劣、人品之高下，與夫病者病情之變化、性格之差異而有別。大夫與病者之間，視若[MASK]。
姨父姨母與侄子侄女之間存親戚之情也。姨父母以其長者慈顧幼小，幼者敬其長者，此為華夏家庭親情倫理之恆常。姨父姨母與侄子侄女之間，視若[MASK]。
行俠仗義者，救受助者於水火災厄之中。仗其勇力，憑其志氣，赴人之困頓，軌俠之道義。至於受助者，則當銜環結草以報其恩也，是俠氣之所傳，而仁義有所弘也，夫緩人之所急，脫人之所危，曷可少也。行俠仗義者與受助者之間，視若[MASK]。
妓女者，誤落風塵，陷於倡家，有姿色者賓客如市而衰老者落拓餘生。嫖客以錢財之豐厚，走馬章台，縱其情欲也。然二者之間，或漸生情愫，以成好合者，往往有之，然沉箱剃髮之悲，蓋尤其多也。狎妓違君子德風之誨，悖於人倫常理，為世之所誅責。然歷代官家律令以存秦樓楚館為慣例，《管子》發其端也。嫖客與妓女之間，視若[MASK]。
掌櫃者，受店主所托，掌日常經營之事宜，凡貨物之進出、價格之定立、賬目之記錄諸類者皆須過問。掌櫃當不負店主所托之責，店主則當行察看之勸，以驗其實績。掌櫃與店主之間，視若[MASK]。
夥計與掌櫃之間，上下級也。夥計，掌櫃之下屬也，掌日常營業之細事，凡接待賓客、售賣商品、搬運貨物之類也。掌櫃行指導管理之勸，而夥計聽其所命。掌櫃與夥計之間，視若[MASK]。
捐助者，施以財物之助，不苛求彼之回報；受惠者，受其所助而當銜環結草，以報其恩德也。仁愛互助之義在其中矣。捐助者與受惠者之間，視若[MASK]。
將領與士兵之間，上下級也。將領之帶兵也，其高明者在於寬嚴並濟，既嚴於治軍，又時彰仁愛兵卒之美德行，以兵為子。然軍令如山，故士兵須惟命是聽。此則軍隊令行禁止之法也。將領與士兵之間，視若[MASK]。
考官之與考生，主試與被試者也。考官評考生之學識才能，而考生須受考官之評鑒。此乃科舉之制公正之途。及考畢，中試者與考官可立師生之誼以擴交際，季世則爲結党之一端也。考官與考生之間，視若[MASK]。
家長敬重信任其子女之師也，是以教育之任托之。師長傳道受業解惑，以誨其子弟。總言之，師長位高權重，掌教學之法諸多事宜，故家長須聽而從之。彼此或以嚴父之姿共擔子弟教育之責。師長與家長之間，視若[MASK]。
同鄉之間往來密切，彼此相助，共解困厄。同鄉之間，同飲一鄉之水，同言一方之音，風土人情共相習知，故他鄉之逢，倍感親切。同鄉之間，視若[MASK]。

鄰里相處之道，可奠鄉里秩序之基。鄰里者，共助、共用、共慶，其要在乎協同互敬，講信修睦，可築鄉里之大同。結姻親、共耕織、連什伍，皆可固鄰里。鄰裡之間，視若[MASK]。
相與出行者，同途之際，經歷相同，利益相干而目的相通也。故可相持互助，以應行途之變。同遊關係之要，在諸同心同德，共克困艱。相與出行者之間，視若[MASK]。
從事買賣者，賣方或以物售之，或以役供之，買方則以貨貝易之。販賣貿買，需重信諾，禁詐紿。賣方所供務必價合質優，買方所償務必踐以約。買者與賣者之間，視若[MASK]。
所謂行人，今之路人也，目有所接而言行不必交，以無深交之所需也。或逢於茶樓酒肆，或見於街巷坊裡，非有際會因緣，相交不過泛泛而已。行人之交多無深交厚誼可溯，然疏而有禮，遠而存敬。行人之間，視若[MASK]。
狐朋狗友，品行不檢而相偕作樂取悅心欲者也，所好皆賭博、酗飲、狎妓之陋習。狐朋狗友之交，觥籌交錯、宴酣之樂顯於外，而犬馬聲色、熏心色欲隱其中也。狐朋狗黨之間，視若[MASK]。
泛泛之友，可為同好，共論琴棋，共試酒茶，然多止於淺交。所謂淺交者，非親非疏，若敬若重，不甘于醴，亦非純淡如水也，以未深交之故也。泛泛之交之間，視若[MASK]。
故舊者，情誼深遠之友也。故舊之友多共曆往事種種，然溫不增華，寒不改葉，能四時而不衰，歷險夷而仍固，相輔相助，情堅若金。故舊之間，視若[MASK]。
摯友者，無血緣之親，然勝乎同產，雖貧富貴賤、生死離別不能阻隔之。摯友相交，以拳拳之心同攜手、共患難，實無價之友誼也。摯友之間，視若[MASK]。
友誼之至境是謂知己。其情之深厚，遠勝泛泛相交，亦相異於親子牽絆，如奏高山流水于知音也，意動即神會，勝卻言語無數。互為知己者，彼之喜怒哀樂皆可歷歷於己心，至情至性，合若符契，而相敬之以禮；若得一知己，遑論肝膽相照，雖九死其猶未悔。友誼之至境，不過是也。知己之間，視若[MASK]。
乞者與行者，多遇於市肆。乞者所欲者惟行者之施，行者之施亦可彰己憐憫之心。然二者相遇，行者多無所施，乞者或無所得，以不必施故也。乞丐與行人之間，視若[MASK]。
新故官吏之閒，權力交接之關係也。去者有升、謫、免、致仕之別，而新任者，生疏于此間府衙事務，故舊任有授新任以經驗故事之責。然則離任者或以親近者安排新任左右，雖去任而威信存，且交接之際，多涉賦稅度支之核查、檔案文書之清點，案件審理之清白，田地戶口之數目，是以輕則生隙，重則黨伐。新故吏之間，視若[MASK]。
獄卒之于囚犯，有羈押之權，囚犯受制于獄卒，受監守之限制。獄卒待囚犯何如，視囚犯家族之貴賤、案情判罰之輕重，及親友打點之多少而各異也。若利益相合，或義氣相投，獄卒囚犯亦可結友，然為獄卒者疾言厲色、受其暴虐者多為常態。獄卒與囚犯之間，視若[MASK]。
告與被告，皆寄之律法以為己申訴辯白，而互為對立也。告劾者所求，伸曲理枉，以示法網恢恢；被告者所求，自證清白，以求洗冤昭雪。告與被告之辯，實關乎法治完備公正之有實否。告劾者與被告者之間，視若[MASK]。
妻妾之間多明暗糾葛。妻者，主内也，總理治家教子之務。妾者，位卑于妻，多以存續香火，姿顏姣好之由納之。妻妾相處，或扶持相依，或勾心鬥角。《毛詩序》曰：“《關雎》樂得淑女以配君子，憂在進賢，不淫其色。”盡言正妻納妾之責，妻妾相處之道。妻妾之間，視若[MASK]。
妻與外婦之間，相視若讎仇。外婦者，未娶而旁通也，無婚姻之名。外婦若有子，易致後宅不寧，亂尊卑之別，生分財之釁，是故妻與外婦多生齟齬。妻與外婦之間，視若[MASK]。
夫暗合於外婦，苟且之舉也。二者無婚姻之名，為世所不齒。暗合者，或生相依相濡之情，亦或僅尋一夕貪歡。夫與外婦之間，視若[MASK]。
遠親者，有血緣之絆，無近鄰之切，往來問候多訴諸婚喪嫁娶節氣，寄乎禮法倫常，以厚親戚之情。然澆薄之世，如涉祖業田產之爭，則雖遠親亦或生齟齬。遠親之間，視若[MASK]。
子婿之於岳家，理應互敬互賴，然岳家垂青與否，多決於子婿之功名、族望。除入贅而改姓易族者，翁婿雖名為父子，實各異家，其情弗如同簷之婆媳遠甚，遑論血緣之親。岳家與子婿之間，視若[MASK]。
同袍之誼，多喻軍旅士伍心心相惜。士卒征戰於沙場，同浴血汗、共赴國難，皆懷身先致死、盡忠報國之念。詩曰：豈曰無衣，與子同袍。是以同袍之親，勝似兄弟。同袍之間，視若[MASK]。
官民之間，上下領屬之關係也。為官之道，必除害興利，善度民力，正風立綱；為民之要，必遵紀守法，立身行道。官民相處亦如父子，為人父則慈，為人子則孝，為人上則明，為人下則聖，父慈子孝，上明下聖，治之紀也。官民之間，視若[MASK]。
結黨而敵對者，始於小人之同利，及其見利則爭先，或利盡而交疏，乃反相賊害。結黨者之利異，多為政見、觀念相抵，至成水火之勢。為求己利，雖其親戚兄弟不保也。敵對黨派之間，視若[MASK]。
同盟即志同道合者。君子與君子以同道為朋，共守道義，行忠信，惜名節。是故同盟者得以守望相助，進退如一，莫逆於心。同盟黨派之間，視若[MASK]。
保人者，受託于雙方顧主，牽繫買賣關係，以局外之身處理其間事務者也。顧主雙方多聘保人以求交易之公正，保人亦從中牟利。保人之制，早至魏晉隋唐已有所載，古商貿制度之完善據此可窺一二。保人與顧主之間，視若[MASK]。
所謂忠臣，效忠于社稷者也，以鞠躬盡瘁、死而後已為己任，多為世之表率，歷代稱頌不絕。所謂逆賊，離君叛國者也，陷社稷於累卵之危、倒懸之急，世人為之不齒。忠臣與逆賊之間，視若[MASK]。
主客之交，以互敬互重為本。為人主者，待人接物需完備周致，以求賓至如歸；為賓客者，亦需禮尚往來，以示謝忱。古之人倫禮制，亦見於主客相交之道也。主人與賓客之間，視若[MASK]。
主奴者，主人為主而女婢為從也。主人有令，奴必應之，不可不從，以其必終於主人故也。奴之衣食起居，身家性命，全仰主意。主人和善體恤，則奴亦可豐足；主慳吝刻薄，則奴亦常縈困頓。然奴之私忠於其主也，不必係於主之慈暴，以世論其忠若犬故也。主奴之間，視若[MASK]。
乳母之與嬰孩之家長，僱傭關係者也。家長或以嬌弱，或以矜貴，或以少乳，僱乳母以照料之。乳母當供乳於彼嬰幼，事其起居，乃或至教導培育。二者既系於僱傭，則信立為本而求職盡也。家長用人不疑，乳母方不墮其職也。乳母與家長之間，視若[MASK]。
乳母之于嬰幼，保育者也。乳母非僅哺之以乳，且兼料其起居，助其成長，與其蒙學。長此以往，乳母或親愛嬰幼，嬰幼亦依戀乳母，此人情所致，本非乳母之分也。及長，嬰幼雖有生母，于禮當母事之，然愛信乳母，厚此而薄彼，亦時有之。雖然，若依通例，嬰幼年齒既長，無需哺乳，乳母之分即盡。更有甚者，就此別過，鮮復往來矣。乳母與嬰幼之間，視若[MASK]。
凡職官者，常設正副。正者，統也。凡執掌決策，籌謀號令，皆出於正者。副者，輔也。或可決策，然猶為行正者之令耳。正副職官，或勾心鬥角，傾軋掣肘；或相交融洽，並力同心。二者相輔相成，乃自然之理，然彼此相爭，亦時有之。正職與副職之間，視若[MASK]。
教首者，亦曰教主，一教之領袖也，享至高威權，眾人視之如神聖。教徒者，此教之信眾也。尊奉教首，篤信之，敬仰之，無敢有違。凡教之規，皆當嚴守；凡本教之義，教首之令，皆應踐行。由此可觀古時宗教神權之廣大威嚴，與夫信徒心靈之精誠純粹也。教首與教徒之間，視若[MASK]。
一家一族，必有其祖。先祖後裔，分支散葉，世代相延，此乃家族形式之基本樣貌。祖為一族之源，綿綿瓜瓞，延而至今，其開創之始，嘉行善德，當銘於子孫，賡續不絕。子子孫孫需尊奉之，稱頌之，祠廟之，祭享之，且以顯祖榮宗為務，不可玷污門楣，蒙羞祖上。重祖以尚孝，古來如此。祖先與後代之間，視若[MASK]。
保長坊長者，鄉裡街坊一方之長也，以平治鄉裡街坊之序，協官府理此地之事，上傳下達於鄉間坊間為責。居鄉裡街坊者，稱居民。居民需從保長，遵鄉規，然後可自主而為。此則城外之鄉裡，城内之街坊，其自轄之法也。保長與居民之間，視若[MASK]。
遠房表親，雖非同胞，血緣略淺，然既系一族，兄弟姊妹之禮，仍需具備，並擔修睦之責，盡扶持之義。蓋開枝散葉，本自同宗，血濃於水，情繫其中，遠方表親，亦不可輕疏也。遠房表親之間，視若[MASK]。
君臣之間，界限分明。君者，一國之主；臣者，輔君以治國也。君可行賞罰於臣，臣當履忠誠於君。君君，臣臣，各從其分，然孟子曰：“君之視臣如手足；則臣視君如腹心；君之視臣如犬馬，則臣視君如國人；君之視臣如土芥，則臣視君如寇讎。”是以君愛臣，則臣親君而易忠，反之則心離而人散，然儒者所謂臣之忠，忠乎社稷天下，非一人一姓也，而鼎革之節，革命之時，何謂稷天下，何謂一人一姓，人多混淆之，而一人一姓多樂其混淆也。由此觀之，君臣之間，錯綜複雜，一言難盡。君臣之義，乃上下之權力關係，亦涉個人與家國集體之關係也。君臣之間，視若[MASK]。
債主與負債者，二者交通，繫於財幣。債務既成，負債者需依契約按時償之，逾期未償，債主可責之。此二者一關乎責權，二關乎財幣也。債主與負債者之間，視若[MASK]。
親家者，姻親是也，為夫妻兩家父母之互稱。親家為同等之親戚，亦關世故人情。若夫婦敦睦，則親家亦諧，鮮有齟齬。親家之間，視若[MASK]。
訟師之與司法者，因其職而相交也。事主有案，託於訟師，代寫文書，申訴有司，而司法者任於官府，審判其案。二者因本職而協作，並行業務於律法之事也。然地方司法，皆委縣令，多起於科舉，熟於治經，疏於律令，訟師與縣吏或沆瀣一氣，操縱案判，則蔽矣。訟師與司法者之間，視若[MASK]。
訟師之於屬者，代理關係也。訟師以代撰訴狀為務，然亦可因之而受屬者之托，代其行訟。此二者一關乎責權，二關乎立信與代理也。訟師與屬者之間，視若[MASK]。
捕快者，地方官府之差役也，以捉賊、治保為務。百姓為全身護財計，仰賴捕快；而捕快或濫權恣肆，百姓見而生畏。是以捕快百姓之間，關係微妙，一言難蔽百世之實。捕快與百姓之間，視若[MASK]。
疑犯捕快，彼此對立。捕快之務，緝拿疑犯，而疑犯聞之，必逋逃藏匿，如鼠畏貓也。二者水火難容，矛盾多生。疑犯與捕快之間，視若[MASK]。
罪犯之於人質，強之以力而脅其性命者也。犯人作奸犯科，將陷囹圄，恐牢獄之災，或挾人質以要官府。人質遭其挾而性命堪憂，以無可自主，常聽命于罪犯。罪犯與人質之間，視若[MASK]。
罪犯所害之人，若有親眷，則稱苦主。苦主與罪犯為敵，視之為仇讎，冀官府緝捕，使其就法。或思血親之仇，不共戴天，則不俟官府，而有私報之也。罪犯與苦主之間，視若[MASK]。
罪犯觸罪，或為旁人所觀。旁人既觀，則或有紛紛議論，批評褒貶。輿論所加，則罪犯聲名地位，亦隨之而更。是以旁人之論，或可左右決獄。而保甲之制，儒家之教，亦或使旁人作證，轉為證人也。罪犯與旁人之間，視若[MASK]。
盜賊失主，彼此對立。盜賊之行，本系非法，謀竊失主，損其財物。依律，賊當償其失，並伏法受罰。盜賊與失主之間，視若[MASK]。
罪犯與受害者，彼此對立。罪犯以非法加害於人，傷其身心。依律，賊當伏法受罰，以償其所害。罪犯與受害者之間，視若[MASK]。
司法者與監察者，互相監督，彼此牽掣者也。司法者以審案為務，昭法之威，執法以正。監察者則督其行事或查其已行，以防其私弊貪腐，使司法必正也。司法者與監察者之間，視若[MASK]。
罪犯同黨者，共犯是也。其所求所行，皆系非法，而三五聚夥，同籌共謀，一朝舉事，乃咸觸罪。依律，犯罪同黨未可消罪，以其明知共犯，或增其罪咎。罪犯同黨之間，視若[MASK]。
賭徒之間，彼此相爭者也。其好博嗜賭，日以鬥雞走馬，喝雉呼盧，投注押寶為事，至於一擲千金，妄希橫富。故彼此爭財奪利，甚為激劇，不免舞弊詐欺，乃至身體相鬥者。厤朝之律法，以賭禁為常，故賭徒之間，世人皆視之為歪門邪道也。賭徒之間，視若[MASK]。
文人與閱者，以文之賞識相交通者也。詩文曲賦，文人所作，常寓以其道其情，因傳其文而載其道也。閱者覽之，可明其道而體其情。夫閱者有感，或建言于文人，使其更改；而流播之廣狹，亦繫於後來之閱者。然限於古之實際，二者不得直接交通，故以單向為多。尋常閱者，難比文人之博觀群覽，不可左右其意。雖然，猶有閱者或與文人相厚，或業相關之業，或知音於後世，因而評論之，紹介之，出版之，則可左右文人之書寫，甚或筆削增潤其原文，而動搖世俗之喜好也。文人與閱者之間，視若[MASK]。
文人多為士人之屬，論者亦品評之士。二者之間，實可相互磋磨學問，評鷙詩文者也。文人作詩文曲賦，而論者品藻之，其建言獻意，雖抒己之見，亦或左右文人之書寫也。於是論者作評，而文人參酌，以修色其作，推敲之定，一字之師，皆此類也。觀古之文俗世情，論者之于文人，抑揚者也。夫論者所尚，則以詩品詞話、文論筆談附益其作，播其芳名，俾傳之百世而其聲益顯，其文益高。反之，亦有詩文曲賦，論者毀之，因聲名不顯，浸微浸消者也。文人與論者之間，視若[MASK]。
男女曖昧之事，悖於人倫，是以隱於心而不擅發於外。其或發於外者，亦以含蓄之言，傳微妙之情，假落紅秋葉之詩，托香囊繡帕之物，暗致其情，不令外人見也，多是之類也。曖昧者之間，彼此[MASK]。
暗戀者，古語或謂單相思。男女之間，礙于父母之命，媒妁之言，婚姻之有定也，於是己固思慕彼而不敢以私意白，彼未知而己切思之，求之不得，其情之至者，所謂“寤寐思服，輾轉反側”是也。其恪于禮者，常以春蠶絲盡、桃花依舊之喻，暗寄其心而不外傳，亦或以暗中護助，不令其有艱困愁苦，而其稍逾制者，則或致佩飾之物也。古之暗戀者，多止乎此，至若季世綱常已墮，男女忽於大防，暗戀轉直，單思為雙，則奔者難禁。暗戀者與被暗戀者之間，彼此[MASK]。
報案者之于受害者也，或同系一人，或其鄰裡親朋之知情者也。自秦法以降，遞有閭閻連坐之策，凡知情不舉者，按律當坐，王安石所目保甲法，即是也。然世有升降，國有治亂，保甲連坐之策，可行乎令行禁止之時，而文恬武嬉之季，多具文視之耳。且古時刑偵之術寡而限期破案之律在，案犯易脫幹係而有司則損利祿，是以報案者亦須證據確鑿，無可指摘，庶免乎官府之糾擾而人財俱困也。又自董子以來，列朝以儒治國，親親相隱之教，風乎百世，是以近親之間，若非大義滅親之舉，概以不報官府為長，而以鄉約族規處置也。報案者與受害者之間，彼此[MASK]。
報案者與罪犯之間多對立之關系。報案者舉罪犯之罪，冀以律法懲之。然報案者或有因擿伏發隱而罹罪犯相脅相報之禍者也。又以保甲連坐之製與大義滅親之理，報案者與罪犯之間亦或為親戚鄰裏，此又非必是兩立之勢也。報案者與罪犯之間，彼此[MASK]。
文選詩集之編者與作者，或因敬重欣賞之情，或為功利實在之用。其功利實在之用著，如著者為高官、長輩、恩師者也，甚者編者或側己文於他人之文，以彰己名也。裁約編選之時，編者常善著者之才華功業。編者亦以其選裁左右讀者之理解。文選詩集之編者與作者，實為古時文人之文化品味、審美觀念、權力關係之鑒鏡也。文選之編者與作者之間，彼此[MASK]。
表兄弟姐妹者，視同近親，關系親近，家族之情亦深也。彼於童稚之時，可共遊學、相長互助，共解所遇之危難。禮，表兄弟姐妹須循一定之禮節，長愛少，少敬長。及漸長，循授受不親之訓，以其為異姓，可通婚姻故也。表兄弟姐妹之間，彼此[MASK]。
庖人之與食客者，為服務被服務之關系也。庖人主烹飪，以甘美之食奉食客，而食客亦須念庖人之生計。故庖人須盡其技以足食客之口，食客亦須慎待庖人所供之物，此亦理之常也。或有庖人專供於食客或主人之家，則曰名廚或私廚，其與食客主人之關系則更甚其他庖人也。庖人與食客之間，彼此[MASK]。
仇敵之間乃對立衝突之關係也。敵者，匹敵也，論其才智，則相儔類，而或以利益之不均、或以地位之不匹、或以權力之不及、或以忠誠之不貞，諸此之屬，心生怨望而欲戕害以快其心者，仇敵之事也。然則，仇敵既以相噬為常，亦以其相匹，而或生相惜之感，且古時人分等級，同匹儔之人，其未為仇敵之初，或有通家之好，秦晉之交而同窗之誼也，是以古之仇敵，視今日為複雜也。故經史詩賦之中，感概仇敵之才智氣節者，亦不知凡幾也。仇敵之間，彼此[MASK]。
施恩者與受恩者為恩義與感恩之關係。施恩者之助受恩者也，或以善行，或以援手，受恩者遂感念其德，雖滴水之恩，木瓜之贈，亦矢報以湧泉瓊瑤也。古以'知恩圖報'為德之大者也。施恩者與受恩者之間，彼此[MASK]。
青梅竹馬，即為男女自幼同遊嬉戲，心生情愫者也。其情純真深沉，或終為伉儷，或為知己。古時文人墨客之述此情者，至純至美，感人心脾。青梅竹馬之間，彼此[MASK]。
情敵者，二三人傾慕同一對象，遂相競爭。此關係中，有敵意、嫉妬、競爭至於殺心之複雜心緒，然亦或有互尊呼諒者。經史詩賦之中，論及情敵，常有激烈戲謔之矛盾，或高雅而囿於禮法，或直率而流於粗鄙。情敵之間，彼此[MASK]。
天人之間，乃天地人三才之並立關系，人宜順天地，而與萬物為一。儒道皆謂人當敬天地而順之，於是乎則和也。欲和天人，需通天意，欲通天意，則在貫三才之王者，以儒家正典之論，王者得位聖賢之大號，非權勢之稱也，是以為古代知識階層與君主權力間之製衡也。天人之間，彼此[MASK]。
人神之間以信仰敬畏為維繫，其方式不離祭祀、祈禱以通達於神靈也，其指歸在乎求得神靈庇佑，解其大惑，脫其苦厄，堅其心志，導其前路也。今之視古，則謂古之信神，原乎科技落後，而驚懼敬畏于自然未知之力量也。然商周以降，中華之地，人以配天，民為神主之論，敬鬼以遠之教，人能弘道之言，天命從德之誡，經籍之載，三教之說，鹹崇人之踐行而斥虛妄之求神也。然則子雖不言怪力亂神，而人之不齊，一致百慮，可導而不可壅，是以君子明辨天理，不惑神鬼，而不責民間之求神問卜以行善避災也。人神之間，彼此[MASK]。
泛泛之交，乃交情淺薄之普通關係也。於此關係，彼此不通心意，交遊往來，相待以禮而已。泛泛之交，或可謂之朋友，然為關係最疏者也。泛泛之交之間，彼此[MASK]。
店主與顧客，為買賣交易之雙方也。店主供貨品服務於顧客，顧客以財貨償之。店主須竭其誠以應顧客之需，顧客亦需尊店主之恭敬服務于我也。所謂“買賣不成仁義在”，古時買賣之道，理不逾此。店主與顧客之間，彼此[MASK]。
官場之尊卑上下，不可逾距。上之於下，等級之中，所差愈多，威勢愈強。是以官員之間，忠敬為首，然忠敬者，忠於所守也，非忠於上司某甲也。上之於下，亦有訓導保全之義，此即古之尊卑有序、和諧中正之道也。然世閒多難行也。官場之上下級之間，彼此[MASK]。
買賣之夥伴，所共求止於利而已，緣此須相信相助，共分其利。其間信與平最為重，買賣之夥伴須以誠交易，以平分利。彼此亦須行為相協，言語相洽，以求買賣之順遂。買賣之夥伴之間，彼此[MASK]。
買賣之競爭對手，以欲求多利，欲天下求購者多求於己而俾天下財富多歸於己，於是乎有對手生焉。然生財亦當有道，故相競爭者雖有相爭之欲而求勝於對方，亦皆須守信持中，不得狡求他人之利。要之，亦有尊重也。買賣之競爭對手之間，彼此[MASK]。
宗教師徒，在於信仰之傳續繼承。師者，教訓徒弟，徒者，尊師重道，忠於師命。其間尊與忠為最重，徒須尊師忠命，師須護持教徒。宗教師徒之間，彼此[MASK]。
百工之師父與學徒，在於技藝之傳承。傳技之時，師者須教導訓誡其徒，徒者須尊敬愛重其師。其間尊與忠為最重，徒須尊師忠命，師須護持教徒。師傅與學徒之間，彼此[MASK]。
古之掌櫃與客人，因買賣交易為緣。掌櫃者經營其店。客人者消費之人也，求店主之所供。掌櫃須供客人所需，以求信與利。客人亦須敬重掌櫃，不得違其買賣之道。掌櫃與客人之間，彼此[MASK]。
古之首領與反賊，以勢不兩雄為常。首領者，為國之首領，反賊者，為國之叛逆。首領須守其威勢與現有之秩序，反賊則欲反叛其威勢與現有之秩序。首領與反賊之間，彼此[MASK]。
叔侄為血親。叔者為父之弟，侄者為兄之子。叔有教育侄之責，侄須愛敬叔，然亦須視其父母之存亡與學識尊卑論叔撫育之任也。叔侄關係於家族之中為極重要之關係。叔侄之間，彼此[MASK]。

雙胞胎因其母一胎同產之同胞，其情於血親手足之中為最近也。同孕母腹，同生一時，同長一處，其形其態其跡在成人之前尤多為相似，故其未冠笄之時，蓋情最深厚，或施及平生。雙胞胎之間，彼此[MASK]。
於政治之中，兩方之會晤多因權與利之爭鬥也。多以其政治與國家所屬不同，冀會晤以求成結盟。兩方須守盟會之理，於守自身之利為上為底，亦宜慮對方之利，以成盟約也。政治談判中對立之雙方之間，彼此[MASK]。
堂兄弟姐妹為親戚，然其親不過於同胞兄弟姐妹。於家族之中，堂兄弟姐妹可與嫡子女同長共學，亦同為長者所愛，然於家財分配，若非嫡子女亡故出繼，則不得分其家財，然亦多有倚勢強奪家財之事。論及尊卑，堂兄弟姐妹之長者亦為家族所重。堂兄弟姐妹之間，彼此[MASK]。
古者以父系別家族，故同父異母與同母異父之子女之所受對待全然不同。若子女為同父異母，則其於家族之中尊卑貴賤則從母之所處為父之發妻、續弦、妾之等而不同，及其母之存亡與母家之勢而定，然其爲一家之人，則無疑也。若子女為同母異父，則多因父之續娶他婦，其母之前夫子女多為後嫁之家族異姓視之，其被賤待，亦其常也，然亦須視其後父家之心與其母家之勢。同父異母與同母異父之子女之間，彼此[MASK]。
繼子女之間，雖為親戚，但彼此犬牙交錯，一言難磬。繼母與繼父之子女之關系亦相去萬裏。古者，父親多主家族，父親續娶，繼母亦為繼子之母也。然若母親改醮，繼子則從母而入繼父家，其家族關系亦全然改換也。若父母於其前夫前妻亡故後另結婚姻，則或因繼父繼母之愛而另生齟齬。家產之分配，若其母為繼母，則繼子女（若其女子未嫁）以律法可得所應之家產。若其父為繼父，則繼子女非繼父及家族所允，以律法不得受家產。繼子女之間，彼此[MASK]。
古之為官，同僚之間以官位相近，同朝合堂，共謀於事。然或因其職所守相近，未免於相爭，而生齟齬者亦多有之。同僚之間尊卑之序則定以官位高低、資望長短。同僚之間，彼此[MASK]。
庠序之間，同窗之間以求學問知識為共識，相助於學，共進於道。然因修業之優劣，成績之高下，而生齟齬者亦有之。同窗之間，常為對等之交，然亦可守尊卑之禮而以年齒為序，此多為交往之禮便耳。同窗之間，彼此[MASK]。
所謂搭訕者，意在親近被搭訕者，以其欲與被搭訕者交好而有所圖也。搭訕者之於被搭訕者，或欲作綈袍之義，或欲結琴瑟之好，或欲為買賣之宜。二者之關系，主動與被動並存，不確與不穩共生。然搭訕者多有所求，故世貶其行，經史詩賦亦多譏之。搭訕者與被搭訕者之間，彼此[MASK]。
施害者乃刑案中為暴力罪行者也。受害者乃因施害者之暴而罹身體乃至於性命之禍也。施害者與受害者，或為兩立，或為抵牾。經史典籍錄此案件，多因其所涉或為欺公罔法，或為其案情之重大曲折，蒙冤者終得昭雪也。然亦多為尋常案件之受害與被害關系。刑案中之施害者與受害者之間，彼此[MASK]。
古之旁觀者乃睹罪案而無與者也。或為偶然，或特持中而觀也。旁觀者之與受害者，論其行多有意疏遠之，跡其心則漠然或哀憫，然則旁觀者亦有因保甲連坐製度而或肯作證者。刑案中之受害者與旁觀者之間，彼此[MASK]。
屋主者，有屋貰於人者也。承租者，僦屋於人者也。屋主與承租者，常為權利義務之交易，或有經濟利益之抵牾，然得租賃者，亦彼此利之中和也。屋主與承租者之間，彼此[MASK]。
夫婦之關係，雖為平等而以男性為主導，家中事務由男性裁決，女子應遵奉，然亦視母家地位及其實力。夫婦之間，尤重忠誠尊重，互為匹敵，互相照顧，守家族和睦也。夫婦之間，彼此[MASK]。
夥計與顧客之關係以商貿為基，夥計須敬、誠、勤、恭，供以良品及服務。顧客則於良品與服務，受之以禮，成兩全之美事。夥計與顧客之間，彼此[MASK]。
父母與子女之閒，以孝為要，從其道，分其憂，解其難。爲其子者須事親以終其天年，爲其女者，既嫁亦省親有定期，且盡力照拂有難者，不以有歸為辭也。父母則應愛憐其子、育其成才，仿三遷而擇佳處也。父母與子女之間，彼此[MASK]。
義父母與義子女之關係，亦以孝為要。養子須事長以終其天年，養女亦受為人女之道。義父母則應愛憐有度、育子成才。義父母與義子女之間，彼此[MASK]。
翁媳若父女，故以孝、敬、恭系之，然以非親之故，兼有男女之防，媳固當孝翁視親，亦從於令而不可逾于矩。翁當護其周全而不可密邇。要約以禮，不忘授受不親之訓也。公公與兒媳之間，彼此[MASK]。
婆媳乃家中上下級關係也。婆為長為尊，有督導教育之責，媳則尊之孝之，有若母子然。婦歸夫家，夫妻之外，婆媳為重大關係也。婆婆與兒媳之間，彼此[MASK]。
主人與家丁為主僕之關係。主人發號施令，家丁則從令而行，稟其忠也。此關係乃權力與經濟之關係之象徵，主人，富貴者也；家丁，卑賤者也，以此業為生。家丁亦有以契約而世代為奴，則主僕之分益固也。主人與家丁之間，彼此[MASK]。
地主與佃農之間，乃經濟之關係。地主佔田地，佃農租田以謀生。此關係為經濟依賴關係，地主因佃農而得益，佃農傍田地以得生。地主與佃農之間，彼此[MASK]。
店主與夥計乃勞動關係。店主以市肆營生，募選數夥計以經營，夥計從其令而行。此關係乃經濟與勞動之關係，店主因夥計而得益，夥計不辭辛苦而獲薪俸。店主與夥計之間，彼此[MASK]。
官員之與行賄者，權錢之交易也。官員有權，行賄者有金，進賄金以鬻權取利也。此雖違法之事，然世非罕見，甚或相沿成習而得以為默規，異代不鮮也。官員與行賄者之間，彼此[MASK]。
狀元、榜眼、探花，為科舉殿試之冠、亞、季稱謂也。考生之間，競爭、合作，以求仕進，固彼此為競爭對手。於科舉中，狀元為首，榜眼、探花次之。狀元與榜眼與探花之間，彼此[MASK]。
綠林好漢首領之與屬下（嘍羅），領導者與被領導者也。首領常以其勇武、智謀得天下，而為領導者。兩者之間，亦視將兵之關係，故於首領命令，屬下（嘍羅）須從而為之，等軍法也。綠林好漢之首領與屬下之間，彼此[MASK]。
繼父母與子女，乃法定親子關係也。或以原配父母猝然離世，或為離鸞別鳳，繼父母入其家庭，擔養育之責，子女須敬之、從之。繼子女承業於繼母家庭，禮也，法也；而繼父家庭者則或否也，視繼父及其家族態度而定。繼父母與子女之間，彼此[MASK]。
繼祖父母與繼孫，亦為法定之親子關係也。若父母猝然離世，或為離鸞別鳳，由一方再婚而入他家，則繼父母父母之父母為繼祖父母。繼祖父母有養育之恩澤，子女須孝敬順從之。繼祖父母與繼子孫之關係，視繼子女之與繼父母關係而迥別也，或為同姓則可親似家人，或為異姓而忽視之也。參繼父母-子女條。繼祖父母與繼孫之間，彼此[MASK]。
養父母與子女，緣以養育之恩，而成親子之情。或父母失於養育，或子女棄於街頭，有善人收養，則為養父母。養父母擔養育之責，子女須孝之同其親然。養子女承業，須視養父母及其家族之意，若有爭議，可訴之官府，然蓋罕見也。養父母與子女之間，彼此[MASK]。
古人尤重師生之誼，尊師重道，古之訓也。師者，傳道受業解惑之人，教人以禮以知以識以技。學生尊之、敬之，師者愛之、誨之，古時師生關係以父子關係為本，然孝廉科舉之興，亦俾染利祿之關聯也。師生之間，彼此[MASK]。
家庭（家族）私塾為昔者大家族子弟啟蒙教育之場所也。所聘之家庭私塾教師，或家族之飽學長者，或科場之落第者，或中而未仕者。教童稚以讀書寫字，其常業也，有言傳身教之責，教導其為人之道。故塾師之於弟子，或代族中長者訓誡子弟，或但為教書先生，視教師身份地位或其家族地位而定。家庭私塾教師與學生之間，彼此[MASK]。
小人于後世多目品行卑劣、心胸狹窄、唯利是圖之人。“小人之交”則指此等人之彼此關係也，其以利為本，漠視誠信，唯權謀與爭利而已。小人之交之間，彼此[MASK]。
佛教徒以佛法信仰為紐，慈悲為懷，同修而互助，以求得佛法真諦，共成和諧、平等、互助之關係。然自佛滅以來，教派紛然，利欲之心，恆難寂滅，故其以宗派、僧團、寺廟之異，彼此爭端，歷代恆有。佛教徒之間，彼此[MASK]。
道教徒以修仙教化為要務，無為而治，自然和諧，天地共生，萬物為一，以求長生不老，故道教徒之間，以平和、寬容、尊重為常。然其亦或以宗派、僧團、寺廟之異，而起爭端。道教徒之間，彼此[MASK]。
髮小者，自幼相識之友也，其行跡相似相同，故其交往甚近。兩人之間，可不甚囿於禮法，故率真而坦誠。發小之間，彼此[MASK]。
本地人之與異鄉人，關係複雜。以編戶齊民之故，民重遷徙，是以處於異域，本地人或嚴以防範，或疏以情感。又以方音之差、風俗之別，異鄉人恆倍感孤困。然亦有好客之人，助其在此安居也。本地人與異鄉人之間，彼此[MASK]。
土籍之人與客籍之人之問題，漢季以來，盤根錯節，乞于民清之際，未有終結也。其世居鄉土之地而編戶于官府者，謂之土籍之人；其離鄉背井、人徙居於他鄉而籍未更者，則為客籍之人。二者之異，於編戶齊民之策率有體現。大抵土籍之人地位高於客籍，故土籍之人多主人自視，深有自得之意。然客籍與土籍，雜處一地，或以田土之不均、或以經濟之不等、或以社會地位之不匹，或以稅賦政令之不平，而勢有消長。其間以土地、人口、政治權力諸此之屬而滋生矛盾，然和中寓爭，爭中寓和，幾世之後，二者以共處、合作與通婚之故，兼之戶籍更新，斷客為主之策，二者之異同，日愈消弭，并同土籍，此其常也。然舊之客籍未泯，而新之客籍又生，此又其常也。土籍人士與客籍人士之間，彼此[MASK]。
外祖父母與外孫或外孫女，多倫常親呢之情也。蓋將綱常倫理而觀之，則外祖父母之於外孫或外孫女，或不及外祖父母之於內孫或內孫女親密。然自私心而論，則未必如是，若紅樓夢中以座次定尊卑，外孫女林黛玉尊於內孫三春則是一例。此皆因家族結構而致，謂之外孫或外孫女當屬妻家，非屬夫家也，故禮數殊矣。外祖父母與外孫/外孫女之間，彼此[MASK]。
門當戶對之訂婚男女，其關係多由家族所定。其婚姻，非止兩人之結合，亦兩家以聯姻相合也。故其關係，或受家族、社會地位、財富等之影響。于訂婚之前，彼此交往不多，甚者未嘗謀面，然皆需遵家族與社會之規定，成合卺之禮。門當戶對之訂婚男女之間，彼此[MASK]。
私奔者，乃背禮叛教所以追情求愛也。常語以爲聘妻奔妾，然或以一見傾心欲早遂佳期，或以門戶不當而父母弗允，或以私情而拋其家室，不顧雙親兒女，終於淫奔者，以其愛戀之深，不可自抑也。然則負罵名，走他鄉，前途何卜，亦難以預知也。私奔男女之間，彼此[MASK]。
同科舉人之間，競爭與互助兼有之也。科舉，士進之途也，遂引天下讀書人埋頭于科舉之書。然進士之途窄矣，應試者多而中試者寡，其得高中以啓顯宦之階者則尤寡也。故于科考之時為競爭對手，然於考試之外，或可相學互助。考中者，若無素時芥蒂，咸可共相交友，以廣交際。同科舉人之間，彼此[MASK]。
同門師兄弟之間存恭謹相敬之情、患難相濟之意。其同拜一師，共得其教，故同門之情宜深矣。彼其有同門之敬助，攜手共進。若無有利祿貪欲之心，則同門師兄弟之間，充盈友愛之情，必也。同門師兄弟之間，彼此[MASK]。
同校學生之間，友情與競爭兼有之也。彼學於同一學校，有同窗共硯之情。然非獨限於共學之時矣，待卒業及從業後，亦可成通力合作之事。同校學生之間，彼此[MASK]。
山長者，書院衆師之長，亦書院之主管也；講席，書院所延聘之教師也。書院之治，向以寬而有別於官學也。官學之治，以屬官府而有等級高下之判。書院則否，以山長之道德文章為維繫也，以地方劃撥之田地房舍為生養也，是以山長之與講席，一講席之首座耳，志同則合，志異則散，山長之管書院者，攝也，固當共尊書院之規，不以勢相凌，是以寬。然有清之後，書院亦官學化也，非概得以寬一之。學府書院之山長與講席之間，彼此[MASK]。
同父同母之子女，為同胞之兄弟姊妹也，此乃血緣至親。同胞兄弟姊妹間多親呢，常勝於非同胞者。同父同母之子女之間，彼此[MASK]。
戲班與劇作者之間多合作也。劇作者撰作戲劇劇本，而戲班搬演劇作，以供觀眾欣賞。戲班之人身卑籍賤，然劇作者或為讀書人，位四民之首，甚者有功名焉，以差距懸殊之故，所謂合作者，亦鬆散之形式也。劇作者未必依演出之狀況而作成案頭之曲，戲班之於作品之呈現，亦未必符契原文，其違作者原意而有自行發揮之處者，蓋不勝舉也。戲班與劇作者之間，彼此[MASK]。
戲子，上臺演出者也；看官，觀賞表演者也。戲子以其表演技巧取悅看客，博看官捧場，而看官之回應，或於大快人心之處喝采，或於角色含冤負屈之處泣下。高超之技藝固得掌聲口譽，反之則致倒彩譏嘲。因之戲子須重看官之反應，然戲子卑微低賤，看官之於戲子，決於看官自身之態度與修養，借其賤戲子，以之為下等，亦不違世俗之德。戲子與看官之間，彼此[MASK]。
音樂曲藝人，以賞心悅耳之音求生計者也；聽眾，品賞其音樂曲藝者也。音樂曲藝人以其曲藝之才悅聽眾之耳，聽眾則據藝人之水準報以讚譽財物也。要之，藝人須以聽眾之反應為重，然曲藝人恆処賤籍，故與聽眾或不對等也。音樂曲藝人與聽眾之間，彼此[MASK]。
祖孫之間尊卑長幼宜井然有序。祖父母位高於父母，是以孫子女之於祖父母，尤須以禮敬重孝順之，以終其天年，是亦儒家倫理之不可或缺者也。祖孫之間，彼此[MASK]。
大夫，醫者之敬稱也。古之良大夫也，以扁鵲華佗之資，行救死扶傷之舉。病者若知曉大夫之醫術兼信之，則病者得瘳而醫者受譽，然則病者之與醫者，亦隨醫者口碑之優劣、人品之高下，與夫病者病情之變化、性格之差異而有別。大夫與病者之間，彼此[MASK]。
姨父姨母與侄子侄女之間存親戚之情也。姨父母以其長者慈顧幼小，幼者敬其長者，此為華夏家庭親情倫理之恆常。姨父姨母與侄子侄女之間，彼此[MASK]。
行俠仗義者，救受助者於水火災厄之中。仗其勇力，憑其志氣，赴人之困頓，軌俠之道義。至於受助者，則當銜環結草以報其恩也，是俠氣之所傳，而仁義有所弘也，夫緩人之所急，脫人之所危，曷可少也。行俠仗義者與受助者之間，彼此[MASK]。
妓女者，誤落風塵，陷於倡家，有姿色者賓客如市而衰老者落拓餘生。嫖客以錢財之豐厚，走馬章台，縱其情欲也。然二者之間，或漸生情愫，以成好合者，往往有之，然沉箱剃髮之悲，蓋尤其多也。狎妓違君子德風之誨，悖於人倫常理，為世之所誅責。然歷代官家律令以存秦樓楚館為慣例，《管子》發其端也。嫖客與妓女之間，彼此[MASK]。
掌櫃者，受店主所托，掌日常經營之事宜，凡貨物之進出、價格之定立、賬目之記錄諸類者皆須過問。掌櫃當不負店主所托之責，店主則當行察看之勸，以驗其實績。掌櫃與店主之間，彼此[MASK]。
夥計與掌櫃之間，上下級也。夥計，掌櫃之下屬也，掌日常營業之細事，凡接待賓客、售賣商品、搬運貨物之類也。掌櫃行指導管理之勸，而夥計聽其所命。掌櫃與夥計之間，彼此[MASK]。
捐助者，施以財物之助，不苛求彼之回報；受惠者，受其所助而當銜環結草，以報其恩德也。仁愛互助之義在其中矣。捐助者與受惠者之間，彼此[MASK]。
將領與士兵之間，上下級也。將領之帶兵也，其高明者在於寬嚴並濟，既嚴於治軍，又時彰仁愛兵卒之美德行，以兵為子。然軍令如山，故士兵須惟命是聽。此則軍隊令行禁止之法也。將領與士兵之間，彼此[MASK]。
考官之與考生，主試與被試者也。考官評考生之學識才能，而考生須受考官之評鑒。此乃科舉之制公正之途。及考畢，中試者與考官可立師生之誼以擴交際，季世則爲結党之一端也。考官與考生之間，彼此[MASK]。
家長敬重信任其子女之師也，是以教育之任托之。師長傳道受業解惑，以誨其子弟。總言之，師長位高權重，掌教學之法諸多事宜，故家長須聽而從之。彼此或以嚴父之姿共擔子弟教育之責。師長與家長之間，彼此[MASK]。
同鄉之間往來密切，彼此相助，共解困厄。同鄉之間，同飲一鄉之水，同言一方之音，風土人情共相習知，故他鄉之逢，倍感親切。同鄉之間，彼此[MASK]。
鄰里相處之道，可奠鄉里秩序之基。鄰里者，共助、共用、共慶，其要在乎協同互敬，講信修睦，可築鄉里之大同。結姻親、共耕織、連什伍，皆可固鄰里。鄰裡之間，彼此[MASK]。
相與出行者，同途之際，經歷相同，利益相干而目的相通也。故可相持互助，以應行途之變。同遊關係之要，在諸同心同德，共克困艱。相與出行者之間，彼此[MASK]。
從事買賣者，賣方或以物售之，或以役供之，買方則以貨貝易之。販賣貿買，需重信諾，禁詐紿。賣方所供務必價合質優，買方所償務必踐以約。買者與賣者之間，彼此[MASK]。
所謂行人，今之路人也，目有所接而言行不必交，以無深交之所需也。或逢於茶樓酒肆，或見於街巷坊裡，非有際會因緣，相交不過泛泛而已。行人之交多無深交厚誼可溯，然疏而有禮，遠而存敬。行人之間，彼此[MASK]。
狐朋狗友，品行不檢而相偕作樂取悅心欲者也，所好皆賭博、酗飲、狎妓之陋習。狐朋狗友之交，觥籌交錯、宴酣之樂顯於外，而犬馬聲色、熏心色欲隱其中也。狐朋狗黨之間，彼此[MASK]。
泛泛之友，可為同好，共論琴棋，共試酒茶，然多止於淺交。所謂淺交者，非親非疏，若敬若重，不甘于醴，亦非純淡如水也，以未深交之故也。泛泛之交之間，彼此[MASK]。
故舊者，情誼深遠之友也。故舊之友多共曆往事種種，然溫不增華，寒不改葉，能四時而不衰，歷險夷而仍固，相輔相助，情堅若金。故舊之間，彼此[MASK]。
摯友者，無血緣之親，然勝乎同產，雖貧富貴賤、生死離別不能阻隔之。摯友相交，以拳拳之心同攜手、共患難，實無價之友誼也。摯友之間，彼此[MASK]。
友誼之至境是謂知己。其情之深厚，遠勝泛泛相交，亦相異於親子牽絆，如奏高山流水于知音也，意動即神會，勝卻言語無數。互為知己者，彼之喜怒哀樂皆可歷歷於己心，至情至性，合若符契，而相敬之以禮；若得一知己，遑論肝膽相照，雖九死其猶未悔。友誼之至境，不過是也。知己之間，彼此[MASK]。
乞者與行者，多遇於市肆。乞者所欲者惟行者之施，行者之施亦可彰己憐憫之心。然二者相遇，行者多無所施，乞者或無所得，以不必施故也。乞丐與行人之間，彼此[MASK]。
新故官吏之閒，權力交接之關係也。去者有升、謫、免、致仕之別，而新任者，生疏于此間府衙事務，故舊任有授新任以經驗故事之責。然則離任者或以親近者安排新任左右，雖去任而威信存，且交接之際，多涉賦稅度支之核查、檔案文書之清點，案件審理之清白，田地戶口之數目，是以輕則生隙，重則黨伐。新故吏之間，彼此[MASK]。
獄卒之于囚犯，有羈押之權，囚犯受制于獄卒，受監守之限制。獄卒待囚犯何如，視囚犯家族之貴賤、案情判罰之輕重，及親友打點之多少而各異也。若利益相合，或義氣相投，獄卒囚犯亦可結友，然為獄卒者疾言厲色、受其暴虐者多為常態。獄卒與囚犯之間，彼此[MASK]。
告與被告，皆寄之律法以為己申訴辯白，而互為對立也。告劾者所求，伸曲理枉，以示法網恢恢；被告者所求，自證清白，以求洗冤昭雪。告與被告之辯，實關乎法治完備公正之有實否。告劾者與被告者之間，彼此[MASK]。
妻妾之間多明暗糾葛。妻者，主内也，總理治家教子之務。妾者，位卑于妻，多以存續香火，姿顏姣好之由納之。妻妾相處，或扶持相依，或勾心鬥角。《毛詩序》曰：“《關雎》樂得淑女以配君子，憂在進賢，不淫其色。”盡言正妻納妾之責，妻妾相處之道。妻妾之間，彼此[MASK]。
妻與外婦之間，相視若讎仇。外婦者，未娶而旁通也，無婚姻之名。外婦若有子，易致後宅不寧，亂尊卑之別，生分財之釁，是故妻與外婦多生齟齬。妻與外婦之間，彼此[MASK]。
夫暗合於外婦，苟且之舉也。二者無婚姻之名，為世所不齒。暗合者，或生相依相濡之情，亦或僅尋一夕貪歡。夫與外婦之間，彼此[MASK]。
遠親者，有血緣之絆，無近鄰之切，往來問候多訴諸婚喪嫁娶節氣，寄乎禮法倫常，以厚親戚之情。然澆薄之世，如涉祖業田產之爭，則雖遠親亦或生齟齬。遠親之間，彼此[MASK]。
子婿之於岳家，理應互敬互賴，然岳家垂青與否，多決於子婿之功名、族望。除入贅而改姓易族者，翁婿雖名為父子，實各異家，其情弗如同簷之婆媳遠甚，遑論血緣之親。岳家與子婿之間，彼此[MASK]。
同袍之誼，多喻軍旅士伍心心相惜。士卒征戰於沙場，同浴血汗、共赴國難，皆懷身先致死、盡忠報國之念。詩曰：豈曰無衣，與子同袍。是以同袍之親，勝似兄弟。同袍之間，彼此[MASK]。

官民之間，上下領屬之關係也。為官之道，必除害興利，善度民力，正風立綱；為民之要，必遵紀守法，立身行道。官民相處亦如父子，為人父則慈，為人子則孝，為人上則明，為人下則聖，父慈子孝，上明下聖，治之紀也。官民之間，彼此[MASK]。
結黨而敵對者，始於小人之同利，及其見利則爭先，或利盡而交疏，乃反相賊害。結黨者之利異，多為政見、觀念相抵，至成水火之勢。為求己利，雖其親戚兄弟不保也。敵對黨派之間，彼此[MASK]。
同盟即志同道合者。君子與君子以同道為朋，共守道義，行忠信，惜名節。是故同盟者得以守望相助，進退如一，莫逆於心。同盟黨派之間，彼此[MASK]。
保人者，受託于雙方顧主，牽繫買賣關係，以局外之身處理其間事務者也。顧主雙方多聘保人以求交易之公正，保人亦從中牟利。保人之制，早至魏晉隋唐已有所載，古商貿制度之完善據此可窺一二。保人與顧主之間，彼此[MASK]。
所謂忠臣，效忠于社稷者也，以鞠躬盡瘁、死而後已為己任，多為世之表率，歷代稱頌不絕。所謂逆賊，離君叛國者也，陷社稷於累卵之危、倒懸之急，世人為之不齒。忠臣與逆賊之間，彼此[MASK]。
主客之交，以互敬互重為本。為人主者，待人接物需完備周致，以求賓至如歸；為賓客者，亦需禮尚往來，以示謝忱。古之人倫禮制，亦見於主客相交之道也。主人與賓客之間，彼此[MASK]。
主奴者，主人為主而女婢為從也。主人有令，奴必應之，不可不從，以其必終於主人故也。奴之衣食起居，身家性命，全仰主意。主人和善體恤，則奴亦可豐足；主慳吝刻薄，則奴亦常縈困頓。然奴之私忠於其主也，不必係於主之慈暴，以世論其忠若犬故也。主奴之間，彼此[MASK]。
乳母之與嬰孩之家長，僱傭關係者也。家長或以嬌弱，或以矜貴，或以少乳，僱乳母以照料之。乳母當供乳於彼嬰幼，事其起居，乃或至教導培育。二者既系於僱傭，則信立為本而求職盡也。家長用人不疑，乳母方不墮其職也。乳母與家長之間，彼此[MASK]。
乳母之于嬰幼，保育者也。乳母非僅哺之以乳，且兼料其起居，助其成長，與其蒙學。長此以往，乳母或親愛嬰幼，嬰幼亦依戀乳母，此人情所致，本非乳母之分也。及長，嬰幼雖有生母，于禮當母事之，然愛信乳母，厚此而薄彼，亦時有之。雖然，若依通例，嬰幼年齒既長，無需哺乳，乳母之分即盡。更有甚者，就此別過，鮮復往來矣。乳母與嬰幼之間，彼此[MASK]。
凡職官者，常設正副。正者，統也。凡執掌決策，籌謀號令，皆出於正者。副者，輔也。或可決策，然猶為行正者之令耳。正副職官，或勾心鬥角，傾軋掣肘；或相交融洽，並力同心。二者相輔相成，乃自然之理，然彼此相爭，亦時有之。正職與副職之間，彼此[MASK]。
教首者，亦曰教主，一教之領袖也，享至高威權，眾人視之如神聖。教徒者，此教之信眾也。尊奉教首，篤信之，敬仰之，無敢有違。凡教之規，皆當嚴守；凡本教之義，教首之令，皆應踐行。由此可觀古時宗教神權之廣大威嚴，與夫信徒心靈之精誠純粹也。教首與教徒之間，彼此[MASK]。
一家一族，必有其祖。先祖後裔，分支散葉，世代相延，此乃家族形式之基本樣貌。祖為一族之源，綿綿瓜瓞，延而至今，其開創之始，嘉行善德，當銘於子孫，賡續不絕。子子孫孫需尊奉之，稱頌之，祠廟之，祭享之，且以顯祖榮宗為務，不可玷污門楣，蒙羞祖上。重祖以尚孝，古來如此。祖先與後代之間，彼此[MASK]。
保長坊長者，鄉裡街坊一方之長也，以平治鄉裡街坊之序，協官府理此地之事，上傳下達於鄉間坊間為責。居鄉裡街坊者，稱居民。居民需從保長，遵鄉規，然後可自主而為。此則城外之鄉裡，城内之街坊，其自轄之法也。保長與居民之間，彼此[MASK]。
遠房表親，雖非同胞，血緣略淺，然既系一族，兄弟姊妹之禮，仍需具備，並擔修睦之責，盡扶持之義。蓋開枝散葉，本自同宗，血濃於水，情繫其中，遠方表親，亦不可輕疏也。遠房表親之間，彼此[MASK]。
君臣之間，界限分明。君者，一國之主；臣者，輔君以治國也。君可行賞罰於臣，臣當履忠誠於君。君君，臣臣，各從其分，然孟子曰：“君之視臣如手足；則臣視君如腹心；君之視臣如犬馬，則臣視君如國人；君之視臣如土芥，則臣視君如寇讎。”是以君愛臣，則臣親君而易忠，反之則心離而人散，然儒者所謂臣之忠，忠乎社稷天下，非一人一姓也，而鼎革之節，革命之時，何謂稷天下，何謂一人一姓，人多混淆之，而一人一姓多樂其混淆也。由此觀之，君臣之間，錯綜複雜，一言難盡。君臣之義，乃上下之權力關係，亦涉個人與家國集體之關係也。君臣之間，彼此[MASK]。
債主與負債者，二者交通，繫於財幣。債務既成，負債者需依契約按時償之，逾期未償，債主可責之。此二者一關乎責權，二關乎財幣也。債主與負債者之間，彼此[MASK]。
親家者，姻親是也，為夫妻兩家父母之互稱。親家為同等之親戚，亦關世故人情。若夫婦敦睦，則親家亦諧，鮮有齟齬。親家之間，彼此[MASK]。
訟師之與司法者，因其職而相交也。事主有案，託於訟師，代寫文書，申訴有司，而司法者任於官府，審判其案。二者因本職而協作，並行業務於律法之事也。然地方司法，皆委縣令，多起於科舉，熟於治經，疏於律令，訟師與縣吏或沆瀣一氣，操縱案判，則蔽矣。訟師與司法者之間，彼此[MASK]。
訟師之於屬者，代理關係也。訟師以代撰訴狀為務，然亦可因之而受屬者之托，代其行訟。此二者一關乎責權，二關乎立信與代理也。訟師與屬者之間，彼此[MASK]。
捕快者，地方官府之差役也，以捉賊、治保為務。百姓為全身護財計，仰賴捕快；而捕快或濫權恣肆，百姓見而生畏。是以捕快百姓之間，關係微妙，一言難蔽百世之實。捕快與百姓之間，彼此[MASK]。
疑犯捕快，彼此對立。捕快之務，緝拿疑犯，而疑犯聞之，必逋逃藏匿，如鼠畏貓也。二者水火難容，矛盾多生。疑犯與捕快之間，彼此[MASK]。
罪犯之於人質，強之以力而脅其性命者也。犯人作奸犯科，將陷囹圄，恐牢獄之災，或挾人質以要官府。人質遭其挾而性命堪憂，以無可自主，常聽命于罪犯。罪犯與人質之間，彼此[MASK]。
罪犯所害之人，若有親眷，則稱苦主。苦主與罪犯為敵，視之為仇讎，冀官府緝捕，使其就法。或思血親之仇，不共戴天，則不俟官府，而有私報之也。罪犯與苦主之間，彼此[MASK]。
罪犯觸罪，或為旁人所觀。旁人既觀，則或有紛紛議論，批評褒貶。輿論所加，則罪犯聲名地位，亦隨之而更。是以旁人之論，或可左右決獄。而保甲之制，儒家之教，亦或使旁人作證，轉為證人也。罪犯與旁人之間，彼此[MASK]。
盜賊失主，彼此對立。盜賊之行，本系非法，謀竊失主，損其財物。依律，賊當償其失，並伏法受罰。盜賊與失主之間，彼此[MASK]。
罪犯與受害者，彼此對立。罪犯以非法加害於人，傷其身心。依律，賊當伏法受罰，以償其所害。罪犯與受害者之間，彼此[MASK]。
司法者與監察者，互相監督，彼此牽掣者也。司法者以審案為務，昭法之威，執法以正。監察者則督其行事或查其已行，以防其私弊貪腐，使司法必正也。司法者與監察者之間，彼此[MASK]。
罪犯同黨者，共犯是也。其所求所行，皆系非法，而三五聚夥，同籌共謀，一朝舉事，乃咸觸罪。依律，犯罪同黨未可消罪，以其明知共犯，或增其罪咎。罪犯同黨之間，彼此[MASK]。
賭徒之間，彼此相爭者也。其好博嗜賭，日以鬥雞走馬，喝雉呼盧，投注押寶為事，至於一擲千金，妄希橫富。故彼此爭財奪利，甚為激劇，不免舞弊詐欺，乃至身體相鬥者。厤朝之律法，以賭禁為常，故賭徒之間，世人皆視之為歪門邪道也。賭徒之間，彼此[MASK]。
文人與閱者，以文之賞識相交通者也。詩文曲賦，文人所作，常寓以其道其情，因傳其文而載其道也。閱者覽之，可明其道而體其情。夫閱者有感，或建言于文人，使其更改；而流播之廣狹，亦繫於後來之閱者。然限於古之實際，二者不得直接交通，故以單向為多。尋常閱者，難比文人之博觀群覽，不可左右其意。雖然，猶有閱者或與文人相厚，或業相關之業，或知音於後世，因而評論之，紹介之，出版之，則可左右文人之書寫，甚或筆削增潤其原文，而動搖世俗之喜好也。文人與閱者之間，彼此[MASK]。
文人多為士人之屬，論者亦品評之士。二者之間，實可相互磋磨學問，評鷙詩文者也。文人作詩文曲賦，而論者品藻之，其建言獻意，雖抒己之見，亦或左右文人之書寫也。於是論者作評，而文人參酌，以修色其作，推敲之定，一字之師，皆此類也。觀古之文俗世情，論者之于文人，抑揚者也。夫論者所尚，則以詩品詞話、文論筆談附益其作，播其芳名，俾傳之百世而其聲益顯，其文益高。反之，亦有詩文曲賦，論者毀之，因聲名不顯，浸微浸消者也。文人與論者之間，彼此[MASK]。